### ISSUE TITLE
Question: Gromacs united atom force field is supported?

### ISSUE THREAD

**Issue by Byun-jinyoung** [Valdes-Tresanco-MS/gmx_MMPBSA#10]
Dear gmx_MMPBSA developers.
Hello. Because I want to use "`gmx_MMPBSA`", I took a look tutorial examples. There is a option for a ligand; -lm option which required the ligand mole2 file from Antechamber.
But I wondered whether the "`gmx_MMPBSA`" supported the gromacs united atom force field because, when I used parmed in order to convert gromacs force field into AMBER format, it was not working properly.....(NOTE: I'm not expert on the parmed....)

Thank you for your reply in advanced. :)

**Comment by Valdes-Tresanco-MS** [comment]
Unfortunately, no. gmx_MMPBSA is based on the MMPBSA.py, so the calculations are done using AMberTools. This means that it will only be compatible if the force field used is compatible with Amber. We plan in the future to check if it is possible to make it fully compatible with GROMACS. However, this is just a guess as it has support for the most common force fields (we are implementing charmm).

Best wishes

**Comment by Byun-jinyoung** [comment]
Thank you
