### ISSUE TITLE
Error in Alanine Scanning in CHARMff

### ISSUE THREAD

**Issue by mtpae** [Valdes-Tresanco-MS/gmx_MMPBSA#104]
Hello all, 
               I have done the MMPBSA analysis of my protein-ligand system and now I want to do alanine scanning but I am facing this error. Please help me.
![Screenshot from 2021-12-21 17-07-25](https://user-images.githubusercontent.com/92774704/147034506-95a4ed6a-bcf8-4c81-a5cc-8446dc59c3f4.png)
[mmpbsa (2).txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7759948/mmpbsa.2.txt)

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7759960/gmx_MMPBSA.log)

**Comment by Valdes-Tresanco-MS** [comment]
Currently, we have an open issue with that error (#88). I am extremely busy, but I will try to spend some time around the holidays to release version 1.5.0 which will include the fix for this bug.

Mario S.

**Comment by mtpae** [comment]
Okay, thank you @Valdes-Tresanco-MS.
