### ISSUE TITLE
Decomposition analysis 

### ISSUE THREAD

**Issue by Jameel9** [Valdes-Tresanco-MS/gmx_MMPBSA#107]
Dear Sir 
I hope you are doing great

we have installed gmx_MMPBSA and tested it successfully. When I tried to do a decomposition analysis of a peptide-protein complex, I got an error which I couldn't solve. The attachments below are: the log file, index, and instructions file.
I did the simulation using Gromacs 2019.2 using Charmm27 forcefield and TIP4P water model.
Could you please help/suggest a solution?
thank you very much.

[Decomp_error.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7799526/Decomp_error.zip)

**Comment by Valdes-Tresanco-MS** [comment]
If you use CHARMMff you must define the option `-cp topol.top`

**Comment by Jameel9** [comment]
Thank you!!

**Comment by Jameel9** [comment]
Dear Sir 

I hope you are doing well

Sorry for any inconvenience caused.

I have been trying to calculate the decomposition energy of my peptide-protein complex simulated on Gromacs 2019.2 using gmx_MMPBSA. Since I used Charmm27 ff, I specified the topology file (-cp topol.top) as you recommended last week. However, I still facing an issue that gmx_mmpbsa found no velocities (Kindly see the log attached file).

What is the core error for this?

Thank you very much for your help and patience! 

Jameel
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7813002/gmx_MMPBSA.log)

**Comment by Valdes-Tresanco-MS** [comment]
Don't worry, you have not generated any inconvenience, we will gladly help you. Send us your files (`tpr`, `index`, `5 frames xtc`, `top` and associated files and `groups`) to identify the error

**Comment by Jameel9** [comment]
That is really kind of you!!
but sorry sir, what do you mean by "associated files and groups"?
On Google drive, I have [zipped ](https://drive.google.com/file/d/1vxUWjpknNbw2mLngSEE3iHMW-QGhR90X/view?usp=sharing)these files:

1. 5frames.xtc
2. index.ndx
3. mdsim.tpr
4. topol.top
5. solvated.gro
6. complex.pdb
7. instructions.in 

for running, I used this command:
 gmx_MMPBSA -O -i instructions.in -cs mdsim.tpr -ci index.ndx -cg 10 11 -ct corrected_traj.xtc -cp topol.top

I also tried the .gro file instead of the .tpr file.

**Comment by marioernestovaldes** [comment]
Hello there!

"topol_Protein_chain_A.itp" and  "topol_Protein_chain_B.itp files are missing...could you please include those?

thanks in advance

**Comment by Jameel9** [comment]
Unfortunately, these files are not provided by the server that ran the simulation.
Is there any way i can follow to generate such files?

**Comment by Valdes-Tresanco-MS** [comment]
The topology (`* .top`) by itself is not functional if the associated files (`*.itp`) are not accessible. In principle, you can regenerate the topology using the same command you used to create it (`gmx pdb2gmx -f clean-C4_P_HDock.pdb -water tip4p -ignh`, and selecting the same options). The server you use should let you download these files, otherwise, the topology in the current state is useless. 
Please consider sharing your terminal output in a txt file, since the **gmx_MMPBSA** log is still limited in handling all errors

**Comment by Jameel9** [comment]
Okay.
Thank you very much Sir.

**Comment by Valdes-Tresanco-MS** [comment]
Do not hesitate to send us the files of your case, so that we can help you solve the problems
Best!
Mario S

**Comment by Jameel9** [comment]
Dear Sir

I hope you're doing great


The simulation was done by Gromacs 2019.2. The problem now is that i can't install this version on my laptop because of "502 Bad Gateway" issue i could not diagnose/solve.
I have generated the required .itp files using gromacs 2020.1.

Should that files do their job in gmx_MMPBSA calculations or should i generate the files using the 2019.2 version?

Thanks for your help and patience

**Comment by marioernestovaldes** [comment]
if you used Charmm27 forcefield and TIP4P water model, it should be fine... send those files to see if we can solve the issue with those...

cheers!

Mario E.

**Comment by Jameel9** [comment]
Thank you very much Sir

I have used those parameters in the pdb2gmx command.
All the files are now zipped in this [link ](https://drive.google.com/file/d/1OaNL4pH5Xb6uLtvR595ux-9fV67UtPgc/view?usp=sharing) on Google Drive.
I also modified the entries in the .in file to check if I am getting it write :).

Thnx again

**Comment by Valdes-Tresanco-MS** [comment]
@Jameel9 Good news
There are a few small problems, but nothing serious.
The * .in file is incorrect. Please review this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/input_file/).
The file should look as follows
```
&general
sys_name="Decomposition",
startframe=1, endframe=5,  interval=1,
/

&gb
igb=2, saltcon=0.150,
/


&decomp
idecomp=2, dec_verbose=2,
print_res="A/230-274 B/1-39"
/
```
Note that each section begins with `&` and ends with`/`.
Note that the definition of each chain residues selection are separated by space, the characters `,` and `;` are reserved for listing the residues. See the [amino acids selection to print](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/input_file/#decomp-namelist-variables)

Using the following command line everything works fine.

    mpirun -np 5 gmx_MMPBSA MPI -O -i instructions.in -cs mdsim.tpr -ci index.ndx -cg 11 12 -cp topol.top -ct 5frames.xtc

This is how it looks. We hope this helps you!!!
![image](https://user-images.githubusercontent.com/36672242/148427338-69614c71-6e06-4d93-9c34-1d705d6ccc4f.png)

**Comment by Jameel9** [comment]
Thank you very much sir

I am deeply grateful for your help, support, and patience. You will be acknowledged in my thesis and paper.

**Comment by Valdes-Tresanco-MS** [comment]
We are pleased to help you. I hope **gmx_MMPBSA** is very helpful to you.
I'll close the issue, but feel free to open a new one if you need.
Best wishes!

**Comment by Jameel9** [comment]
Dear Sir 

I have tried to replicate the calculations you have already made for 5 frames with all required files. Unfortunately, I got this error:

(AmberTools21) biophysics@HCV:~/Jameel/gmx_MMPBSA$ gmx_MMPBSA -O -i instructions.in -cs mdsim.tpr -ci index.ndx -cg 11 12 -cp topol.top -ct 5frames.xtc
[INFO   ] Starting
[INFO   ] Command-line
  gmx_MMPBSA -O -i instructions.in -cs mdsim.tpr -ci index.ndx -cg 11 12 -cp topol.top -ct 5frames.xtc

[WARNING] protein_forcefield and ligand_forcefield variables are deprecate since version 1.4.1 and will be remove in the next version. Please, use forcefield instead.
[WARNING] entropy_seg variable is deprecate since version 1.4.2 and will be remove in v1.5.0. Please, use ie_segment instead.
[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/biophysics/anaconda3/envs/AmberTools21/bin/cpptraj
[INFO   ] tleap found! Using /home/biophysics/anaconda3/envs/AmberTools21/bin/tleap
[INFO   ] parmchk2 found! Using /home/biophysics/anaconda3/envs/AmberTools21/bin/parmchk2
[INFO   ] sander found! Using /home/biophysics/anaconda3/envs/AmberTools21/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER Topologies from GROMACS files...
[INFO   ] Checking gmxMMPBSA data folder exists in Amber data...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 11_12 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[ERROR  ] MMPBSA_Error /usr/local/gromacs/bin/gmx editconf failed when querying mdsim.tpr.
           Check the gmx_MMPBSA.log file to report the problem.
  File "/home/biophysics/anaconda3/envs/AmberTools21/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 95, in gmxmmpbsa
    app.make_prmtops()
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 576, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 115, in buildTopology
    self.gmx2pdb()
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 166, in gmx2pdb
    GMXMMPBSA_ERROR('%s failed when querying %s' % (' '.join(self.editconf), self.FILES.complex_tpr))
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '. Check the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: /usr/local/gromacs/bin/gmx editconf failed when querying mdsim.tpr. Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.
(AmberTools21) biophysics@HCV:~/Jameel/gmx_MMPBSA$ 


 
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7838424/gmx_MMPBSA.log)

**Comment by marioernestovaldes** [comment]
Try with this command line:

gmx_MMPBSA -O -i instructions.in -cs mdsim.tpr -ci index.ndx -cg 10 11 -cp topol.top -ct 5frames.xtc

Group 12 doesn't exist in the index file you are using... Please, check the input files carefully

cheers!

**Comment by Jameel9** [comment]
I already did that sir 
i got this

(base) biophysics@HCV:~/Jameel/gmx_MMPBSA$ conda activate AmberTools21
(AmberTools21) biophysics@HCV:~/Jameel/gmx_MMPBSA$ source /usr/local/gromacs/bin/GMXRC
(AmberTools21) biophysics@HCV:~/Jameel/gmx_MMPBSA$ gmx_MMPBSA -O -i instructions.in -cs mdsim.tpr -ci index.ndx -cg 10 11 -cp topol.top -ct 5frames.xtc
[INFO   ] Starting
[INFO   ] Command-line
  gmx_MMPBSA -O -i instructions.in -cs mdsim.tpr -ci index.ndx -cg 10 11 -cp topol.top -ct 5frames.xtc

[WARNING] protein_forcefield and ligand_forcefield variables are deprecate since version 1.4.1 and will be remove in the next version. Please, use forcefield instead.
[WARNING] entropy_seg variable is deprecate since version 1.4.2 and will be remove in v1.5.0. Please, use ie_segment instead.
[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/biophysics/anaconda3/envs/AmberTools21/bin/cpptraj
[INFO   ] tleap found! Using /home/biophysics/anaconda3/envs/AmberTools21/bin/tleap
[INFO   ] parmchk2 found! Using /home/biophysics/anaconda3/envs/AmberTools21/bin/parmchk2
[INFO   ] sander found! Using /home/biophysics/anaconda3/envs/AmberTools21/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER Topologies from GROMACS files...
[INFO   ] Checking gmxMMPBSA data folder exists in Amber data...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 10_11 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Complex: Saving group 10 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal ligand: Saving group 11 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Building Normal Complex Amber Topology...
  File "/home/biophysics/anaconda3/envs/AmberTools21/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 95, in gmxmmpbsa
    app.make_prmtops()
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 576, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 117, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 318, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes[0] + self.indexes[1])
  File "/home/biophysics/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 603, in cleantop
    if rtemp_top.atoms[i-1].residue.number + 1 not in res_list:
IndexError: list index out of range
Exiting. All files have been retained.
(AmberTools21) biophysics@HCV:~/Jameel/gmx_MMPBSA$ 
[gmx_MMPBSA_test.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7838507/gmx_MMPBSA_test.log)

**Comment by Jameel9** [comment]
Thanks.. I think it is working now
it says:
  calculating complex contribution...
