### ISSUE TITLE
Error while running gmx_MMPBSA command.

### ISSUE THREAD

**Issue by user-accoun** [Valdes-Tresanco-MS/gmx_MMPBSA#11]
Hello sir,
After installation of gmx_MMPBSA , i'm getting error while running the code.

~/Downloads/amber20_src/bin$ gmx_MMPBSA
Traceback (most recent call last):
  File "/home/user/Downloads/amber20_src/miniconda/bin/gmx_MMPBSA", line 5, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File "/home/user/Downloads/amber20_src/miniconda/lib/python2.7/site-packages/GMXMMPBSA/app.py", line 122
    sys.exit(app.exec())
                    ^
SyntaxError: invalid syntax

**Comment by Valdes-Tresanco-MS** [comment]
Oh... I didn't test it with python2.
gmx_MMPBSA is only compatible with Python 3 for two reasons: python2 is no longer supported and we assume that AmberTools20 was only compatible with python3 because it recommends installing miniconda 3.
We invite you to install gmx_MMPBSA using python 3.
Best wishes

**Comment by user-accoun** [comment]
Could you please provide a detailed instruction on how to install it using python3 ?

**Comment by Valdes-Tresanco-MS** [comment]
You can review how to install AmberTools20 in an existing miniconda3/conda3 environment on the official Amber site (https://ambermd.org/GetAmber.php) or you can install AmberTools20 by compiling it yourself and allowing it to install their internal miniconda environment (https://ambermd.org/doc12/Amber20.pdf#installation)
After proper AmberTools20 installation, you can follow these instructions to install gmx_MMPBSA ([Installing `gmx_MMPBSA`](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/blob/master/README.md#installing-gmx_mmpbsa))

**Comment by user-accoun** [comment]
Thanks a lot.

**Comment by Valdes-Tresanco-MS** [comment]
To you for considering using our tool.
If you want you can share questions, suggestions, or ideas in our [Google group](https://groups.google.com/g/gmx_mmpbsa)
Best wishes
