### ISSUE TITLE
improve debugging...

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/gmx_MMPBSA#110]
When users report an error,  most of the time it is necessary to request the files the user is using. Is it possible to create a compressed file with all the necessary files (*in, *ndx, 5 frames of the trajectory, etc) that way, the user just has to send around the compressed file if needed...

**Comment by Valdes-Tresanco-MS** [comment]
Since it is very difficult to handle all the errors associated with the program and its dependencies, it becomes a bit complicated to carry out this process. Thus, the responsibility remains with the users.
