### ISSUE TITLE
Add GBNSR6 support

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#111]
Create an `*.mdin` to compute the rest of the energy components with `sander` and a `*.mdin` for `GBNSR6`.
**Note:** _The `*.mdin` of GBNSR6 must have the `namelist` starting from the first line_

```

&cntrl
inp=0
/
&gb
alpb=1, chagb=1
/
```
- It is necessary to generate the `*.inpcrd` of each frame to be processed because it does not have support for dynamics.
- The `*.prmtop` generated by conversion need revision, because there may be type errors:
`ERROR: Flag "TITLE" not found in PARM file`
- Each result should be put in a file similar to the `*.mdout` of the rest of the calculations for greater comfort

**Comment by marioernestovaldes** [comment]
set variables `igb` and `gbsa` = 0 and use sander...

**Comment by Valdes-Tresanco-MS** [comment]
`*.mdin` for computing the rest of energy components with `sander`

```
File generated by gmx_MMPBSA
&cntrl
 ntb=0, nsnb=99999, cut=999.0, imin=5, 
 igb=0, dec_verbose=0, 
/
```
Command-line:
`sander -O -i _GMXMMPBSA_pb.mdin -p COM.prmtop -c _GMXMMPBSA_dummycomplex.inpcrd -y _GMXMMPBSA_complex.mdcrd.0 -o test2.mdout`

**Comment by marioernestovaldes** [comment]
check the README in the stand-alone version of GBNSR6 code available [here](http://people.cs.vt.edu/~onufriev/CODES/R6bornRadius.zip) for more info. More options are available in the stand-alone version of GBNSR6 code not based on Cartesian grid.
