### ISSUE TITLE
error with qt.qpa.screen

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/gmx_MMPBSA#114]
An error with qt.qpa.screen is obtained when running gmx_MMPBSA_test... see image attached...

![IMG_20220111_165534](https://user-images.githubusercontent.com/46581661/148978458-96ccca40-681f-40bb-8e72-50937a47a028.jpg)

**Comment by Valdes-Tresanco-MS** [comment]
This could be solved by following [Microsoft's instructions](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps). However, the issues related to this are beyond our reach, as we cannot support everything.
