### ISSUE TITLE
Failed to generate parameters

### ISSUE THREAD

**Issue by carltonbiotec** [Valdes-Tresanco-MS/gmx_MMPBSA#115]
Hai,

I am getting this error
/home/dextro/amber/amber20_src/bin/teLeap: Warning!
The unperturbed charge of the unit (-1.000000) is not zero.
FATAL:  Atom .R<CASP 23>.A<O2 15> does not have a type.
FATAL:  Atom .R<CASP 23>.A<O1 14> does not have a type.

/home/dextro/amber/amber20_src/bin/teLeap: Fatal Error!
Failed to generate parameters

Exiting LEaP: Errors = 1; Warnings = 1; Notes = 0.

Please let me know what has to be done

1. protein peptide interaction

**Additional context**
The gmx_MMPBSA.log file

[INFO   ] Starting
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs mdsim.tpr -ci index.ndx -cg 19 20 -ct mdsim_allframes.pdb

[WARNING] protein_forcefield and ligand_forcefield variables are deprecate since version 1.4.1 and will be remove in the next version. Please, use forcefield instead.
[WARNING] entropy_seg variable is deprecate since version 1.4.2 and will be remove in v1.5.0. Please, use ie_segment instead.
[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/dextro/amber/amber20_src/bin/cpptraj
[INFO   ] tleap found! Using /home/dextro/amber/amber20_src/bin/tleap
[INFO   ] parmchk2 found! Using /home/dextro/amber/amber20_src/bin/parmchk2
[INFO   ] mmpbsa_py_energy found! Using /home/dextro/amber/amber20_src/bin/mmpbsa_py_energy
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER Topologies from GROMACS files...
[INFO   ] Checking gmxMMPBSA data folder exists in Amber data...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 19_20 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[WARNING] You must define the ligand mol2 file (-lm) if ligand_forcefield is "leaprc.gaff" or "leaprc.gaff2". If the ligand is parametrized in Amber force fields ignore this warning
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Complex: Saving group 19 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal ligand: Saving group 20 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Generating AMBER Compatible PDB Files...
[INFO   ] Building tleap input files...
[ERROR  ] MMPBSA_Error /home/dextro/amber/amber20_src/bin/tleap failed when querying _GMXMMPBSA_leap.in.
           Check the gmx_MMPBSA.log file to report the problem.
m, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx make_ndx, version 2020.1-Ubuntu-2020.1-1
Executable:   /usr/bin/gmx
Data prefix:  /usr
Working dir:  /home/dextro/amber/amber20_src
Command line:
  gmx make_ndx -n index.ndx -o _GMXMMPBSA_COM_index.ndx

GROMACS reminds you: "It's Against the Rules" (Pulp Fiction)

Going to read 1 old index file(s)
Counted atom numbers up to 88130 in index file

  0 System              : 88130 atoms
  1 Protein             : 10282 atoms
  2 Protein-H           :  8070 atoms
  3 C-alpha             :  1013 atoms
  4 Backbone            :  3039 atoms
  5 MainChain           :  4054 atoms
  6 MainChain+Cb        :  5010 atoms
  7 MainChain+H         :  5005 atoms
  8 SideChain           :  5277 atoms
  9 SideChain-H         :  4016 atoms
 10 Prot-Masses         : 10282 atoms
 11 non-Protein         : 77848 atoms
 12 Water               : 77700 atoms
 13 SOL                 : 77700 atoms
 14 non-Water           : 10430 atoms
 15 Ion                 :   148 atoms
 16 NA                  :    83 atoms
 17 CL                  :    65 atoms
 18 Water_and_ions      : 77848 atoms
 19 r_1-1004            : 10178 atoms
 20 r_1005-1013         :   104 atoms

 nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
 'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
 't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
 'r': residue              'res' nr         'chain' char
 "name": group             'case': case sensitive           'q': save and quit
 'ri': residue index

> 

> 

> 
Copied index group 19 'GMXMMPBSA_REC'
Copied index group 20 'GMXMMPBSA_LIG'
Merged two groups with OR: 10178 104 -> 10282

 21 GMXMMPBSA_REC_GMXMMPBSA_LIG: 10282 atoms

> 
             :-) GROMACS - gmx editconf, 2020.1-Ubuntu-2020.1-1 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf      Artem Zhmurov   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx editconf, version 2020.1-Ubuntu-2020.1-1
Executable:   /usr/bin/gmx
Data prefix:  /usr
Working dir:  /home/dextro/amber/amber20_src
Command line:
  gmx editconf -f mdsim.tpr -o _GMXMMPBSA_COM.pdb -n _GMXMMPBSA_COM_index.ndx

Reading file mdsim.tpr, VERSION 2019.2 (single precision)
Reading file mdsim.tpr, VERSION 2019.2 (single precision)

Select a group for output:
Group     0 (         System) has 88130 elements
Group     1 (        Protein) has 10282 elements
Group     2 (      Protein-H) has  8070 elements
Group     3 (        C-alpha) has  1013 elements
Group     4 (       Backbone) has  3039 elements
Group     5 (      MainChain) has  4054 elements
Group     6 (   MainChain+Cb) has  5010 elements
Group     7 (    MainChain+H) has  5005 elements
Group     8 (      SideChain) has  5277 elements
Group     9 (    SideChain-H) has  4016 elements
Group    10 (    Prot-Masses) has 10282 elements
Group    11 (    non-Protein) has 77848 elements
Group    12 (          Water) has 77700 elements
Group    13 (            SOL) has 77700 elements
Group    14 (      non-Water) has 10430 elements
Group    15 (            Ion) has   148 elements
Group    16 (             NA) has    83 elements
Group    17 (             CL) has    65 elements
Group    18 ( Water_and_ions) has 77848 elements
Group    19 (  GMXMMPBSA_REC) has 10178 elements
Group    20 (  GMXMMPBSA_LIG) has   104 elements
Group    21 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has 10282 elements
Select a group: 
GROMACS reminds you: "No, no, you're not thinking, you're just being logical." (Niels Bohr)

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 88130 atoms
Volume: 713.709 nm^3, corresponds to roughly 321100 electrons
Velocities found
Selected 21: 'GMXMMPBSA_REC_GMXMMPBSA_LIG'
             :-) GROMACS - gmx editconf, 2020.1-Ubuntu-2020.1-1 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf      Artem Zhmurov   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx editconf, version 2020.1-Ubuntu-2020.1-1
Executable:   /usr/bin/gmx
Data prefix:  /usr
Working dir:  /home/dextro/amber/amber20_src
Command line:
  gmx editconf -f mdsim.tpr -o _GMXMMPBSA_REC.pdb -n _GMXMMPBSA_COM_index.ndx

Reading file mdsim.tpr, VERSION 2019.2 (single precision)
Reading file mdsim.tpr, VERSION 2019.2 (single precision)

Select a group for output:
Group     0 (         System) has 88130 elements
Group     1 (        Protein) has 10282 elements
Group     2 (      Protein-H) has  8070 elements
Group     3 (        C-alpha) has  1013 elements
Group     4 (       Backbone) has  3039 elements
Group     5 (      MainChain) has  4054 elements
Group     6 (   MainChain+Cb) has  5010 elements
Group     7 (    MainChain+H) has  5005 elements
Group     8 (      SideChain) has  5277 elements
Group     9 (    SideChain-H) has  4016 elements
Group    10 (    Prot-Masses) has 10282 elements
Group    11 (    non-Protein) has 77848 elements
Group    12 (          Water) has 77700 elements
Group    13 (            SOL) has 77700 elements
Group    14 (      non-Water) has 10430 elements
Group    15 (            Ion) has   148 elements
Group    16 (             NA) has    83 elements
Group    17 (             CL) has    65 elements
Group    18 ( Water_and_ions) has 77848 elements
Group    19 (  GMXMMPBSA_REC) has 10178 elements
Group    20 (  GMXMMPBSA_LIG) has   104 elements
Group    21 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has 10282 elements
Select a group: 
GROMACS reminds you: "Let Me Do This" (Urban Dance Squad)

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 88130 atoms
Volume: 713.709 nm^3, corresponds to roughly 321100 electrons
Velocities found
Selected 19: 'GMXMMPBSA_REC'
             :-) GROMACS - gmx editconf, 2020.1-Ubuntu-2020.1-1 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf      Artem Zhmurov   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx editconf, version 2020.1-Ubuntu-2020.1-1
Executable:   /usr/bin/gmx
Data prefix:  /usr
Working dir:  /home/dextro/amber/amber20_src
Command line:
  gmx editconf -f mdsim.tpr -o _GMXMMPBSA_LIG.pdb -n _GMXMMPBSA_COM_index.ndx

Reading file mdsim.tpr, VERSION 2019.2 (single precision)
Reading file mdsim.tpr, VERSION 2019.2 (single precision)

Select a group for output:
Group     0 (         System) has 88130 elements
Group     1 (        Protein) has 10282 elements
Group     2 (      Protein-H) has  8070 elements
Group     3 (        C-alpha) has  1013 elements
Group     4 (       Backbone) has  3039 elements
Group     5 (      MainChain) has  4054 elements
Group     6 (   MainChain+Cb) has  5010 elements
Group     7 (    MainChain+H) has  5005 elements
Group     8 (      SideChain) has  5277 elements
Group     9 (    SideChain-H) has  4016 elements
Group    10 (    Prot-Masses) has 10282 elements
Group    11 (    non-Protein) has 77848 elements
Group    12 (          Water) has 77700 elements
Group    13 (            SOL) has 77700 elements
Group    14 (      non-Water) has 10430 elements
Group    15 (            Ion) has   148 elements
Group    16 (             NA) has    83 elements
Group    17 (             CL) has    65 elements
Group    18 ( Water_and_ions) has 77848 elements
Group    19 (  GMXMMPBSA_REC) has 10178 elements
Group    20 (  GMXMMPBSA_LIG) has   104 elements
Group    21 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has 10282 elements
Select a group: 
GROMACS reminds you: "I ought to warn you, I have no faith" (Jane Eyre in Jane Eyre by Charlotte Bronte)

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 88130 atoms
Volume: 713.709 nm^3, corresponds to roughly 321100 electrons
Velocities found
Selected 20: 'GMXMMPBSA_LIG'
-I: Adding /home/dextro/amber/amber20_src/dat/leap/prep to search path.
-I: Adding /home/dextro/amber/amber20_src/dat/leap/lib to search path.
-I: Adding /home/dextro/amber/amber20_src/dat/leap/parm to search path.
-I: Adding /home/dextro/amber/amber20_src/dat/leap/cmd to search path.
-f: Source _GMXMMPBSA_leap.in.
-I: Adding /home/dextro/.local/lib/python3.8/site-packages/GMXMMPBSA/data to search path.

Welcome to LEaP!
(no leaprc in search path)
Sourcing: ./_GMXMMPBSA_leap.in
----- Source: /home/dextro/amber/amber20_src/dat/leap/cmd/oldff/leaprc.ff99SB
----- Source of /home/dextro/amber/amber20_src/dat/leap/cmd/oldff/leaprc.ff99SB done
Log file: ./leap.log
Loading parameters: /home/dextro/amber/amber20_src/dat/leap/parm/parm99.dat
Reading title:
PARM99 for DNA,RNA,AA, organic molecules, Polariz.& LP incl.02/04/99
Loading parameters: /home/dextro/amber/amber20_src/dat/leap/parm/frcmod.ff99SB
Reading force field modification type file (frcmod)
Reading title:
Modification/update of parm99.dat (Hornak & Simmerling)
Loading library: /home/dextro/amber/amber20_src/dat/leap/lib/all_nucleic94.lib
Loading library: /home/dextro/amber/amber20_src/dat/leap/lib/all_amino94.lib
Loading library: /home/dextro/amber/amber20_src/dat/leap/lib/all_aminoct94.lib
Loading library: /home/dextro/amber/amber20_src/dat/leap/lib/all_aminont94.lib
Loading library: /home/dextro/amber/amber20_src/dat/leap/lib/ions94.lib
Loading library: /home/dextro/amber/amber20_src/dat/leap/lib/solvents.lib
----- Source: /home/dextro/amber/amber20_src/dat/leap/cmd/leaprc.gaff
----- Source of /home/dextro/amber/amber20_src/dat/leap/cmd/leaprc.gaff done
Log file: ./leap.log
Loading parameters: /home/dextro/amber/amber20_src/dat/leap/parm/gaff.dat
Reading title:
AMBER General Force Field for organic molecules (Version 1.81, May 2017)
Loading library: /home/dextro/amber/amber20_src/dat/leap/lib/atomic_ions.lib
Loading parameters: /home/dextro/amber/amber20_src/dat/leap/parm/frcmod.ions234lm_126_tip3p
Reading force field modification type file (frcmod)
Reading title:
Li/Merz ion parameters of divalent to tetravalent ions for TIP3P water model (12-6 normal usage set)
Using H(N)-modified Bondi radii
Loading PDB file: ./_GMXMMPBSA_REC_F1.pdb
Created a new atom named: O1 within residue: .R<CILE 1036>
Created a new atom named: O2 within residue: .R<CILE 1036>
  Added missing heavy atom: .R<CILE 1036>.A<O 19>
  Added missing heavy atom: .R<CILE 1036>.A<OXT 20>
  total atoms in file: 7992
  Leap added 7875 missing atoms according to residue templates:
       2 Heavy
       7873 H / lone pairs
  The file contained 2 atoms not in residue templates
Loading PDB file: ./_GMXMMPBSA_LIG_F1.pdb
Created a new atom named: O1 within residue: .R<CASP 23>
Created a new atom named: O2 within residue: .R<CASP 23>
  Added missing heavy atom: .R<CASP 23>.A<O 12>
  Added missing heavy atom: .R<CASP 23>.A<OXT 13>
  total atoms in file: 78
  Leap added 78 missing atoms according to residue templates:
       2 Heavy
       76 H / lone pairs
  The file contained 2 atoms not in residue templates
Checking Unit.

/home/dextro/amber/amber20_src/bin/teLeap: Warning!
The unperturbed charge of the unit (-1.000000) is not zero.
FATAL:  Atom .R<CASP 23>.A<O2 15> does not have a type.
FATAL:  Atom .R<CASP 23>.A<O1 14> does not have a type.

/home/dextro/amber/amber20_src/bin/teLeap: Fatal Error!
Failed to generate parameters

Exiting LEaP: Errors = 1; Warnings = 1; Notes = 0.

**Comment by Valdes-Tresanco-MS** [comment]
With what force field did you parameterize your system?

**Comment by carltonbiotec** [comment]
;
;	Created by:
;	                     :-) GROMACS - gmx pdb2gmx, 2019 (-:
;	
;	Executable:   /usr/local/gromacs/bin/gmx
;	Data prefix:  /usr/local/gromacs
;	
;	Command line:
;	  gmx pdb2gmx -f clean-Native.pdb -water tip4p -ignh
;	Force field was read from the standard GROMACS share directory.
;

; Include forcefield parameters
#include "gromos43a1.ff/forcefield.itp"

; Include chain topologies
#include "topol_Protein_chain_A.itp"
#include "topol_Protein_chain_B.itp"

; Include water topology
#include "gromos43a1.ff/tip4p.itp"

#ifdef POSRES_WATER
; Position restraint for each water oxygen
[ position_restraints ]
;  i funct       fcx        fcy        fcz
   1    1       1000       1000       1000
#endif

; Include topology for ions
#include "gromos43a1.ff/ions.itp"

[ system ]
; Name
Protein in water

[ molecules ]
; Compound        #mols
Protein_chain_A     1
Protein_chain_B     1
SOL         19425
NA               83
CL               65

**Comment by Valdes-Tresanco-MS** [comment]
Currently, **gmx_MMPBSA** only supports AMBER and CHARMM force fields. We are working to implement the calculation with APBS but it will be available for version 2.0, which may take a while yet.
