### ISSUE TITLE
How to extract per frame energy values

### ISSUE THREAD

**Issue by ataulislam80** [Valdes-Tresanco-MS/gmx_MMPBSA#116]
**Describe the issue**
I am interested to extract protein ligand each frame mmgbsa evergy value. My aim is to prepare a table of 10k frames vs mmgbsa energy in excel. requesting you kindly guide me how to get those values and which file contain those values?

**_If you will report an error, please complete this form_**
**To Reproduce**
1. Which system type are you running? (Protein-Protein, Protein-Ligand, etc)
2. The command-line are you using.

**Additional context**
The gmx_MMPBSA.log file

**Comment by marioernestovaldes** [comment]
check this [video](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/analyzer/#functionalities) in the documentation (44 seconds to be more precise) about gmx_MMPBSA_ana functionalities... you can extract the data in CSV files that can be opened afterward in excel...

hope this helps!

**Comment by Valdes-Tresanco-MS** [comment]
If you are familiar with Python, you can also use the API to get this information
