### ISSUE TITLE
Error in quering _GMXMMPBSA_leap.in file .

### ISSUE THREAD

**Issue by user-accoun** [Valdes-Tresanco-MS/gmx_MMPBSA#12]
After fresh installation of Amber 20 gmxmmpbsa was installed as mentioned on your websire. While running the given test tutorial I'm finding error.

**Comment by Valdes-Tresanco-MS** [comment]
What tutorial are you trying to reproduce?
This command line is common for several tutorials, but it is missing information.
> "gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 1 13 -ct com_traj.xtc

In all the tutorials that are used it also includes the -lm flag. Please, give me more information, as all the tutorials have been reproduced in several different environments and have not reported problems.
The `make_top.log` file contains all the information related to the output of the programs. Check the error that tleap gives or attach the file.

**Comment by user-accoun** [comment]
TWO THINGS I WANT TO ADD HERE-1) i alredy worked on amber18 and i also find problem with tleap so instead using tleap i preferred xleap that is nothing but it's gui platform of tleap so it was easy to handle and execution. So if u can add xleap in ur software it would be very helpful. 2) when i checked the _GMXPBSA_tleap.in file i found first line written SOURCE OLDFF/leaprc.ff99SB
But the oldff library exist in $AMBERHOME/dat/oldff folder of amber20 .
How can i tackle this kind of error..Could you please help me out?

**Comment by user-accoun** [comment]
I'm trying protein-ligand MT tutorial.

**Comment by user-accoun** [comment]
[make_top.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/5792791/make_top.log)

**Comment by Valdes-Tresanco-MS** [comment]
Thanks for the suggestion. 
> TWO THINGS I WANT TO ADD HERE-1) i alredy worked on amber18 and i also find problem with tleap so instead using tleap i preferred xleap that is nothing but it's gui platform of tleap so it was easy to handle and execution. So if u can add xleap in ur software it would be very helpful. 

However, the idea of gmx_MMPBSA is not to prepare the files for dynamics, as this is a post-production analysis. We assume that the user has already generated the ligand topology using antechamber, so you shouldn't find any errors. It is also important that the user knows the methodology, regardless of whether we have a wide variety of tutorials.

> when i checked the _GMXPBSA_tleap.in file i found first line written SOURCE OLDFF/leaprc.ff99SB
> But the oldff library exist in $AMBERHOME/dat/oldff folder of amber20 .

We know that AmberTools20 recommends using Amber14SB, however, it has compatibility with relatively old force fields that are still widely used. That is why we decided to include these force fields as options. Tleap can recognize these FFs in the indicated format, that is, oldff/leaprc.ff99SB. This way users can use the FFs without having to modify the contents of the AmberTools folders.

**Also, you need to make sure that the force fields you use for the protein and the ligand are the same as you used in GROMACS and antechamber respectively.**

> How can i tackle this kind of error..Could you please help me out?

Please review the documentation. We have been working on understanding the documentation for non-Amber users. To find out what compatibility options you have, review this topic (https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/blob/master/README.md#the-input-file).

**Comment by user-accoun** [comment]
Right now the given error was produced on running the tutorial test ligand-protein MT files , without any modifications in command and files.

**Comment by Valdes-Tresanco-MS** [comment]
> [make_top.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/5792791/make_top.log)

The error is because tleap does not have the ligand parameters (RAL). This is probably because you are not entering the command line correctly.
Evidence:
Parmchk2 did not run
tleap does not read the ligand parameter file.

This log file corresponds to the ST approach

The correct command line is:

    gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 1 13 -ct com_traj.xtc -lm ligand.mol2

For MT approach the command line is:

    gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 1 13 -ct com_traj.xtc -rs rec.pdb -ri rec_index.ndx -rg 1 -rt rec_traj.pdb -lm ligand.mol2 -ls lig.pdb -li lig_index.ndx -lg 2 -lt lig_traj.pdb

Please, check this.

**Comment by Valdes-Tresanco-MS** [comment]
@user-accoun Could you solve the problem? If not, we can help you solve it.
Best wishes

**Comment by user-accoun** [comment]
I'm able to run the program on given test files. Thanks for your valuable assistance. 
I want you to delete the particular issue since it contains some sensitive information.

**Comment by Valdes-Tresanco-MS** [comment]
I already removed the make_top.log that contained your information. Is there something else that you do not want this public?
We take the privacy of our users very seriously. Feel free to tell us if something is missing.
Best wishes
