### ISSUE TITLE
Difficulty to install gmx-mmpbsa 

### ISSUE THREAD

**Issue by srdjan125** [Valdes-Tresanco-MS/gmx_MMPBSA#122]
Hello,

I have tried to install the gmx-mmpbsa program today.  First I have installed Ambertools by conda command, then mpirun (which I already have), then I have tried to test if program is working by downloading files from "protein-protein tutorial" , however after typing command: gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 19 20 -ct com_traj.xtc

  I get the following error:

Traceback (most recent call last):
  File "/home/srdjan/anaconda3/lib/python3.7/site-packages/GMXMMPBSA/app.py", line 26, in <module>
    from GMXMMPBSA import main
  File "/home/srdjan/anaconda3/lib/python3.7/site-packages/GMXMMPBSA/main.py", line 38, in <module>
    from GMXMMPBSA.createinput import create_inputs
  File "/home/srdjan/anaconda3/lib/python3.7/site-packages/GMXMMPBSA/createinput.py", line 43, in <module>
    from parmed.amber.mdin import Mdin
ModuleNotFoundError: No module named 'parmed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/srdjan/anaconda3/bin/gmx_MMPBSA", line 5, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File "/home/srdjan/anaconda3/lib/python3.7/site-packages/GMXMMPBSA/app.py", line 35, in <module>
    (amberhome, amberhome))
(base) srdjan@srdjan-HP-ProDesk-400-G4-SFF:~/Desktop/gmx-MMPBSA/Tutorial/Protein_protein$ conda activate AmberTools21
(AmberTools21) srdjan@srdjan-HP-ProDesk-400-G4-SFF:~/Desktop/gmx-MMPBSA/Tutorial/Protein_protein$ gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 19 20 -ct com_traj.xtc
gmx_MMPBSA: command not found

  If I tried to run the same command by activating AmberTools20 (AmberTools21) environment, I get that gmx-mmpbsa command does not exist.

 I would appreciate if someone could help me with this.

**Comment by Valdes-Tresanco-MS** [comment]
Did you install AmberTools following the instructions on the Amber website?
If so, then it is normal that both are not in the same environment.
The **gmx_MMPBSA** installation instructions are based on the AmberTools compilation. The **gmx_MMPBSA** installation procedure, assuming you will install AmberTools as described on the Amber website, would be as follows:
`conda create --name AmberTools21`
`conda activate AmberTools21`
`conda install -c conda-forge mpi4py ambertools=21 compilers`
`python -m pip install PyQt5 gmx_MMPBSA`

To use **gmx_MMPBSA** you must always activate this environment

**Comment by srdjan125** [comment]
Hello,

  Thank you for help, now it is working. I was also trying something similar but with AmberTools20 (because I thought that I needto have AmberTools20) and it did not work.

   Greetings.
________________________________

**Comment by Valdes-Tresanco-MS** [comment]
**gmx_MMPBSA** is compatible with both the compiled version of `ambertools20` and the conda versions (`ambertools21`). Currently, we have a conda package that installs all the dependencies, so we'll be updating the documentation soon.
Cheers!
Mario S.

**Comment by srdjan125** [comment]
Hello,

 May I ask again for help.

I have run Generalized Born calculations for protein-protein system by opton:

    gmx_MMPBSA -O -i mmpbsa.in -cs Check.tpr -ci ind3.ndx -cg 19 20 -ct CheckB.xtc -cp topol1.top -cr First.pdb

At the end of calculations, gmx_ana givrs me only bar plots of final/average energies for complex, protein1, protein and delta.

   However, I want to see also plots of time evolution (for example VdW versus simulation time), but I cannot get it. In tutorials I can see that gmx_ana can give also those plots and I could export data I want into csv file.

     May I ask what is the issue?  Maybe I do not start calculation with right command?


________________________________

**Comment by marioernestovaldes** [comment]
Check these two videos 

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/analyzer/#binding-free-energy-calculation-gb-ie

And 

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/analyzer/#functionalities

Cheers!

**Comment by srdjan125** [comment]
Thank you 🙂 . I did not notice that I can click on delta/complex and it will give me more options to plot VdW, EL etc.  I also saw that I can write it into csv file at the end calculation by adding option -eo File_name.csv

    Greetings.
________________________________
