### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#123]
Currently, we have a docker container thanks to @vsdepontes. However, we haven't added it to the documentation yet. I will open this issue exclusively for it

_Originally posted by @vsdepontes in https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/55#issuecomment-874452029_

**Comment by vsdepontes** [comment]
Hello, @Valdes-Tresanco-MS! I have been short on time since the initial creation of the Dockerfile to the container image due to some professional changes, but everything have settle down for now and you can count me in on this issue. I will also review the Dockerfile and see if I can improve it.

**Comment by Valdes-Tresanco-MS** [comment]
We are working to release the version 1.5.0, so soon we will be updating the latest version. Likewise, with the creation of the conda package, we directly install mpi4py, ambertools, and the rest of the dependencies. It would only be necessary to install Gromacs (conda install -c bioconda gromacs [v2021.3]) and pyqt5 (python -m pip pyqt5). As soon as we release the new version we will be in contact to update those related to the docker container and the documentation
