### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by pacho2** [Valdes-Tresanco-MS/gmx_MMPBSA#125]
I was trying to learn about the different Generalized Born methods to use with GB calculations but documentation refers to a "Section 4" that I don't know where to find:
https://valdes-tresanco-ms.github.io/gmx_MMPBSA/input_file/#gb-namelist-variables
"Generalized Born method to use (seeSection 4). Allowed values are 1, 2, 5, 7 and 8"

Thanks a lot !

**Comment by Valdes-Tresanco-MS** [comment]
It refers to [chapter 4](https://ambermd.org/doc12/Amber21.pdf#chapter.4) in the Amber Documentation. I fixed it

**Comment by pacho2** [comment]
Thanks!
