### ISSUE TITLE
error when running gmx_MMPBSA_test

### ISSUE THREAD

**Issue by wangjiaqi8710** [Valdes-Tresanco-MS/gmx_MMPBSA#130]
Hello Sir,

I have encountered the below error when I try to run gmx_MMPBSA_test. Could you suggest a way to fix it? 
I used ubuntu 18.04 and have python3.6.9 installed in the system.

#The error message is 
"FileNotFoundError: [Errno 2] No such file or directory: 'gmx_MMPBSA_test/docs/examples/Protein_DNA_RNA_Ion_ligand/README.md'"

#The full output is shown below
$ gmx_MMPBSA_test
Error processing line 1 of /home/amber20/miniconda/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/amber20/miniconda/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
[INFO   ] Cloning gmx_MMPBSA repository in gmx_MMPBSA_test
Cloning into 'gmx_MMPBSA_test'...
remote: Enumerating objects: 10527, done.
remote: Counting objects: 100% (1233/1233), done.
remote: Compressing objects: 100% (299/299), done.
remote: Total 10527 (delta 848), reused 1100 (delta 735), pack-reused 9294
Receiving objects: 100% (10527/10527), 262.32 MiB | 2.71 MiB/s, done.
Resolving deltas: 100% (7454/7454), done.
Checking out files: 100% (456/456), done.
[INFO   ] Cloning gmx_MMPBSA repository...Done.
Traceback (most recent call last):
  File "/home/amber20/miniconda/bin/gmx_MMPBSA_test", line 8, in <module>
    sys.exit(gmxmmpbsa_test())
  File "/home/amber20/miniconda/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 146, in gmxmmpbsa_test
    run_test(parser)
  File "/home/amber20/miniconda/lib/python3.9/site-packages/GMXMMPBSA/tester.py", line 110, in run_test
    with open(test[x][0].joinpath('README.md')) as readme:
FileNotFoundError: [Errno 2] No such file or directory: 'gmx_MMPBSA_test/docs/examples/Protein_DNA_RNA_Ion_ligand/README.md'

Thank you for your help.

Jiaqi wang

**Describe the issue**
A clear and concise description of what the issue is.

**_If you will report an error, please complete this form_**
**To Reproduce**
1. Which system type are you running? (Protein-Protein, Protein-Ligand, etc)
2. The command-line are you using.

**Additional context**
The gmx_MMPBSA.log file

**Comment by Valdes-Tresanco-MS** [comment]
In the current version of the program (`v1.4.3`), it is a reported bug (See issue #46). It is solved by specifying the path where the folder will be created using the `-f` option explicitly. This error has already been fixed for the version v1.5.0 that is coming out soon

**Comment by wangjiaqi8710** [comment]
> In the current version of the program (`v1.4.3`), it is a reported bug (See issue #46). It is solved by specifying the path where the folder will be created using the `-f` option explicitly. This error has already been fixed for the version v1.5.0 that is coming out soon

may I know in which step should I specify the path? I currently install it based on what is suggested in this link https://valdes-tresanco-ms.github.io/gmx_MMPBSA/installation/.

$amber.python -m pip install PyQt5
$amber.python -m pip install gmx_MMPBSA

Am I doing it right?

Thanks for reply.
JQ

**Comment by Valdes-Tresanco-MS** [comment]
The error you get when running **gmx_MMPBSA_test** has been previously reported (See issue #46). To solve it you must explicitly define the address of the test folder with the `-f` option, for example, `gmx_MMPBSA_test -f /home/mario/Documents`. A folder called **gmx_MMPBSA_test** will be created at that address.
