### ISSUE TITLE
error while doing analysis with a ligand containing 1 virtual site

### ISSUE THREAD

**Issue by hima111997** [Valdes-Tresanco-MS/gmx_MMPBSA#136]
**Describe the issue**
A clear and concise description of what the issue is.
i have a trajectory file with a ligand containing one virtual site but it produced an error.
GromacsError: Only 3-point vsite type 1 is supported

**_If you will report an error, please complete this form_**
**To Reproduce**
1. Which system type are you running? (Protein-Protein, Protein-Ligand, etc)
i am running a protein-ligand system
2. The command-line are you using.
gmx_MMPBSA -O -i pbs.in -cs step5_production.tpr -cp topol.top -cr 6L6E_AVANAFIL_complex_noh.pdb -ci new_index.ndx -cg 1 13 -ct step5_production_noPBC.xtc

**Additional context**
The gmx_MMPBSA.log file
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8032588/gmx_MMPBSA.log)

**Comment by marioernestovaldes** [comment]
Hello there! Seems like your ligand contains halogens and your system was prepared with charmm-gui. If so, the ligand contains LP particles which are not supported in gmx_MMPBSA... you can follow this tutorial to work around this problem...

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/examples/Protein_ligand_LPH_atoms_CHARMMff/

let us know if that solves the problem...

cheers!
