### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: gmx_MMPBSA_ana does not run

### ISSUE THREAD

**Issue by hima111997** [Valdes-Tresanco-MS/gmx_MMPBSA#138]
### Bug summary

gmx_MMPBSA_ana does not open after finishing calculations.

The command used is:
gmx_MMPBSA -O -i new_pbs.in -cs str_noLP.pdb -cp topol.top -ci index_LPH.ndx -cg 1 18 -ct step5_production_noPBC_noLP.xtc

### Terminal output

```bash
Error processing line 1 of /home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of /home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
[INFO   ] Starting
[INFO   ] Command-line
  gmx_MMPBSA -O -i new_pbs.in -cs str_noLP.pdb -cp topol.top -ci index_LPH.ndx -cg 1 18 -ct step5_production_noPBC_noLP.xtc

[WARNING] protein_forcefield and ligand_forcefield variables are deprecate since version 1.4.1 and will be remove in the next version. Please, use forcefield instead.
[WARNING] entropy_seg variable is deprecate since version 1.4.2 and will be remove in v1.5.0. Please, use ie_segment instead.
[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/ibrahim/Downloads/amb/bin/cpptraj
[INFO   ] tleap found! Using /home/ibrahim/Downloads/amb/bin/tleap
[INFO   ] parmchk2 found! Using /home/ibrahim/Downloads/amb/bin/parmchk2
[INFO   ] sander found! Using /home/ibrahim/Downloads/amb/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER Topologies from GROMACS files...
[INFO   ] Checking gmxMMPBSA data folder exists in Amber data...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 1_18 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Complex: Saving group 1 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal ligand: Saving group 18 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Building Normal Complex Amber Topology...
[INFO   ] Writing Normal Complex Amber Topology...
[INFO   ] No Receptor topology files was defined. Using ST approach...
[INFO   ] Building AMBER Receptor Topology from Complex...
[INFO   ] No Ligand Topology files was defined. Using ST approach...
[INFO   ] Building AMBER Ligand Topology from Complex...
[INFO   ] Building AMBER Topologies from GROMACS files...Done.

[INFO   ] Loading and checking parameter files for compatibility...

CHAMBER prmtops found. Forcing use of sander
Preparing trajectories for simulation...
3 frames were processed by cpptraj for use in calculation.

Running calculations on normal system...

Beginning GB calculations with /home/ibrahim/Downloads/amb/bin/sander
  calculating complex contribution...
  calculating receptor contribution...
  calculating ligand contribution...

Timing:
Total GROMACS setup time:                  13.113 sec.
Total AMBER setup time:                     1.085 sec.
Creating trajectories with cpptraj:         0.151 sec.
Total calculation time:                    44.530 sec.

Total GB calculation time:                 44.529 sec.

Statistics calculation & output writing:    0.027 sec.
Total time taken:                          59.042 sec.
[INFO   ] 

Thank you for using gmx_MMPBSA. Please cite us if you publish this work with this reference:
    Mario S. Valdés Tresanco, Mario E. Valdes-Tresanco, Pedro A. Valiente, & Ernesto Moreno Frías 
    gmx_MMPBSA (Version v1.4.2). Zenodo. http://doi.org/10.5281/zenodo.4569307

Also consider citing MMPBSA.py
    Miller III, B. R., McGee Jr., T. D., Swails, J. M. Homeyer, N. Gohlke, H. and Roitberg, A. E.
    J. Chem. Theory Comput., 2012, 8 (9) pp 3314-3321

[INFO   ] Opening gmx_MMPBSA_ana to analyze results...

Error processing line 1 of /home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
WARNING:root:_GMXMMPBSA_info not found
ERROR:root:MMPBSA_Error No info files found!.
           Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/home/ibrahim/Downloads/amb/miniconda/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana
    ifiles = get_files(parser)
  File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/GMXMMPBSA/analyzer/utils.py", line 162, in get_files
    GMXMMPBSA_ERROR('No info files found!')
  File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '. Check the gmx_MMPBSA.log file to report the problem.')
GMXMMPBSA.exceptions.MMPBSA_Error: No info files found!. Check the gmx_MMPBSA.log file to report the problem.
[ERROR  ] Unable to start gmx_MMPBSA_ana...
[INFO   ] Finalized...
```

### Actual outcome

[INFO   ] Opening gmx_MMPBSA_ana to analyze results...

Error processing line 1 of /home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
WARNING:root:_GMXMMPBSA_info not found
ERROR:root:MMPBSA_Error No info files found!.
           Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/home/ibrahim/Downloads/amb/miniconda/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana
    ifiles = get_files(parser)
  File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/GMXMMPBSA/analyzer/utils.py", line 162, in get_files
    GMXMMPBSA_ERROR('No info files found!')
  File "/home/ibrahim/Downloads/amb/miniconda/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '. Check the gmx_MMPBSA.log file to report the problem.')
GMXMMPBSA.exceptions.MMPBSA_Error: No info files found!. Check the gmx_MMPBSA.log file to report the problem.
[ERROR  ] Unable to start gmx_MMPBSA_ana...
[INFO   ] Finalized...

### Expected outcome

gmx_MMPBSA_ana runs correctly

### Additional information

these are the input parameters:
&general
startframe=1,interval=1, endframe=3,
temperature=310, solvated_trajectory=0,
verbose=1, keep_files=0,
strip_mask=":WAT:CLA:SOD"
/
&gb
igb=5, saltcon=0.154
/
&decomp
idecomp=2, dec_verbose=2, csv_format=1, print_res="within 10"
/

### Operating system

i am using ubuntu 20.04

### gmx_MMPBSA_ana Version

gmx_MMPBSA_ana v1.4.3 based on MMPBSA version 16.0

### Python version

Python 3.9.10

### Installation

AmberTools compilation + pip

**Comment by Valdes-Tresanco-MS** [comment]
Can you check that the `_GMXMMPBSA_info` file is in the run folder? If so, can you run `gmx_MMPBSA_ana -f _GMXMMPBSA_info`?

**Comment by hima111997** [comment]
no it is not in the folder

**Comment by Valdes-Tresanco-MS** [comment]
Since **gmx_MMPBSA** finished fine, I would expect the `_GMXMMPBSA_info` file to be in the folder. I am not sure if it has something to do with that module error that is shown, because I have never seen this case. It seems that your environment has conflicts. Could you try following these [installation instructions](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/129#issuecomment-1024415800) if you get the same error?

**Comment by hima111997** [comment]
i removed Ambertools21 and installed it using anaconda by following the instructions in the link you provided. then ran an analysis but the same error appeared:

WARNING:root:_GMXMMPBSA_info not found
ERROR:root:MMPBSA_Error No info files found!.
           Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/AmberTools21/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/home/ibrahim/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana
    ifiles = get_files(parser)
  File "/home/ibrahim/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/analyzer/utils.py", line 162, in get_files
    GMXMMPBSA_ERROR('No info files found!')
  File "/home/ibrahim/anaconda3/envs/AmberTools21/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '. Check the gmx_MMPBSA.log file to report the problem.')
GMXMMPBSA.exceptions.MMPBSA_Error: No info files found!. Check the gmx_MMPBSA.log file to report the problem.

the input file i used is this:

&general
startframe=1, endframe=3,interval=1,temperature=310,
verbose=1, keep_files=0,
strip_mask=":WAT:CLA:SOD"
/
&gb
igb=5, saltcon=0.154
/
&decomp
idecomp=2, dec_verbose=2, csv_format=1, print_res="within 10"
/

maybe should i change the verbose value? since the file contains _ at the start and end of the file name?

**Comment by Valdes-Tresanco-MS** [comment]
> maybe should i change the verbose value? since the file contains _ at the start and end of the file name?

The `verbose` variable only determines which term will be displayed in the output files. Unfortunately, I can't reproduce this error.
Are you running one of our examples or is it your system? If it's your system, consider sending us your files so we can check if it's a **gmx_MMPBSA** error

Mario S.

**Comment by hima111997** [comment]
I tried one of examples and it opened correctly. i noticed that the number of files produced from the example is larger than my data an in the .in file of the example does not contain keep_files=0 which is found in my case. so i removed this argument and it opened well. 
So the solution is not to write keep_files = 0 in the input file

**Comment by hima111997** [comment]
now i have another problem which is that when i try to open pymol by pressing the V checkbox it says that pymol is not in path. however i downloaded python from their website using the linux tar.bz archive as the installation command produced conflicts and made and alias to run it

**Comment by Valdes-Tresanco-MS** [comment]
> I tried one of examples and it opened correctly. i noticed that the number of files produced from the example is larger than my data and the .in file of the example does not contain keep_files=0 which is found in my case. so i removed this argument and it opened well. **So the solution is not to write keep_files = 0 or 1 in the input file. it must be 2 for gmx_MMPBSA_ana to work**

The `keep_files` variable cannot be modified, so it is not defined in the documentation. I didn't even notice it in your input file. Since **gmx_MMPBSA_ana** use all data explicitly, it requires all files to be in the working directory. To avoid the huge number of files that are generated, we are working on implementing a single file, but it is still in the experimental phase.

>now i have another problem which is that when i try to open pymol by pressing the V checkbox it says that pymol is not in path. however i downloaded python from their website using the linux tar.bz archive as the installation command produced conflicts and made and alias to run it

This happens because `aliases` are not executables, but command lines. To redefine an executable in the `PATH`, simply add the program bin folder or [create a symbolic link](https://linuxize.com/post/how-to-create-symbolic-links-in-linux-using-the-ln-command/) of the executable

**Comment by hima111997** [comment]
thank you. i added it to the path and it is now working well
