### ISSUE TITLE
Error when trajectory does not start at time = 0

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#14]
The PDB file is extracted using trjconv at time = 0. Would it be better to use editconf to generate the PDB file? editconf has the disadvantage that it uses the tpr structure instead of the initial structure of the trajectory. In most cases, these structures must match

**Comment by marioernestovaldes** [comment]
editconf is use to generate the structure out of the .tpr file
