### ISSUE TITLE
[Bug-gmx_MMPBSA]: Ala scaning Error

### ISSUE THREAD

**Issue by Paulie-ai** [Valdes-Tresanco-MS/gmx_MMPBSA#145]
### Bug summary

MMPBSA_Error: Wrong notation... You most define the residue to mutate as follow: CHAIN:RES_NUMBER or CHAIN:RES_NUMBER:INSERTION_CODE. Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.

### Terminal output

```bash
MMPBSA_Error: Wrong notation... You most define the residue to mutate as follow: CHAIN:RES_NUMBER or CHAIN:RES_NUMBER:INSERTION_CODE. Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

blank

### Operating system

Linux

### gmx_MMPBSA Version

gmx_MMPBSA v1.4.3 based on MMPBSA version 16.0 and AmberTools 20

### Python version

3.9

### Installation

conda AmberTools + pip

**Comment by Valdes-Tresanco-MS** [comment]
You have to be more specific. The error is clear, but I can't figure out what you defined to get it.

**Comment by Paulie-ai** [comment]
I find in Alanine scanning test file, the&nbsp;mmpbsa.in file should correct&nbsp;as mutant_res='B:13' not mutant_res='B/13', the problem is solved.
Thanks for your reply!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Valdes-Tresanco-MS/gmx_MMPBSA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 中午1:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Bug-gmx_MMPBSA]: Ala scaning Error (Issue #145)





 
You have to be more specific. The error is clear, but I can't figure out what you defined to get it.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Valdes-Tresanco-MS** [comment]
> I find in Alanine scanning test file, the&nbsp;mmpbsa.in file should correct&nbsp;as mutant_res='B:13' not mutant_res='B/13', the problem is solved. Thanks for your reply!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Valdes-Tresanco-MS/gmx_MMPBSA" ***@***.***&gt;; 发送时间:&nbsp;2022年2月17日(星期四) 中午1:19 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Bug-gmx_MMPBSA]: Ala scaning Error (Issue #145) You have to be more specific. The error is clear, but I can't figure out what you defined to get it. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

That is because this notation is for the new version (v1.5.0). Sorry about that.
