### ISSUE TITLE
trjconv failed when querying md.tpr

### ISSUE THREAD

**Issue by mar-ko2020** [Valdes-Tresanco-MS/gmx_MMPBSA#15]
Hi 
I am trying to calculate the mmpbsa between a protein and DNA. I use the following command
gmx_MMPBSA -O -i mmpbsa.in -cs md.tpr -ci index.ndx -cg 1 15 -ct md.xtc
However, it gives me this error and the job stops after a few minutes
MMPBSA_Error: /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/gromacs/2020.4/bin/gmx trjconv failed when querying md.tpr
Exiting. All files have been retained.
I used gromacs2020 and the pbc was removed from the trajectory. 
Any help would be appreciated.
Thanks!

**Comment by Valdes-Tresanco-MS** [comment]
You can share The error information is contained in the `make_top.log` file. Sorry about that.:sweat_smile: We are working to improve the error output. Can you share the file `make_top.log`?. If it has sensitive information you can send it to my email.

**Comment by mar-ko2020** [comment]
Thanks Valdes. Could you share your email address, please?

**Comment by Valdes-Tresanco-MS** [comment]
mariosergiovaldes145@gmail.com

**Comment by gayatripanda5** [comment]
Hi, 
I also facing the same issue. gmx_MMPBSA worked perfectly fine with files in Protein-DNA examples but failed while running it for my files.

Command used: gmx_MMPBSA -O -i mmpbsa_onlygbsa.in -cs md_0-900ns-1000ns_nodt_nocpmact.tpr -ci index_prot.ndx  -cg 1 12 -ct md_0-900ns-1000ns_nodt_nocpmact.xtc


 Error reported: File "/home/gayatrip/miniconda3/envs/amber/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '. Check the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: /home/gayatrip/gromacs-2020/build/bin/gmx trjconv failed when querying md_0-900ns-1000ns_nodt_nocpmact.tpr. Check the gmx_MMPBSA.log file to report the problem.

Could you please tell me where am I going wrong?

Thanks in advance

**Comment by marioernestovaldes** [comment]
Could you please send us the files (.in, .tpr, .xtc, .ndx) for review...
That way will be easy for us to determine where the error is quickly...
make sure to send just a piece of the xtc (10 frames)

**Comment by gayatripanda5** [comment]
Hi, 
Apologies for the delayed response! Shall I send these files at this email id: mariosergiovaldes145@gmail.com?

**Comment by Valdes-Tresanco-MS** [comment]
> Hi,
> Apologies for the delayed response! Shall I send these files at this email id: [mariosergiovaldes145@gmail.com](mailto:mariosergiovaldes145@gmail.com)?

Yes, you can send me the files.

For future errors, doubts or problems, please open a new issue. If you think your issue is similar to an existing one you can simply reference it as #issue number (no spaces, eg #15 for the current one). This makes it easier for us to follow up properly since once an issue is closed it means that it has been solved. We appreciate your understanding and we will help you solve your problem.

Best!
Mario S.

**Comment by gayatripanda5** [comment]
Dear Mario S.,

Apologies for the inconvenience caused!. I have submitted this as a new issue. It is easier for me also to track down any update associated with this issue. Thanks for this suggestion. Also, as suggested by you, I have shared with you the required files.

**Comment by Ridwan20-alt** [comment]
Hi
I am trying to calculate the mmpbsa between a protein and a ligand with LPH atoms. After following this tutorial(https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/tree/master/examples/Protein_ligand_LPH_atoms_CHARMMff) to prepare my input files I use the following command:
 gmx_MMPBSA -O -i mmpbsa.in -cs str_noLP.pdb -ci index_mod_gromacs.ndx -cg 1 18 -ct com_traj.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv
However, it gives me this error and the job stops after a few minutes:
[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 1_18 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[ERROR  ] MMPBSA_Error /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/gromacs/2021.4/bin/gmx editconf failed when querying com_traj.xtc.
           Check the gmx_MMPBSA.log file to report the problem.
  File "/scratch/oladayo/Dynamics/LIG2/L32/L32/venv_gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/scratch/oladayo/Dynamics/LIG2/L32/L32/venv_gmxMMPBSA/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/scratch/oladayo/Dynamics/LIG2/L32/L32/venv_gmxMMPBSA/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 533, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/scratch/oladayo/Dynamics/LIG2/L32/L32/venv_gmxMMPBSA/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 116, in buildTopology
    self.gmx2pdb()
  File "/scratch/oladayo/Dynamics/LIG2/L32/L32/venv_gmxMMPBSA/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 232, in gmx2pdb
    GMXMMPBSA_ERROR('%s failed when querying %s' % (' '.join(comprog), self.FILES.complex_trajs[0]))
  File "/scratch/oladayo/Dynamics/LIG2/L32/L32/venv_gmxMMPBSA/lib/python3.8/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/gromacs/2021.4/bin/gmx editconf failed when querying com_traj.xtc
Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.

**Comment by Ridwan20-alt** [comment]
I will be glad if you can guide me on to get this error resolved

Thanks

**Comment by Valdes-Tresanco-MS** [comment]
Please, open a new issue to better follow up on the problem and attach the gmx_MMPBSA.log file

**Comment by elahehtavili** [comment]
Hi
I am trying to calculate the mmpbsa between a protein and protein. I use the following command
gmx_MMPBSA -O -i mmpbsa.in -cs md_2_3.tpr -ci index.ndx -cg 17 18 -ct  final_noPBC.xtc
However, it gives me this error and the job stops after a few minutes
/opt/miniconda/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx trjconv failed when querying final_noPBC.xtc

Check the gmx_MMPBSA.log file to report the problem.
  File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 687, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 123, in buildTopology
    self.gmx2pdb()
  File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 289, in gmx2pdb
    GMXMMPBSA_ERROR('%s failed when querying %s' % (' '.join(comprog), self.FILES.complex_trajs[0]))
  File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 171, in __init__
    raise exc('\n\n' + msg + '\n\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error:

/opt/miniconda/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx trjconv failed when querying final_noPBC.xtc

Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.

I used gromacs2020 and the pbc was removed from the trajectory.
Any help would be appreciated.
Thanks!

**Comment by elahehtavili** [comment]
Hi
I am trying to calculate the mmpbsa between a protein and protein. I use the following command
gmx_MMPBSA -O -i mmpbsa.in -cs md_2_3.tpr -ci index.ndx -cg 17 18 -ct final_noPBC.xtc
However, it gives me this error and the job stops after a few minutes
/opt/miniconda/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx trjconv failed when querying final_noPBC.xtc

Check the gmx_MMPBSA.log file to report the problem.
File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in
sys.exit(gmxmmpbsa())
File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
app.make_prmtops()
File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 687, in make_prmtops
self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 123, in buildTopology
self.gmx2pdb()
File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 289, in gmx2pdb
GMXMMPBSA_ERROR('%s failed when querying %s' % (' '.join(comprog), self.FILES.complex_trajs[0]))
File "/opt/miniconda/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 171, in init
raise exc('\n\n' + msg + '\n\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error:

/opt/miniconda/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx trjconv failed when querying final_noPBC.xtc

Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.

I used gromacs2022 and the pbc was removed from the trajectory.
Any help would be appreciated.
Thanks!

**Comment by Valdes-Tresanco-MS** [comment]
@elahehtavili This issue is already closed and corresponds to an old version. Please, open a new issue and attach all required information and files.
