### ISSUE TITLE
[ENH]: Add tooltips to chart options

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#151]
### In which tool?

gmx_MMPBSA_ana

### New Feature

Add tooltips to chart options

### Relevance

medium

### Difficulty to implement

low

**Comment by marioernestovaldes** [comment]
fixed via https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/commit/0ed1962376b2cac2291ca5df38405f04dad7626b
