### ISSUE TITLE
[Bug-gmx_MMPBSA]: change 3D-RISM calculation to sander

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/gmx_MMPBSA#153]
### Bug summary

Overload CPU usage when using `rism3d.snglpnt`... same with sander? needs more tests...

### Terminal output

```bash
None
```

### gmx_MMPBSA.log

None

**Comment by marioernestovaldes** [comment]
added via 8ff8f752e98ba7dd42d1d4b0479fa9fdbbda111f, c7673e536d72927f29c1ced4bfb2018a88b8b05b, 31ad74765f3bbbef1f04058f995292a5c8701e66, 0f2bd659f5b06dcc9f192722b0b341995a94a23b, f0033f7de5f2a90593c4943c20ab9b939e2410da

**Comment by AbdelmoujoudFaris** [comment]
but when I launch mmgbsa I have met this problem : bin/gmx editconf failed when querying com_traj.xtc.
           Check the gmx_MMPBSA.log file to report the problem.
