### ISSUE TITLE
[Bug-gmx_MMPBSA]: Doesn't exit when input parameters are invalid

### ISSUE THREAD

**Issue by wrmartin** [Valdes-Tresanco-MS/gmx_MMPBSA#156]
### Bug summary

gmx_MMPBSA does not exit when one of the input parameters is invalid. Running "mpirun -np 16 gmx_MMPBSA MPI -O -i mmpbsa.in -cs last.pdb -ci mmpbsa.ndx -cg "Pro" "II" -ct fixed.xtc -cp topol.top -nogui" results in all 16 cores being held at 100% usage with no exit.

### Terminal output

```bash
[INFO   ] Starting gmx_MMPBSA v1.5.0+2.gc36d71b
[INFO   ] Command-line
  mpirun -np 16 gmx_MMPBSA MPI -O -i mmpbsa.in -cs last.pdb -ci mmpbsa.ndx -cg Pro II -ct fixed.xtc -cp topol.top -nogui

usage: gmx_MMPBSA
       [-h]
       [-v]
       [--input-file-help]
       [--create_input [{gb,pb,rism,ala,decomp,nmode,all} ...]]
       [-O]
       [-prefix <file prefix>]
       [-i FILE]
       [-xvvfile XVVFILE]
       [-o FILE]
       [-do FILE]
       [-eo FILE]
       [-deo FILE]
       [-nogui]
       [-s]
       [-cs <Structure File>]
       [-ci <Index File>]
       [-cg index index]
       [-ct [TRJ ...]]
       [-cp <Topology>]
       [-cr <PDB File>]
       [-rs <Structure File>]
       [-ri <Index File>]
       [-rg index]
       [-rt [TRJ ...]]
       [-rp <Topology>]
       [-lm <Structure File>]
       [-ls <Structure File>]
       [-li <Index File>]
       [-lg index]
       [-lt [TRJ ...]]
       [-lp <Topology>]
       [--rewrite-output]
       [--clean]
gmx_MMPBSA: error: argument -cg: invalid int value: 'Pro'
```

### gmx_MMPBSA.log

[INFO   ] Starting gmx_MMPBSA v1.5.0+2.gc36d71b
[DEBUG  ] WDIR          : /mnt/beegfs/martinw3/working/Pro/WT_2
[DEBUG  ] AMBERHOME     : /cm/shared/apps/amber/21
[DEBUG  ] PYTHON EXE    : /cm/shared/apps/amber/21/miniconda/bin/python
[DEBUG  ] PYTHON VERSION: 3.9.5 (default, Jun  4 2021, 12:28:51) [GCC 7.5.0]
[DEBUG  ] MPI           : /usr/mpi/gcc/openmpi-4.0.3rc4/bin/mpirun
[DEBUG  ] ParmEd        : 3.4.1
[DEBUG  ] OS PLATFORM   : Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-glibc2.17
[DEBUG  ] OS SYSTEM     : Linux
[DEBUG  ] OS VERSION    : #1 SMP Tue Feb 4 23:02:59 UTC 2020
[DEBUG  ] OS PROCESSOR  : x86_64

[INFO   ] Command-line
  mpirun -np 16 gmx_MMPBSA MPI -O -i mmpbsa.in -cs last.pdb -ci mmpbsa.ndx -cg Pro II -ct fixed.xtc -cp topol.top -nogui

### Operating system

Linux (Slurm batch system)

### gmx_MMPBSA Version

1.5.0

### Python version

3.9.5

**Comment by wrmartin** [comment]
I'm aware the solution to get around this is "use numbers", but I figured I should report it. Additionally, it would be nice in some cases if the index groups could be given as their string instead of just the group number if it's something that's not a pain to do.

**Comment by Valdes-Tresanco-MS** [comment]
Hi Martin, thanks for reporting the error.
Sure, we can review this option to implement it soon. Please, open a new issue (Feature request) to give it a better follow-up
