### ISSUE TITLE
[ENH]: Allow index group name for group selection

### ISSUE THREAD

**Issue by wrmartin** [Valdes-Tresanco-MS/gmx_MMPBSA#157]
### In which tool?

gmx_MMPBSA

### New Feature

In addition to the number for the index group selection, allow the string for the group. For instance, instead of group 0, using "System".

### Relevance

low

**Comment by Valdes-Tresanco-MS** [comment]
@wrmartin After a long time, I implemented this feature. It would be helpful if you tell me if it works for you.

**Comment by wrmartin** [comment]
I will update, give it a shot, and let you know! Thanks!

**Comment by wrmartin** [comment]
No go. Log attached; hopefully it's enough information.

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10581772/gmx_MMPBSA.log)

**Comment by Valdes-Tresanco-MS** [comment]
Can you send me this system? In the tests I did it worked without any problems

**Comment by wrmartin** [comment]
Nevermind, it works. I had a broken .xtc file.
