### ISSUE TITLE
ModuleNotFoundError: No module named 'parmed'

### ISSUE THREAD

**Issue by btam125** [Valdes-Tresanco-MS/gmx_MMPBSA#16]
Hi, 

I have followed the previous issue about this error, however I still unable to solve this problem. 

in my ~./bashrc, I have put the path: 

source /home/user/Coral/software/amber20_src/amber.sh
export PYTHONPATH="/home/user/Coral/software/amber20_src/miniconda/bin:$PATH"

and when I echo $PYTHONPATH:

(myvenv) [login-0-0 gmx_MMPBSA-1.1.1]$ echo $PYTHONPATH
/home/user/Coral/software/amber20_src/lib/python3.8/site-packages

Can you give me a hand? 

Best,

Ben

**Comment by Valdes-Tresanco-MS** [comment]
Hi Ben.

Did you install `gmx_MMPBSA` using `amber.python` or from Amber's conda environment?

Can you make sure if it is the python of Amber's conda environment? To do this, run in a terminal:
    
    amber.python

and later
    
    import parmed

If it still doesn't work, disable environment `myenv` and try again

**Comment by btam125** [comment]
Hi Valdes,

I tried it again with myenv disable. The same thing happened after I put it down: 

[ben@login-0-0 base_2]$ am
am1bcc         amber.conda    amber.ipython  amber.jupyter  amber.pip      amber.python   amuFormat.sh
[ben@login-0-0 base_2]$ amber.python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import parmed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'parmed'

**Comment by Valdes-Tresanco-MS** [comment]
Please, check this line...
I see that you source and export the `amber20_src` folder. 

> source /home/user/Coral/software/amber20_src/amber.sh
> export PYTHONPATH="/home/user/Coral/software/amber20_src/miniconda/bin:$PATH"
> 
> and when I echo $PYTHONPATH:
> 
> (myvenv) [login-0-0 gmx_MMPBSA-1.1.1]$ echo $PYTHONPATH
> /home/user/Coral/software/amber20_src/lib/python3.8/site-packages

According to the amber configuration, when it is installed it does so in the `amber20` folder. Please check this. You are probably exporting the wrong `amber.sh`.

**Comment by Valdes-Tresanco-MS** [comment]
Hi Ben
Finally, have you been able to solve the issue?

**Comment by btam125** [comment]
Hi,

No, I am unable to solve the issue at the moment. Still working on it.

Best,

Ben

**Comment by Valdes-Tresanco-MS** [comment]
Hi Ben.
You still have not been able to solve the problem?

**Comment by Valdes-Tresanco-MS** [comment]
We close this issue due to inactivity. We hope you have resolved the problem. If not, feel free to open a new issue or write to us directly.
