### ISSUE TITLE
[Bug-gmx_MMPBSA]: 

### ISSUE THREAD

**Issue by mtpae** [Valdes-Tresanco-MS/gmx_MMPBSA#172]
### Bug summary

Hello all, I am facing this error while running the MMPBSA calculation. I have attached the log file also. Please help me. 

### Terminal output

```bash
image attached with log file
```

### gmx_MMPBSA.log

![Screenshot from 2022-03-01 14-17-46](https://user-images.githubusercontent.com/92774704/156139292-7b7b10a3-b2ed-4bf8-97df-bf947ec6ef79.png)
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8160289/gmx_MMPBSA.log)

### Operating system

ubuntu 

### gmx_MMPBSA Version

1.4

**Comment by marioernestovaldes** [comment]
seems like something is going on with the topology as ParmEd is trying to obtain the values for epsilon and sigma and doesn't find anything... Update if possible the program as it is in v1.5.0.3 already and see if the error persists. If the error still persists after upgrading you can send us the files to see if we can spot the problem...

cheers!

**Comment by mtpae** [comment]
I am not able to update the version because I have already performed the MMPBSA calculation for some ligands. Is there any other option?

**Comment by marioernestovaldes** [comment]
It's ok...send us the files to see what's the problem and find a solution...

**Comment by mtpae** [comment]
@marioernestovaldes  I have attached the required files.
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8161767/gmx_MMPBSA.log)
[mmpbsa.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8161768/mmpbsa.txt)
[MMPBSA.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8161775/MMPBSA.zip)

**Comment by Valdes-Tresanco-MS** [comment]
Please note that the topology file contains several references to `itp` files. You must also include the folder `charmm36-mar2019.ff`

**Comment by marioernestovaldes** [comment]
@mtpae in the topol.top file, line 23, add a semicolon at the beginning of the line
```
;
;	File 'topol.top' was generated
;	By user: dhaval (1000)
;	On host: dhaval-X570-AORUS-PRO-WIFI
;	At date: Mon Feb 28 17:46:20 2022
;
;	This is a standalone topology file
;
;	Created by:
;	            :-) GROMACS - gmx pdb2gmx, 2020.1-Ubuntu-2020.1-1 (-:
;	
;	Executable:   /usr/bin/gmx
;	Data prefix:  /usr
;	Working dir:  /home/dhaval/Desktop/Analysis/Meet/PRO1_3191
;	Command line:
;	  gmx pdb2gmx -f receptor.pdb -ignh
;	Force field was read from current directory or a relative path - path added.
;

; Include forcefield parameters
#include "./charmm36-mar2019.ff/forcefield.itp"

;Include ligand topology <-- this line should start with semicolon
#include "ligand.itp"

[ moleculetype ]
...
```

This should solve the problem... let us know if you have any other issues...

cheers!
