### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: charts options

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/gmx_MMPBSA#185]
### Bug summary

fix the following charts options:
- [x] `Reset to default` updates correctly the options tree but not the graphs

Line Plot
- [x] legend-fontsize
- [x] figure-width and height

Bar plot
- [x] error-line width
- [x] ~error-line color~
- [x] figure-width and height

Heatmap plot
- [x] ~per-residue num-xticks~
- [x] per-wise and residue annotation
- [x] fontsize-legend
- [x] fontsize colorbar-ticks
- [x] fontsize colorbar-label
- [x] fontsize annotation
- [x] figure-width and height

Visualization
- [x] check everything but chain-helper and palette

Control
- [x] maximize button crashes the app with the following error

```
File "/media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/gmxMMPBSA/lib/python3.9/site-packages/matplotlib/backends/backend_qt.py", line 262, in enterEvent
    x, y = self.mouseEventCoords(self._get_position(event))
AttributeError: 'QResizeEvent' object has no attribute 'pos'
Aborted (core dumped)

```

**Comment by Valdes-Tresanco-MS** [comment]
> * [x]  maximize button crashes the app with the following error
> 
> ```
> File "/media/mario/92bb1dc0-1f5c-4566-bfea-709a64de54f8/mario/Programs/Installation/AmberTools20/amber20/miniconda/envs/gmxMMPBSA/lib/python3.9/site-packages/matplotlib/backends/backend_qt.py", line 262, in enterEvent
>     x, y = self.mouseEventCoords(self._get_position(event))
> AttributeError: 'QResizeEvent' object has no attribute 'pos'
> Aborted (core dumped)
> ```

This is a [bug](https://github.com/matplotlib/matplotlib/issues/22409) reported by me in the matplotlib repository with no apparent solution. You get it when combining PyQt5 and matplotlib=3.5.1. It does not happen with PyQt6, so if possible, use this one instead of PyQt5.
