### ISSUE TITLE
[Question]: what are the files needed for gmx_MMPBSA_ana to run?

### ISSUE THREAD

**Issue by hima111997** [Valdes-Tresanco-MS/gmx_MMPBSA#186]
### My Question is...

what are the files needed for gmx_MMPBSA_ana to run?

**Comment by Valdes-Tresanco-MS** [comment]
**gmx_MMPBSA_ana** requires, at the moment, that all output files of **gmx_MMPBSA** be present. Although we implemented a single output file, it is not yet production-ready. In case you have not defined it explicitly, **gmx_MMPBSA_ana** will always be launched after the calculations are finished. You can still do it yourself as specified in the [documentation](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/gmx_MMPBSA_ana_running/#running-gmx_mmpbsa_ana)

**Comment by hima111997** [comment]
okay thank you
