### ISSUE TITLE
Support for GROMOS force field

### ISSUE THREAD

**Issue by Jameel9** [Valdes-Tresanco-MS/gmx_MMPBSA#197]
Hello Sir

Is there any plan for updates that support GROMOS96 forcefields?

**Comment by Valdes-Tresanco-MS** [comment]
Gromos has a different structure than Amber, so it is not compatible with the current calculation tool. However, we are planning the implementation of `APBS` and other external tools that would allow the calculations to be done with `GROMOS` (#195 and #198). Please note that these methods are not parameterized with `GROMOS`, so the results may be questionable.
