### ISSUE TITLE
It shows Warning...will it create some issue ?

### ISSUE THREAD

**Issue by debanjansen48** [Valdes-Tresanco-MS/gmx_MMPBSA#2]
Hope  installed it.. But returns following WARNING...

$:amber.python -m pip install gmx_MMPBSA
Collecting gmx_MMPBSA
  Downloading gmx_MMPBSA-1.0.0-py3-none-any.whl (135 kB)
     |████████████████████████████████| 135 kB 962 kB/s 
Installing collected packages: gmx-MMPBSA
  WARNING: The scripts gmx_MMPBSA and gmx_MMPBSA_gui are installed in '/home/debanjan/Amber/amber20/miniconda/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed gmx-MMPBSA-1.0.0

when I call it from the installed directory " **'/home/debanjan/Amber/amber20/miniconda/bin**"  it returns following error
(base) debanjan@debanjan:~/Amber/amber20/miniconda/bin$ gmx
gmx             gmx_d           gmx_MMPBSA      gmx_MMPBSA_gui
(base) debanjan@debanjan:~/Amber/amber20/miniconda/bin$ gmx_MMPBSA_gui 
Traceback (most recent call last):
  File "/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 24, in <module>
    from GMXMMPBSA import main
  File "/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 44, in <module>
    from GMXMMPBSA.createinput import create_inputs
  File "/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/createinput.py", line 43, in <module>
    from parmed.amber.mdin import Mdin
ModuleNotFoundError: No module named 'parmed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gmx_MMPBSA_gui", line 5, in <module>
    from GMXMMPBSA.app import gmxmmpbsa_gui
  File "/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 30, in <module>
    raise ImportError('Could not import Amber Python modules. Please make sure '
ImportError: Could not import Amber Python modules. Please make sure you have sourced /home/debanjan/Amber/amber20/amber.sh (if you are using sh/ksh/bash/zsh) or /home/debanjan/Amber/amber20/amber.csh (if you are using csh/tcsh)
(base) debanjan@debanjan:~/Amber/amber20/miniconda/bin$ gmx_MMPBSA
Traceback (most recent call last):
  File "/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 24, in <module>
    from GMXMMPBSA import main
  File "/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 44, in <module>
    from GMXMMPBSA.createinput import create_inputs
  File "/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/createinput.py", line 43, in <module>
    from parmed.amber.mdin import Mdin
ModuleNotFoundError: No module named 'parmed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gmx_MMPBSA", line 5, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File "/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 30, in <module>
    raise ImportError('Could not import Amber Python modules. Please make sure '
ImportError: Could not import Amber Python modules. Please make sure you have sourced /home/debanjan/Amber/amber20/amber.sh (if you are using sh/ksh/bash/zsh) or /home/debanjan/Amber/amber20/amber.csh (if you are using csh/tcsh)
(base) debanjan@debanjan:~/Amber/amber20/miniconda/bin$ 

**However parmed is installed**
(base) debanjan@debanjan:~/Amber/amber20/miniconda/bin$ parm
parmcal   parmchk2  parmed    
(base) debanjan@debanjan:~/Amber/amber20/miniconda/bin$ whereis parmed
parmed: /usr/local/bin/parmed /home/debanjan/Amber/amber20/bin/parmed

**Comment by Valdes-Tresanco-MS** [comment]
Please, check two things:
- Open the executable (/home/debanjan/Amber/amber20/miniconda/bin/gmx_MMPBSA) with a text editor and show me the content.
- run amber.python in a terminal and then show me the output when you enter the following line
    `import parmed`

**Comment by debanjansen48** [comment]
*Open the executable (/home/debanjan/Amber/amber20/**miniconda/bin/gmx_MMPBSA)
with a text editor and show me the content.*
#!/home/debanjan/Amber/amber20/bin/amber.python
# -*- coding: utf-8 -*-
import re
import sys
from GMXMMPBSA.app import gmxmmpbsa
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(gmxmmpbsa())
*run amber.python in a terminal and then show me the output when you enter
the following line*

(base) debanjan@debanjan:~/Desktop$ amber.python
Python 3.8.3 (default, May 19 2020, 18:47:26)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import parmed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'parmed'

**Comment by Valdes-Tresanco-MS** [comment]
Ok the problem is that amber.python does not detect the parmed module. This is probably because the python modules are not in the default path or the amber source has not been done correctly. Try adding this line to your .bashrc file
`/home/debanjan/Amber/amber20/amber.sh`

**Comment by debanjansen48** [comment]
I added that line in  ~/.bashrc

than source ~/.bashrc

from the folder ~miniconda/bin i call gmx_MMPBSA
(base) debanjan@debanjan:~/Amber/amber20/miniconda/bin$ gmx_MMPBSA
Traceback (most recent call last):
  File
"/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/app.py",
line 24, in <module>
    from GMXMMPBSA import main
  File
"/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/main.py",
line 44, in <module>
    from GMXMMPBSA.createinput import create_inputs
  File
"/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/createinput.py",
line 43, in <module>
    from parmed.amber.mdin import Mdin
ModuleNotFoundError: No module named 'parmed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gmx_MMPBSA", line 5, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File
"/home/debanjan/Amber/amber20/miniconda/lib/python3.8/site-packages/GMXMMPBSA/app.py",
line 30, in <module>
    raise ImportError('Could not import Amber Python modules. Please make
sure '
ImportError: Could not import Amber Python modules. Please make sure you
have sourced /home/debanjan/Amber/amber20/amber.sh (if you are using
sh/ksh/bash/zsh) or /home/debanjan/Amber/amber20/amber.csh (if you are
using csh/tcsh)

it returns error

**Comment by Valdes-Tresanco-MS** [comment]
Please, check the PYTHONPATH variable
`echo $PYTHONPATH`

**Comment by debanjansen48** [comment]
(base) debanjan@debanjan:~$ echo $PYTHONPATH
/home/debanjan/MGLTools-1.5.7/bin/python

**Comment by debanjansen48** [comment]
i removed this path "/home/debanjan/MGLTools-1.5.7/bin/python"

(base) debanjan@debanjan:~/Desktop$ echo $PYTHONPATH
/home/debanjan/Amber/amber20/lib/python3.8/site-packages:/home/debanjan/amber18/lib/python2.7/site-packages:/home/debanjan/pDynamo-1.9.0/pBabel-1.9.0:/home/debanjan/pDynamo-1.9.0/pCore-1.9.0:/home/debanjan/pDynamo-1.9.0/pGraph-0.1:/home/debanjan/pDynamo-1.9.0/pMolecule-1.9.0:/home/debanjan/pDynamo-1.9.0/pMoleculeScripts-1.9.0

**Comment by debanjansen48** [comment]
Yahhhhhhhhhh!!!!!!!!!!!!!!!!!!!!

ITS WORKING NOW...............
(base) debanjan@debanjan:~/Amber/amber20/miniconda/bin$ gmx_MMPBSA
InputError: No input file was provided!
  Enter `gmx_MMPBSA --help` for help
shall i move gmx_MMPBSA to /usr/local/bin
or how to call gmx_MMPBSA from any location sir?

**Comment by Valdes-Tresanco-MS** [comment]
Excellent. I will try to optimize the process for future reference.
I will add a section in the documentation for new users. Thanks for reporting the problem.
Enjoy it

**Comment by Valdes-Tresanco-MS** [comment]
Oh sorry I forgot the warning !!!
This warning is because pip installs the executables (gmx_MMPBSA and gmx_MMPBSA_gui) in \*/amber20/miniconda/bin.
You have two options to solve this:

Add this folder (*/amber20/miniconda/bin) to PATH:
`export PATH="/home/mario/programs/amber20/miniconda/bin:$PATH"`
or
initializing the environment of conda amber:
`amber.conda init bash`

You can deactivate like this:
`conda deactivate`

**Comment by debanjansen48** [comment]
thanks...

I found in the literature  that u mentioned in git... there are options for
Amber forcefields .... I did 3 MD simulations (protein ligand and it's the
repetation) using CHARMM36 force field and 2 simulations (repetation) using
OPLS AA forcefield..

1. shall I calculate thermo data for Charmm36 trajectories?

2. shall I calculate the same for OPLS trajectories?

3. It was mentioned ligand simulation data required.. Shall I need to run
the simulation for solo ligand (protein free ligand)?

please Assist...

I must acknowledge, it's a great pakage for Gromacs users...

**Comment by Valdes-Tresanco-MS** [comment]
Sorry, only amber force fields are supported at the moment. We will do our best to implement the Charmm force field.
I'm not sure if OPLS is supported by Amber, I'll check

3. Actually it refers to the mol2 file that is obtained from the ligand parameterization (small molecule) with antechamber. This file contains the data (charges, type and bond order, atom type, etc.) to generate the ligand topology. 

If you want to do the Single trajectory approach then you only require the complex dynamics and if the ligand is a small molecule the mol2 file. If, on the other hand, you want to do it using Multiple trajectory, then you require the complex, receptor and ligand data.
