### ISSUE TITLE
[ENH]: Add support for pbsa.cuda

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/gmx_MMPBSA#200]
### New Feature

- [ ] Add support for pbsa.cuda

### Description

Install pbsa.cuda as follows:

Line 37 run.cmake file in amber20_src/build:

```
#  Assume this is Linux:

  cmake $AMBER_PREFIX/amber20_src \
    -DCMAKE_INSTALL_PREFIX=$AMBER_PREFIX/amber20 \
    -DCOMPILER=MANUAL -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_Fortran_COMPILER=gfortran-7\
    -DMPI=FALSE -DCUDA=TRUE -DINSTALL_TESTS=TRUE \
    -DDOWNLOAD_MINICONDA=TRUE -DMINICONDA_USE_PY3=TRUE \
    2>&1 | tee  cmake.log
```

See that `-DCUDA=TRUE` and we specify `MANUAL` for `-DCOMPILER` with all the routes to different compilers

if we want to test this in hpc, run this command to get a temporal assignation of resources:

`salloc --nodes=1 --ntasks-per-node=1 --mem-per-cpu=2G --time=5 --gpus=2 --account='name_of_the_project'`

### Relevance

low

### Difficulty to implement

medium

**Comment by ssagar61** [comment]
how to use all CPUs...?

**Comment by Valdes-Tresanco-MS** [comment]
@ssagar61 
Use mpirun. For example:
```bash
mpirun -np 20 gmx_MMPBSA -O ....
```
Please, check this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/gmx_MMPBSA_running/#running-gmx_mmpbsa)

**Comment by Valdes-Tresanco-MS** [comment]
@sherwoodyao 
We are finally working on adding pbsa.cuda to gmx_MMPBSA. We are a bit stuck in determining the number of available GPUs, especially when they are not on the same computer or node. We have a script that works well for the same node, detecting all available devices, but we don't have any way to test in multiple nodes.
Do you have a way to test a script for this task on an HPC with multiple GPUs on several different nodes? We just need you to run the script in your HPC queuing system. The execution time is less than 1 second.
Thank you

**Comment by Valdes-Tresanco-MS** [comment]
After a few intense days of implementing this functionality, we have decided to drop it momentarily :(
Currently, it has too many problems, for example, it does not process topologies generated from charmm ff, it bombs on systems that sander runs fine, and ultimately, in some cases, it is twice as slow as a sander. At the moment, it will stay in dev mode, waiting for updates.
