### ISSUE TITLE
ERROR: Failed building wheel for mpi4py[Question]: 

### ISSUE THREAD

**Issue by sathishdasari** [Valdes-Tresanco-MS/gmx_MMPBSA#202]
### My Question is...

While Installing gmx_MMPBSA using miniconda I faced the following error. How to resolve this?

**Comment by sathishdasari** [comment]
collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      error: Cannot link MPI programs. Check your configuration!!!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpi4py
Failed to build mpi4py
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based proje

**Comment by Valdes-Tresanco-MS** [comment]
`mpi4py` must be installed from conda. 
I assume your installation is from the AmberTools compilation. In that case, you must install `mpi4py` as follows

```bash
amber.conda install -c conda-forge mpi4py
```
You can check other possible problems and their solution in the [documentation](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/installation/)

If this is not your case, please be clearer in explaining your problem as there are multiple factors to consider.

HTH!
Mario S.

**Comment by Valdes-Tresanco-MS** [comment]
Can you repeat the process and save the output to a file? This is the first time this problem has been reported.

**Comment by sathishdasari** [comment]
Here I am attaching the output to the files for each step
[output_files.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8336288/output_files.zip)

**Comment by Valdes-Tresanco-MS** [comment]
Ok, for some reason `mpi4py = 3.0.3` is being installed, but **gmx_MMPBSA** requires version `3.1.3`. Please, run this command line 
```
conda install -c conda-forge mpi4py=3.1.3 ambertools=21.12 compilers -y -q
```

**Comment by sathishdasari** [comment]
Ok, I will try and let you know. Thank you

**Comment by sathishdasari** [comment]
Yes, It is working now. Thank you very much.

**Comment by Valdes-Tresanco-MS** [comment]
Excellent. Thanks for report this issue.
Cheers!
