### ISSUE TITLE
gmx trjconv failed when querying md_fit.xtc

### ISSUE THREAD

**Issue by avnikonenko** [Valdes-Tresanco-MS/gmx_MMPBSA#205]
### Bug summary

Hello!
I successfully have run many times the last version (1.4.3) of gmx_MMPBSA, but after I upgrade it I have this problem despite different examples I use.
I knew about #33 and I have grouped the Protein and ligand, removed PBC, and fitted the trajectory:
gmx trjconv -s md_0_10.tpr -f md_0_10.xtc -o md_noPBC.xtc -pbc mol -center -n index.ndx  <<< "Protein_4SP  0"
gmx trjconv -s md_0_10.tpr -f md_noPBC.xtc -o md_fit.xtc -n index.ndx -fit rot+trans  <<< "Protein_4SP  0"
 
Versions:
GROMACS/2018.1-intel-2017c-hybrid-single-PLUMED
ambertools 21.12

full error log:
[error.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8344716/error.txt)

Could you help me please?

### Terminal output

```bash
[INFO   ] gmx found! Using /apps/all/GROMACS/2018.1-intel-2017c-hybrid-single-PLUMED/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 1_13 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] Starting gmx_MMPBSA v1.5.1
[ERROR  ] MMPBSA_Error /apps/all/GROMACS/2018.1-intel-2017c-hybrid-single-PLUMED/bin/gmx trjconv failed when querying md_fit.xtc.
           Check the gmx_MMPBSA.log file to report the problem.
  File "/home/anikonenko/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/anikonenko/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/anikonenko/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 533, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/anikonenko/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 116, in buildTopology
    self.gmx2pdb()
  File "/home/anikonenko/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 259, in gmx2pdb
    GMXMMPBSA_ERROR('%s failed when querying %s' % (' '.join(comprog), self.FILES.complex_trajs[0]))
  File "/home/anikonenko/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: /apps/all/GROMACS/2018.1-intel-2017c-hybrid-single-PLUMED/bin/gmx trjconv failed when querying md_fit.xtc
Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[INFO   ] Command-line
  mpirun -np 1 gmx_MMPBSA MPI -O -i ../../../../md-scripts/Protein-Ligand_MD_PBGBSA/scripts/mmpbsa.in -cs md_0_10.tpr -ci index.ndx -cg 1 13 -ct md_fit.xtc -cp topol.top -nogui
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8344712/gmx_MMPBSA.log)

### Operating system

Linux

### gmx_MMPBSA Version

v1.5.1

### Python version

3.9.10

**Comment by Valdes-Tresanco-MS** [comment]
There seems to be some conflict with the execution with MPI. The error.txt file contains the execution of the instructions multiple times, so it seems that it is executed with mpirun but not the MPI instruction. Please send me your files to check if it is a bug or some MPI conflict.

**Comment by avnikonenko** [comment]
The command was 
```
mpirun -np 101 gmx_MMPBSA MPI -O -i mmpbsa.in -cs md_0_10.tpr -ci index.ndx -cg 1 13 -ct md-fit.xtc -cp topo.topl -nogui.
```
Which files do you need? I have already attached short MD trajectory and mmpbsa.in. Here are topol, tpr and index files.
[topol.top.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8352042/topol.top.txt)
[index.ndx.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8352040/index.ndx.txt)
[md_0_10.tpr.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8352048/md_0_10.tpr.txt)

Thank you!

**Comment by Valdes-Tresanco-MS** [comment]
The required files are :
- *.tpr
- 10 frames *.xtc
- *.ndx
- *.top with associated files (*.itp)

Please compress these sample files and attach them or send them directly to my email address.
I will try to find a solution as soon as possible

**Comment by Valdes-Tresanco-MS** [comment]
Everything works fine. The difference between your system and mine are the mpirun and Gromacs executables. You can try to use conda mpirun if possible (`/home/anikonenko/miniconda3/envs/gmxMMPBSA/bin/mpirun`) and if it's worth it, change the Gromacs executable too.

**An additional usability note.** 
The PB calculation includes the `EDISPER` component and the final value obtained is positive. If you choose to ignore this term, you can do so without having to do the calculation again (which is expensive). Just change `inp=1` in the `_GMXMMPBSA_info` file and run `gmx_MMPBSA --rewrite-output`. The output files will be written again ignoring this term.

**Comment by avnikonenko** [comment]
I will try. 
Thank you for the fast response!
And special thanks for the additional note!
