### ISSUE TITLE
[Bug-gmx_MMPBSA]: Installation Error: Failed building wheel for mpi4py

### ISSUE THREAD

**Issue by jssantiago3** [Valdes-Tresanco-MS/gmx_MMPBSA#206]
### Bug summary

I've followed the following steps as per instruction

conda update conda
conda create -n gmxMMPBSA python=3.9 -y -q                                      # 
conda activate gmxMMPBSA                                                        # 
conda install -c conda-forge mpi4py=3.1.3 ambertools=21.12 compilers -y -q      # 
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4 # 
python -m pip install pyqt5                                                     # 
conda install -c bioconda gromacs==2021.3 -y -q
python -m pip install gmx_MMPBSA

I get the following error after i"python -m pip install gmx_MMPBSA"

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpi4py
Failed to build mpi4py
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects

Appreciate your help in resolving this. Thank you!

### Terminal output

```bash
building 'mpi4py.MPI' extension
      /home/josh/miniconda3/envs/gmxMMPBSA/bin/mpicc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/josh/miniconda3/envs/AmberTools21/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/josh/miniconda3/envs/AmberTools21/include -fPIC -DPyMPI_MISSING_MPI_LB=1 -DPyMPI_MISSING_MPI_UB=1 -DHAVE_DLFCN_H=1 -DHAVE_DLOPEN=1 -I/home/josh/pymol/include/python3.7m -c src/MPI.c -o build/temp.linux-x86_64-3.7/src/MPI.o
      In file included from src/MPI.c:4:
      src/mpi4py.MPI.c:6:10: fatal error: Python.h: No such file or directory
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/home/josh/miniconda3/envs/gmxMMPBSA/bin/mpicc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpi4py
Failed to build mpi4py
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects
```

### gmx_MMPBSA.log

n/a

### Operating system

Pop!_OS 21.10

### gmx_MMPBSA Version

1.5.2

### Python version

Python 3.7.10

**Comment by Valdes-Tresanco-MS** [comment]
Can you check that Python.h is in this path (`/home/josh/miniconda3/envs/gmxMMPBSA/include/python3.9/`)?

**Comment by jssantiago3** [comment]
Just checked. Python.h is in the folder.

**Comment by Valdes-Tresanco-MS** [comment]
It seems to be a matter of setting environment variables. Do you have any variables defined that overwrite the conda variables?

**Comment by jssantiago3** [comment]
hmmm I'm not sure. I've reinstalled miniconda to rule this out. Is there a way to check this?

**Comment by Valdes-Tresanco-MS** [comment]
I have this configuration when the conda environment is active
```
env | grep -i include
```
```bash

DEBUG_FFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
FFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include
CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include
DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include
DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include
CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include
DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include
DEBUG_FORTRANFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
FORTRANFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include
CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/mario/programs/miniconda3/envs/gmxMMPBSAtest/include
```

While I get nothing when I am out of the environment. I would expect this configuration.

**Comment by jssantiago3** [comment]
I ran env | grep -i include

here's my result.

DEBUG_FFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_FFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/josh/miniconda3/envs/AmberTools21/include -D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
FFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_DEBUG_FORTRANFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/josh/miniconda3/envs/AmberTools21/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/josh/miniconda3/envs/AmberTools21/include -D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/josh/miniconda3/envs/AmberTools21/include
DEBUG_FORTRANFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
FORTRANFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/josh/miniconda3/envs/AmberTools21/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_DEBUG_FFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include
CONDA_BACKUP_FORTRANFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/josh/miniconda3/envs/AmberTools21/include

**Comment by Valdes-Tresanco-MS** [comment]
But here you are showing me the result within a conda environment? The `AmberTools21` environment appears instead of `gmxMMPBSA`. To avoid conflicts, you must deactivate any active environment before performing the installation process described above.

**Comment by jssantiago3** [comment]
Thanks for the help! I had to reinstall conda, it seems I screwed up my environment variables.

**Comment by Valdes-Tresanco-MS** [comment]
Did you solve the problem?

**Comment by marioernestovaldes** [comment]
closing this... feel free to reopen if the problem persists
