### ISSUE TITLE
[Question]: MMPBSA_Error: gmx_mpi and gmx_mpi_d are not supported when running gmx_MMPBSA in parallel

### ISSUE THREAD

**Issue by sathishdasari** [Valdes-Tresanco-MS/gmx_MMPBSA#207]
### My Question is...

When I was running the gmx_MMPBSA inparallel using the following command it gives the error

mpirun -np 2 gmx_MMPBSA MPI -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 19 20 -ct com_traj.xtc

ERROR:
[INFO   ] Starting gmx_MMPBSA v1.5.1
[INFO   ] Command-line
  mpirun -np 2 gmx_MMPBSA MPI -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 19 20 -ct com_traj.xtc

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/sathish/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/sathish/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/sathish/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/sathish/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[ERROR  ] MMPBSA_Error gmx_mpi and gmx_mpi_d are not supported when running gmx_MMPBSA in parallel due to incompatibility between the mpi libraries used to compile GROMACS and mpi4py respectively. You can still use gmx_mpi or gmx_mpi_d to run gmx_MMPBSA serial. For parallel calculations use gmx instead.
           Check the gmx_MMPBSA.log file to report the problem.
  File "/home/sathish/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 523, in make_prmtops
    external_progs = utils.find_progs(self.INPUT, self.mpi_size) if self.master else {}
  File "/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/utils.py", line 667, in find_progs
    GMXMMPBSA_ERROR('gmx_mpi and gmx_mpi_d are not supported when running gmx_MMPBSA in parallel '
  File "/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
_**MMPBSA_Error: gmx_mpi and gmx_mpi_d are not supported when running gmx_MMPBSA in parallel due to incompatibility between the mpi libraries used to compile GROMACS and mpi4py respectively. You can still use gmx_mpi or gmx_mpi_d to run gmx_MMPBSA serial. For parallel calculations use gmx instead**_
Check the gmx_MMPBSA.log file to report the problem.
Error occurred on rank 0.
Exiting. All files have been retained.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

**Comment by Valdes-Tresanco-MS** [comment]
As the error report says, Gromacs versions compiled with MPI are not compatible with **gmx_MMPBSA** in parallel. To solve the problem, simply recompile Gromacs without MPI (you can still compile mdrun with MPI which is the only Gromacs tool that uses parallel processing. Check the [Gromacs manual](https://manual.gromacs.org/documentation/2021-current/install-guide/index.html#building-only-mdrun) only available for 2021.x and early versions).
To avoid changing the global configuration, you can create aliases containing the configuration instructions of the current profile or specify the new executable path defining the variable [`gmx_path` in the input file](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/input_file/#miscellaneous-options)

This limitation is tested only for versions prior to 2021.3. We have not yet tested the most recent versions (2022.x).

**Comment by sathishdasari** [comment]
Ok, Thank you.
