### ISSUE TITLE
[ENH]: Improve gmx_MMPBSA_ana performance

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#209]
### In which tool?

gmx_MMPBSA_ana

### New Feature

Improve **gmx_MMPBSA_ana** performance (memory usage, data storage, plot rendering, and processing)

### Description

gmx_MMPBSA_ana currently has an inefficient data management system. Replicating data redundantly consumes a considerable amount of resources, especially when dealing with a very large data set. Coupled with this, using pandas multi-index can degrade performance.
Some preliminary ideas about the problems
- Pandas multiindex vs performance
   - Remove the multi-index and make small df's according to the data they store (dictionaries can be inefficient)
   - Order the multi-index, have a dictionary for each type of graph with the index in the order we need, and reorder the index before graphing
- data overload in memory
    - do data cleanup that is already used and not required
    - load only the strictly necessary data
    - store data in temporary files
    - use generators instead of lists
    - Option to users decides in the initial dialog if wants to handle it as big data (use of temporary files) or not (memory)
- Data pre-processing vs on-site processing
   - Allow if the user wants to preprocess the data when the app is initialized or before graphing.
   - Delete chart data from memory when the window is closed
- Storage of the original and current data
  - always store the original data as a temporary file
- Read and process data asynchronously  

### Relevance

high

### Difficulty to implement

high

**Comment by Valdes-Tresanco-MS** [comment]
The problem is that data is removed from the dataframe while it is being processed. By eliminating this operation, execution time is reduced by ~35 times and memory usage by more than half.

**Comment by Valdes-Tresanco-MS** [comment]
@wrmartin Update **gmx_MMPBSA** from the master branch (`python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA.git`). I only removed these operations that greatly degraded performance and overloaded memory. In principle, although it is not optimal, you should be able to open your data. I'm working on improving **gmx_MMPBSA_ana**, including handling the outputs and the API. I hope to have it ready by next week.
Let me know any problem

**Comment by wrmartin** [comment]
`(gmxMMPBSA) [martinw3@lri-109709 WT_2]$ gmx_MMPBSA_ana
Traceback (most recent call last):
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 360, in get_data
    self.parent.read_data(queue, self.options)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py", line 989, in read_data
    gmx_mmpbsa_api.load_file(path)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 78, in load_file
    self._get_fromApp(fname)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 376, in _get_fromApp
    app.parse_output_files()
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 1039, in parse_output_files
    if not INPUT[triggers[i]]:
KeyError: 'rismrun_pcplus'
Aborted (core dumped)
`

New error now.

**Comment by Valdes-Tresanco-MS** [comment]
Fixed. Try now...

**Comment by wrmartin** [comment]
Things work now with the exception of maximizing a window. The PerformanceWarning lines pop up during loading; the traceback occurs upon trying to maximize a window within gmx_MMPBSA_ana.

`/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1469: PerformanceWarning: indexing past lexsort depth may impact performance.
  self.systems[sys_index]['items_data'][(part, level, (level1,))] = self._setup_data(data[level][(level1,)],
/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1472: PerformanceWarning: indexing past lexsort depth may impact performance.
  if self._remove_empty_charts(data[level][(level1, level2)]):
/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1485: PerformanceWarning: indexing past lexsort depth may impact performance.
  temp_dat = data[level][(level1, level2)]
/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1493: PerformanceWarning: indexing past lexsort depth may impact performance.
  temp_dat = data[level][(level1, level2, level3)]
Traceback (most recent call last):
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/matplotlib/backends/backend_qt.py", line 262, in enterEvent
    x, y = self.mouseEventCoords(self._get_position(event))
AttributeError: 'QResizeEvent' object has no attribute 'pos'
Aborted (core dumped)
`

**Comment by Valdes-Tresanco-MS** [comment]
Unfortunately, it is a bug that I reported myself in matplotlib (https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/185#issuecomment-1076908289). It is also not possible to upgrade to PyQt6 on Centos7 since the required library is `2.18` and upgrading can be problematic.

We are working on improving the performance of **gmx_MMPBSA_ana**. These warnings will be removed in the next release.

**Comment by Valdes-Tresanco-MS** [comment]
**Improvements**
_Calculations_
- [x] Improved IE calculation (`up to 2.3x speed and up to 2x less memory`)

_Output and API_
- [x] Improved all OutputReading class (`up to 350x speed and up to 60x less memory`)
- [x] Data processing
    - [x] Remove empty terms (`up to 3x speed and up to 1.5x less memory`)
    - [x] Data iteration (Using keys maps instead items iteration) (`up to 1.3x speed and up to 0.3x less memory`)
    - [x] Dataframe generation (Now, it is created with the selected data subset instead of the whole data) (`up to 2x speed and up to 2x less memory`) 

_Analyzer_
- [x] Using multiprocessing to read output files (Speed depends on `NumSys / ncpu `)
- [ ] Using multithreading to calculate/get energy data

**Comment by wrmartin** [comment]
As long as I don't accidentally click the maximize button within the window, everything is loading up now. For some reason, I get an error when I try to load a C2 entropy calculation, but can load data without entropy.

**Comment by Valdes-Tresanco-MS** [comment]
@wrmartin you can modify the matplotlib module as I describe in this [issue](https://github.com/matplotlib/matplotlib/issues/22409) since the matplotlib module in this conda environment should only be used with **gmx_MMPBSA**

Can you show me the terminal output of this error?

**Comment by wrmartin** [comment]
`Traceback (most recent call last):
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 360, in get_data
    self.parent.read_data(queue, self.options)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py", line 989, in read_data
    gmx_mmpbsa_api.load_file(path)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 76, in load_file
    self._get_fromH5(fname)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 361, in _get_fromH5
    h5file = H5Output(h5file)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/amber_outputs.py", line 1696, in __init__
    self._h52decomp(key)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/amber_outputs.py", line 1767, in _h52decomp
    calc_types[key1][key2].parse_from_h5(self.h5f[key][key1][key2])
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/amber_outputs.py", line 1161, in parse_from_h5
    self[term][res][res_e][res2] = EnergyVector(d[term][res][res_e][res2][()])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 783, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home0/martinw3/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 213, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process 36.278
Aborted (core dumped)
`

All of the original files are present, so I don't know where the issue is. I know you mentioned before that the h5 reader isn't ready yet, but I don't know why it's defaulting this way.

**Comment by Valdes-Tresanco-MS** [comment]
Simply run `gmx_MMPBSA_ana -f _GMXMMPBSA_info`
Just to carry out a testing process, since we cannot cover all possible possibilities. We are thinking of modifying this output file. However, users have the option to include it or not, both when doing the calculation and when analyzing the results.

**Comment by Valdes-Tresanco-MS** [comment]
We are very excited to release this new version, the improvement of gmx_MMPBSA_ana is incredible.
Here is a preview
| Number of systems | type                    | Frames  | v1.5.2 | v1.5.2+20 | This version | v1.5.2+20 vs This |
|:-----------------:|-------------------------|---------|:------:|:---------:|:------------:|:-----------------:|
|         1         | Energy                  | 200 000 |  fail  |   960s    |     17s      |        56x        |
|         4         | Energy                  | 200 000 |  fail  |   4515s   |     17s      |       265x        |
|         1         | Energy+Decomp(per-wise) | 11      |  fail  |   192s    |      9s      |        21x        |
|         4         | Energy+Decomp(per-wise) | 11      |  fail  |   960s    |     14s      |        69x        |

We have also reduced RAM usage by 2-10 times.
