### ISSUE TITLE
[ENH]: Is it possible to use this tool for AMBER files?

### ISSUE THREAD

**Issue by aboelnga** [Valdes-Tresanco-MS/gmx_MMPBSA#210]
### New Feature

I am using amber to generate my top and trajectory files and want to take advantage of your gmx_MMPBSA_ana analyiss tool to experience this user-friendly feature to automate generating these many plots.
It will be greatly appreciated if that is manageable. I am confident amber community will be grateful for that
Thanks

### Relevance

medium

### Difficulty to implement

low

**Comment by Valdes-Tresanco-MS** [comment]
Not at the moment, but it is in our plan #192.
(We can probably move it forward in our roadmap).

**Comment by aboelnga** [comment]
Thanks. There is away to convert amber files (topology and trajectory) into gromocs ones but not sure what the equivalent files for the remaining input files.

**Comment by Valdes-Tresanco-MS** [comment]
Yes, however, the process can be a bit complicated and requires knowledge of both programs.
If you want to continue, @marioernestovaldes can help you
