### ISSUE TITLE
Error in nmode calculation... Invalid periodicity in the prmtop file

### ISSUE THREAD

**Issue by shiyu-wangbyte** [Valdes-Tresanco-MS/gmx_MMPBSA#211]
### Bug summary

run pbsa compute successfully, but an error occur when compute nmode entropy.

Error is "Found an invalid periodicity in the prmtop file: 60"

I have noted that, : pbsa compute via sander, but nmode entropy compute via mmpbsa_py_nabnmode.

is it the reason?

mmpbsa.in is :
&general
startframe=500, endframe=550, verbose=2, interval=5,use_sander=1,
/

&gb
igb=5, saltcon=0.150,
/
&nmode
nmstartframe=2, nmendframe=10, nminterval=1, maxcyc=5, drms=2,
/

### Terminal output

```bash
[INFO   ] Starting
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs protein_UNK_prod.tpr -ci protein_UNK_prod.ndx -cg 1 13 -ct protein_UNK_prod.xtc -cp protein_UNK_gmx_solvated.top -nogui

[WARNING] protein_forcefield and ligand_forcefield variables are deprecate since version 1.4.1 and will be remove in the next version. Please, use forcefield instead.
[WARNING] entropy_seg variable is deprecate since version 1.4.2 and will be remove in v1.5.0. Please, use ie_segment instead.
[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /soft/amber20/bin/cpptraj
[INFO   ] tleap found! Using /soft/amber20/bin/tleap
[INFO   ] parmchk2 found! Using /soft/amber20/bin/parmchk2
[INFO   ] sander found! Using /soft/amber20/bin/sander
[INFO   ] mmpbsa_py_nabnmode found! Using /soft/amber20/bin/mmpbsa_py_nabnmode
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx_mpi found! Using /soft/gromacs/2020v4/bin/gmx_mpi
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER Topologies from GROMACS files...
[INFO   ] Checking gmxMMPBSA data folder exists in Amber data...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 1_13 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Complex: Saving group 1 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal ligand: Saving group 13 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Building Normal Complex Amber Topology...
[INFO   ] Writing Normal Complex Amber Topology...
[INFO   ] No Receptor topology files was defined. Using ST approach...
[INFO   ] Building AMBER Receptor Topology from Complex...
[INFO   ] No Ligand Topology files was defined. Using ST approach...
[INFO   ] Building AMBER Ligand Topology from Complex...
[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER Topologies from GROMACS files...Done.

[INFO   ] Loading and checking parameter files for compatibility...

Preparing trajectories for simulation...
11 frames were processed by cpptraj for use in calculation.
5 frames were processed by cpptraj for nmode calculations.

Running calculations on normal system...

Beginning GB calculations with /soft/amber20/bin/sander
  calculating complex contribution...
  calculating receptor contribution...
  calculating ligand contribution...

Beginning nmode calculations with /soft/amber20/bin/mmpbsa_py_nabnmode
  calculating complex contribution...
Found an invalid periodicity in the prmtop file: 60
  File "/home/shiyu/anaconda3/envs/fast/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/shiyu/anaconda3/envs/fast/lib/python3.7/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.run_mmpbsa()
  File "/home/shiyu/anaconda3/envs/fast/lib/python3.7/site-packages/GMXMMPBSA/main.py", line 209, in run_mmpbsa
    self.calc_list.run(rank, self.stdout)
  File "/home/shiyu/anaconda3/envs/fast/lib/python3.7/site-packages/GMXMMPBSA/calculation.py", line 84, in run
    calc.run(rank, stdout=stdout, stderr=stderr)
  File "/home/shiyu/anaconda3/envs/fast/lib/python3.7/site-packages/GMXMMPBSA/calculation.py", line 323, in run
    Calculation.run(self, rank, stdout=self.output % rank)
  File "/home/shiyu/anaconda3/envs/fast/lib/python3.7/site-packages/GMXMMPBSA/calculation.py", line 159, in run
    self.prmtop))
CalcError: /soft/amber20/bin/mmpbsa_py_nabnmode failed with prmtop COM.prmtop!
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

[INFO   ] Starting
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs protein_UNK_prod.tpr -ci protein_UNK_prod.ndx -cg 1 13 -ct protein_UNK_prod.xtc -cp protein_UNK_gmx_solvated.top -nogui

[WARNING] protein_forcefield and ligand_forcefield variables are deprecate since version 1.4.1 and will be remove in the next version. Please, use forcefield instead.
[WARNING] entropy_seg variable is deprecate since version 1.4.2 and will be remove in v1.5.0. Please, use ie_segment instead.
[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /soft/amber20/bin/cpptraj
[INFO   ] tleap found! Using /soft/amber20/bin/tleap
[INFO   ] parmchk2 found! Using /soft/amber20/bin/parmchk2
[INFO   ] sander found! Using /soft/amber20/bin/sander
[INFO   ] mmpbsa_py_nabnmode found! Using /soft/amber20/bin/mmpbsa_py_nabnmode
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx_mpi found! Using /soft/gromacs/2020v4/bin/gmx_mpi
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER Topologies from GROMACS files...
[INFO   ] Checking gmxMMPBSA data folder exists in Amber data...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 1_13 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Complex: Saving group 1 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal ligand: Saving group 13 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Building Normal Complex Amber Topology...
[INFO   ] Writing Normal Complex Amber Topology...
[INFO   ] No Receptor topology files was defined. Using ST approach...
[INFO   ] Building AMBER Receptor Topology from Complex...
[INFO   ] No Ligand Topology files was defined. Using ST approach...
[INFO   ] Building AMBER Ligand Topology from Complex...
[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER Topologies from GROMACS files...Done.
[INFO   ] Loading and checking parameter files for compatibility...

 Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx make_ndx, version 2020.4
Executable:   /soft/gromacs/2020v4/bin/gmx_mpi
Data prefix:  /soft/gromacs/2020v4
Working dir:  /data/shiyu/Thrombin/Thrombin_bcc_ff99SB_restrain_1/1/output
Command line:
  gmx_mpi make_ndx -n protein_UNK_prod.ndx -o _GMXMMPBSA_COM_index.ndx

GROMACS reminds you: "What about my nose?" (Aneesur Rahman, responding to an Argonne manager arguing the long hair of Charles Bennett in his group was disreputing the lab; Retold by Michael Klein)

Going to read 1 old index file(s)
Counted atom numbers up to 37518 in index file
  0 System              : 37518 atoms
  1 Protein             :  4465 atoms
  2 Protein-H           :  2240 atoms
  3 C-alpha             :   276 atoms
  4 Backbone            :   828 atoms
  5 MainChain           :  1106 atoms
  6 MainChain+Cb        :  1360 atoms
  7 MainChain+H         :  1371 atoms
  8 SideChain           :  3094 atoms
  9 SideChain-H         :  1134 atoms
 10 Prot-Masses         :  4465 atoms
 11 non-Protein         : 33053 atoms
 12 Other               :    52 atoms
 13 32U                 :    52 atoms
 14 NA                  :    35 atoms
 15 CL                  :    35 atoms
 16 Water               : 32931 atoms
 17 SOL                 : 32931 atoms
 18 non-Water           :  4587 atoms
 19 Ion                 :    70 atoms
 20 32U                 :    52 atoms
 21 NA                  :    35 atoms
 22 CL                  :    35 atoms
 23 Water_and_ions      : 33001 atoms
 24 Protein_32U         :  4517 atoms
 nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
 'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
 't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
 'r': residue              'res' nr         'chain' char
 "name": group             'case': case sensitive           'q': save and quit
 'ri': residue index

>

>

>
Copied index group 1 'GMXMMPBSA_REC'
Copied index group 13 'GMXMMPBSA_LIG'
Merged two groups with OR: 4465 52 -> 4517

 25 GMXMMPBSA_REC_GMXMMPBSA_LIG:  4517 atoms

>
                     :-) GROMACS - gmx editconf, 2020.4 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf      Artem Zhmurov
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx editconf, version 2020.4
Executable:   /soft/gromacs/2020v4/bin/gmx_mpi
Data prefix:  /soft/gromacs/2020v4
Working dir:  /data/shiyu/Thrombin/Thrombin_bcc_ff99SB_restrain_1/1/output
Command line:
  gmx_mpi editconf -f protein_UNK_prod.tpr -o _GMXMMPBSA_COM.pdb -n _GMXMMPBSA_COM_index.ndx

Reading file protein_UNK_prod.tpr, VERSION 2020.4 (single precision)
Reading file protein_UNK_prod.tpr, VERSION 2020.4 (single precision)

Select a group for output:
Group     0 (         System) has 37518 elements
Group     1 (  GMXMMPBSA_REC) has  4465 elements
Group     2 (      Protein-H) has  2240 elements
Group     3 (        C-alpha) has   276 elements
Group     4 (       Backbone) has   828 elements
Group     5 (      MainChain) has  1106 elements
Group     6 (   MainChain+Cb) has  1360 elements
Group     7 (    MainChain+H) has  1371 elements
Group     8 (      SideChain) has  3094 elements
Group     9 (    SideChain-H) has  1134 elements
Group    10 (    Prot-Masses) has  4465 elements
Group    11 (    non-Protein) has 33053 elements
Group    12 (          Other) has    52 elements
Group    13 (  GMXMMPBSA_LIG) has    52 elements
Group    14 (             NA) has    35 elements
Group    15 (             CL) has    35 elements
Group    16 (          Water) has 32931 elements
Group    17 (            SOL) has 32931 elements
Group    18 (      non-Water) has  4587 elements
Group    19 (            Ion) has    70 elements
Group    20 (            32U) has    52 elements
Group    21 (             NA) has    35 elements
Group    22 (             CL) has    35 elements
Group    23 ( Water_and_ions) has 33001 elements
Group    24 (    Protein_32U) has  4517 elements
Group    25 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4517 elements
Select a group:
GROMACS reminds you: "I'm An Oakman" (Pulp Fiction)

Note that major changes are planned in future for editconf, to improve usability and utility.
Read 37518 atoms
Volume: 376.536 nm^3, corresponds to roughly 169400 electrons
Velocities found
Selected 25: 'GMXMMPBSA_REC_GMXMMPBSA_LIG'
                     :-) GROMACS - gmx editconf, 2020.4 (-:
                     :-) GROMACS - gmx editconf, 2020.4 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf      Artem Zhmurov
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx editconf, version 2020.4
Executable:   /soft/gromacs/2020v4/bin/gmx_mpi
Data prefix:  /soft/gromacs/2020v4
Working dir:  /data/shiyu/Thrombin/Thrombin_bcc_ff99SB_restrain_1/1/output
Command line:
  gmx_mpi editconf -f protein_UNK_prod.tpr -o _GMXMMPBSA_REC.pdb -n _GMXMMPBSA_COM_index.ndx
Reading file protein_UNK_prod.tpr, VERSION 2020.4 (single precision)
Reading file protein_UNK_prod.tpr, VERSION 2020.4 (single precision)

Select a group for output:
Group     0 (         System) has 37518 elements
Group     1 (  GMXMMPBSA_REC) has  4465 elements
Group     2 (      Protein-H) has  2240 elements
Group     3 (        C-alpha) has   276 elements
Group     4 (       Backbone) has   828 elements
Group     5 (      MainChain) has  1106 elements
Group     6 (   MainChain+Cb) has  1360 elements
Group     7 (    MainChain+H) has  1371 elements
Group     8 (      SideChain) has  3094 elements
Group     9 (    SideChain-H) has  1134 elements
Group    10 (    Prot-Masses) has  4465 elements
Group    11 (    non-Protein) has 33053 elements
Group    12 (          Other) has    52 elements
Group    13 (  GMXMMPBSA_LIG) has    52 elements
Group    14 (             NA) has    35 elements
Group    15 (             CL) has    35 elements
Group    16 (          Water) has 32931 elements
Group    17 (            SOL) has 32931 elements
Group    18 (      non-Water) has  4587 elements
Group    19 (            Ion) has    70 elements
Group    20 (            32U) has    52 elements
Group    21 (             NA) has    35 elements
Group    22 (             CL) has    35 elements
Group    23 ( Water_and_ions) has 33001 elements
Group    24 (    Protein_32U) has  4517 elements
Group    25 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4517 elements
Select a group:
GROMACS reminds you: "Louis Pasteur's theory of germs is ridiculous fiction." (Pierre Pachet, Professor of Physiology at Toulouse, 1872)
Note that major changes are planned in future for editconf, to improve usability and utility.
Read 37518 atoms
Volume: 376.536 nm^3, corresponds to roughly 169400 electrons
Velocities found
Selected 1: 'GMXMMPBSA_REC'
                     :-) GROMACS - gmx editconf, 2020.4 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf      Artem Zhmurov
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx editconf, version 2020.4
Reading file protein_UNK_prod.tpr, VERSION 2020.4 (single precision)
Reading file protein_UNK_prod.tpr, VERSION 2020.4 (single precision)

Select a group for output:
Group     0 (         System) has 37518 elements
Group     1 (  GMXMMPBSA_REC) has  4465 elements
Group     2 (      Protein-H) has  2240 elements
Group     3 (        C-alpha) has   276 elements
Group     4 (       Backbone) has   828 elements
Group     5 (      MainChain) has  1106 elements
Group     6 (   MainChain+Cb) has  1360 elements
Group     7 (    MainChain+H) has  1371 elements
Group     8 (      SideChain) has  3094 elements
Group     9 (    SideChain-H) has  1134 elements
Group    10 (    Prot-Masses) has  4465 elements
Group    11 (    non-Protein) has 33053 elements
Group    12 (          Other) has    52 elements
Group    13 (  GMXMMPBSA_LIG) has    52 elements
Group    14 (             NA) has    35 elements
Group    15 (             CL) has    35 elements
Group    16 (          Water) has 32931 elements
Group    17 (            SOL) has 32931 elements
Group    18 (      non-Water) has  4587 elements
Group    19 (            Ion) has    70 elements
Group    20 (            32U) has    52 elements
Group    21 (             NA) has    35 elements
Group    22 (             CL) has    35 elements
Group    23 ( Water_and_ions) has 33001 elements
Group    24 (    Protein_32U) has  4517 elements
Group    25 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4517 elements
Select a group:
GROMACS reminds you: "This Doesn't Suck, It's a Black Hole !" (K.A. Feenstra)

Note that major changes are planned in future for editconf, to improve usability and utility.
Note that major changes are planned in future for editconf, to improve usability and utility.
Read 37518 atoms
Volume: 376.536 nm^3, corresponds to roughly 169400 electrons
Velocities found
Selected 13: 'GMXMMPBSA_LIG'
                     :-) GROMACS - gmx trjconv, 2020.4 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen
 Christian Wennberg    Maarten Wolf      Artem Zhmurov
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.
GROMACS:      gmx trjconv, version 2020.4
Executable:   /soft/gromacs/2020v4/bin/gmx_mpi
Data prefix:  /soft/gromacs/2020v4
Working dir:  /data/shiyu/Thrombin/Thrombin_bcc_ff99SB_restrain_1/1/output
Command line:
  gmx_mpi trjconv -f protein_UNK_prod.xtc -s protein_UNK_prod.tpr -o COM_traj_0.xtc -n _GMXMMPBSA_COM_index.ndx

Will write xtc: Compressed trajectory (portable xdr format): xtc
Reading file protein_UNK_prod.tpr, VERSION 2020.4 (single precision)
Reading file protein_UNK_prod.tpr, VERSION 2020.4 (single precision)
Group     0 (         System) has 37518 elements
Group     1 (  GMXMMPBSA_REC) has  4465 elements
Group     2 (      Protein-H) has  2240 elements
Group     3 (        C-alpha) has   276 elements
Group     4 (       Backbone) has   828 elements
Group     5 (      MainChain) has  1106 elements
Group     6 (   MainChain+Cb) has  1360 elements
Group     7 (    MainChain+H) has  1371 elements
Group     8 (      SideChain) has  3094 elements
Group     9 (    SideChain-H) has  1134 elements
Group    10 (    Prot-Masses) has  4465 elements
Group    11 (    non-Protein) has 33053 elements
Group    12 (          Other) has    52 elements
Group    13 (  GMXMMPBSA_LIG) has    52 elements
Group    14 (             NA) has    35 elements
Group    15 (             CL) has    35 elements
Group    16 (          Water) has 32931 elements
Group    17 (            SOL) has 32931 elements
Group    18 (      non-Water) has  4587 elements
Group    19 (            Ion) has    70 elements
Group    20 (            32U) has    52 elements
Group    21 (             NA) has    35 elements
Group    22 (             CL) has    35 elements
Group    23 ( Water_and_ions) has 33001 elements
Group    24 (    Protein_32U) has  4517 elements
Group    25 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4517 elements
                 GROMACS reminds you: "Jesus Not Only Saves, He Also Frequently Makes Backups." (Myron Bradshaw)
Back Off! I just backed up COM_traj_0.xtc to ./#COM_traj_0.xtc.1#
 ->  frame      0 time    0.000      ^M^MReading frame       1 time    5.000    ->  frame      1 time    5.000      ^M^MReading frame       2 time   10.000    ->  frame      2 time   10.000      ^M^MReading frame       3 time   15.000    ->  frame      3 time   15.000      ^M^MReading frame       4 time   20.000    ->  frame      4 time   20.000      ^M^MReading frame       5 time   25.000    ->  frame      5 time   25.000      ^M^MReading frame       6 time   30.000    ->  frame      6 time   30.000      ^M^MReading frame       7 time   35.000    ->  frame      7 time   35.000      ^M^MReading frame       8 time   40.000    ->  frame      8 time   40.000      ^M^MReading frame       9 time   45.000    ->  frame      9 time   45.000      ^M^MReading frame      10 time   50.000    ->  frame     10 time   50.000      ^M^MReading frame      11 time   55.000   ^MReading frame      12 time   60.000   ^MReading frame      13 time   65.000   ^MReading frame      14 time   70.000   ^MReading frame      15 time   75.000   ^MReading frame      16 time   80.000   ^MReading frame      17 time   85.000   ^MReading frame      18 time   90.000   ^MReading frame      19 time   95.000   ^MReading frame      20 time  100.000    ->  frame     20 time  100.000      ^M^MReading frame      30 time  150.000    ->  frame     30 time  150.000      ^M^MReading frame      40 time  200.000    ->  frame     40 time  200.000      ^M^MReading frame      50 time  250.000    ->  frame     50 time  250.000      ^M^MReading frame      60 time  300.000    ->  frame     60 time  300.000      ^M^MReading frame      70 time  350.000    ->  frame     70 time  350.000      ^M^MReading frame      80 time  400.000    ->  frame     80 time  400.000      ^M^MReading frame      90 time  450.000    ->  frame     90 time  450.000      ^M^MReading frame     100 time  500.000    ->  frame    100 time  500.000      ^M^MReading frame     110 time  550.000    ->  frame    110 time  550.000      ^M^MReading frame     120 time  600.000    ->  frame    120 time  600.000      ^M^MReading frame     130 time  650.000    ->  frame    130 time  650.000      ^M^MReading frame     140 time  700.000    ->  frame    140 time  700.000      ^M^MReading frame     150 time  750.000    ->  frame    150 time  750.000      ^M^MReading frame     160 time  800.000    ->  frame    160 time  800.000      ^M^MReading frame     170 time  850.000    ->  frame    170 time  850.000      ^M^MReading frame     180 time  900.000    ->  frame    180 time  900.000      ^M^MReading frame     190 time  950.000    ->  frame    190 time  950.000      ^M^MReading frame     200 time 1000.000    ->  frame    200 time 1000.000      ^M ->  frame    210 time 1050.000      ^M ->  frame    220 time 1100.000      ^M ->  frame    230 time 1150.000      ^M ->  frame    240 time 1200.000      ^M ->  frame    250 time 1250.000      ^M ->  frame    260 time 1300.000      ^M ->  frame    270 time 1350.000      ^M ->  frame    280 time 1400.000      ^M ->  frame    290 time 1450.000      ^M^MReading frame     300 time 1500.000    ->  frame    300 time 1500.000      ^M ->  frame    310 time 1550.000      ^M ->  frame    320 time 1600.000      ^M ->  frame    330 time 1650.000      ^M ->  frame    340 time 1700.000      ^M ->  frame    350 time 1750.000      ^M ->  frame    360 time 1800.000      ^M ->  frame    370 time 1850.000      ^M ->  frame    380 time 1900.000      ^M ->  frame    390 time 1950.000      ^M^MReading frame     400 time 2000.000    ->  frame    400 time 2000.000      ^M ->  frame    410 time 2050.000      ^M ->  frame    420 time 2100.000      ^M ->  frame    430 time 2150.000      ^M ->  frame    440 time 2200.000      ^M ->  frame    450 time 2250.000      ^M ->  frame    460 time 2300.000      ^M ->  frame    470 time 2350.000      ^M ->  frame    480 time 2400.000      ^M ->  frame    490 time 2450.000      ^M^MReading frame     500 time 2500.000    ->  frame    500 time 2500.000      ^M ->  frame    510 time 2550.000      ^M ->  frame    520 time 2600.000      ^M ->  frame    530 time 2650.000      ^M ->  frame    540 time 2700.000      ^M ->  frame    550 time 2750.000      ^M ->  frame    560 time 2800.000      ^M ->  frame    570 time 2850.000      ^M ->  frame    580 time 2900.000      ^M ->  frame    590 time 2950.000      ^M^MReading frame     600 time 3000.000    ->  frame    600 time 3000.000      ^M ->  frame    610 time 305
Note that major changes are planned in future for trjconv, to improve usability and utility.
Select group for output
Selected 25: 'GMXMMPBSA_REC_GMXMMPBSA_LIG'
                                                                         

### Operating system

opensuse(linux)

### gmx_MMPBSA Version

gmx_MMPBSA v1.4.3 based on MMPBSA version 16.0 and AmberTools 20

### Python version

Python 3.7.7

### Installation

conda AmberTools + conda

**Comment by marioernestovaldes** [comment]
Hi there! There was a similar error reported in our google group (https://groups.google.com/g/gmx_mmpbsa/c/fb8YguZCPtA) unfortunately, I didn't receive the files to propose a workaround... Probably one of the values for the periodicity in the prmtop file is zero and this is causing everything to fail... could you please send the files you re using to see if I can come up with a workaround?

thanks in advance...

cheers!

Mario

**Comment by shiyu-wangbyte** [comment]
Yeah, but how could I send files to you?

By email?

**Comment by marioernestovaldes** [comment]
sure, that will work... send them to marioe911116@gmail.com

**Comment by marioernestovaldes** [comment]
to sum up, as we talked about this offline:

currently is not possible to execute nmode calculations with chamber files... nmode is designed to work with amber force filed files, and charm includes several terms that the program can't handle...

**Comment by shiyu-wangbyte** [comment]
I have sent a new system to you.
It is prepared by ff99SB force filed.
could you help me test this system?

**Comment by marioernestovaldes** [comment]
sure!

**Comment by shiyu-wangbyte** [comment]
Please tell me, If you need any else files.
Thanks a lot.

**Comment by marioernestovaldes** [comment]
we have added an additional checking step when generating the Amber formatted topology... it basically checks for DIHEDRAL_PERIODICITY = 0 and changes them to 1 as DIHEDRAL_PERIODICITY = 0 is not allowed in nmode calculations. As you may want to use v1.4.3 for other stuff, the best way here is to create a dedicated conda environment for the newest version of gmx_MMPBSA as follows:

```python
conda create -n gmxMMPBSA python=3.9 -y -q
conda activate gmxMMPBSA 
conda install -c conda-forge mpi4py=3.1.3 ambertools=21.12 compilers -y -q
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4
python -m pip install pyqt5
# Optional
conda install -c bioconda gromacs==2021.3 -y -q

#Install gmx_MMPBSA from GitHub repository
python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA
```

let us know if you have any issues with the new installation...

cheers!

**Comment by shiyu-wangbyte** [comment]
Thanks a lot! As your guidance， I update gmx_MMPBSA to 1.5 version. The issues are solved.

The software shows: "[WARNING] 6 invalid DIHEDRAL_PERIODICITY = 0 found in Complex topology... Setting DIHEDRAL_PERIODICITY = 1"

I wonder whether setting DIHEDRAL_PERIODICITY = 1 solved this issue?

And how could set  DIHEDRAL_PERIODICITY to 1?

Just export DIHEDRAL_PERIODICITY = 1?

Or must modify the amber.prmtop?

**Comment by Valdes-Tresanco-MS** [comment]
DIHEDRAL_PERIODICITY is a flag in the topology (https://ambermd.org/FileFormats.php). Each dihedral has an associated dihedral type. In your case, there is one invalid dihedral type since the periodicity must never be 0 (http://archive.ambermd.org/201912/0082.html). In this case, it would be ideal to know why it has an invalid periodicity, but in most cases, it is sufficient to set it to 1. Also, according to our tests, it does not affect the calculations at all, so in a sense the value is irrelevant. 
gmx_MMPBSA checks the validity of the dihedrals for you 
https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/blob/168e3c146ba4545910b7c70ee72be3e7cd479211/GMXMMPBSA/make_top.py#L438-L453) 
so you should do nothing. The warning report uses the flag name (DIHEDRAL_PERIODICITY), but if you find it confusing you can suggest changes, we will gladly consider them.

**Comment by shiyu-wangbyte** [comment]
Sure!
Thanks a lot!
