### ISSUE TITLE
program freeze when using 1micro second trajectory

### ISSUE THREAD

**Issue by mayank-kohli** [Valdes-Tresanco-MS/gmx_MMPBSA#213]
### Discussed in https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/discussions/212

<sup>Originally posted by **mayank-kohli** April  7, 2022</sup>
when I am using a gromacs trajectory of 1 micro second the program freezes during this step "Cleaning normal complex trajectories..."
and the file size of "COM_traj_0.xtc" stuck at 342 mb and it wont response after that.
But when I did for the 100ns trajectory I didn't faced any error everything ran smoothly. 

Does anyone have any idea where I might be going wrong?

**Comment by marioernestovaldes** [comment]
ok, lets follow up this issue here:

a possible workaround for a problem like this is to provide a "clean" trajectory, that is, a trajectory containing only the elements you are interested in, and then set solvated_trajectory=1 in the &general namelist of the mmpbsa.in file... have a go with this a see how it goes

**Comment by marioernestovaldes** [comment]
sorry, solvated_trajectory should be set as 0... that way, gmx_MMPBSA doesn't generate the clean trajectory with no water and ions...

another possible solution could be to provide chunks of this trajectory to the -ct flag, something like this:

gmx_MMPBSA -O -i .... -ct chunk1 chunk2 chunk3

**Comment by mayank-kohli** [comment]
It worked by adding "solvated_trajectory=0" this in the mmpbsa.in,  and the calculations are running now.
Thank you for the suggestion.

**Comment by Valdes-Tresanco-MS** [comment]
@mayank-kohli Could you share the files with me? This problem has already been reported, but I can't find a justification for this to happen. So, I would like to do some testing, but I don't have any MD that long, so your files would be helpful. Your data will be kept confidential and then I will delete it as soon as I identify the problem.
Mario S.

**Comment by marioernestovaldes** [comment]
Hi @mayank-kohli! we have fixed the bug (https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/commit/1c6f7762fa80998ada1c78f1c6fff093ca494e19)... now gmx_MMPBSA should be able to handle big trajectories smoothly... please update gmx_MMPBSA from the GitHub repository as follows:

`python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA -U`

cheers!

**Comment by mayank-kohli** [comment]
Thank you for the help and update.
