### ISSUE TITLE
[ERROR]: GromacsWarning: angles funct != 1 or 5

### ISSUE THREAD

**Issue by jssantiago3** [Valdes-Tresanco-MS/gmx_MMPBSA#214]
### My Question is...

I'm getting a an error regarding angles as follows:

GromacsWarning: angles funct != 1 or 5; unknown functional

my topology has g96 angles in it, is there a way to convert these to be compatible with Amber?

**Comment by marioernestovaldes** [comment]
Did you prepare your system with GROMOS force field?

**Comment by Valdes-Tresanco-MS** [comment]
> ### My Question is...
> I'm getting a an error regarding angles as follows:
> 
> GromacsWarning: angles funct != 1 or 5; unknown functional
> 
> my topology has g96 angles in it, is there a way to convert these to be compatible with Amber?

No, GROMOS ff is not supported. 
We will implement some calculation methods that can use it, but since it is not possible to generate an Amber topology from it, at the moment it is not supported.
