### ISSUE TITLE
Insertion code error (invalid literal for int() with base 10: '52A')

### ISSUE THREAD

**Issue by drsandhyaks** [Valdes-Tresanco-MS/gmx_MMPBSA#224]
Dear Valdes,
After dynamics simulation, i conducted gmx mmpbsa .but i got errors.
i found in the trajectory file, rsmd is very huge for sometimes. but overall system is stable.
i got like this for anothe systems but i able to do gmx_mmpbsa cal.
i dont know wht is the plm here

 
![test](https://user-images.githubusercontent.com/91943320/166130684-00ebb197-f6d4-40db-b0a6-e3e9b168d7ca.png)

 

(base) dcbsandhya@kugpu1:~/O/BA1CR302302$ gmx_MMPBSA -O -i mmpbsa.in -cs md_0_1.tpr -ci index.ndx -cg 18 19 -ct  md_0_1_noPBC.xtc -cp topol.top
[INFO   ] Starting
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs md_0_1.tpr -ci index.ndx -cg 18 19 -ct md_0_1_noPBC.xtc -cp topol.top

[WARNING] protein_forcefield and ligand_forcefield variables are deprecate since version 1.4.1 and will be remove in the next version. Please, use forcefield instead.
[WARNING] entropy_seg variable is deprecate since version 1.4.2 and will be remove in v1.5.0. Please, use ie_segment instead.
[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /opt/anaconda3/bin/cpptraj
[INFO   ] tleap found! Using /opt/anaconda3/bin/tleap
[INFO   ] parmchk2 found! Using /opt/anaconda3/bin/parmchk2
[INFO   ] sander found! Using /opt/anaconda3/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER Topologies from GROMACS files...
[INFO   ] Checking gmxMMPBSA data folder exists in Amber data...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 18_19 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Complex: Saving group 18 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal ligand: Saving group 19 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Building Normal Complex Amber Topology...
  File "/opt/anaconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/opt/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 95, in gmxmmpbsa
    app.make_prmtops()
  File "/opt/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 576, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/opt/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 117, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/opt/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 318, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes[0] + self.indexes[1])
  File "/opt/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 598, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/opt/anaconda3/lib/python3.8/site-packages/parmed/gromacs/gromacstop.py", line 251, in __init__
    self.read(fname, defines, parametrize)
  File "/opt/anaconda3/lib/python3.8/site-packages/parmed/gromacs/gromacstop.py", line 311, in read
    molecule.add_atom(*self._parse_atoms(line, params))
  File "/opt/anaconda3/lib/python3.8/site-packages/parmed/gromacs/gromacstop.py", line 492, in _parse_atoms
    return atom, words[3], int(words[2])
ValueError: invalid literal for int() with base 10: '52A'
Exiting. All files have been retained.

**Comment by Valdes-Tresanco-MS** [comment]
Please use understandable language, I am not a natural English speaker and it is difficult to understand what you are trying to say with so many incomplete words.
For future errors, please use the template we have provided, that way we can get a minimum of information.

**Solution**
This bug is fixed by updating parmed 
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4
```

**Notes**
That jumps in the RMSD are probably because you have not completely eliminated the PBCs. Note that this can lead to errors in the energy calculation and many cases, an increase in computation time. Make sure that you have completely removed the PBCs before using **gmx_MMPBSA**.

**Comment by drsandhyaks** [comment]
Dear valdes,
Sorry for that.
I will try once more by removing pbc in md.

Can we use truncated  .xtc file for gmx calculation??

**Comment by marioernestovaldes** [comment]
what do you mean with truncated  .xtc file?

**Comment by drsandhyaks** [comment]
shorten by cutting of .xtc file.

**Comment by drsandhyaks** [comment]
thanks valdes..🙏👍😁
now its working
I updated parmed..

.

**Comment by Valdes-Tresanco-MS** [comment]
> shorten by cutting of .xtc file.

Yes, you can pass one or several trajectories fragments, or select the range using the `startframe`, `endframe` and `interval` variables in the input file

**Comment by drsandhyaks** [comment]
shorten by cutting of one portion of .xtc file
