### ISSUE TITLE
gmx_MMPBSA_ana ends abruptly

### ISSUE THREAD

**Issue by sathishdasari** [Valdes-Tresanco-MS/gmx_MMPBSA#230]
### My Question is...

When I am trying to open gmx_MMPBSA_ana to see result it was giving following error

/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1466: PerformanceWarning: indexing past lexsort depth may impact performance.
  self.systems[sys_index]['items_data'][(part, level, (level1,))] = self._setup_data(data[level][(level1,)],
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1469: PerformanceWarning: indexing past lexsort depth may impact performance.
  if self._remove_empty_charts(data[level][(level1, level2)]):
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1482: PerformanceWarning: indexing past lexsort depth may impact performance.
  temp_dat = data[level][(level1, level2)]
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1490: PerformanceWarning: indexing past lexsort depth may impact performance.
  temp_dat = data[level][(level1, level2, level3)]
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1498: PerformanceWarning: indexing past lexsort depth may impact performance.
  data[level][(level1, level2, level3, level4)]
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1505: PerformanceWarning: indexing past lexsort depth may impact performance.
  temp_dat = data[level][(level1, level2, level3, level4)]
Killed

**Comment by Valdes-Tresanco-MS** [comment]
This is probably due to RAM saturation. Version v1.5.2 has this technical problem that we are working on. Please update from Github (`python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA -U`) and let me know if you can solve the problem.
We should be releasing the version that solves this bug in a few days.

**Comment by sathishdasari** [comment]
No it does not work, After I used the above pip install it keeps on printing the following

/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1469: PerformanceWarning: indexing past lexsort depth may impact performance.
  self.systems[sys_index]['items_data'][(part, level, (level1,))] = self._setup_data(data[level][(level1,)],
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1472: PerformanceWarning: indexing past lexsort depth may impact performance.
  if self._remove_empty_charts(data[level][(level1, level2)]):
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1485: PerformanceWarning: indexing past lexsort depth may impact performance.
  temp_dat = data[level][(level1, level2)]
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1493: PerformanceWarning: indexing past lexsort depth may impact performance.
  temp_dat = data[level][(level1, level2, level3)]
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1501: PerformanceWarning: indexing past lexsort depth may impact performance.
  data[level][(level1, level2, level3, level4)]
/home/sathish/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/gui.py:1508: PerformanceWarning: indexing past lexsort depth may impact performance.
  temp_dat = data[level][(level1, level2, level3, level4)]

**Comment by Valdes-Tresanco-MS** [comment]
Can you use the application or does it close abruptly?
These warnings can be ignored since they do not represent such a drastic performance problem. We are working on it right now.
