### ISSUE TITLE
How to pass Phosphorylated AA in protein 

### ISSUE THREAD

**Issue by mayank-kohli** [Valdes-Tresanco-MS/gmx_MMPBSA#232]
I have a protein system with a phosphorylated amino acid, when I am trying to run the program  I am getting following error:

MMPBSA_Error gmx_MMPBSA does not support water/ions molecules in any structure, but we found 1 molecules in the complex.. Check the gmx_MMPBSA.log file to report the problem.

and I am only passing the protein and ligand trajectory.
How this error can be rectified?

**Comment by marioernestovaldes** [comment]
could you send the files you are working with?

**Comment by mayank-kohli** [comment]
I am sharing you the trajectory without the ligand. Basically, the protein has 2 chains and I was trying to calculate the interaction energy between the two chains.
https://drive.google.com/file/d/1QWtcbkXd01tCfX9gKgf6kDPOZhQL9iV0/view?usp=sharing
Please find the link 
If I left any file do let me know I ll update it.

Thank you

**Comment by marioernestovaldes** [comment]
I need access to the file

**Comment by marioernestovaldes** [comment]
can you also include Protein_chain_A and Protein_chain_B .itp files?

**Comment by mayank-kohli** [comment]
[apo.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8759983/apo.zip)

**Comment by marioernestovaldes** [comment]
found the problem... the phosphorilated residue TPO in your strcuture has one of the oxygen atoms nameed as 'OPC'... turns out this is the name also for the oxygen atom in the new OPC water model from amber, and gmx_MMPBSA thinks it is a water molecule... the easiest solution is to change the name of this atom in the topology (line 2802 in topol_Protein_chain_A.itp) and in the pdb file (line 2619 in protein.pdb) you can use OP3 for example... after this, everything should be fine...

let me know if you have any other questions

**Comment by mayank-kohli** [comment]
It worked fine thank you for the fix.

**Comment by mayank-kohli** [comment]
got another error! 

Parsing results to output files...

  File "/home/conda1/anaconda3/envs/pbsa/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/conda1/anaconda3/envs/pbsa/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 113, in gmxmmpbsa
    app.write_final_outputs()
  File "/home/conda1/anaconda3/envs/pbsa/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 601, in write_final_outputs
    write_outputs(self)
  File "/home/conda1/anaconda3/envs/pbsa/lib/python3.8/site-packages/GMXMMPBSA/output_file.py", line 339, in write_outputs
    final_output.writeline(sys_norm.report_inconsistency())
  File "/home/conda1/anaconda3/envs/pbsa/lib/python3.8/site-packages/GMXMMPBSA/output_file.py", line 668, in writeline
    self.write(line + ls)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by marioernestovaldes** [comment]
check this [thread](https://groups.google.com/g/gmx_mmpbsa/c/L5Tpv0AWRK0/m/ImpD5PFhDwAJ)... it's a bug that was corrected
