### ISSUE TITLE
[Question]: gmx_mmpbsa Installation Question

### ISSUE THREAD

**Issue by design69xxx** [Valdes-Tresanco-MS/gmx_MMPBSA#233]
### My Question is...

I am trying to install gmx_mmpbsa in my computer. However, there was a problem when I followed installation instruction "python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4". The result was "ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/Valdes-Tresanco-MS/ParmEd.git /tmp/pip-req-build-g6ao05z3 ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?"

**Comment by marioernestovaldes** [comment]
seems like git program is missing... read this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/installation/#extra-dependencies) in the docs... it says how to install git depending on the gmx_MMPBSA installation...
