### ISSUE TITLE
gmx_MMPBSA_test error

### ISSUE THREAD

**Issue by itszomarquez** [Valdes-Tresanco-MS/gmx_MMPBSA#234]
Hello! I tried to install gmx_MMPBSA and just ran gmx_MMPBSA_test using a conda environment. However, I got the following:
![image](https://user-images.githubusercontent.com/58214457/170132386-71c54c20-117c-496f-a3d6-7184911bc39c.png)

**Comment by marioernestovaldes** [comment]
check this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/Q%26A/OS_issues/#solution_2) in the docs and see if that solves the issue...

**Comment by Valdes-Tresanco-MS** [comment]
You can try [this solution](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/208#issuecomment-1082037051) also

**Comment by itszomarquez** [comment]
Thank you for this!
