### ISSUE TITLE
ParameterError

### ISSUE THREAD

**Issue by BilalRehman01** [Valdes-Tresanco-MS/gmx_MMPBSA#238]
Hi
I am trying to run gmx_MMPBSA  for decomposition analyysis. On running the command 
Command:  gmx_MMPBSA -O -i mmpbsa.in -cs md300.tpr -ci index1.ndx -cg 18 19 -ct md_fit.xtc -cp topol.top

It throws the following error.

File "/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 1021, in parametrize
    raise ParameterError('Not all bond parameters found')
ParameterError: Not all bond parameters found

**Comment by Valdes-Tresanco-MS** [comment]
It seems that the topology is inconsistent or incompatible. What force field have you used to prepare the topology?

**Comment by BilalRehman01** [comment]
Thank you for the prompt response.
I used gromos54a7.ff force field.

**Comment by Valdes-Tresanco-MS** [comment]
Unfortunately, GROMOS is not supported, neither by ParmEd (structure/topology manipulation tool) nor by the calculation engine. You can use any version of Amber, Charmm, or OPLSAA (limited) force fields.

**Comment by BilalRehman01** [comment]
Thank you
