### ISSUE TITLE
[ERROR  ] You did not specify any type of calculation!

### ISSUE THREAD

**Issue by raylab-projects** [Valdes-Tresanco-MS/gmx_MMPBSA#24]
While following the Protein-DNA binding free energy calculation, it gave this error after executing command

 gmx_MMPBSA  -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 1 12 -ct com_traj.xtc

"[INFO   ] Started
[ERROR  ] You did not specify any type of calculation!
"
Can you please guide me where am I going wrong?
Thanks

**Comment by marioernestovaldes** [comment]
Could you please send around the mmpbsa.in you are using!?

**Comment by raylab-projects** [comment]
Thanks for pointing this out.
