### ISSUE TITLE
Positive binding energy in a protein-ligabd complex

### ISSUE THREAD

**Issue by Jameel9** [Valdes-Tresanco-MS/gmx_MMPBSA#244]
Dear Sir 

I hope this quey finds you well

I have an enzyme-ligabd compkex with a Zn atoms in the pocket. When I tried to calculate MMGBSA I got a postive values. MD simulation inputs were generated via CHARMM-GUI. 
Any suggestions or hints to troubleshoot are highly appreciated. 

Kind regards.

**Comment by marioernestovaldes** [comment]
I assume you are using the PB model... if so, check this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/Q%26A/calculations/#possible-solutions_2) in the docs... you can change the value of the `inp` variable in the `_GMXMMPBSA_info` file and rewrite the output files just running the following command:

```
gmx_MMPBSA --rewrite-output
```

hope this helps!

**Comment by Jameel9** [comment]
I actually used the gb model.

**Comment by marioernestovaldes** [comment]
Can you send the output file to see the values?

**Comment by Jameel9** [comment]
of course
[FINAL_RESULTS_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8883934/FINAL_RESULTS_MMPBSA.log)

**Comment by marioernestovaldes** [comment]
There is nothing wrong with the processing or the calculation, seems like the parameters you are using aren't working for your system... Try to play with different GB models, the dielectric constant or use PB model...

**Comment by Jameel9** [comment]
Thank you very much for your time and hints. 
I hope you all the best.

Jameel
