### ISSUE TITLE
[Issue-gmx_MMPBSA_ana]: gmx_MMPBSA_ana ends abruptly reporting TypeError

### ISSUE THREAD

**Issue by wusiru2019** [Valdes-Tresanco-MS/gmx_MMPBSA#247]
### Bug summary

**gmx_MMMPBS_ana ended abruptly when analyzing the results.**

As I have reported the gmx_MMPBSA output files failure of my system, the problem was solved by using "--rewrite-output".
In case of failing to create output files directly, I have updated my gmx_MMPBSA version from v1.5.2 to v1.5.5. And I did the same gmx_MMPBSA calculation using my system as before, only changing the value of indi to 4 and print_res to "within 15". I'm glad that it worked out successfully. However, when I used gmx_MMMPBS_ana to view the results, the program ended abruptly. I thought maybe it was related to some changes in the code of the new version. But it also failed with the results I have analyzed successfully before when using v1.5.2, and the error is as follows : 

### Terminal output

```bash
"Got keys from plugin meta data ("webp")
QFactoryLoader::QFactoryLoader() checking directory path "/home/wsr/anaconda3/bin/imageformats" ...
loaded library "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so"
loaded library "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so"
loaded library "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so"
loaded library "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqico.so"
loaded library "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so"
loaded library "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so"
loaded library "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so"
loaded library "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so"
loaded library "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so"
QFactoryLoader::QFactoryLoader() checking directory path "/home/wsr/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/accessiblebridge" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/wsr/anaconda3/bin/accessiblebridge" ...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wsr/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/wsr/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 583, in run_process
    obj = obj_method(**v['args']) if v['args'] else obj_method()
  File "/home/wsr/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/API.py", line 818, in get_ana_data
    for t, id, result in imap_unordered_it:
  File "/home/wsr/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/home/wsr/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/wsr/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/API.py", line 189, in calculatestar
    return t, id, func(data, level, iec2, name, index, memory, id)
  File "/home/wsr/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/API.py", line 118, in _setup_data
    options = ({'iec2': True} if iec2 else {}) | dict(groups=_itemdata_properties(data))
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wsr/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/analyzer/dialogs.py", line 596, in run
    for result in imap_unordered_it:
  File "/home/wsr/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
Segmentation fault"
```

### Actual outcome

[_GMXMMPBSA_info.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8953775/_GMXMMPBSA_info.txt)
Here's my __GMXMMPBSA_info file in case of need, I added the .txt to the file name for uploading successfully.

![image](https://user-images.githubusercontent.com/49088089/174926229-4d964579-4b61-45d9-9799-25efe8f9df2c.png)
It started fine, but when I clicked accept, it started to read files and then ended.

### Expected outcome

Viewing results succesfully. 

### Additional information

Here's my mmpbsa.in file.
MMPBSA.py input file for running PB

&general

   startframe=1, endframe=200,interval=1
   PBRadii=7,temperature=310.15

/
&pb

  istrng=0.15, exdi=80, indi=4.0,

  inp=2, cavity_surften=0.0378, cavity_offset=-0.5692,

  fillratio=4, scale=2.0, 

  linit=1000, prbrad=1.4, radiopt=0,

/

&decomp

  idecomp=2, dec_verbose=3,
  csv_format=0, print_res="within 15" 

/

### Operating system

ubuntu20.04

### gmx_MMPBSA_ana Version

v1.5.5

### Python version

python3.8

### Installation

AmberTools compilation + pip

**Comment by Valdes-Tresanco-MS** [comment]
Oh, this error is due to the python version, the `|:` operator was implemented from Python 3.9. 
Can you try to make a conda environment with Python 3.9 and test if it works?

**Comment by wusiru2019** [comment]
Sure, I will try that. Thanks!

**Comment by wusiru2019** [comment]
Do I need to install the Ambertools and ParmEd in the new conda environment with Python 3.9? Because I have tried to reinstall gmx_MMPBSA alone in the new conda environment with Python 3.9, and it did not work. It seems that gmx_MMPBSA didn't find these programs.

**Comment by marioernestovaldes** [comment]
you can see how to install gmx_MMPBSA in a separate environment with all the programs associated here:

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/installation/#installing-gmx_mmpbsa-v15x

**Comment by wusiru2019** [comment]
OK. Thanks!
