### ISSUE TITLE
[Question]: Can I get GBSA value for every frame in the trajectory?

### ISSUE THREAD

**Issue by Aunity** [Valdes-Tresanco-MS/gmx_MMPBSA#250]
### My Question is...

Can I get GBSA value for every frame in the trajectory?

**Comment by Valdes-Tresanco-MS** [comment]
Yes, you can display it using gmx_MMPBSA_ana or if you prefer, export it as csv directly using the `-eo` and `-deo` flags depending on the type of calculation. See this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/analyzer/#4-plot-area) and this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/gmx_MMPBSA_command-line/#gmx_mmpbsa-command-line) for more information
