### ISSUE TITLE
[Bug-gmx_MMPBSA]: ChangeRadiiError: You must choose from bondi, mbondi, mbondi2, mbondi3, amber6 radii sets

### ISSUE THREAD

**Issue by laiyii** [Valdes-Tresanco-MS/gmx_MMPBSA#251]
### Bug summary

Command line:
mpirun -np 2 gmx_MMPBSA MPI -O -i mmpbsa.in -cs md_50.tpr -ci index_0615.ndx -cg 20 19 -ct mono28_0614.xtc -cp mono28_0615.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

returns a bug
ChangeRadiiError: You must choose from bondi, mbondi, mbondi2, mbondi3, amber6 radii sets

I have seen a similar issue https://githubmemory.com/repo/Valdes-Tresanco-MS/gmx_MMPBSA/issues/231
unfortunately, it doesn't solve my bug.

### Terminal output

```bash
[INFO   ] Starting gmx_MMPBSA v1.5.5
[INFO   ] Command-line
  mpirun -np 2 gmx_MMPBSA MPI -O -i mmpbsa.in -cs md_50.tpr -ci index_0615.ndx -cg 20 19 -ct mono28_0614.xtc -cp mono28_0615.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/laiyi/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/laiyi/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/laiyi/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/laiyi/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /home/laiyi/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 20_19 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group 20 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 19 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected CHARMM force field topology format...
[INFO   ] Assigning PBRadii mbondi_pb2 to Complex...
  File "/home/laiyi/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/laiyi/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/laiyi/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 538, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/laiyi/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 118, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/laiyi/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 496, in gmxtop2prmtop
    action = ChRad(com_amb_prm, PBRadii[self.INPUT['PBRadii']])
  File "/home/laiyi/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/tools/changeradii.py", line 293, in ChRad
    raise ChangeRadiiError("You must choose from %s radii sets" %
ChangeRadiiError: You must choose from bondi, mbondi, mbondi2, mbondi3, amber6 radii sets
Error occurred on rank 0.
Exiting. All files have been retained.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8983782/gmx_MMPBSA.log)

### Operating system

win10, ubun20.04 wsl

### gmx_MMPBSA Version

[INFO   ] Starting gmx_MMPBSA v1.5.5 [INFO   ] Command-line   gmx_MMPBSA -v  gmx_MMPBSA v1.5.5 based on MMPBSA version 16.0 and AmberTools 20

### Python version

Python 3.9.13

### Installation

conda AmberTools + pip

**Comment by Valdes-Tresanco-MS** [comment]
You must install parmed from my fork.
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4
```
In the gmx_MMPBSA.log file it should appear as follows:
`ParmEd : 3.4.3+10.ga195c7ec`

**Comment by laiyii** [comment]
thanks for your quick reply. I tried but failed, it returns an error as follow:
(gmxMMPBSA) laiyi@LAPTOP-UMOUHUJD:/mnt/d/study/2022/curl/design/opt/final/mmpbsa/gmx_mmpbsa$ python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4
Collecting git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4
  Cloning https://github.com/Valdes-Tresanco-MS/ParmEd.git (to revision v3.4) to /tmp/pip-req-build-fdtnqgry
  Running command git clone --filter=blob:none --quiet https://github.com/Valdes-Tresanco-MS/ParmEd.git /tmp/pip-req-build-fdtnqgry
  fatal: unable to access 'https://github.com/Valdes-Tresanco-MS/ParmEd.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/Valdes-Tresanco-MS/ParmEd.git /tmp/pip-req-build-fdtnqgry did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/Valdes-Tresanco-MS/ParmEd.git /tmp/pip-req-build-fdtnqgry did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I think it is due to the internet shield in my current region. Is there another way to download this parmed, such as a tgz file?

**Comment by Valdes-Tresanco-MS** [comment]
In principle you can download the [forked repository](https://github.com/Valdes-Tresanco-MS/ParmEd) in zip format, unzip it, move to the folder and run `python -m pip install . -U`

**Comment by laiyii** [comment]
It works successfully, thanks a lot~
