### ISSUE TITLE
[Doc]: Undesired visual effects on per-residue PyMOL visualization

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#256]
### Documentation Link

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/analyzer/

### Problem

In several cases, `set cartoon_side_chain_helper, 1` causes undesired visual effects, e.g. it shows the terminal chain residue incompletely or hides the oxygen atoms of the PO3 group. Additionally, since it distorts the cartoon shape so it joins with the sidechain, it prevents the user from displaying any atoms that are hidden by this method, i.e., even if he wants to, no hidden atoms will be displayed, e.g., the backbone atoms.

### Suggested improvement

We must clarify this in the documentation by including the command `set cartoon_side_chain_helper, 0` to disable it and make the user aware of this "limitation".

**Comment by marioernestovaldes** [comment]
added 9c897d15e3be8e65034633d3426dda1d22406c62
