### ISSUE TITLE
 [ERROR  ] MMPBSA_Error CHAMBER prmtops cannot be used with NMODE.

### ISSUE THREAD

**Issue by hima111997** [Valdes-Tresanco-MS/gmx_MMPBSA#261]
### My Question is...

i have run a dynamics with NAMD then converted the files to GROMACS to run gmx_MMPBSA. when i tried to run it with NMODE with &gb, it produced this error: MMPBSA_Error CHAMBER prmtops cannot be used with NMODE.

**Comment by Valdes-Tresanco-MS** [comment]
Unfortunately, and as the output says, NMode is not compatible with Charmm topologies. 
We have just looked for other methodologies for NMode calculation that we will try to implement in the future.
Sincerely
Mario S.
