### ISSUE TITLE
Unable to start gmx_MMPBSA_ana

### ISSUE THREAD

**Issue by Atulsingh17** [Valdes-Tresanco-MS/gmx_MMPBSA#264]
### My Question is...

I have completd the gmx_mmpbsa calculation but got this problem in the end.  
```
[INFO ] Opening gmx_MMPBSA_ana to analyze results...  
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found. 
This application failed to start because no Qt platform plugin could be initialized. Reinstalling
 the application may fix this problem.  Available platform plugins are: eglfs, linuxfb, minimal, 
minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, 
wayland-xcomposite-glx, webgl, xcb.  
[ERROR ] Unable to start gmx_MMPBSA_ana... 
[INFO ] Finalized... 
```
 Do I have to reinstall gmx_mmpbsa or something else please suggest.

**Comment by Valdes-Tresanco-MS** [comment]
It depends on the OS. If you have Ubuntu or derivatives, you can follow these [instructions](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/Q%26A/OS_issues/#solution_2). If you have Centos or Debian, you should follow these [instructions](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/208#issuecomment-1082037051)
