### ISSUE TITLE
 # atoms in XTC file does not match # atoms in parm COM.prmtop

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#268]
Thank you for your great software in advance; I am working on a protein-protein interaction and I have got the mentioned error. I have searched rigorously but nothing were found to help me fix the problem. It would be your kindness to help me fix this issue. I will send you the required files by email.
many thanks!

_Originally posted by @masoudrezaei in https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/50#issuecomment-1185208764_

**Comment by Valdes-Tresanco-MS** [comment]
Send me your files for review

**Comment by masoudrezaei** [comment]
Thank you for your response. I have sent you the files already but I
attached them in this email.

**Comment by Valdes-Tresanco-MS** [comment]
I don't have any email from you (I checked in spam too). Please send it again.

**Comment by masoudrezaei** [comment]
Of course. This email contains attached files as a zip file (
gmx_mmpsa_files.zip  ).

**Comment by masoudrezaei** [comment]
Excuse me because I did not knew that. I have attached the files in a
GitHub message.
