### ISSUE TITLE
[Question]: Positive Binding Energy

### ISSUE THREAD

**Issue by laiyii** [Valdes-Tresanco-MS/gmx_MMPBSA#273]
### My Question is...

How can I avoid calculating ΔEDISPER term when performing a CHARMMFF pbsa calculation? I found a solution: https://groups.google.com/g/gmx_mmpbsa/c/pYeE20pbhnc?pli=1
however, I still don't know how to discard this term just by changing 'inp=2' to 'inp=1' in _GMXMMPBSA_info

**Comment by Valdes-Tresanco-MS** [comment]
Simply change the value of the variable to `INPUT['inp'] = 1` in the `_GMXMMPBSA_info` file and then run 
```
gmx_MMPBSA --rewrite-output
```

**Comment by laiyii** [comment]
thanks for your reply!

**Comment by laiyii** [comment]
I find two ways of discarding ΔEDISPER term (add inp=1 in mmpbsa.in or rewrite output) return different ddG results, up to 60 kcal/mol, it is confusing for me, how is this happen?

**Comment by Valdes-Tresanco-MS** [comment]
When you add `inp=1` to the mmpbsa.in file does the calculation run again?
mmpbsa.in is a parameter file for the calculation, so any modification requires rerunning the calculation. On the other hand, the `_GMXMMPBSA_info` file contains the run configuration, so you can only modify parameters that do not require recalculation, just rewrite the output.

**Comment by laiyii** [comment]
yes, I did run again.

**Comment by laiyii** [comment]
cmd:
`gmx_MMPBSA -O -i mmpbsa.in -cs ../md.tpr -ci ../index.ndx -cg 20 19 -ct ../mono28_%s.xtc -cp ../topol.top -o mono28_%s.dat -eo mono28_%s.csv -nogui`
mmpbsa.in is bellow:
&general
sys_name="Prot-Lig-CHARMM",
startframe=1,
endframe=800,
# In gmx_MMPBSA v1.5.0 we have added a new PB radii set named charmm_radii. 
# This radii set should be used only with systems prepared with CHARMM force fields. 
# Uncomment the line below to use charmm_radii set
PBRadii=5,
/
&pb
# radiopt=0 is recommended which means using radii from the prmtop file for both the PB calculation and for the NP
# calculation
istrng=0.15, fillratio=4.0, radiopt=0,inp=1
/

**Comment by Valdes-Tresanco-MS** [comment]
Oh, I see what you mean. In itself, both solutions are not equivalent because of the way the non-polar component of the solvation is computed. If the variable `inp=1` in the mmpbsa.in file, you must also define `use_sav=0` as well. In such a case, the total non-polar solvation free energy will be modeled as a single term linearly proportional to the solvent-accessible surface area. On the other hand, if you modify the `INPUT['inp']` variable in the `_GMXMMPBSA_info` file you will be ignoring the `EDISPER` term, but the computation of the non-polar component of the solvation, specifically the cavity term will still be maintained having been computed using the molecular volume enclosed by SASA instead of being modeled as a single term linearly proportional to the SASA. 
Definitely, we must clarify this since it is an approximation in itself so as not to have to recalculate, but it can be confusing and contain errors. We will review this content as soon as possible.
Thank you for reporting it.

**Comment by laiyii** [comment]
thanks for your reply, very glad to help you.

**Comment by Valdes-Tresanco-MS** [comment]
For the moment, it is best to modify the variables of the input file and rerun the calculation to avoid inaccuracies.

**Comment by Valdes-Tresanco-MS** [comment]
@marioernestovaldes Please help me with this theory doubt, should we remove the rewrite output option with `inp=1`? I think the rerun is inaccurate because of what I explained above.
Also we must configure the change of `use_sav = 0` when `inp = 1`.

**Comment by marioernestovaldes** [comment]
clarified `inp` variable usage in fa0d1e9

**Comment by laiyii** [comment]
adding inp=1 in mmpbsa.in and both inp=1, use_sav=0 in .in file give same results.

**Comment by Valdes-Tresanco-MS** [comment]
@marioernestovaldes Reviewing the theory and [this section](https://ambermd.org/doc12/Amber22.pdf#capter.6), I think we need to work on improving this. `inp = 2` is optimized to use multiple predefined parameters, among them Tan & Luo's radii which are not done. In the Tan & Luo publication, they specify various combinations of optimized parameters depending on the decomposition scheme. These are the things we have to check/do:
- [ ] Tan & Luo radii implementation. Currently, when the `radiiopt` is set to 0, the radii defined by the user is used. Although it may be common, we should show a warning and clarify it in the documentation.
- [ ] Implement a variable that defines the parameter sets defined by Tan & Luo. That is each value of this variable changes all the associated parameters.
- [ ] Add a warning in the documentation for `inp = 1`. When defined this way, Sander automatically resets the variables `sprob`, `cavity_surften`, and `cavity_offset`, whose default values are optimized for `inp = 2`. Should we add more options to this variable? 
- [ ] Since the ENPOLAR changes when using `inp = 2` or` inp = 1`, we should remove the option to do the rewrite-output. According to my tests, you have to modify many parameters to get close values, so what we currently do is "inaccurate".

**Comment by Clare-xiong** [comment]
I have the same issue. When I add inp=1, use_sav=0 in the mmpbsa.in, the results is -6.63, but when I change inp=1 in the _GMXMMPBSA_info and then run gmx_MMPBSA --rewrite-output, the result is -34.99. I want to know which result is more accurate?

**Comment by marioernestovaldes** [comment]
@Clare-xiong The more accurate value will be the one obtained with the correct parameters in the input file mmpbsa.in as stated here (https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/273#issuecomment-1207144247). The option of --rewrite-output can be used for relative comparisons though as the "error" is the same for all the systems.

**Comment by Clare-xiong** [comment]
Thanks for your reply.

**Comment by Tangbbmc** [comment]
> ### My Question is...
> How can I avoid calculating ΔEDISPER term when performing a CHARMMFF pbsa calculation? I found a solution: https://groups.google.com/g/gmx_mmpbsa/c/pYeE20pbhnc?pli=1 however, I still don't know how to discard this term just by changing 'inp=2' to 'inp=1' in _GMXMMPBSA_info

Could you please tell me in which situation the ΔEDISPER term can be dicarded? Thank you!

**Comment by Valdes-Tresanco-MS** [comment]
@Tangbbmc 
The EDISPER term (`inp = 2`) should be computed only when the topology is generated from a structure and not by conversion. This method is only optimized for the Tan&Luo radii(applicable only to proteins and nucleic acids), which is applied internally when `radiopt = 1`. In most cases, it ends in an error, so it is used in virtually very few cases. In the version we are working on, the parameter we set `inp = 1` by default to avoid these problems. However, we are also working on an external implementation of the Tan&Luo radii to have more flexibility. `inp = 1` applies the same method to compute the non-polar component of the solvation as the other programs (g_mmpbsa, GMXPBSA, APBS, etc.).

**Comment by Tangbbmc** [comment]
Thank you for your kind explanation! However, in the version I installed (gmx_MMPBSA v1.5.7), the default value for “inp” is two, which is reported in _GMXMMPBSA_info file. When adding inp=1, use_sav=0 in the mmpbsa.in and rerunning the calculation, the value for ΔEDISPER term is zero.

From: "Mario Sergio Valdés Tresanco" ***@***.***>
Date: 2023-02-18 23:28:06
To: Valdes-Tresanco-MS/gmx_MMPBSA ***@***.***>
Cc: Tangbbmc ***@***.***>,Mention ***@***.***>
Subject: Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Question]: Positive Binding Energy (Issue #273)

@Tangbbmc
 The EDISPER term (inp = 2) should be computed only when the topology is generated from a structure and not by conversion. This method is only optimized for the Tan&Luo radii(applicable only to proteins and nucleic acids), which is applied internally when radiopt = 1. In most cases, it ends in an error, so it is used in virtually very few cases. In the version we are working on, the parameter we set inp = 1 by default to avoid these problems. However, we are also working on an external implementation of the Tan&Luo radii to have more flexibility. inp = 1 applies the same method to compute the non-polar component of the solvation as the other programs (g_mmpbsa, GMXPBSA, APBS, etc.).

**Comment by Valdes-Tresanco-MS** [comment]
That's why. As this problem is recurring, for version 1.6.0 (current version under development) the default value will be `inp = 1`. The EDISPER term will only have a value when `inp = 2`, while it will be equal to 0.

**Comment by Tangbbmc** [comment]
@Valdes-Tresanco-MS Ok, I see. Thank you!

**Comment by Luckaswww** [comment]
@Valdes-Tresanco-MS Hello, according to the above answer, I just updated gmxMMPBSA to 1.60. But it appear a Indexerror. This error is unexist at 1.5.7  version. The calculation is a test file for gmx_MMPBSA_example. The example is decomposition_analysis. Looking forward to your reply!

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group SOLU_chain1_SOLU_chain2 (3_4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group SOLU_chain1 (3) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group SOLU_chain2 (4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected Amber/OPLS force field topology format...
[INFO   ] Assigning PBRadii mbondi2 to Complex...
[INFO   ] Writing Normal Complex AMBER topology...
[INFO   ] No Receptor topology file was defined. Using ST approach...
[INFO   ] Building AMBER Receptor topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Receptor...
[INFO   ] Writing Normal Receptor AMBER topology...
[INFO   ] No Ligand topology file was defined. Using ST approach...
[INFO   ] Building AMBER Ligand topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Ligand...
[INFO   ] Writing Normal Ligand AMBER topology...
[INFO   ] Selecting residues by distance (4 ?) between receptor and ligand for decomposition analysis...
[INFO   ] Selected 17 residues:
R:A:THR:13  R:A:HID:15  R:A:SER:17  R:A:PRO:18  R:A:TYR:23  R:A:TYR:24  R:A:TYR:25  R:A:GLN:31  R:A:SER:32  R:A:THR:33
R:A:TRP:34  L:B:ALA:4   L:B:PRO:5   L:B:PRO:6   L:B:LEU:7   L:B:PRO:8   L:B:ARG:9

[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 100, in gmxmmpbsa
    app.file_setup()
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 127, in file_setup
    create_inputs(INPUT, self.normal_system, self.pre)
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 109, in create_inputs
    com_mdin = SanderGBDecomp(com_input, rec_res, lig_res, pri_res)
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 841, in __init__
    self.make_mdin()
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 326, in make_mdin
    self.mdin.change(self.parent_namelist[key], key, value)
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/amber/mdin/mdin.py", line 197, in change
    if (value[0] == value[-1] == "'") or (value[0] == value[-1] == '"'):
IndexError: string index out of range
Exiting. All files have been retained.

**Comment by Valdes-Tresanco-MS** [comment]
I closed this issue since I opened two issues to track appropriately these problems
