### ISSUE TITLE
[ENH]: add 3D-RISM-AI

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/gmx_MMPBSA#282]
### In which tool?

gmx_MMPBSA

### New Feature

https://github.com/IkeguchiLab/3D-RISM-AI

https://pubs.acs.org/doi/full/10.1021/acs.jpcb.2c03384

### Relevance

low

**Comment by Valdes-Tresanco-MS** [comment]
This also looks good. GPU/CPU deep learning 3D-RISM solvation energy estimation 
https://www.biorxiv.org/content/10.1101/2022.04.18.488616v1
