### ISSUE TITLE
[Question]: [WARNING] 21 invalid DIHEDRAL_PERIODICITY = 0 found in Complex topology... Setting DIHEDRAL_PERIODICITY = 1

### ISSUE THREAD

**Issue by giangpth** [Valdes-Tresanco-MS/gmx_MMPBSA#284]
### My Question is...
[WARNING] 21 invalid DIHEDRAL_PERIODICITY = 0 found in Complex topology... Setting DIHEDRAL_PERIODICITY = 1
Hello, I often see this warning when I use gmx_MMPBSA. Is this normal or not? If not what do I have to do to solve it? Thank you.

**Comment by marioernestovaldes** [comment]
check this [thread](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/211#issuecomment-1091917533)

hope this helps!
