### ISSUE TITLE
MMPBSA_Error Could not find necessary program [ GROMACS ][Question]: 

### ISSUE THREAD

**Issue by avinashkarkada** [Valdes-Tresanco-MS/gmx_MMPBSA#286]
### My Question is...

I have my gromacs 2020.6 installed in usr/local/bin/bin/ . How do I make gmx_MMPBSA installed in a mini conda env recognize gromacs?

**Comment by Valdes-Tresanco-MS** [comment]
Normally, if `gmx` is available in the `PATH`, then no matter where you install **gmx_MMPBSA**, whether in miniconda, conda or in the AmberTools compilation, it should see the executable. Have you modified the PATH variable? Is gmx included in the PATH?(check the `echo $PATH` output) 
In my case, gromacs is installed locally and included in the PATH.
```bash
(base) mario@mario-LabPC:~$ which gmx
/usr/local/gromacs/bin/gmx
```
If I activate my test conda environment, it is still accessible. 
```bash
(gmxMMPBSA_1.5.5) mario@mario-LabPC:~$ which gmx
/usr/local/gromacs/bin/gmx
```
The creation of this environment should not modify the PATH, at least it should not delete the previous path definitions. If you have several versions of gromacs, you can define which one to use by [setting the variable `gmx_path` in the input file](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/#miscellaneous-options)

**Comment by avinashkarkada** [comment]
I tried adding gromacs to the path. But I dont know what I am doing wrong. Could you please tell me how to add it to the path?
I tried adding gmx_path to the input file and I got this:


`[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/aka/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/aka/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/aka/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/aka/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version 4.x.x!
[ERROR  ] MMPBSA_Error Could not find necessary program [ GROMACS ].
           Check the gmx_MMPBSA.log file to report the problem.
  File "/home/aka/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/aka/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/aka/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 527, in make_prmtops
    external_progs = utils.find_progs(self.INPUT, self.mpi_size) if self.master else {}
  File "/home/aka/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/utils.py", line 741, in find_progs
    GMXMMPBSA_ERROR('Could not find necessary program [ GROMACS ]')
  File "/home/aka/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: Could not find necessary program [ GROMACS ]
Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.
`

**Comment by avinashkarkada** [comment]
**I got this:**

![Screenshot from 2022-08-31 00-28-55](https://user-images.githubusercontent.com/80105987/187520422-b1c1cb21-073a-4c57-9c17-b9dce9b09329.png)

**Comment by avinashkarkada** [comment]
**I also realized that I cannot source GMXRC directly as my root is at home/username: 
I could source it after changing the dir**
![Screenshot from 2022-08-31 00-31-26](https://user-images.githubusercontent.com/80105987/187520997-51561700-2712-4a91-9848-502407c9dc23.png)

**Comment by Valdes-Tresanco-MS** [comment]
If you do not get output on the `which gmx` and `which GMXRC` commands then you have not sourced the GMXRC file. This command you are executing (`source /usr/local/gromacs/bin/bin/GMXRC`), you should add it to your `.bashrc` or executed it whenever you open a new terminal

Actually you are executing the command wrong. In linux, when you run `command folder/script`, it assumes that `folder` is located in the current directory. Whenever you access a global address, i.e. from anywhere, you must start from the root (`/`). Therefore, your command should be `source /usr/...`.

**Comment by avinashkarkada** [comment]
**It is working now. 
Thank you very much sir!!**
