### ISSUE TITLE
[Doc]: Need example with small-molecule cofactor, ie. a GTPase containing GDP and Mg2+

### ISSUE THREAD

**Issue by sammun-insitro** [Valdes-Tresanco-MS/gmx_MMPBSA#288]
### Problem

I tried to run gmx_MMPBSA on a GTPase but was having a lot of trouble setting up the gmx_MMPBSA run. How do I write/partition the mol2 file for this purpose?

### Suggested improvement

New example would be very helpful.

**Comment by Valdes-Tresanco-MS** [comment]
Please set the `-cp topol.top` option. You should be able to do your calculations without any problems. See this [example](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Metalloprotein_peptide/)

**Comment by sammun-insitro** [comment]
Thank you for pointing me to the right documentation!! You just made my day :)
