### ISSUE TITLE
[Question]: MMPBSA_Error when querying .mol2 files

### ISSUE THREAD

**Issue by 2SSSCN** [Valdes-Tresanco-MS/gmx_MMPBSA#294]
Dear gmx_MMPBSA developer: 
      I have some troubles in using gmx_MMPBSA when my system contains metal atoms, such as Au atom and Ag stom.  For example, when I calculated BFE between the protein and ligand by using AMBER+GAFF forcefield, I followed the instruction on your website and I understood the ligand parameters file(.mol2) output from Antechamber must be defined. However, GAFF does not have sufficient parameters for molecules having unusual elements (those other than H,C,N,O,S,P and halogens) so that Antechamber could not output the .mol2 file if ligand has Au atom. 
     Is any way to calculate BFE between the protein and ligand when the ligand has Au atom? Should I change my forcefield to Charmm or other? Besides, If my system has metal atoms, how should I do can make the calculation result more accurate?Thanks a lot.

    
[gmx_MMPBSA_au.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9886320/gmx_MMPBSA_au.log)

[mmpbsain.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9886418/mmpbsain.txt)

**Comment by Valdes-Tresanco-MS** [comment]
Sorry for the delay. I didn't realize I hadn't replied. 
This problem is solved by using the `-cp topol.top` option. This way, all system parameters are converted from Gromacs to Amber without needing the `*.mol2` file.

**Comment by 2SSSCN** [comment]
Thanks for your reply! I have tried this way to solve my problem, but an error occured:
[MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9937235/MMPBSA.log)
[issue.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9937249/issue.zip)

**Comment by Valdes-Tresanco-MS** [comment]
`aur.top` is a binary file, so I cannot open it to examine it. Assuming the topology is `Auranofin.top`, it has serious problems. For example, the `[ defaults ]`, `[ system ]`, and `[ molecules ]` sections are repeated. Also, there is a huge line full of `NULL`. In `Auranofin.itp`, something similar happens. The `[ moleculetype ]` section is repeated, and in the first one, `Index 23` does not contain atoms. 
As far as I can see, this topology was not created with conventional software, so you should check that it is correct. The error you get is in ParmEd, meaning your topology is not readable.

**Comment by 2SSSCN** [comment]
Thanks for your reply. In fact, aur.top is the topology file, i just pasted the topology file here, the [atomtypes] section was copied from the Auranofin.itp file to prevent this section repeated. 
The Auranofin.itp file was generated by Sobtop software, because this ligand's topology file could not generated by AmberTools.

; Include forcefield parameters
#include "amber03.ff/forcefield.itp"

[ atomtypes ]
; name   at.num      mass       charge   ptype     sigma (nm)    epsilon (kJ/mol)
c2           6    12.010736    0.000000    A      3.399670E-01    3.598240E-01
os           8    15.999405    0.000000    A      3.000012E-01    7.112800E-01
s4          16    32.064787    0.000000    A      3.563595E-01    1.046000E+00
c            6    12.010736    0.000000    A      3.399670E-01    3.598240E-01
o            8    15.999405    0.000000    A      2.959922E-01    8.786400E-01
c1           6    12.010736    0.000000    A      3.399670E-01    8.786400E-01
p5          15    30.973762    0.000000    A      3.741775E-01    8.368000E-01
cx           6    12.010736    0.000000    A      3.399670E-01    3.598240E-01
UF_C         6    12.010736    0.000000    A      3.430851E-01    4.393200E-01
UF_Au       79   196.966569    0.000000    A      2.933729E-01    1.631760E-01
cu           6    12.010736    0.000000    A      3.399670E-01    3.598240E-01

; Include chain topologies
#include "3k9m_Protein_chain_A.itp"
#ifdef POSRES
#include "posre_Protein_chain_A.itp"
#endif

#include "3k9m_Protein_chain_B.itp"
#ifdef POSRES
#include "posre_Protein_chain_B.itp"
#endif

#include "3k9m_Protein_chain_C.itp"
#ifdef POSRES
#include "posre_Protein_chain_C.itp"
#endif

#include "3k9m_Protein_chain_D.itp"
#ifdef POSRES
#include "posre_Protein_chain_D.itp"
#endif

; Include ligand topology
#include "Auranofin.itp"


; Include water topology
#include "amber03.ff/tip3p.itp"

#ifdef POSRES_WATER
; Position restraint for each water oxygen
[ position_restraints ]
;  i funct       fcx        fcy        fcz
   1    1       1000       1000       1000
#endif

; Include topology for ions
#include "amber03.ff/ions.itp"

[ system ]
; Name
Protein in water

[ molecules ]
; Compound        #mols
Protein_chain_A     1
Protein_chain_B     1
Protein_chain_C     1
Protein_chain_D     1
Auranofin 1
SOL         32603
NA               127
CL               101

**Comment by Valdes-Tresanco-MS** [comment]
Unfortunately, its topology is not yet readable. For example, the `3k9m_Protein_chain_A.itp` has the section `[ moleculetype ]` repeated. You can check if it is readable or not using the following command in the same execution environment of **gmx_MMPBSA**
```python
import parmed
top = parmed.load_file('aur.top')
top
```

**Comment by 2SSSCN** [comment]
THANKS, I will examine my topology file later, by the way, if my system has metal atoms, how should I do can make the calculation result more accurate?

**Comment by Valdes-Tresanco-MS** [comment]
Certainly, these models are not parameterized for metals, especially with rare metals such as Au. So the reliability of your results can be an enigma. That doesn't mean you can't do it, probably, any method you use will have similar problems. You just need to make sure your results are consistent

**Comment by 2SSSCN** [comment]
I see, thanks so much.
