### ISSUE TITLE
[Question]: Calculation of binding energy in a system with multiple ligands

### ISSUE THREAD

**Issue by immortalfame** [Valdes-Tresanco-MS/gmx_MMPBSA#295]
### My Question is...

I am trying to calculate the binding energy of one ligand in a protein system with two ligands.

(ligands: gaff2) In the system using the AMBER99SB-ILDN force field,
it was calculated with the -cp option even without the -lm option. 

However, in the system using the AMBER19SB force field obtained from the CHARMM-GUI,
the -cp option did not work.
And, the -lm option did not work when two ligands were included,
and calculation was possible when only one ligand was included.

I would like to calculate the binding energy for a single ligand in a system with multiple ligands.
Is there any possible way?
If not, is it possible to update?

**Comment by Valdes-Tresanco-MS** [comment]
Yes, the problem with the systems prepared in CHARMM-GUI is that sometimes the name of the molecule in the topology and the itp do not match (it is capitalized in the `*.top` and not in the `*.itp`, for example). Please check that this is not the problem. Otherwise, using the `-cp` option, you can define practically any type of system with any number of molecules in it.

**Comment by chaninpark0806** [comment]
I found that when I use the -cp option, an error occurs because of the cmap information of the protein (topol_Protein.itp).

After removing the cmap information, the calculation was done without any problem.

Does the removal of cmap information affect the calculation of binding energy values?

**Comment by chaninpark0806** [comment]
[WARNING] 33 invalid DIHEDRAL_PERIODICITY = 0 found in Complex topology... Setting DIHEDRAL_PERIODICITY = 1

I found a warning message in the result of the above calculation.
I couldn't find any information about this warning.

**Comment by marioernestovaldes** [comment]
The cmap is part of the bonded terms and is used to estimate the free energy...in principle you shouldn't remove it... If you send us the files, perhaps we can help you to figure out whats going wrong... Regarding the periodicity, please check this thread https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/211#issuecomment-1091917533

**Comment by chaninpark0806** [comment]
Please check the md result files.

https://drive.google.com/file/d/1YzG1AWhoP9BtKCaxlTvuuKnyzb0cPeG0/view?usp=share_link

**Comment by immortalfame** [comment]
Please check the md result files.

https://drive.google.com/file/d/1YzG1AWhoP9BtKCaxlTvuuKnyzb0cPeG0/view?usp=share_link

**Comment by Valdes-Tresanco-MS** [comment]
The error with CMAP is that you are using an older version of ParmEd. Since the Amber19SB architecture includes CMAP which was not in the previous ones, it requires updating ParmEd. 
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4
```

**Comment by immortalfame** [comment]
Um...  I have already installed parmed of 3.4.3.

**Comment by Valdes-Tresanco-MS** [comment]
This version from my fork is version `3.4.3+10.ga195c7ec` which includes those updates. ParmEd has been updated several times without changing the semantic version. The recommendation is to upgrade it from my fork as it appears in the instructions in the documentation.

**Comment by immortalfame** [comment]
As you said, the problem was solved after reinstalling parmed.

Thank you very much.
