### ISSUE TITLE
[Bug-gmx_MMPBSA_test]: Protein-Protein

### ISSUE THREAD

**Issue by aptamer1234** [Valdes-Tresanco-MS/gmx_MMPBSA#297]
### Bug summary

When using gmx_MMPBSA, I get an error. I don't know if it's because of the atomic problem in the model or the problem of the algorithm statement. Please help me to answer it. Thank you very much.

### Terminal output

```bash
[ERROR  ] MMPBSA_Error /home/b1612/miniconda3/envs/gmxMMPBSA/bin/tleap failed when querying _GMXMMPBSA_leap.in.
           Check the gmx_MMPBSA.log file to report the problem.
  File "/home/b1612/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/b1612/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/b1612/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 545, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/b1612/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 121, in buildTopology
    tops = self.makeToptleap()
  File "/home/b1612/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 1382, in makeToptleap
    self._run_tleap(tleap, 'leap.in', data_path)
  File "/home/b1612/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 1509, in _run_tleap
    GMXMMPBSA_ERROR('%s failed when querying %s' % (tleap, self.FILES.prefix + arg1))
  File "/home/b1612/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: /home/b1612/miniconda3/envs/gmxMMPBSA/bin/tleap failed when querying _GMXMMPBSA_leap.in
Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.
```

### Log files of failed tests

[DEBUG  ] Building topology.
[DEBUG  ] Building atom parameters.
[DEBUG  ] Building bond parameters.
[DEBUG  ] Building angle parameters.
[DEBUG  ] Building proper torsion parameters.
[DEBUG  ] Building improper torsion parameters.
[DEBUG  ]  total 724 improper torsions applied
[DEBUG  ] Building H-Bond parameters.
[DEBUG  ] Incorporating Non-Bonded adjustments.
[DEBUG  ] Not Marking per-residue atom chain types.
[DEBUG  ] Marking per-residue atom chain types.
[DEBUG  ]   (Residues lacking connect0/connect1 - 
[DEBUG  ]    these don't have chain types marked:
[DEBUG  ] 
[DEBUG  ] 	res	total affected
[DEBUG  ] 
[DEBUG  ] 	CALA	1
[DEBUG  ] 	NASP	1
[DEBUG  ]   )
[DEBUG  ]  (no restraints)
[DEBUG  ] 
[DEBUG  ] /home/b1612/miniconda3/envs/gmxMMPBSA/bin/teLeap: Fatal Error!
[DEBUG  ] bond: Argument #1 is type String must be of type: [atom]
[DEBUG  ] usage:  bond <atom1> <atom2> [order]
[DEBUG  ] 
[DEBUG  ] Exiting LEaP: Errors = 1; Warnings = 2; Notes = 2.
[ERROR  ] MMPBSA_Error /home/b1612/miniconda3/envs/gmxMMPBSA/bin/tleap failed when querying _GMXMMPBSA_leap.in.
           Check the gmx_MMPBSA.log file to report the problem.

### Operating system

Ubuntu22.04

### gmx_MMPBSA_test Version

gmx_MMPBSA_test v1.5.6+30.g0c3c6ec based on MMPBSA version 16.0

### Python version

python 3.9

### Installation

from source (.tar.gz)

**Comment by marioernestovaldes** [comment]
There are errors during the tleap process... please use '-cp topol.top' flag to avoid this and convert directly the topology

**Comment by aptamer1234** [comment]
> There are errors during the tleap process... please use '-cp topol.top' flag to avoid this and convert directly the topology

Thanks! It works.
