### ISSUE TITLE
[Question]: MMPBSA_Error Could not find necessary program [cpptraj].

### ISSUE THREAD

**Issue by purvacart** [Valdes-Tresanco-MS/gmx_MMPBSA#300]
### My Question is...

What to do when you get this error:
Checking external programs...
[ERROR  ] MMPBSA_Error Could not find necessary program [cpptraj].
           Check the gmx_MMPBSA.log file to report the problem.
  File "/home/sos/miniconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/sos/miniconda3/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/sos/miniconda3/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 538, in make_prmtops
    external_progs = utils.find_progs(self.INPUT, self.mpi_size) if self.master else {}
  File "/home/sos/miniconda3/lib/python3.9/site-packages/GMXMMPBSA/utils.py", line 709, in find_progs
    GMXMMPBSA_ERROR('Could not find necessary program [%s]' % prog)
  File "/home/sos/miniconda3/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: Could not find necessary program [cpptraj]
Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.

**Comment by marioernestovaldes** [comment]
did you follow all the instructions given here to install gmx_MMPBSA in an isolated environment?

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/installation/

**Comment by purvacart** [comment]
Ill check once again and get back

**Comment by elahehtavili** [comment]
Hi, thank you for the recommendations, I solved the problem but, when I am trying to calculate binding energy between two proteins using gmx_mmpbsa, by gb.  I need to determine the entropy and delta G of the connection, so I changed the mmpbsa.in file. but I got this error (MMPBSA_Error:  Some energy terms are undefined. Please, check the input structure and trajectory) in time of  Parsing results to output files. 
Thanks in advance. 
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/12505326/gmx_MMPBSA.log)
[mmpba.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/12505338/mmpba.txt)
