### ISSUE TITLE
[Bug-gmx_MMPBSA]: 3D-RISM model from the examples are not working

### ISSUE THREAD

**Issue by spalgit** [Valdes-Tresanco-MS/gmx_MMPBSA#301]
### Bug summary

Hello, 

   I am trying to run gmx_MMPBSA with the 3d_rism from the examples and it complains with the error as shown in the "Terminal output". Not sure why it says Unknown namelist (rism) !

Other things work well. 

Thanks
Sandeep

------------

--------------------

### Terminal output

```bash
gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 20 21 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv
[INFO   ] Starting gmx_MMPBSA v1.5.7
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 20 21 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[WARNING] Default TOLERANCE value is 0.00001! However 0.001 is been used. Check documentation for more details...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/sandeep/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/sandeep/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/sandeep/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/sandeep/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /home/sandeep/anaconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 20_21 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group 20 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 21 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Generating AMBER Compatible PDB Files...
[INFO   ] Changing the Complex residues name format from GROMACS to AMBER...
[INFO   ] Changing the Receptor residues name format from GROMACS to AMBER...
[INFO   ] Changing the Ligand residues name format from GROMACS to AMBER...
[INFO   ] Splitting  receptor and ligand in PDB files..
[INFO   ] Building tleap input files...
[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
  File "/home/sandeep/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/sandeep/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 100, in gmxmmpbsa
    app.file_setup()
  File "/home/sandeep/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 127, in file_setup
    create_inputs(INPUT, self.normal_system, self.pre)
  File "/home/sandeep/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 229, in create_inputs
    rism_mdin = SanderRISMInput(INPUT)
  File "/home/sandeep/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 262, in __init__
    self.mdin.change(self.parent_namelist[key], key, INPUT[self.name_map[key]])
  File "/home/sandeep/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/amber/mdin/mdin.py", line 316, in change
    raise InputError('Unknown namelist (%s)!' % namelist)
InputError: Unknown namelist (rism)!
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10105315/gmx_MMPBSA.log)

### Operating system

Linux 

### gmx_MMPBSA Version

1.5.7

### Python version

3.9.15

### Installation

conda AmberTools + conda

**Comment by Valdes-Tresanco-MS** [comment]
This error occurs because you have an outdated version of ParmEd, please update it
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4
```

**Comment by spalgit** [comment]
I did run the command as you said and it still gives the same error. The mmpbsa.in file is

&general
sys_name="3D-RISM",
startframe=5,
endframe=8,
/

&rism
polardecomp=1, tolerance=0.001, rism_verbose=2, closure="kh"

**Comment by spalgit** [comment]
My Parmed version is 3.4.3 
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10105770/gmx_MMPBSA.log)


The log file is attached

**Comment by spalgit** [comment]
Hi Valdes,

    My conda list looks like this. Do you think I am not using the correct versions of any package/software? The Parmed looks exactly what you have mentioned. Python is 3.9. 

I am not able to revert back to Python=3.4. As I understand conda does not support that.

Will you be able to please look at my conda list and let me know if this is different from yours? I am still struggling with 3D-RISM.

----------- conda list
# packages in environment at /home/sandeep/anaconda3/envs/gmxMMPBSA:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ambertools                21.12            py39hc630cb1_0    conda-forge
amberutils                21.0                     pypi_0    pypi
arpack                    3.7.0                hdefa2d7_2    conda-forge
binutils                  2.39                 hdd6e379_1    conda-forge
binutils_impl_linux-64    2.39                 he00db2b_1    conda-forge
binutils_linux-64         2.39                h5fc0e48_11    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
c-compiler                1.5.1                h166bdaf_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
compilers                 1.5.1                ha770c72_0    conda-forge
contourpy                 1.0.6            py39hf939315_0    conda-forge
curl                      7.86.0               h7bff187_1    conda-forge
cxx-compiler              1.5.1                h924138e_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.32          py39h5a03fae_1    conda-forge
fftw                      3.3.10          nompi_hf0379b8_105    conda-forge
fonttools                 4.38.0           py39hb9d737c_1    conda-forge
fortran-compiler          1.5.1                h2a4ca65_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gcc                       10.4.0              hb92f740_11    conda-forge
gcc_impl_linux-64         10.4.0              h5231bdf_19    conda-forge
gcc_linux-64              10.4.0              h9215b83_11    conda-forge
gfortran                  10.4.0              h0c96582_11    conda-forge
gfortran_impl_linux-64    10.4.0              h7d168d2_19    conda-forge
gfortran_linux-64         10.4.0              h69d5af5_11    conda-forge
gmx-mmpbsa                1.5.7                    pypi_0    pypi
gromacs                   2021.3          nompi_hcc3dda7_0    bioconda
gxx                       10.4.0              hb92f740_11    conda-forge
gxx_impl_linux-64         10.4.0              h5231bdf_19    conda-forge
gxx_linux-64              10.4.0              h6e491c6_11    conda-forge
h5py                      3.7.0                    pypi_0    pypi
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.2          nompi_h2386368_100    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py39hf939315_1    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.86.0               h7bff187_1    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     10.4.0              hd38fd1e_19    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libhwloc                  2.5.0                h6746aa3_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h261ec11_106    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsanitizer              10.4.0              h5246dfb_19    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-devel_linux-64  10.4.0              hd38fd1e_19    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzip                    1.9.2                hc869a4a_1    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
matplotlib-base           3.6.2            py39hf9fd14e_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.1.3            py39h32b9844_3    conda-forge
mpich                     4.0.3              h846660c_100    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
netcdf-fortran            4.5.4           nompi_hc402ea5_102    conda-forge
numpy                     1.23.5           py39h3d75532_0    conda-forge
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1s               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
packmol                   20.010               h86c2bf4_0    conda-forge
packmol-memgen            1.2.1rc0                 pypi_0    pypi
pandas                    1.5.2            py39h4661b88_0    conda-forge
parmed                    3.4.3+10.ga195c7e          pypi_0    pypi
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pillow                    9.2.0            py39hf3a2cdf_3    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.0                  pypi_0    pypi
python                    3.9.15          h47a2c10_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
sander                    16.0                     pypi_0    pypi
scipy                     1.9.3            py39hddc5342_2    conda-forge
seaborn                   0.11.2                   pypi_0    pypi
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.64.1                   pypi_0    pypi
tzdata                    2022f                h191b570_0    conda-forge
unicodedata2              15.0.0           py39hb9d737c_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge

**Comment by Valdes-Tresanco-MS** [comment]
You definitely have the right version in this conda environment. However, for some reason, the version that the program is taking, is not this one. Do you happen to have another version of AmberTools installed? That is, do you have the AMBERHOME variable defined?

**Comment by spalgit** [comment]
Hi, I am also using acpype but under a different conda environment. In acpype it uses ambertools 22. 

No in my bashrc I do not have AMBERHOME variable defined.

Interestingly &gb works fine. 

Not sure what is happening?

**Comment by Valdes-Tresanco-MS** [comment]
Both GB and PB will work. The 3D-RISM configuration was recently added to ParmEd, that's why you have to install the version from my fork.
If you are in another conda environment, you should have no problems once you activate the gmx_MMPBSA one.
Please show me the terminal output after this command
```bash
python   
```
Make sure that it is the correct environment, then
```python
import parmed
parmed.__file__
```
Another question, do you have the `LD_LIBRARY_PATH` variable defined?

**Comment by spalgit** [comment]
Thanks, the result from the previous commands is

/home/sandeep/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/__init__.py.

Can you please let me know how can I install the version from fork? I am not sure I understand that.

**Comment by Valdes-Tresanco-MS** [comment]
Please, update as follow:

```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4 -U
```

After you installed it, please check the version in conda `conda list` and make sure that it is `3.4.3+10.ga195c7e`

Do you have the `PYTHONPATH` variable defined? This could be another reason why it is taking another version instead of the one you have installed in this environment. If you have it set, try `unset PYTHONPATH`, and then run **gmx_MMPBSA** again.
