### ISSUE TITLE
[leaprc for CHARMM force-field]: 

### ISSUE THREAD

**Issue by sathishdasari** [Valdes-Tresanco-MS/gmx_MMPBSA#302]
### In which tool?

gmx_MMPBSA

### New Feature

I have used charmm36-jul2021.ff force-field for my simulation of protein-protein complex. When I am trying to calculate the MM-GBSA binding free energy using gmx_MMPBSA it gives the following error.

_MMPBSA_Error: /home/sathish/miniconda3/envs/gmxMMPBSA/bin/tleap failed when querying _GMXMMPBSA_leap.in_

going through the log file I understand that it was trying to read the parameters from the 
source oldff/leaprc.ff99SB
source leaprc.gaff
I understand that there is no leaprc file corresponding to the CHARMM force-field to mention. Is it possible to incorporate leaprc file corresponding to the CHARMM force-field?

### Relevance

high

**Comment by marioernestovaldes** [comment]
Add the -cp topol.top flag

it is mandatory when using charmm FF

**Comment by sathishdasari** [comment]
Thank you
