### ISSUE TITLE
[Question]: Why is my △TOTAL positive?

### ISSUE THREAD

**Issue by Clare-xiong** [Valdes-Tresanco-MS/gmx_MMPBSA#304]
### My Question is...

I check the trajectory. The molecules can stay very stable in the pocket and bind to the protein very well. However, the △TATOL=266.84kcal/mol, and the △EEL333.16kcal/mol. But the ligand is negative, and there are positive residues in the pocket. I want to know if there is something I did wrong. Here is my mmpbsa.in.
[md2.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10131664/md2.zip)

**Comment by marioernestovaldes** [comment]
Could you please attach the result file ?

**Comment by marioernestovaldes** [comment]
there is no error in teh processing... this results are related to the parameters you are using and the system... you can send me the files if you want me to look at it more closely and see if I can come up with a solution

**Comment by Clare-xiong** [comment]
What files do you need?

**Comment by marioernestovaldes** [comment]
The ones you used to run the calcualtion... the trajectory can be 5 frames long only

**Comment by Clare-xiong** [comment]
[all.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10132395/all.zip)
Here are the files I used to run the calculation.

**Comment by marioernestovaldes** [comment]
found the reason, and it is that the two Zn atoms are not incorporated into the receptor group... please, include these two atoms as they are essential for the interacdtion and everything should be fine

**Comment by marioernestovaldes** [comment]
> did you find the reason? I got the positive ΔTotal too, but I don't know why.

@BigMary2001 To better follow up your issue, please, open a new issue and submit your files there. A  positive energy value can be related to several reasons.

**Comment by BigMary2001** [comment]
> 

Thank you! I'll do that.

**Comment by BigMary2001** [comment]
@marioernestovaldes  Thank you! I'll do that soon.

**Comment by Valdes-Tresanco-MS** [comment]
@marioernestovaldes I have been checking, and I think that might be due to the relationship between the Radii and the method for computing Non-polar Gsolv (`inp`). According to the amber manual,` inp = 2` is parameterized to use Tan & Luo's Radii, while by default, gmx_MMPBSA uses another. When topology conversion is done, radiiopt is automatically disabled, so the radii is used from the topology. 
I think I should pay attention to the radii implementation before other things #161.
@Clare-xiong and @BigMary2001 
Please try setting `inp = 1` and rerun the calculation.

**Comment by Clare-xiong** [comment]
> found the reason, and it is that the two Zn atoms are not incorporated into the receptor group... please, include these two atoms as they are essential for the interacdtion and everything should be fine

Thanks for your suggestion. I will try again.

**Comment by Clare-xiong** [comment]
> @marioernestovaldes I have been checking, and I think that might be due to the relationship between the Radii and the method for computing Non-polar Gsolv (`inp`). According to the amber manual,` inp = 2` is parameterized to use Tan & Luo's Radii, while by default, gmx_MMPBSA uses another. When topology conversion is done, radiiopt is automatically disabled, so the radii is used from the topology. I think I should pay attention to the radii implementation before other things #161. @Clare-xiong and @BigMary2001 Please try setting `inp = 1` and rerun the calculation.

Actually, the results were obtained with inp=1.
