### ISSUE TITLE
[Question]: positive ΔTotal using gmx_MMPBSA

### ISSUE THREAD

**Issue by BigMary2001** [Valdes-Tresanco-MS/gmx_MMPBSA#305]
### My Question is...

Why I got positive ΔTotal using gmx_MMPBSA? I docked my ligand to the receptor protein, then I ran the GROMACS simulation using charmm36 force filed. Finally I calculated the binding free energy using gmx_MMPBSA and got positive ΔTotal. I don't know why it happened.

**Comment by BigMary2001** [comment]
My files used to run gmx_MMPBSA are her
[Uploading all.zip…]()
e. Command is `gmx_MMPBSA -O -i mmpbsa.in -cs md.tpr -ci index.ndx -cg 1 13 -ct md.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv -do FINAL_DECOMP_MMPBSA.dat -deo FINAL_DECOMP_MMPBSA.csv `

**Comment by BigMary2001** [comment]
My files used to run gmx_MMPBSA are here. `Command is gmx_MMPBSA -O -i mmpbsa.in -cs md.tpr -ci index.ndx -cg 1 13 -ct md.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv -do FINAL_DECOMP_MMPBSA.dat -deo FINAL_DECOMP_MMPBSA.csv`

**Comment by Valdes-Tresanco-MS** [comment]
Did you close the issue by mistake?
Please, share with us your files
