### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by asharp07** [Valdes-Tresanco-MS/gmx_MMPBSA#306]
### My Question is...

[INFO   ] Parsing results to output files...    File "/home/aksharp/.conda/envs/AmberTools22/bin/gmx_MMPBSA", line 8, in <module>     sys.exit(gmxmmpbsa())   File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 112, in gmxmmpbsa     app.parse_output_files()   File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 1097, in parse_output_files     self._get_decomp()   File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 1212, in _get_decomp     self.calc_types.decomp_normal[key]['ligand'].parse_from_file(self.pre + basename[i] % 'ligand',   File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 1214, in parse_from_file     self._read()   File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 1242, in _read     self._get_decomp_energies(output_file)   File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 1252, in _get_decomp_energies     resnum = self.resl[int(line[4:10])].string KeyError: 1 Exiting. All files have been retained.

**Comment by asharp07** [comment]
Sorry, I received the errorr above and I am not sure how to address it to fix, can someone provide me some insight in how to fix this error?

**Comment by Valdes-Tresanco-MS** [comment]
Please, check this [issue](#293 )

**Comment by asharp07** [comment]
Hi that issue link is the link to this thread, was it intended to be linked to another issue?

**Comment by Valdes-Tresanco-MS** [comment]
My bad... Fixed.

**Comment by asharp07** [comment]
Thank you so much! That was exactly what I needed!
