### ISSUE TITLE
How can use multiple CPU for gmx calculation?

### ISSUE THREAD

**Issue by phuochuynh99** [Valdes-Tresanco-MS/gmx_MMPBSA#307]
### My Question is...

Dear sir and member, how can I increase the CPU for gmx calculation? My project just do with 1 CPU and it spents 10 hours!!!

**Comment by marioernestovaldes** [comment]
mpirun -np CPU gmx_MMPBSA MPI -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 19 20 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

where CPU is the number of CPU you want to use for the calculation

**Comment by phuochuynh99** [comment]
Thank you so much. I got it!!
