### ISSUE TITLE
[Question]: gmx_MMPBSA decomposition question

### ISSUE THREAD

**Issue by BigMary2001** [Valdes-Tresanco-MS/gmx_MMPBSA#311]
### My Question is...

I did decomposistion calculation for every residues in the protein. But energies of some residues are too low. For example, ARG 100 is approximate -240 kcal/mol, will the total ΔG is -22.15 kcal/mol. I don't konw why it happens.

**Comment by BigMary2001** [comment]
the input file is as below:
&general
sys_name="Prot-Lig-CHARMM",
startframe=1,
endframe=701,
interval=20,
temperature=300,
PBRadii=7,
/
&pb
istrng=0.15, fillratio=4.0, radiopt=0, inp=1,use_sav=0,
/
&decomp
idecomp=2, dec_verbose=3,
print_res="all"
/

**Comment by marioernestovaldes** [comment]
please, share the result file... so we can take a closer look

**Comment by BigMary2001** [comment]
The input and output files are [here](https://github.com/BigMary2001/gmxMMPBSA)

**Comment by BigMary2001** [comment]
The input and output files are [here](https://github.com/BigMary2001/gmxMMPBSA)

**Comment by marioernestovaldes** [comment]
The energy you reported above is the one belonging to the complex... you should look at the one located in "DELTAS" on row # 66984... for instance for ARG100 is only 1.19:

Frame # Residue Internal van der Waals Electrostatic Polar Solvation Non-Polar Solv. TOTAL

1	R:A:ARG:100	0	-0.6	1.38	0.4	0	1.19

I would recommend using gmx_MMPBSA _ana to visualize these results and have an idea of the most important residues

**Comment by BigMary2001** [comment]
> The energy you reported above is the one belonging to the complex... you should look at the one located in "DELTAS" on row # 66984... for instance for ARG100 is only 1.19:
> 
> Frame # Residue Internal van der Waals Electrostatic Polar Solvation Non-Polar Solv. TOTAL
> 
> 1 R:A:ARG:100 0 -0.6 1.38 0.4 0 1.19
> 
> I would recommend using gmx_MMPBSA _ana to visualize these results and have an idea of the most important residues

Thank you very much！！！This problem has confused me for a long time.
