### ISSUE TITLE
binding free energy calculation between covalently bonded ligand and protein

### ISSUE THREAD

**Issue by leiqian-nmsu** [Valdes-Tresanco-MS/gmx_MMPBSA#314]
### My Question is...

Dear users, my question is about the binding free energy calculation between covalently bonded ligand and protein. If a ligand binds to a metalloprotein through a meta ion (i.e. a metal ion links ligand and protein through coordination bonds). In this case, do we need to use three-trajectory method rather than single-trajectory method to calculate the binding free energy? Thanks!

**Comment by marioernestovaldes** [comment]
You can use single trajectory method as well... check this tutorial https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Metalloprotein_peptide/
