### ISSUE TITLE
IndexError while parsing dihedraltypes 

### ISSUE THREAD

**Issue by wangshuai-simulation** [Valdes-Tresanco-MS/gmx_MMPBSA#315]
I got an error while run gmx_MMPBSA: IndexError: list index out of range
Here i show the details: 
[INFO   ] Starting gmx_MMPBSA v1.5.6
[INFO   ] Command-line
  mpirun -np 20 gmx_MMPBSA MPI -O -i mmpbsa.in -ct md350K-1-50-60ns-pbcwhole-nosolv-noAU.xtc -cs ../md350KnoDPOSRES-nosolv-noAU.tpr -cp ../topol.top -ci index.ndx -cg 15 1 -cr 0ps-nosolv-noAU-test.pdb -eo FINAL_RESULTS_MMPBSA.csv
[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.
[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /home/tea_yiming/wangshuai/gromacs-2018.3/2018.3-cuda-node/bin/gmx
[INFO   ] Checking external programs...Done.
[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 15_1 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group 15 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 1 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ] Assigning chain ID to structures files according to the reference structure...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 537, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 118, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 461, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 748, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/home/tea_yiming/.local/lib/python3.9/site-packages/ParmEd-3.4.3-py3.9-linux-x86_64.egg/parmed/gromacs/gromacstop.py", line 251, in __init__
    self.read(fname, defines, parametrize)
  File "/home/tea_yiming/.local/lib/python3.9/site-packages/ParmEd-3.4.3-py3.9-linux-x86_64.egg/parmed/gromacs/gromacstop.py", line 403, in read
    key, knd, t, replace = self._parse_dihedraltypes(line)
  File "/home/tea_yiming/.local/lib/python3.9/site-packages/ParmEd-3.4.3-py3.9-linux-x86_64.egg/parmed/gromacs/gromacstop.py", line 805, in _parse_dihedraltypes
    if words[2] in ('1', '2', '3', '4', '5', '8', '9', '10', '11'):
IndexError: list index out of range
Error occurred on rank 0.
Exiting. All files have been retained.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

**Comment by wangshuai-simulation** [comment]
Here are the files:
[file.tar.gz](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10303385/file.tar.gz)

**Comment by wangshuai-simulation** [comment]
Thanks a lot if anyone can help me !

**Comment by Valdes-Tresanco-MS** [comment]
I'm not very familiar with this system. The error seems to be related to
the definition of the dihedral angles in the topology. Please send me the
charmm36-mar2019.ff folder to my email. Right now I'm in another country,
so I can't access Github. Please write to my personal email
***@***.***
Mario S.

**Comment by wangshuai-simulation** [comment]
I have send the files of charmm36-mar2019.ff to your email mariosergiovaldes145@gmail.com.
Thanks for your help !
