### ISSUE TITLE
[Bug-gmx_MMPBSA]: 

### ISSUE THREAD

**Issue by anneichner** [Valdes-Tresanco-MS/gmx_MMPBSA#319]
### Bug summary

hi ;] 

First time using gmx_mmpbsa : i am trying to get the binding energy for my protein-protein complex. However when i execute the command: gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 19 20 -ct com_traj.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

I get the error: MMPBSA_Error: gmx_MMPBSA does not support water/ions molecules in any structure, but we found 6036 molecules in the complex.
Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.

How do I fix this? thank you

### Terminal output

```bash
MMPBSA_Error: gmx_MMPBSA does not support water/ions molecules in any structure, but we found 6036 molecules in the complex.
Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.
```

### Operating system

OS/X

### gmx_MMPBSA Version

gmx_MMPBSA v1.5.7+10.g072297c based on MMPBSA version 16.0 and AmberTools 20

### Python version

Python 3.9.15

### Installation

conda AmberTools + pip

**Comment by Valdes-Tresanco-MS** [comment]
The problem lies in the groups you defined. I suppose they are the ones in the example and do not correspond to the molecules in your system. Make sure you are selecting the correct groups and that they are well-defined (only contain the molecules of interest and not water or ions).

**Comment by anneichner** [comment]
Thank you so much for all your help. I was able to obtain the binding energies for my complex and mutant =]
