### ISSUE TITLE
[Bug-gmx_MMPBSA]:  Can Not output _GMXMMPBSA_COM_index.ndx when using GMX2023

### ISSUE THREAD

**Issue by RazzyChen** [Valdes-Tresanco-MS/gmx_MMPBSA#327]
### Bug summary

My topo and tpr file are generated by GMX2023 and gmx_MMPBSA, Can not output _GMXMMPBSA_COM_index.ndx.
I think this is a GMX issue, not gmx_MMPBSA.

### Terminal output

```bash
MMPBSA_Error: /home/yangzichen/Software/GMX-2023/bin/gmx make_ndx failed when querying index.ndx
Check the gmx_MMPBSA.log file to report the problem.

After I read gmx_MMPBSA.log, I runing this command:
gmx make_ndx -n index.ndx -o _GMXMMPBSA_COM_index.ndx

3585 segmentation fault (core dumped)
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10699489/gmx_MMPBSA.log)

### Operating system

Arch

### gmx_MMPBSA Version

gmx_MMPBSA v1.5.7

### Python version

Python 3.9.15

### Installation

conda AmberTools + pip

**Comment by Valdes-Tresanco-MS** [comment]
It's hard to know what's going on. I just tried the latest version of gromacs and it works fine, both for generating and modifying indexes made with other versions. Please send me the tpr and ndx files to check them.

**Comment by RazzyChen** [comment]
I am so glad to hear from you. I reran the whole process using a smaller protein and ligand. And I did my best to compress the file size but it is still very large(65M). [MD_File](https://drive.google.com/file/d/1eRp42q0R_TLh_JsWoeZbCt82USYlLGJH/view?usp=sharing)

I will reply as soon as I get your message：）

Thank you

**Comment by Valdes-Tresanco-MS** [comment]
According to my tests it seems that Gromacs2023 has a bug. To modify the index.ndx it requires the tpr, which does not happen in previous versions. We will try to fix the problem as soon as possible in **gmx_MMPBSA**.

**Comment by RazzyChen** [comment]
Thanks for your message : )

If there is anything else I can do please contact me.

Thank you for all you have done for gmx_MMPBSA, it is the first choice to calculate the free energy.

**Comment by Valdes-Tresanco-MS** [comment]
Hi there. I solve the problem. 
Please, update gmx_MMPBSA from GitHub
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA.git -U
```
Please also check if you are using Gromacs2023 as you may be using version 2021.8 which is installed with conda, which is not compatible. You can make sure by executing the `source /path/to/gromacs/bin/GMXRC` after activating the gmxMMPBSA environment.
Let me know if work for you

**Comment by RazzyChen** [comment]
It works. gmx_MMPBSA can correctly process the index file generated by GMX2023. Thank you

**Comment by hanahg** [comment]
Hi,
I have the same problem, i updated gmx_MMPBSA using the command you mentioned, but the problem did not resolved.  
I did the calculation before without any error but now i want to redo with some changes.
summary of error:

 [DEBUG  ] Reading structure file
[DEBUG  ] Reading file md10_rerun.tpr, VERSION 2024.4 (single precision)
[DEBUG  ] 
[DEBUG  ] -------------------------------------------------------
[DEBUG  ] Program:     gmx make_ndx, version 2019.6
[DEBUG  ] Source file: src/gromacs/fileio/tpxio.cpp (line 2695)
[DEBUG  ] 
[DEBUG  ] Fatal error:
[DEBUG  ] reading tpx file (md10_rerun.tpr) version 134 with version 116 program
[DEBUG  ] 
[DEBUG  ] For more information and tips for troubleshooting, please check the GROMACS
[DEBUG  ] website at http://www.gromacs.org/Documentation/Errors
[DEBUG  ] -------------------------------------------------------
[ERROR  ] MMPBSA_Error 

/home/fati/miniforge3/envs/gmxMMPBSA/bin.AVX2_256/gmx make_ndx failed when querying index_new.ndx

Check the gmx_MMPBSA.log file to report the problem.

**Comment by hanahg** [comment]
I resolved it

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
