### ISSUE TITLE
[Bug-gmx_MMPBSA]: sander failed with prmtop COM.prmtop!

### ISSUE THREAD

**Issue by Tangbbmc** [Valdes-Tresanco-MS/gmx_MMPBSA#336]
### Bug summary

[ERROR  ] CalcError /home/twg/miniconda3/envs/AmberTools22/bin/sander failed with prmtop COM.prmtop!

### Terminal output

```bash
[INFO   ] 10 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 2 CPUs...
[WARNING] PB/RISM/NMODE will be calculated with multiple threads, make sure you have enough RAM.
[INFO   ] Running calculations on normal system...
[INFO   ] Beginning GB calculations with /home/twg/miniconda3/envs/AmberTools22/bin/sander
[INFO   ]   calculating complex contribution...
[INFO   ]   calculating receptor contribution...
[INFO   ]   calculating ligand contribution...
[INFO   ]   Beginning PB calculations with /home/twg/miniconda3/envs/AmberTools22/bin/sander
[INFO   ]   calculating complex contribution...
[ERROR  ] CalcError /home/twg/miniconda3/envs/AmberTools22/bin/sander failed with prmtop COM.prmtop!
	
If you are using sander and PB calculation, check the *.mdout files to get the sander error
.
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10768191/gmx_MMPBSA.log)

### Operating system

Ubuntu 18.04

### gmx_MMPBSA Version

gmx_MMPBSA v1.5.7

### Python version

 PYTHON VERSION: 3.9.16 

### Installation

conda AmberTools + pip

**Comment by marioernestovaldes** [comment]
can you send us the *.mdout files?

**Comment by Tangbbmc** [comment]
Sure, attached are  *.mdout files.





唐王刚 Wanggang Tang
博士 副教授 
Ph.D.  Associate Professor
Organization: Bengbu Medical College
Address: No. 2600, Donghai Avenue. Bengbu, Anhui, China









发件人："Mario E. Valdés-Tresanco" ***@***.***>
发送日期：2023-02-18 05:32:55
收件人：Valdes-Tresanco-MS/gmx_MMPBSA ***@***.***>
抄送人：Tangbbmc ***@***.***>,Author ***@***.***>
主题：Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Bug-gmx_MMPBSA]: (Issue #336)

can you send us the *.mdout files?

**Comment by marioernestovaldes** [comment]
sorry, only the .log file is attached

**Comment by Tangbbmc** [comment]
[mdout_files.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10773670/mdout_files.zip)

The *.mdout files was also attached.

**Comment by Tangbbmc** [comment]
All output files are attached! Thank you！It's worth noting that when using command "gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 1 13 -ct com_traj.xtc -lm ligand.mol2 -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv" (without MPI), there are any errors reported. 





唐王刚 Wanggang Tang
博士 副教授 
Ph.D.  Associate Professor
Organization: Bengbu Medical College
Address: No. 2600, Donghai Avenue. Bengbu, Anhui, China









发件人："Mario E. Valdés-Tresanco" ***@***.***>
发送日期：2023-02-18 14:15:35
收件人：Valdes-Tresanco-MS/gmx_MMPBSA ***@***.***>
抄送人：Tangbbmc ***@***.***>,Author ***@***.***>
主题：Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Bug-gmx_MMPBSA]: (Issue #336)

sorry, only the .log file is attached

**Comment by marioernestovaldes** [comment]
There is no error reported in the *.mdout files... try reducing the fillratio to 2 to see if that solves the problem

**Comment by Tangbbmc** [comment]
As you suggested, I reduced the fillratio from 4 to 2, no errors were reported. Thanks for your kind help!

发件人："Mario E. Valdés-Tresanco" ***@***.***>
发送日期：2023-02-19 06:12:25
收件人：Valdes-Tresanco-MS/gmx_MMPBSA ***@***.***>
抄送人：Tangbbmc ***@***.***>,Author ***@***.***>
主题：Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Bug-gmx_MMPBSA]: sander failed with prmtop COM.prmtop! (Issue #336)

There is no error reported in the *.mdout files... try reducing the fillratio to 2 to see if that solves the problem

**Comment by marioernestovaldes** [comment]
If that solves the problem, seems the RAM memory is insufficient to run the PB calculation in parallel with `fillratio=4`. Anyway, keep in mind that running PB in parallel will consume more RAM, especially when using `fillratio=4`
