### ISSUE TITLE
Install gmx_MMPBSA in HPC

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/gmx_MMPBSA#342]
### Discussed in https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/discussions/341

<div type='discussions-op-text'>

<sup>Originally posted by **AbdelmoujoudFaris** February 22, 2023</sup>
Dear, I hope this message finds you well. I am writing to request your assistance with installing GMXMMPBSA on an HPC. I have attempted to install the software myself, but have encountered some issues that I have been unable to resolve.

If possible, I would greatly appreciate your guidance on the installation process and any troubleshooting tips you may have. I am also happy to provide any additional information or log files that may be helpful in diagnosing the problem.

Thank you for considering my request. I look forward to hearing from you soon.

Best regards,</div>

**Comment by marioernestovaldes** [comment]
No error in the log file... do you have any other log file from the job in the cluster that could contain the error?

**Comment by AbdelmoujoudFaris** [comment]
i have slurm file
![Screenshot 2023-02-22 135233](https://user-images.githubusercontent.com/110561389/220624948-abb52968-8e8a-4217-a0f8-96e01737d551.jpg)

**Comment by AbdelmoujoudFaris** [comment]
[bigmem42:664247] OPAL ERROR: Unreachable in file ext3x_client.c at line 112
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

  version 16.05 or later: you can use SLURM's PMIx support. This
  requires that you configure and build SLURM --with-pmix.

  Versions earlier than 16.05: you must use either SLURM's PMI-1 or
  PMI-2 support. SLURM builds PMI-1 by default, or you can manually
  install PMI-2. You must then build Open MPI using --with-pmi pointing
  to the SLURM PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[bigmem42:664247] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

**Comment by marioernestovaldes** [comment]
Do you have a halogen atom in your system? If so please follow this tutorial https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Protein_ligand_LPH_atoms_CHARMMff/

**Comment by AbdelmoujoudFaris** [comment]
I obtained  the same results

**Comment by Valdes-Tresanco-MS** [comment]
This error is due to the fact that ParmEd does not support virtual sites in the topology. Please check the files (`*.top` and `*.itp`) very well, as this example has been extensively tested.

**Comment by AbdelmoujoudFaris** [comment]
.top 
;;
;; Generated by CHARMM-GUI FF-Converter
;;
;; Correspondance:
;; jul316@lehigh.edu or wonpil@lehigh.edu
;;
;; The main GROMACS topology file
;;

; Include forcefield parameters
#include "toppar/forcefield.itp"
#include "toppar/PROA.itp"
#include "toppar/LIG.itp"
#include "toppar/SOD.itp"
#include "toppar/CLA.itp"
#include "toppar/TIP3.itp"

[ system ]
; Name
Title

[ molecules ]
; Compound	#mols
PROA  	           1
LIG   	           1
SOD   	          50
CLA   	          50
TIP3  	       17598

**Comment by Valdes-Tresanco-MS** [comment]
Please, attach the LIG.itp file

**Comment by AbdelmoujoudFaris** [comment]
Please when can i found .itp

**Comment by Valdes-Tresanco-MS** [comment]
As you can see in the topology file, all itp files are inside the toppar folder:
```
#include "toppar/forcefield.itp"
#include "toppar/PROA.itp"
#include "toppar/LIG.itp"
#include "toppar/SOD.itp"
#include "toppar/CLA.itp"
#include "toppar/TIP3.itp"
```

In these cases, the virtual site is defined in the itp of the ligand (LIG.itp). Please, follow the instructions detailed in the example. In this case, LIG.itp is equivalent to HETA.itp in the example.

**Comment by AbdelmoujoudFaris** [comment]
Thank you, her it is,
[LIG.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10808447/LIG.zip)

**Comment by Valdes-Tresanco-MS** [comment]
As you can see in lines 315-317, this file contain virtual sites. Please, follow the instructions detailed in the example

**Comment by AbdelmoujoudFaris** [comment]
When I opened the terminal and followed the example, I received this message, and I am re-running the calculation: /cm/local/apps/slurm/var/spool/job176985/slurm_script: line 7: gmx_MMPBSA: command not found

**Comment by Valdes-Tresanco-MS** [comment]
Are you activating the conda environment? If you followed the installation instructions, you must run this command every time you start the terminal

```bash
conda activate gmxMMPBSA
```

**Comment by AbdelmoujoudFaris** [comment]
Yes, with this command, MMPSA is active and please, if you have a sample with a script for the effector in my space, could you share it with me? Thank you.

**Comment by Valdes-Tresanco-MS** [comment]
Sorry, I'm lost. Which script are you referring to? What example are you running? Why is the error reported inside a script?

**Comment by AbdelmoujoudFaris** [comment]
i used this script : gmx_MMPBSA -O -i mmpbsa.in -cs step5_production.tpr -cp topol.top -ci new_index.ndx -cg 1 17 -ct step5_production_noPBC_trial.xtc

**Comment by Valdes-Tresanco-MS** [comment]
Your prompt should initially display `(base)username@PCname$`. That means you have conda running on that terminal. When you activate the environment using the above command, it should change to `(gmxMMPBSA)username@PCname$`. You will then be in the proper environment. If the gmx_MMPBSA command is not available, you have not installed gmx_MMPBSA. To do this, run 
```bash
python -m pip install gmx_MMPBSA
```
You can check if gmx_MMPBSA is installed as follow:
```
conda list
```
or
```
python -m pip list
```

**Comment by AbdelmoujoudFaris** [comment]
![Screenshot 2023-02-22 135233](https://user-images.githubusercontent.com/110561389/220824117-33184826-7abd-4493-8ff6-ca2e44c61236.jpg)

**Comment by AbdelmoujoudFaris** [comment]
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.24.2                   pypi_0    pypi
openssl                   3.0.8                h0b41bf4_0    conda-forge
packaging                 23.0                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.9.16          h2782a2a_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.7.1                 pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
setuptools                67.4.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.64.1                   pypi_0    pypi
tzdata                    2022g                h191b570_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.14.0                   pypi_0    pypi

**Comment by AbdelmoujoudFaris** [comment]
(gmxMMPBSA) [a.faris@login02 gromacs]$ python -m pip list
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
appdirs                       1.4.4
asn1crypto                    1.4.0
atomicwrites                  1.4.0
attrs                         21.2.0
Babel                         2.9.1
bcrypt                        3.2.0
bitstring                     3.1.7
blist                         1.3.6
Bottleneck                    1.3.2
CacheControl                  0.12.6
cachy                         0.3.0
certifi                       2020.12.5
cffi                          1.14.5
chardet                       4.0.0
cleo                          0.8.1
click                         7.1.2
clikit                        0.6.2
colorama                      0.4.4
contourpy                     1.0.7
crashtest                     0.3.1
cryptography                  3.4.7
cycler                        0.11.0
Cython                        0.29.23
deap                          1.3.1
decorator                     5.0.7
distlib                       0.3.1
docopt                        0.6.2
docutils                      0.17.1
ecdsa                         0.16.1
filelock                      3.0.12
flit                          3.2.0
flit-core                     3.2.0
fonttools                     4.38.0
fsspec                        2021.4.0
future                        0.18.2
gmx-MMPBSA                    1.6.0

**Comment by Valdes-Tresanco-MS** [comment]
This is very rare. gmx_MMPBSA should be on both lists. I don't understand how it may have gmx_MMPBSA installed, but the executables are unavailable. Please remove that environment and do a fresh install of gmx_MMPBSA. I think this is the simplest way to solve the problem.

**Comment by AbdelmoujoudFaris** [comment]
Ok thanks, note that when I used 'conda activate gmxMMPBSA', I got '(gmxMMPBSSA)username@PCname$'. And when I used 'activate gmxMMPBSA', I got '(base)username@PCname$', which I can use. Thanks

**Comment by Valdes-Tresanco-MS** [comment]
Always you must use `conda activate environment_name`. As I know, activate is not a command, so you should get an error like this `activate: command not found`

**Comment by AbdelmoujoudFaris** [comment]
I reinstalled GMXMMPBSA and after running it, it gives... : Traceback (most recent call last):
  File "/home/a.faris/.conda/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 6, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File "/home/a.faris/.local/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 27, in <module>
    from GMXMMPBSA import main
  File "/home/a.faris/.local/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 31, in <module>
    from GMXMMPBSA import utils, __version__
  File "/home/a.faris/.local/lib/python3.9/site-packages/GMXMMPBSA/utils.py", line 43, in <module>
    import pandas as pd
  File "/cm/shared/apps/eb/software/SciPy-bundle/2021.05-foss-2021a/lib/python3.9/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/cm/shared/apps/eb/software/SciPy-bundle/2021.05-foss-2021a/lib/python3.9/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/cm/shared/apps/eb/software/SciPy-bundle/2021.05-foss-2021a/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/cm/shared/apps/eb/software/SciPy-bundle/2021.05-foss-2021a/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/cm/shared/apps/eb/software/SciPy-bundle/2021.05-foss-2021a/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
RuntimeError: NumPy was built with baseline optimizations: 
(SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX) but your machine doesn't support:
(AVX512_CLX).

**Comment by AbdelmoujoudFaris** [comment]
[New folder1.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10812568/New.folder1.zip)
Please can you check this new ffiles

**Comment by AbdelmoujoudFaris** [comment]
Sir, your sample worked. I have resolved the problem. Thank you so much

**Comment by AbdelmoujoudFaris** [comment]
In the 'toppar' folder of your sample, there are two files named HETA...itp. However, in my 'toppar' folder, there are only two files named HETA for the same molecule.

**Comment by AbdelmoujoudFaris** [comment]
> Do you have a halogen atom in your system? If so please follow this tutorial https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Protein_ligand_LPH_atoms_CHARMMff/

how can generate these files : HETA.itp, HETA_original_with_LPH_info.itp

**Comment by Valdes-Tresanco-MS** [comment]
As the first issue was solved, I closed the issue. Please, reopen it if required or open a new one for other questions

**Comment by Valdes-Tresanco-MS** [comment]
Please, report these problems in Github or our Google groups. We are
applying for funding and we need evidence of interaction with our
community. And this can be an error for other members of our community.

Please, use all packages installed in the conda environment. Unset the
variable PYTHONPATH before executing gmx_MMPBSA.
As I said before, in your case LIG.itp = HETA.itp in our example.

**Comment by AbdelmoujoudFaris** [comment]
I will put the instructions in the approach in detail and thank you so much

**Comment by AbdelmoujoudFaris** [comment]
Regarding the use of gmx_MMPBSA, I followed the step-by-step tutorial that you attached, which can be found at https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Protein_ligand_LPH_atoms_CHARMMff/.

To install gmx_MMPBSA, I followed the instructions in the installation guide at https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/installation/. Before that, I used the source activate command as instructed in the tutorial.

For the Amber-related part, I skipped all the Amber. commands and directly launched the command as with Python.

**Comment by AbdelmoujoudFaris** [comment]
Hello @Valdes-Tresanco-MS @marioernestovaldes , please I tried to make mmpbsa protein-protein, but it does not work with my proteins, with the exmpl of you it works.
Knowing I do splitch for 1 - protein to separate the two protein and specify who ligand and then I do protein|ligand to put it eco. but does not work
![comlex](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/110561389/35aa8922-3f56-4d33-9706-5c2507313be0)

**Comment by AbdelmoujoudFaris** [comment]
[ota.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/15213292/ota.zip)

**Comment by AbdelmoujoudFaris** [comment]
[ota.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/15213293/ota.txt)
