### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#343]
@Valdes-Tresanco-MS Hello, according to the above answer, I just updated gmxMMPBSA to 1.60. But it appear a Indexerror. This error is unexist at 1.5.7  version. The calculation is a test file for gmx_MMPBSA_example. The example is decomposition_analysis. Looking forward to your reply!

```bash
[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group SOLU_chain1_SOLU_chain2 (3_4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group SOLU_chain1 (3) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group SOLU_chain2 (4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected Amber/OPLS force field topology format...
[INFO   ] Assigning PBRadii mbondi2 to Complex...
[INFO   ] Writing Normal Complex AMBER topology...
[INFO   ] No Receptor topology file was defined. Using ST approach...
[INFO   ] Building AMBER Receptor topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Receptor...
[INFO   ] Writing Normal Receptor AMBER topology...
[INFO   ] No Ligand topology file was defined. Using ST approach...
[INFO   ] Building AMBER Ligand topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Ligand...
[INFO   ] Writing Normal Ligand AMBER topology...
[INFO   ] Selecting residues by distance (4 ?) between receptor and ligand for decomposition analysis...
[INFO   ] Selected 17 residues:
R:A:THR:13  R:A:HID:15  R:A:SER:17  R:A:PRO:18  R:A:TYR:23  R:A:TYR:24  R:A:TYR:25  R:A:GLN:31  R:A:SER:32  R:A:THR:33
R:A:TRP:34  L:B:ALA:4   L:B:PRO:5   L:B:PRO:6   L:B:LEU:7   L:B:PRO:8   L:B:ARG:9

[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 100, in gmxmmpbsa
    app.file_setup()
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 127, in file_setup
    create_inputs(INPUT, self.normal_system, self.pre)
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 109, in create_inputs
    com_mdin = SanderGBDecomp(com_input, rec_res, lig_res, pri_res)
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 841, in __init__
    self.make_mdin()
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 326, in make_mdin
    self.mdin.change(self.parent_namelist[key], key, value)
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/amber/mdin/mdin.py", line 197, in change
    if (value[0] == value[-1] == "'") or (value[0] == value[-1] == '"'):
IndexError: string index out of range
Exiting. All files have been retained.
```
_Originally posted by @Luckaswww in https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/273#issuecomment-1439616921_

**Comment by marioernestovaldes** [comment]
Please, send the gmx_MMPBSA.log file

**Comment by Luckaswww** [comment]
Sorry. This is the gmx_MMPBSA.log file
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/10904490/gmx_MMPBSA.log)

**Comment by Valdes-Tresanco-MS** [comment]
I don't see any error in this gmx_MMPBSA.log. What error do you get?

**Comment by Luckaswww** [comment]
You are right, however, I import the line gmx_MMPBS -O -i mmpbsa.in .......，the error will appear, and causing the process to end(this is a test about decomposition_analysis).  The error is not found in other examples. So, I don't know why it appear.
[INFO   ] Loading and checking parameter files for compatibility...
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 100, in gmxmmpbsa
    app.file_setup()
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 127, in file_setup
    create_inputs(INPUT, self.normal_system, self.pre)
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 109, in create_inputs
    com_mdin = SanderGBDecomp(com_input, rec_res, lig_res, pri_res)
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 841, in __init__
    self.make_mdin()
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 326, in make_mdin
    self.mdin.change(self.parent_namelist[key], key, value)
  File "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/amber/mdin/mdin.py", line 197, in change
    if (value[0] == value[-1] == "'") or (value[0] == value[-1] == '"'):
IndexError: string index out of range
Exiting. All files have been retained.

**Comment by Valdes-Tresanco-MS** [comment]
You are using a wrong ParmEd version. Please, update ParmEd as follow:
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4 -U
```

**Comment by Luckaswww** [comment]
OK，I will have a try ，thank you so much


发件人："Mario Sergio Valdés Tresanco" ***@***.***>
发送日期：2023-03-08 14:58:38
收件人：Valdes-Tresanco-MS/gmx_MMPBSA ***@***.***>
抄送人：
主 题：Re: [Valdes-Tresanco-MS/gmx_MMPBSA] IndexError: string index out of range (Issue #343)

You are using a wrong ParmEd version. Please, update ParmEd as follow:

python -m pip install ***@***.*** -U

**Comment by Luckaswww** [comment]
Oh, I'm so sorry. I have been try to update Parmed, however, the result is unchange. I'm confused. To be honested, I also tried to calculate other example, except Protein_ligand_CHARMM and Protein _membrane_CHARMM，other case is not work. It appear similarly error. The parmed version was updated at 4.0.0. And the pyqt5 is 5.15.6 version, python is 3.9.15, mpi4py is 3.1.3.

**Comment by xxxiaogangg** [comment]
I got the same problem today. The problem was solved by editing the Python file "/work/home/nano005/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/amber/mdin/mdin.py" in line 197.

`
if isinstance(value, str):
    if (value[0] == value[-1] == "'") or (value[0] == value[-1] == '"'):
        value = value[1:-1]
`
replace the above code with:
`
if isinstance(value, str):
    try:
        if (value[0] == value[-1] == "'") or (value[0] == value[-1] == '"'):
            value = value[1:-1]
    expect IndexError as e:
        pass
`

I don't know if that's a good choice, but at least it works.

**Comment by Valdes-Tresanco-MS** [comment]
I haven't tested ParmEd v4.0.0 compatibility with gmx_MMPBSA yet. My recommendation is:
- Uninstall ParmEd (`python -m pip uninstall parmed`)
- Install ParmEd from my fork (`python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4 -U`)

**Comment by Valdes-Tresanco-MS** [comment]
This bug has recently been fixed in parmed and in my most recent contribution, I've tested compatibility with gmx_MMPBSA, including several missing features from the v3.4 to the main branch.
It should work by installing ParmEd from the repository directly.
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git -U
```
Let me know if it works for you
