### ISSUE TITLE
[Bug-gmx_MMPBSA]: Can't load "_GMXMMPBSA_info"

### ISSUE THREAD

**Issue by yanze039** [Valdes-Tresanco-MS/gmx_MMPBSA#347]
### Bug summary

I got an error when I tried to use the API to load my result.

My code is:

```
from GMXMMPBSA import API as gmxMMPBSAapi
data = gmxMMPBSAapi.load_gmxmmpbsa_info("_GMXMMPBSA_info")
```

### Terminal output

```bash
Traceback (most recent call last):
  File "/home/gridsan/ywang3/Project/Capping/md_trajs/analysis_decomp.py", line 6, in <module>
    data = gmxMMPBSAapi.load_gmxmmpbsa_info("_GMXMMPBSA_info")
  File "/home/gridsan/ywang3/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 1047, in load_gmxmmpbsa_info
    d_mmpbsa.load_file(fname)
  File "/home/gridsan/ywang3/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 251, in load_file
    self._get_fromApp(self.fname)
  File "/home/gridsan/ywang3/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 876, in _get_fromApp
    self._finalize_reading(ifile)
  File "/home/gridsan/ywang3/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 893, in _finalize_reading
    self._get_frames()
  File "/home/gridsan/ywang3/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/API.py", line 932, in _get_frames
    ts = self.timestep or 1
AttributeError: 'MMPBSA_API' object has no attribute 'timestep'
```

### gmx_MMPBSA.log

No log files.

### Operating system

Slurm Cluster

### gmx_MMPBSA Version

gmx_MMPBSA v1.6.0 based on MMPBSA version 16.0 and AmberTools 20

### Python version

3.9.15

### Installation

conda AmberTools + pip

**Comment by Valdes-Tresanco-MS** [comment]
From v1.5.0 we changed the API structure. Now is as follows:
```python
from GMXMMPBSA.API import MMPBSA_API


mmpbsa = MMPBSA_API()
mmpbsa.setting_time()
mmpbsa.load_file("COMPACT_MMXSA_RESULTS.mmxsa")

energy_data = mmpbsa.get_energy()
#decomp_data = mmpbsa.get_decomp_energy()
#entropy_data = mmpbsa.get_entropy()

energy['data']
```
`energy['data']` is a dict with the following structure:
```python
{'normal': {'gb': 

     delta                        
           VDWAALS        EEL        EGB     ESURF       GGAS      GSOLV      TOTAL 
Frames                                                                              
1       -39.051500 -38.236800  53.039300  4.343968 -77.288300  48.695332 -28.592968 
2       -35.311800 -42.644600  51.566700  4.368333 -77.956400  47.198367 -30.758033 
3       -28.630300 -54.648600  59.819300  4.642126 -83.278900  55.177174 -28.101726 
4       -35.300300 -53.736400  62.242100  4.680450 -89.036700  57.561650 -31.475050 
5       -35.992100 -44.765600  56.710300  4.465416 -80.757700  52.244884 -28.512816 
6       -33.517300 -51.878800  61.891700  4.533808 -85.396100  57.357892 -28.038208 
7       -30.114700 -53.579200  61.549800  4.492163 -83.693900  57.057637 -26.636263 
8       -35.820100 -50.719400  61.046400  4.641547 -86.539500  56.404853 -30.134647 
9       -31.962200 -53.611400  62.280300  4.778150 -85.573600  57.502150 -28.071450 
10      -28.342100 -55.196800  60.370500  4.570723 -83.538900  55.799777 -27.739123 
Average -33.404240 -49.901760  59.051640  4.551668 -83.306000  54.499972 -28.806028 
SD        3.361367   5.587973   3.726556  0.131360   3.526148   3.618918   1.424849 
SEM       1.062958   1.767072   1.178441  0.041540   1.115066   1.144402   0.450577  }}
```
It means, `{'type of system': {'model': Dataframe containing all parts (com, rec, lig, delta) data}}`

I am sorry that the API is not documented. We plan to make some big changes for version 2.0, so we have delayed the documentation of this API. If what you require is the data, it is easily exportable from gmx_MMPBSA_ana for each chart. Anyway, let me what do you want to do and I'll be happy to help you program it.

**Comment by Dead-fisher** [comment]
Hi Valdes, 

Thanks so much for your replying. 
```
decomp_data = mmpbsa.get_decomp_energy()
```
is what I exactly want to do.

I am using the HPC cluster to handle a bunch of ligand-protein pairs, and I would like to do some customized analysis from the source data. That's why I am refering to the API to retrive the raw results.

Anyway, I believe I can manipulate from your code to achieve my goal. I'll let you know if I have any question.

BTW, when the version 2.0 will come out? I'd like to try the new guy.

Thanks for developing this tool.

Cheers,
Yanze

**Comment by Valdes-Tresanco-MS** [comment]
> Hi Valdes,
> Thanks so much for your replying.
> ```
> decomp_data = mmpbsa.get_decomp_energy()
> ```
> is what I exactly want to do.
> I am using the HPC cluster to handle a bunch of ligand-protein pairs, and I would like to do some customized analysis from the source data. That's why I am refering to the API to retrive the raw results.
> Anyway, I believe I can manipulate from your code to achieve my goal. I'll let you know if I have any question.

Well, in gmx_MMPBSA_ana you can deal with a large amount of data simultaneously. If you carried out your calculations on an HPC, then you can copy the file COMPACT_MMXSA_RESULTS.mmxsa to your PC and analyze the results with gmx_MMPBSA_ana. But whatever you feel comfortable with is fine.


> BTW, when the version 2.0 will come out? I'd like to try the new guy.

We are going to apply for funding now in April. If we win the grant, I would be dedicated full-time to the development of the program. Funding starts in November, but I think I would release version 2 a little earlier. We're actually considering changing the name to make it more generic, but it's not decided yet.

**Comment by Dead-fisher** [comment]
Thanks, that helps alot.

Well, since my PC is Mac with arm framework, I can't `conda install ambertools` in a normal way (which will give 'PackageNotFoundError'). There is basically no arm source package for it ...

**Comment by Valdes-Tresanco-MS** [comment]
Oh, I see. One of the things we are planning for version 2 is to separate the analysis tool from the calculation tool. That way, we will support analysis on all operating systems without installing all the tools.

**Comment by Dead-fisher** [comment]
That's cool.

Thank you so much anyway.
