### ISSUE TITLE
Mismatch atom numbers

### ISSUE THREAD

**Issue by asharp07** [Valdes-Tresanco-MS/gmx_MMPBSA#357]
Hi I am running into the following fatal error: 

Fatal error:
[DEBUG  ] Index[2022] 2035 is larger than the number of atoms in the
[DEBUG  ] trajectory file (2034). There is a mismatch in the contents
[DEBUG  ] of your -f, -s and/or -n files.

The code I am running: 
gmx_MMPBSA -i mmpbsa.in -o MMPBSA.dat -cs pd1mn11.tpr -ct pd1mn11_750_trnc.xtc -ci pd1mn11.ndx -cg 1 3

I have tried including and excluding a -cr pdb file, including and excluding topol.top file, and using gromacs 2019 and three versions of 2020. I used the same index file to generate my tpr, xtc, and pdb files. I will note that my simulation has caps, but when I export the full system from my xtc after using my index file, the caps do not appear to be there (which is what I want). Everything I look at seems to have 2034 atoms, I am not sure why it is saying 2035. I'd appreciate any help in this topic.

**Comment by marioernestovaldes** [comment]
it seems there is something going on with the input files... could you please send us the files you are using:

- mmpbsa.in 
- pd1mn11.tpr 
- pd1mn11_750_trnc.xtc
- pd1mn11.ndx

**Comment by Valdes-Tresanco-MS** [comment]
Sometimes the problem is solved by creating a new index. We recommend using the full system trajectory. gmx_MMPB creates a clean trajectory from the groups you define. Please, create a new index based on your tpr, redefine your interest groups, if necessary, and check if the error persists.

**Comment by asharp07** [comment]
I ended up solving this by including the peptide caps. I did run into another error after this though - at step "Parsing results to output files" I get the following:

 File "/home/aksharp/.conda/envs/AmberTools22/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 112, in gmxmmpbsa
    app.parse_output_files()
  File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 1097, in parse_output_files
    self._get_decomp()
  File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 1208, in _get_decomp
    self.calc_types.decomp_normal[key]['receptor'].parse_from_file(self.pre + basename[i] % 'receptor',
  File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 1214, in parse_from_file
    self._read()
  File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 1242, in _read
    self._get_decomp_energies(output_file)
  File "/home/aksharp/.conda/envs/AmberTools22/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 1252, in _get_decomp_energies
    resnum = self.resl[int(line[4:10])].string
KeyError: 1

Do you have an suggestions on how to fix this?

**Comment by Valdes-Tresanco-MS** [comment]
Which version of gmx_MMPBSA are you using?

**Comment by asharp07** [comment]
I believe its v3.4

**Comment by Valdes-Tresanco-MS** [comment]
The current version of gmx_MMPBSA is v1.6.0. Please, check which version you are using in the gmx_MMPBSA.log file or the terminal output or executing `gmx_MMPBSA -v`

**Comment by asharp07** [comment]
Oops! Yeah v1.5.6, I will try updating to v1.6.0 and see if that fixes my issue. I appreciate the quick responses!

**Comment by Valdes-Tresanco-MS** [comment]
You can update gmx_MMPBSA to v1.6.0 (`python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA.git -U`) and then make a rewrite output (`gmx_MMPBSA --rewrite-output`) to process the calculations of v1.5.6. Please, note that you must install the dev version since version v1.6.0 has a bug related to the PB decomposition.

**Comment by Valdes-Tresanco-MS** [comment]
Hey @asharp07, did everything work fine?

**Comment by asharp07** [comment]
Hi I am trying to work through with an incompatibility on my slurm version now. I will close this out and open a new one if I still face issues once my sys admin helps me work through that error. I really appreciate the support!
