### ISSUE TITLE
[ENH]: Hoping that gmx_MMPBSA can also perform binding free energy calculation and decomposition using the output files from another molecular dynamic software, YASARA (http://yasara.org/products.htm#dynamics).

### ISSUE THREAD

**Issue by Tangbbmc** [Valdes-Tresanco-MS/gmx_MMPBSA#358]
### In which tool?

gmx_MMPBSA

### New Feature

Many researchers (like me) performed molecular dynamic simulation using YASARA Dynamics/Structure. The molecular dynamic simulation steps can be simply completed via running an edited md_run.mcr script. Therefore, I hope gmx_MMPBSA can handle the output files from YASARA to perform binding free energy calculation and energy decomposition analysis.

### Relevance

None

### Difficulty to implement

None

**Comment by marioernestovaldes** [comment]
As far as I know, YASARA is paid software (is this correct?) Since we don't have the license, it will be difficult to perform the tests. Probably you can follow this thread (https://groups.google.com/g/gmx_mmpbsa/c/IzIO-2ZR26U), although Paul ended up performing MD simulation in GROMACS...

**Comment by Tangbbmc** [comment]
Oh. That's a pity. As you said, YASARA is indeed a paid program.



唐王刚 Wanggang Tang
博士 副教授 
Ph.D.  Associate Professor
Organization: Bengbu Medical College
Address: No. 2600, Donghai Avenue. Bengbu, Anhui, China






  



---- Replied Message ----
From  Mario E. ***@***.***> Date  03/20/2023 17:12 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [ENH]: Hoping that gmx_MMPBSA can also perform binding free energy calculation and decomposition using the output files from another molecular dynamic software, YASARA (http://yasara.org/products.htm#dynamics). (Issue #358)  

As far as I know, YASARA is paid software (is this correct?) Since we don't have the license, it will be difficult to perform the tests. Probably you can follow this thread (https://groups.google.com/g/gmx_mmpbsa/c/IzIO-2ZR26U), although Paul ended up performing MD simulation in GROMACS...

**Comment by Valdes-Tresanco-MS** [comment]
@Tangbbmc Thank you for considering using gmx_MMPBSA.
Our intention is to support as many MD engines as possible. However, it is difficult because in many cases, the software is paid and in the worst case, it is difficult to port (convert and compatibility with other formats). At the moment, we are focused on supporting AMBER and NAMD, but we will work so that everyone is welcome
