### ISSUE TITLE
PreProcessorError: Bad #include syntax

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/gmx_MMPBSA#359]
I have run a simulation for a protein-ligand complex using amber99 force field（amber 99 for protein，acpype for ligand） in GROMACS and when I tried to run gmx_MMPBSA it gave me this error

[INFO   ] Building Normal Complex Amber topology...
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 689, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 125, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 534, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 821, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 251, in __init__
    self.read(fname, defines, parametrize)
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 289, in read
    for line in f:
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/_gromacsfile.py", line 44, in __iter__
    for line in self._handle:
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/_cpp.py", line 175, in __iter__
    self._ppcmdmap[cmd](self, args)
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/_cpp.py", line 30, in wrapper
    return func(self, args)
  File "/home/lixin347/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/_cpp.py", line 279, in _pp_include
    raise PreProcessorError('Bad #include syntax')
PreProcessorError: Bad #include syntax
Exiting. All files have been retained.

_Originally posted by @347lixin in https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/84#issuecomment-1477752985_

**Comment by 347lixin** [comment]
This is my data of MD 100 ns,topol.top is in it, protein CD36 is generated by amber99 force field, ligand daidzein (DAI) is generated by acpype.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Valdes-Tresanco-MS/gmx_MMPBSA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 凌晨1:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Valdes-Tresanco-MS/gmx_MMPBSA] PreProcessorError: Bad #include syntax (Issue #359)





 
This seems to be something related to the topology format... could you please attach the topology file?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

MD of CD36_daidzin 100 ns.zip (2.52G, 2023年04月21日 02:23 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=37663263f9e7e36ba4e21e314562561a1d1202015b03520248040053514f5705045f1f535303051853520506510705045d040551637f647821465d0543212006533956020a061e5c0b46035353420a464b1c5b13635f&t=exs_ftn_download&code=ef2ccbd5

**Comment by Valdes-Tresanco-MS** [comment]
Commonly acpype generates topologies with format problems, for example, space before `#` statement, missing `;`, etc. Please, make sure that the topology format is correct. Also, I don't sure if a response via email sends the files as expected. A better option is to share these files via Google Drive, One Drive, or any other platform, and give us the access permission

**Comment by 347lixin** [comment]
I uploaded the file in google drive. please open this link: https://drive.google.com/file/d/1l05esa3Eli_eaG9cF2LkpFdMuk4US_qG/view?usp=sharing,thank you very much.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Valdes-Tresanco-MS/gmx_MMPBSA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 凌晨3:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Valdes-Tresanco-MS/gmx_MMPBSA] PreProcessorError: Bad #include syntax (Issue #359)





 
Commonly acpype generates topologies with format problems, for example, space before # statement, missing ;, etc. Please, make sure that the topology format is correct. Also, I don't sure if a response via email sends the files as expected. A better option is to share these files via Google Drive, One Drive, or any other platform, and give us the access permission

**Comment by marioernestovaldes** [comment]
line 22 the quotation marks are missing... it should be 

#include "CD36.itp"

let me know if that solves the problem

**Comment by Valdes-Tresanco-MS** [comment]
This is a known bug in v1.6.0 that we already fixed (#346, #352). We are compiling other reported problems to release v1.6.1. Please, install the development version until we release the next one.
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA.git -U
```

**Comment by 347lixin** [comment]
thank you very much



---Original---
From: "Mario Sergio Valdés ***@***.***&gt;
Date: Wed, Mar 22, 2023 23:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Valdes-Tresanco-MS/gmx_MMPBSA] PreProcessorError: Bad #includesyntax (Issue #359)




 
This is a known bug in v1.6.0 that we already fixed (#346, #352). We are compiling other reported problems to release v1.6.1. Please, install the development version until we release the next one.
 python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA.git -U

**Comment by 347lixin** [comment]
Dear professor,
I caculated MMPBSA in WSL(Windows subsystem for linux) by gmx_MMPBSA, but this subsystem in not launched gmx_MMPBSA_ana, is there any method to install gmx_MMPBSA_ana in windows system,thank you very much.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Valdes-Tresanco-MS/gmx_MMPBSA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 晚上11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Valdes-Tresanco-MS/gmx_MMPBSA] PreProcessorError: Bad #include syntax (Issue #359)





 
This is a known bug in v1.6.0 that we already fixed (#346, #352). We are compiling other reported problems to release v1.6.1. Please, install the development version until we release the next one.
 python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA.git -U

**Comment by Valdes-Tresanco-MS** [comment]
There is this [tutorial for able to run GUI applications in WSL](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
I don't test it, so I don't know if working.
Currently, we are working on a new version as an independent application called xBFreE-Analyzer which will run on Windows OS as well
Stay tuned

**Comment by 347lixin** [comment]
thank you，I try this test.



---Original---
From: "Mario Sergio Valdés ***@***.***&gt;
Date: Thu, Mar 23, 2023 13:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Valdes-Tresanco-MS/gmx_MMPBSA] PreProcessorError: Bad #includesyntax (Issue #359)




 
There is this tutorial for able to run GUI applications in WSL
 I don't test it, so I don't know if working.
 Currently, we are working on a new version as an independent application called xBFreE-Analyzer which will run on Windows OS as well
 Stay tuned
