### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: 

### ISSUE THREAD

**Issue by mido410** [Valdes-Tresanco-MS/gmx_MMPBSA#360]
### Bug summary

Whenever I try to run the gmx_MMPBSA_ana, it runs its GUI. But if I chose to view any chart, it closes abruptly.

### Terminal output

```bash
Aborted (core dumped)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/122587393/231245651-607bc55d-595b-40b1-aba8-acccffa9ad85.png)

### Expected outcome

The gmx_MMPBSA_ana initiats its GUI but when I press on any chart it suddenly closes.

### Operating system

Ubunto 20.04

### gmx_MMPBSA_ana Version

1.6.1

### Python version

3.9

### Installation

conda AmberTools + pip

**Comment by Valdes-Tresanco-MS** [comment]
Definitively is a compatibility problem. You can try to downgrade pandas...
```bash
python -m pip uninstall pandas
```
and then 
```bash
python -m pip install pandas==1.2.2
```
I will fix this asap

**Comment by mido410** [comment]
Thank you very much. It works.
