### ISSUE TITLE
Alanine scanning fails when the system does not contain ALA

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#364]
Oh thank you! But then I came up with this ...

```bash
tets
  File "/home/yxy/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/yxy/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/yxy/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 687, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/yxy/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 125, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/yxy/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 674, in gmxtop2prmtop
    mut_com_amb_prm = self.makeMutTop(com_amb_prm, self.com_mut_index)
  File "/home/yxy/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 1121, in makeMutTop
    at.type = h_atoms_prop['type']
KeyError: 'type'
Error occurred on rank 0.
Exiting. All files have been retained.
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11300057/gmx_MMPBSA.log)

_Originally posted by @stomachacheee in https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/363#issuecomment-1518474217_

**Comment by Valdes-Tresanco-MS** [comment]
Sorry for the delay. I was responding to the review of my last submitted article.
Well, I found the problem. When gmx_MMPBSA makes an alanine mutant, depending on the aa that is mutated, it is necessary to change a heavy atom for hydrogen. This means this atom must be moved to the bond distance of C-H and change its name, type, and other properties. For this, we use a hydrogen atom of some alanine in the system as a reference. We assumed there would be some, which is not the case in your system. I'm reviewing the charge of alanine hydrogen in case any ALA does not exist.

**Comment by stomachacheee** [comment]
It's OK. While you are solving this problem I shall concentrate on other parts of my thesis. 

So the tool needs an alanine in the sequence to run correctly right? I have another peptide containing an alanine, I will try it later.

Thank you for your help!

**Comment by Valdes-Tresanco-MS** [comment]
I already fixed the bug and improved other things. Please, test if works for you...
```bash
python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA -U
```
Let me know if you get inconsistent energy

**Comment by stomachacheee** [comment]
Great! It works now!
