### ISSUE TITLE
packages are not available

### ISSUE THREAD

**Issue by hanahg** [Valdes-Tresanco-MS/gmx_MMPBSA#365]
Igot the following error:
onda install -c conda-forge mpi4py=3.1.3 ambertools=2.12 compiler=1.2.0 -y -q
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - compiler=1.2.0
  - ambertools=2.12

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by Valdes-Tresanco-MS** [comment]
Please follow the installation instructions carefully. The correct packages are:
```yaml
compilers=1.2.0
ambertools=21.12
```

**Comment by hanahg** [comment]
PackagesNotFoundError: The following packages are not available from current channels:

  - compiler=1.2.0

**Comment by Valdes-Tresanco-MS** [comment]
Please, read carefully... it is `compilers` ending in `s`, not `compiler`.
Please, copy textually te following command-line:
```bash
conda install -c conda-forge mpi4py=3.1.3 ambertools=21.12 compilers=1.2.0 -y -q
```
