### ISSUE TITLE
but when I launch mmgbsa I have met this problem : bin/gmx editconf failed when querying com_traj.xtc.

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#368]
but when I launch mmgbsa I have met this problem : bin/gmx editconf failed when querying com_traj.xtc.
           Check the gmx_MMPBSA.log file to report the problem.

_Originally posted by @AbdelmoujoudFaris in https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/153#issuecomment-1535602792_

**Comment by Valdes-Tresanco-MS** [comment]
Please, open a new issue to report any error, since is easier to track. 
Please, attach/upload the gmx_MMPBSA.log file

**Comment by AbdelmoujoudFaris** [comment]
here's the log file in this link https://github.com/AbdelmoujoudFaris/mmgbsa1/blob/main/mmgbsalog

**Comment by Valdes-Tresanco-MS** [comment]
Probably, the problem here is you are using a PDB file as the structure, which does not contain the same number of atoms as the index.ndx. Please, try using a tpr file instead of pdb.

PS: You can upload files to this issue specifically. If the format is not allowed, only change the extension.

**Comment by AbdelmoujoudFaris** [comment]
log: [INFO   ] Starting gmx_MMPBSA v1.6.0
[DEBUG  ] WDIR          : /home/a.alix/Redynamicarti2/5/gromacs/gmxx
[DEBUG  ] AMBERHOME     : /home/a.alix/.conda/envs/gmxMMPBSA
[DEBUG  ] PYTHON EXE    : /home/a.alix/.conda/envs/gmxMMPBSA/bin/python
[DEBUG  ] PYTHON VERSION: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) [GCC 10.4.0]
[DEBUG  ] MPI           : /home/a.alix/.conda/envs/gmxMMPBSA/bin/mpirun
[DEBUG  ] ParmEd        : 3.4.4
[DEBUG  ] OS PLATFORM   : Linux-4.18.0-348.12.2.el8_5.x86_64-x86_64-with-glibc2.28
[DEBUG  ] OS SYSTEM     : Linux
[DEBUG  ] OS VERSION    : #1 SMP Mon Jan 17 07:06:06 EST 2022
[DEBUG  ] OS PROCESSOR  : x86_64

[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs str_noLP.pdb -ci index_mod_gromacs.ndx -cg 1 17 -ct com_traj.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[DEBUG  ] |Input file:
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] |Sample input file for GB calculation
[DEBUG  ] |#This input file is meant to show only that gmx_MMPBSA works. Although, we tried to use the input files as recommended in the
[DEBUG  ] |#Amber manual, some parameters have been changed to perform more expensive calculations in a reasonable amount of time. Feel free to change the parameters
[DEBUG  ] |#according to what is better for your system.
[DEBUG  ] |
[DEBUG  ] |&general
[DEBUG  ] |sys_name="Protein_lig",
[DEBUG  ] |startframe=5,
[DEBUG  ] |endframe=50,
[DEBUG  ] |forcefields="oldff/leaprc.ff99SB",leaprc.gaff"
[DEBUG  ] |/
[DEBUG  ] |&gb
[DEBUG  ] |igb=5, saltcon=0.150,
[DEBUG  ] |/
[DEBUG  ] |
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] 
[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/a.alix/.conda/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/a.alix/.conda/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/a.alix/.conda/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/a.alix/.conda/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /cm/shared/apps/eb/software/GROMACS/2021.3-foss-2021a/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[DEBUG  ] Running command: echo -e "name 1 GMXMMPBSA_REC\n name 17 GMXMMPBSA_LIG\n  1 | 17\n q\n" | /cm/shared/apps/eb/software/GROMACS/2021.3-foss-2021a/bin/gmx make_ndx -n index_mod_gromacs.ndx -o _GMXMMPBSA_COM_index.ndx -f str_noLP.pdb
[DEBUG  ]              :-) GROMACS - gmx make_ndx, 2021.3-EasyBuild-4.5.2 (-:
[DEBUG  ] 
[DEBUG  ]                             GROMACS is written by:
[DEBUG  ]      Andrey Alekseenko              Emile Apol              Rossen Apostolov     
[DEBUG  ]          Paul Bauer           Herman J.C. Berendsen           Par Bjelkmar       
[DEBUG  ]        Christian Blau           Viacheslav Bolnykh             Kevin Boyd        
[DEBUG  ]      Aldert van Buuren           Rudi van Drunen             Anton Feenstra      
[DEBUG  ]     Gilles Gouaillardet             Alan Gray               Gerrit Groenhof      
[DEBUG  ]        Anca Hamuraru            Vincent Hindriksen          M. Eric Irrgang      
[DEBUG  ]       Aleksei Iupinov           Christoph Junghans             Joe Jordan        
[DEBUG  ]     Dimitrios Karkoulis            Peter Kasson                Jiri Kraus        
[DEBUG  ]       Carsten Kutzner              Per Larsson              Justin A. Lemkul     
[DEBUG  ]        Viveca Lindahl            Magnus Lundborg             Erik Marklund       
[DEBUG  ]         Pascal Merz             Pieter Meulenhoff            Teemu Murtola       
[DEBUG  ]         Szilard Pall               Sander Pronk              Roland Schulz       
[DEBUG  ]        Michael Shirts            Alexey Shvetsov             Alfons Sijbers      
[DEBUG  ]        Peter Tieleman              Jon Vincent              Teemu Virolainen     
[DEBUG  ]      Christian Wennberg            Maarten Wolf              Artem Zhmurov       
[DEBUG  ]                            and the project leaders:
[DEBUG  ]         Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel
[DEBUG  ] 
[DEBUG  ] Copyright (c) 1991-2000, University of Groningen, The Netherlands.
[DEBUG  ] Copyright (c) 2001-2019, The GROMACS development team at
[DEBUG  ] Uppsala University, Stockholm University and
[DEBUG  ] the Royal Institute of Technology, Sweden.
[DEBUG  ] check out http://www.gromacs.org for more information.
[DEBUG  ] 
[DEBUG  ] GROMACS is free software; you can redistribute it and/or modify it
[DEBUG  ] under the terms of the GNU Lesser General Public License
[DEBUG  ] as published by the Free Software Foundation; either version 2.1
[DEBUG  ] of the License, or (at your option) any later version.
[DEBUG  ] 
[DEBUG  ] GROMACS:      gmx make_ndx, version 2021.3-EasyBuild-4.5.2
[DEBUG  ] Executable:   /cm/shared/apps/eb/software/GROMACS/2021.3-foss-2021a/bin/gmx
[DEBUG  ] Data prefix:  /cm/shared/apps/eb/software/GROMACS/2021.3-foss-2021a
[DEBUG  ] Working dir:  /home/a.alix/Redynamicarti2/5/gromacs/gmxx
[DEBUG  ] Command line:
[DEBUG  ]   gmx make_ndx -n index_mod_gromacs.ndx -o _GMXMMPBSA_COM_index.ndx -f str_noLP.pdb
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] Reading structure file
[DEBUG  ] 
[DEBUG  ] -------------------------------------------------------
[DEBUG  ] Program:     gmx make_ndx, version 2021.3-EasyBuild-4.5.2
[DEBUG  ] Source file: src/gromacs/tools/make_ndx.cpp (line 1204)
[DEBUG  ] 
[DEBUG  ] Fatal error:
[DEBUG  ] Error reading user input
[DEBUG  ] 
[DEBUG  ] For more information and tips for troubleshooting, please check the GROMACS
[DEBUG  ] website at http://www.gromacs.org/Documentation/Errors
[DEBUG  ] -------------------------------------------------------
[DEBUG  ] Going to read 1 old index file(s)
[DEBUG  ] 
[DEBUG  ]   0 System              : 57264 atoms
[DEBUG  ]   1 Protein             :  4349 atoms
[DEBUG  ]   2 Protein-H           :  2176 atoms
[DEBUG  ]   3 C-alpha             :   271 atoms
[DEBUG  ]   4 Backbone            :   813 atoms
[DEBUG  ]   5 MainChain           :  1083 atoms
[DEBUG  ]   6 MainChain+Cb        :  1339 atoms
[DEBUG  ]   7 MainChain+H         :  1338 atoms
[DEBUG  ]   8 SideChain           :  3011 atoms
[DEBUG  ]   9 SideChain-H         :  1093 atoms
[DEBUG  ]  10 Prot-Masses         :  4349 atoms
[DEBUG  ]  11 non-Protein         : 52915 atoms
[DEBUG  ]  12 Other               : 52915 atoms
[DEBUG  ]  13 PTR                 :    50 atoms
[DEBUG  ]  14 LIG                 :    56 atoms
[DEBUG  ]  15 SOD                 :    52 atoms
[DEBUG  ]  16 CLA                 :    50 atoms
[DEBUG  ]  17 TIP3                : 52707 atoms
[DEBUG  ]  18 Protein_lig         :  4405 atoms
[DEBUG  ] 
[DEBUG  ]  nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
[DEBUG  ]  'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
[DEBUG  ]  't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
[DEBUG  ]  'r': residue              'res' nr         'chain' char
[DEBUG  ]  "name": group             'case': case sensitive           'q': save and quit
[DEBUG  ]  'ri': residue index
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] Copied index group 1 'GMXMMPBSA_REC'
[DEBUG  ] Copied index group 17 'GMXMMPBSA_LIG'
[DEBUG  ] Merged two groups with OR: 4349 52707 -> 57056
[DEBUG  ] 
[DEBUG  ]  19 GMXMMPBSA_REC_GMXMMPBSA_LIG: 57056 atoms
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ]   0 System              : 57264 atoms
[DEBUG  ]   1 GMXMMPBSA_REC       :  4349 atoms
[DEBUG  ]   2 Protein-H           :  2176 atoms
[DEBUG  ]   3 C-alpha             :   271 atoms
[DEBUG  ]   4 Backbone            :   813 atoms
[DEBUG  ]   5 MainChain           :  1083 atoms
[DEBUG  ]   6 MainChain+Cb        :  1339 atoms
[DEBUG  ]   7 MainChain+H         :  1338 atoms
[DEBUG  ]   8 SideChain           :  3011 atoms
[DEBUG  ]   9 SideChain-H         :  1093 atoms
[DEBUG  ]  10 Prot-Masses         :  4349 atoms
[DEBUG  ]  11 non-Protein         : 52915 atoms
[DEBUG  ]  12 Other               : 52915 atoms
[DEBUG  ]  13 PTR                 :    50 atoms
[DEBUG  ]  14 LIG                 :    56 atoms
[DEBUG  ]  15 SOD                 :    52 atoms
[DEBUG  ]  16 CLA                 :    50 atoms
[DEBUG  ]  17 GMXMMPBSA_LIG       : 52707 atoms
[DEBUG  ]  18 Protein_lig         :  4405 atoms
[DEBUG  ]  19 GMXMMPBSA_REC_GMXMMPBSA_LIG: 57056 atoms
[DEBUG  ] 
[DEBUG  ]  nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
[DEBUG  ]  'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
[DEBUG  ]  't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
[DEBUG  ]  'r': residue              'res' nr         'chain' char
[DEBUG  ]  "name": group             'case': case sensitive           'q': save and quit
[DEBUG  ]  'ri': residue index
[DEBUG  ] 
[DEBUG  ] > 
[ERROR  ] MMPBSA_Error /cm/shared/apps/eb/software/GROMACS/2021.3-foss-2021a/bin/gmx make_ndx failed when querying index_mod_gromacs.ndx.
           Check the gmx_MMPBSA.log file to report the problem.

**Comment by AbdelmoujoudFaris** [comment]
slurm out: [INFO   ] Starting gmx_MMPBSA v1.6.0
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs str_noLP.pdb -ci index_mod_gromacs.ndx -cg 1 17 -ct com_traj.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/a.alix/.conda/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/a.alix/.conda/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/a.alix/.conda/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/a.alix/.conda/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /cm/shared/apps/eb/software/GROMACS/2021.3-foss-2021a/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[ERROR  ] MMPBSA_Error /cm/shared/apps/eb/software/GROMACS/2021.3-foss-2021a/bin/gmx make_ndx failed when querying index_mod_gromacs.ndx.
           Check the gmx_MMPBSA.log file to report the problem.
  File "/home/a.alix/.conda/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 10, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/a.alix/.local/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/a.alix/.local/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 689, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/a.alix/.local/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 123, in buildTopology
    self.gmx2pdb()
  File "/home/a.alix/.local/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 263, in gmx2pdb
    GMXMMPBSA_ERROR('%s failed when querying %s' % (' '.join(self.make_ndx), self.FILES.complex_index))
  File "/home/a.alix/.local/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: /cm/shared/apps/eb/software/GROMACS/2021.3-foss-2021a/bin/gmx make_ndx failed when querying index_mod_gromacs.ndx
Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.
[1683281374.285894] [data36:1415793:0]          ib_md.c:1161 UCX  WARN  IB: ibv_fork_init() was disabled or failed, yet a fork() has been issued.
[1683281374.286448] [data36:1415793:0]          ib_md.c:1162 UCX  WARN  IB: data corruption might occur when using registered memory.
[1683281374.376486] [data36:1415793:0]          ib_md.c:1161 UCX  WARN  IB: ibv_fork_init() was disabled or failed, yet a fork() has been issued.
[1683281374.376496] [data36:1415793:0]          ib_md.c:1162 UCX  WARN  IB: data corruption might occur when using registered memory.
[1683281374.452471] [data36:1415793:0]          ib_md.c:1161 UCX  WARN  IB: ibv_fork_init() was disabled or failed, yet a fork() has been issued.
[1683281374.452480] [data36:1415793:0]          ib_md.c:1162 UCX  WARN  IB: data corruption might occur when using registered memory.

**Comment by AbdelmoujoudFaris** [comment]
i have made mmgbsa succesfly for other complexes out files md , but for this I can't do it,

**Comment by AbdelmoujoudFaris** [comment]
0 System              : 57264 atoms
  1 Protein             :  4349 atoms
  2 Protein-H           :  2176 atoms
  3 C-alpha             :   271 atoms
  4 Backbone            :   813 atoms
  5 MainChain           :  1083 atoms
  6 MainChain+Cb        :  1339 atoms
  7 MainChain+H         :  1338 atoms
  8 SideChain           :  3011 atoms
  9 SideChain-H         :  1093 atoms
 10 Prot-Masses         :  4349 atoms
 11 non-Protein         : 52915 atoms
 12 Other               : 52915 atoms
 13 PTR                 :    50 atoms
 14 LIG                 :    56 atoms
 15 SOD                 :    52 atoms
 16 CLA                 :    50 atoms
 17 TIP3                : 52707 atoms

**Comment by Valdes-Tresanco-MS** [comment]
Please, send me your files (tpr, ndx, 5frames xtc, top, it's and the toppar)

**Comment by AbdelmoujoudFaris** [comment]
[New folder - 1.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11409522/New.folder.-.1.zip)
Okay, here are the files you need and thank you

**Comment by Valdes-Tresanco-MS** [comment]
Please, attach the toppar folder

**Comment by AbdelmoujoudFaris** [comment]
[toppar.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11410685/toppar.zip)

**Comment by Valdes-Tresanco-MS** [comment]
I don't get any errors, but I see suspicious things. In the index, LIG appears in group 14, while PTR appears in group 13, which I'm not sure what it is. In one of your outputs, you seem to be carrying out the procedure for ligands with LPH but it doesn't seem to be the case with the system you sent me. As I also see, the ligand has a carbanion, is it due to a bad procedure to eliminate the LPH?
I this system the correct one?

**Comment by AbdelmoujoudFaris** [comment]
for the systems without LPH I have already made the same procedure it works well without touching the files in toppar, but for this case also I noted that LIG in 14

**Comment by Valdes-Tresanco-MS** [comment]
I think I'm lost. Which system is not working? Please send those files (include all necessary files in a zip). Make sure you are sending the ones that have problems

**Comment by Valdes-Tresanco-MS** [comment]
@AbdelmoujoudFaris  Did you solve the problem?

**Comment by AbdelmoujoudFaris** [comment]
Hello dear Valdes-Tresanco, yes I did it by merging proteins with PTR and deleting single PTR.
