### ISSUE TITLE
MMPBSA_Error: No info files found!

### ISSUE THREAD

**Issue by julianaamorim** [Valdes-Tresanco-MS/gmx_MMPBSA#37]
Hi Mario, after the installation I followed with the command gmx_MMPBSA_test to test all the examples and I encountered the error below, however I cannot identify the error in the installation steps

(base) juliana@juliana-VB:~$ gmx_MMPBSA_test -f /home/juliana/Documents -t all -n 10
[INFO   ] Cloning gmx_MMPBSA repository in /home/juliana/Documents/gmx_MMPBSA_test
Cloning into '/home/juliana/Documents/gmx_MMPBSA_test'...
remote: Enumerating objects: 5030, done.
remote: Counting objects: 100% (383/383), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 5030 (delta 234), reused 336 (delta 212), pack-reused 4647
Receiving objects: 100% (5030/5030), 245.85 MiB | 1.74 MiB/s, done.
Resolving deltas: 100% (3559/3559), done.
Updating files: 100% (326/326), done.
[INFO   ] Cloning gmx_MMPBSA repository...Done.
[WARNING] Using all processors
[INFO   ]                           Example                                STATE
--------------------------------------------------------------------------------
[INFO   ] Protein-Ligand (Single trajectory approximation)               RUNNING
[INFO   ] Protein-Protein                                                RUNNING
[ERROR  ] Protein-Ligand (Single trajectory approximation)       [ 1/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Protein_ligand/ST/prot_lig_st.log)
[INFO   ] Protein-DNA                                                    RUNNING
[ERROR  ] Protein-Protein                                        [ 2/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Protein_protein/prot_prot.log)
[INFO   ] Protein-Membrane                                               RUNNING
[ERROR  ] Protein-DNA                                            [ 3/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Protein_DNA/prot_dna.log)
[INFO   ] Protein-Glycan                                                 RUNNING
[ERROR  ] Protein-Membrane                                       [ 4/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Protein_membrane/memb_prot.log)
[INFO   ] Metalloprotein-Peptide                                         RUNNING
[ERROR  ] Protein-Glycan                                         [ 5/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Protein_glycan/prot_glycan.log)
[INFO   ] Protein-DNA-RNA-IONs-Ligand                                    RUNNING
[ERROR  ] Metalloprotein-Peptide                                 [ 6/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Metalloprotein_peptide/metalloprot_pep.log)
[INFO   ] Protein-Ligand (CHARMM force field)                            RUNNING
[ERROR  ] Protein-DNA-RNA-IONs-Ligand                            [ 7/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Protein_DNA_RNA_Ion_ligand/prot_dna_rna_ions_lig.log)
[INFO   ] Protein-ligand complex in membrane with CHARMMff               RUNNING
[ERROR  ] Protein-Ligand (CHARMM force field)                    [ 8/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Protein_ligand_CHARMMff/prot_lig_charmm.log)
[INFO   ] Alanine Scanning                                               RUNNING
[ERROR  ] Protein-ligand complex in membrane with CHARMMff       [ 9/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Protein_membrane_CHARMMff/memb_charmm.log)
[INFO   ] Stability calculation                                          RUNNING
[ERROR  ] Alanine Scanning                                       [10/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Alanine_scanning/ala_scan.log)
[INFO   ] Decomposition Analysis                                         RUNNING
[ERROR  ] Stability calculation                                  [11/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Stability/stability.log)
[INFO   ] Protein-Ligand (Multiple trajectory approximation)             RUNNING
[ERROR  ] Decomposition Analysis                                 [12/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Decomposition_analysis/decomp.log)
[INFO   ] Interaction Entropy approximation                              RUNNING
[ERROR  ] Protein-Ligand (Multiple trajectory approximation)     [13/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Protein_ligand/MT/prot_lig_mt.log)
[INFO   ] Entropy calculation using Normal Mode approximation            RUNNING
[ERROR  ] Interaction Entropy approximation                      [14/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Entropy_calculations/Interaction_Entropy/ie.log)
[INFO   ] Calculations using 3D-RISM approximation                       RUNNING
[ERROR  ] Entropy calculation using Normal Mode approximation    [15/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/Entropy_calculations/nmode/nmode.log)
[ERROR  ] Calculations using 3D-RISM approximation               [16/16]   ERROR
           Please, check the test log
           (/home/juliana/Documents/gmx_MMPBSA_test/docs/examples/3D-RISM/3drism.log)
--------------------------------------------------------------------------------
[INFO   ] Opening gmx_MMPBSA_ana...
ERROR:root:MMPBSA_Error No info files found!.
           Check the gmx_MMPBSA.log file to report the problem.
Traceback (most recent call last):
  File "/home/juliana/Downloads/AmberTools20/amber20/miniconda/bin/gmx_MMPBSA_ana", line 8, in <module>
    sys.exit(gmxmmpbsa_ana())
  File "/home/juliana/.local/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 126, in gmxmmpbsa_ana
    ifiles = get_files(parser)
  File "/home/juliana/.local/lib/python3.8/site-packages/GMXMMPBSA/analyzer/utils.py", line 162, in get_files
    GMXMMPBSA_ERROR('No info files found!')
  File "/home/juliana/.local/lib/python3.8/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__
    raise exc(msg + '. Check the gmx_MMPBSA.log file to report the problem.')
GMXMMPBSA.exceptions.MMPBSA_Error: No info files found!. Check the gmx_MMPBSA.log file to report the problem.

**Comment by Valdes-Tresanco-MS** [comment]
Hi @julianaamorim 
This error is expected as all tests did not finish successfully.

Can you send me the log files of the failed tests? This way I can identify the problems, which I assume are related to the installation since they all failed.

Mario S.

**Comment by julianaamorim** [comment]
Thank you very much Mario, here follows the .log file

[gmx_MMPBSA_test.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416873/gmx_MMPBSA_test.log)

**Comment by Valdes-Tresanco-MS** [comment]
I mean the log files for each example. After showing that each example ends in error a reference to a log file appears, please send me those files.

**Comment by julianaamorim** [comment]
[3drism.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416923/3drism.log)
[ala_scan.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416925/ala_scan.log)
[decomp.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416926/decomp.log)
[prot_dna.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416933/prot_dna.log)
[prot_dna_rna_ions_lig.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416935/prot_dna_rna_ions_lig.log)
[prot_glycan.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416940/prot_glycan.log)
[prot_lig_mt.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416947/prot_lig_mt.log)
[prot_lig_st.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416949/prot_lig_st.log)
[prot_lig_charmm.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416951/prot_lig_charmm.log)
[memb_prot.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416958/memb_prot.log)
[stability.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6416961/stability.log)

**Comment by Valdes-Tresanco-MS** [comment]
As you can see from the log files, the error is that there is no Gromacs executable in the PATH. Make sure you have Gromacs installed and accessible from the PATH
Best!
Mario S.

**Comment by julianaamorim** [comment]
Beginner's mistake, I will continue this way, thank you very much for the prompt reply...

great week

**Comment by Valdes-Tresanco-MS** [comment]
No problem, we will gladly guide and help you.
I will close the issue, feel free to open other at any time or ask in the [group](https://groups.google.com/g/gmx_mmpbsa). You can also consult the [Q&A](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/Q%26A/) section of the documentation.

Best wishes
Mario S.
