### ISSUE TITLE
[Question]: problem when run mmgbsa with hem

### ISSUE THREAD

**Issue by tianyuruoxue** [Valdes-Tresanco-MS/gmx_MMPBSA#372]
### My Question is...

When I use the MMGBSA calculation, the protein pocket contains two small molecules, hem and my ligand. I want to think of hem as part of the protein to calculate the binding energy between my ligand. The last run reported an error: [ERROR] MMPBSA_Error   Some energy terms are undefined. Please, check the input structure and trajectory.

**Comment by Valdes-Tresanco-MS** [comment]
Please, use the issue template and provide all the relevant information... 
Also, check this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/gmx_MMPBSA_running/#before-running-gmx_mmpbsa) in the documentation and make sure you are selecting the proper groups

**Comment by Valdes-Tresanco-MS** [comment]
@tianyuruoxue Did you solve the error?

**Comment by tianyuruoxue** [comment]
I have solve theproblem



---Original---
From: "Mario Sergio Valdés ***@***.***&gt;
Date: Sat, Jun 3, 2023 22:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Question]: problem when runmmgbsa with hem (Issue #372)




 
@tianyuruoxue Did you solve the error?
