### ISSUE TITLE
[Bug-gmx_MMPBSA]: RAM issue with PB function

### ISSUE THREAD

**Issue by michalispapadourakis** [Valdes-Tresanco-MS/gmx_MMPBSA#382]
### Bug summary

The calculation for 100 frames using:
mpirun -np 2 gmx_MMPBSA -O -i mmpbsa.in -cs md010.tpr -ci index.ndx -cg 1 22 -ct md010_fit.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv 

seems to consume a big amount of RAM (ca. 80 Gb). So, I cannot increase the number of threads and the speed of the calculations (~16 hours for the complex part). Can you suggest a way to tackle this issue. Please find attach the mmpbsa.in file
[mmpbsa.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11707477/mmpbsa.txt)

### Terminal output

```bash
not relevant
```

### gmx_MMPBSA.log

not relevant

### Operating system

Linux

### gmx_MMPBSA Version

gmx_MMPBSA v1.6.1 based on MMPBSA version 16.0 and AmberTools 20

### Python version

Python 3.9.15

### Installation

git checkout

**Comment by marioernestovaldes** [comment]
What kind of system are you modelling; protein-protein, protein-ligand? How many atoms? One way to decrease the amount of RAM used is by decreasing the fillratio from 4 to 2

**Comment by michalispapadourakis** [comment]
Thanks a lot for your quick response.

I am simulating a protein-ligand system with number of atoms equal to 87,640. I will try first the fillratio suggestion and I will get back to you with the outcome

**Comment by Valdes-Tresanco-MS** [comment]
Excellent. Don't hesitate to contact us if you need help.
