### ISSUE TITLE
[Question]: gmx make_ndx failed when querying index. ndx after putting topol. top file also

### ISSUE THREAD

**Issue by kunal74** [Valdes-Tresanco-MS/gmx_MMPBSA#384]
### My Question is...

[Question]: gmx make_ndx failed when querying index. ndx after putting topol. top file also

**Comment by kunal74** [comment]
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11799205/gmx_MMPBSA.log)

**Comment by Valdes-Tresanco-MS** [comment]
As you can see in the log file, you are using Gromacs v2022.4 to process a index generated by v2023.1. To solve this problem, you can update the gromacs version from conda 
```bash
conda update gromacs
```
or use your own through the gmx_path variable in the input file

**Comment by kunal74** [comment]
Thank you I will do it and let u know tomorrow

**Comment by kunal74** [comment]
I downgraded gromacs to 2022.4 version. It worked. Thankx for the solution
