### ISSUE TITLE
[Question]: "_GMXMMPBSA_gb.mdin" is missing or unreadable issue during calculation

### ISSUE THREAD

**Issue by peng-jj** [Valdes-Tresanco-MS/gmx_MMPBSA#387]
### Bug summary

![error](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/84639229/45e64771-3a46-48d1-a243-7eeef12372ef)

Wondering if anyone has encountered the same problem? This stops my calculation about a minute in and I'm not sure where to begin looking.

### Terminal output

```bash
[INFO   ] 20000 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 2 CPUs...
[INFO   ] Running calculations on normal system...
[INFO   ] Beginning GB calculations with /home/users/astar/bii/pengjj/.conda/envs/gmxMMPBSA/bin/sander
[INFO   ]   calculating complex contribution...

  Error opening unit    5: File "_GMXMMPBSA_gb.mdin" is missing or unreadable

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
^M              0%|          | 0/20000 [elapsed: 00:00 remaining: ?]#0  0x7fda9afcfacf in ???
  File "/home/users/astar/bii/pengjj/.conda/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/users/astar/bii/pengjj/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.run_mmpbsa()
  File "/home/users/astar/bii/pengjj/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 205, in run_mmpbsa
    self.calc_list.run(rank, self.stdout)
  File "/home/users/astar/bii/pengjj/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 142, in run
    calc.run(rank, stdout=stdout, stderr=stderr)
  File "/home/users/astar/bii/pengjj/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 284, in run
    raise CalcError(f'{self.program} failed with prmtop {self.prmtop}!')
CalcError: /home/users/astar/bii/pengjj/.conda/envs/gmxMMPBSA/bin/sander failed with prmtop COM.prmtop!
Error occurred on rank 1.
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11878223/gmx_MMPBSA.log)
[Traj1_PBSA-733165.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11878226/Traj1_PBSA-733165.txt)

### Operating system

Mobaxterm on Windows

### gmx_MMPBSA Version

v1.6.1

### Python version

3.8.6

### Installation

conda AmberTools + conda

**Comment by Valdes-Tresanco-MS** [comment]
I can't reproduce this error, it works for me with no problem. Can you create an environment from scratch using Python 3.9 or higher? According to the log, you are using two different Python versions, which may lead to incompatibility.

**Comment by peng-jj** [comment]
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11883672/gmx_MMPBSA.log)

I couldn't create another environment on my cluster using Python 3.9, so I reinstalled gmx_MMPBSA with Python 3.8.15 instead. The same error popped up so it does not seem to be a compatibility issue. Any other possibilities I could look into? 

Thanks!

**Comment by Valdes-Tresanco-MS** [comment]
Can you try to reproduce this error on your PC? It could also be the write permissions of the working folder

**Comment by peng-jj** [comment]
It could be that, we also suspect an OS version incompatibility between the login node and compute nodes on our HPC. I resolved that by recompiling gmx_MMPBSA on an interactive session in the compute node and then running the calculations on command line, instead of submitting a script.

Thanks for your help! On another note, is there a way to resume calculations from where they left off, if they are interrupted?

**Comment by Valdes-Tresanco-MS** [comment]
> It could be that, we also suspect an OS version incompatibility between the login node and compute nodes on our HPC. I resolved that by recompiling gmx_MMPBSA on an interactive session in the compute node and then running the calculations on command line, instead of submitting a script.

We are working on other installations and packaging methods like docker, singularity, and virtual environments to solve these problems

> Thanks for your help! On another note, is there a way to resume calculations from where they left off, if they are interrupted?

Unfortunately, no :(

**Comment by peng-jj** [comment]
Great to hear, looking forward to those!
