### ISSUE TITLE
[Bug-gmx_MMPBSA]: energy too large with ************* for a normal system

### ISSUE THREAD

**Issue by Aunity** [Valdes-Tresanco-MS/gmx_MMPBSA#389]
### Bug summary

* I checked the `_GMXMMPBSA_complex_gb.mdout.0` file and see the energy too large like this:
```
   NSTEP       ENERGY          RMS            GMAX         NAME    NUMBER
      1       3.4933E+17     2.5182E+17     3.4933E+19     CB       5614

 BOND    =  1010877.6344  ANGLE   =     2623.4665  DIHED      =     9028.8882
 VDWAALS = *************  EEL     =   -17036.0135  EGB        =    -2042.6948
 1-4 VDW =     5128.4701  1-4 EEL =    11580.9554  RESTRAINT  =        0.0000
minimization completed, ENE= 0.34932637E+18 RMS= 0.251818E+18
TRAJENE: Trajectory file ended
TRAJENE: Trajene complete.
```
* This is my complex: it's a dimer with ligand binding to chain A.
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/18044835/931c1275-543f-4c7e-b9e0-ce010e89c075)

* It seems a sander bug?

### Terminal output

```bash
[INFO   ] Running calculations on normal system...
[INFO   ] Beginning GB calculations with /opt/miniconda3/envs/gbsa/bin/sander
[INFO   ]   calculating complex contribution...
            100%|##########| 1/1 [elapsed: 00:28 remaining: 00:00]
[INFO   ]   calculating receptor contribution...
            100%|##########| 1/1 [elapsed: 00:21 remaining: 00:00]
[INFO   ]   calculating ligand contribution...
            100%|##########| 1/1 [elapsed: 00:01 remaining: 00:00]
[INFO   ] Parsing results to output files...

[ERROR  ] MMPBSA_Error

Some energy terms are undefined. Please, check the input structure and trajectory. Check this section the docs for more info https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/Q%26A/calculations/#possible-solutions

Check the gmx_MMPBSA.log file to report the problem.
  File "/opt/miniconda3/envs/gbsa/bin/gmx_MMPBSA", line 33, in <module>
    sys.exit(load_entry_point('gmx-MMPBSA==1.6.1', 'console_scripts', 'gmx_MMPBSA')())
  File "/opt/miniconda3/envs/gbsa/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 109, in gmxmmpbsa
    app.parse_output_files()
  File "/opt/miniconda3/envs/gbsa/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 1211, in parse_output_files
    self.calc_types.normal[key]['complex'].parse_from_file(self.pre + basename[i] % 'complex',
  File "/opt/miniconda3/envs/gbsa/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 108, in parse_from_file
    AmberOutput._read(self)
  File "/opt/miniconda3/envs/gbsa/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 197, in _read
    self._get_energies(output_file)
  File "/opt/miniconda3/envs/gbsa/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 639, in _get_energies
    self['VDWAALS'][self.frame_idx] = conv_float(words[2])
  File "/opt/miniconda3/envs/gbsa/lib/python3.10/site-packages/GMXMMPBSA/amber_outputs.py", line 603, in conv_float
    GMXMMPBSA_ERROR('Some energy terms are undefined. Please, check the input structure and trajectory. Check this '
  File "/opt/miniconda3/envs/gbsa/lib/python3.10/site-packages/GMXMMPBSA/exceptions.py", line 171, in __init__
    raise exc('\n\n' + msg + '\n\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error:

Some energy terms are undefined. Please, check the input structure and trajectory. Check this section the docs for more info https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/Q%26A/calculations/#possible-solutions

Check the gmx_MMPBSA.log file to report the problem.
```

### gmx_MMPBSA.log

[DEBUG  ] Using output precision of 0.001 (nm)
[DEBUG  ]  '', 15395 atoms
[DEBUG  ]
[DEBUG  ] Last written: frame      0 time    0.000
[DEBUG  ]
[DEBUG  ]
[DEBUG  ] GROMACS reminds you: "This Puke Stinks Like Beer" (LIVE)
[DEBUG  ]
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 15: 'GMXMMPBSA_REC_GMXMMPBSA_LIG'
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...

[INFO   ] 1 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 1 CPUs...
[INFO   ] Running calculations on normal system...
[INFO   ] Beginning GB calculations with /opt/miniconda3/envs/gbsa/bin/sander
[INFO   ]   calculating complex contribution...
[INFO   ]   calculating receptor contribution...
[INFO   ]   calculating ligand contribution...
[INFO   ] Parsing results to output files...

[ERROR  ] MMPBSA_Error

Some energy terms are undefined. Please, check the input structure and trajectory. Check this section the docs for more info https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/Q%26A/calculations/#possible-solutions

Check the gmx_MMPBSA.log file to report the problem.

### Operating system

Ubuntu

### gmx_MMPBSA Version

v1.6.1

### Python version

Python 3.10.10

### Installation

pip

**Comment by Valdes-Tresanco-MS** [comment]
Please, check the link 
https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/Q%26A/calculations/#possible-solutions

**Comment by Aunity** [comment]
I have read the link and checked my pdb file. My pdb do not have these problem

**Comment by Valdes-Tresanco-MS** [comment]
What PDB? These problems are fundamentally related to PBCs. Please, check the trajectory carefully and analyze the RMSD to check that there is no jump.

**Comment by Aunity** [comment]
Here is my complex pdb file and complex's top file. I have checked my pdb file many times and it do not have the pbc problem. [complex.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11944321/complex.zip)

**Comment by Valdes-Tresanco-MS** [comment]
Please, check the consistency of your system. As you can see, there are clashes in the ligand
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/36672242/16dbf62a-a31b-47ec-8e70-bafa8fd9da24)

**Comment by Aunity** [comment]
Thanks, I repaired this clashes but still have the "*******" problems.
[complex_preped.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11944901/complex_preped.zip)

**Comment by Valdes-Tresanco-MS** [comment]
Please, send me all the files to check what's going on

**Comment by Aunity** [comment]
Here is all my files. Thanks!
[rundir.tar.gz](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11953512/rundir.tar.gz)

**Comment by Valdes-Tresanco-MS** [comment]
Are you trying to calculate the energy for the complex resulting from docking? It doesn't work that way due to structural problems. The ligand has serious protonation problems. Given the ring structure, C23 should not be protonated, so the geometry of H35 is completely wrong. The same happens for H42 and H43. The protein structure is inconsistent. For example, residue ASP360 has atoms with coordinates similar to ASP857, which is completely inconsistent.
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/36672242/957e3740-6a53-4945-ae72-dbd3223046a7)

It also has a serious problem at the C-terminus of monomer 1.
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/36672242/4c795575-3b1e-4fb1-8e9c-ff11d3d9ee7a)

The atoms overlapped trigger the VWAALS energy values. Please follow a proper pipeline for system preparation. Also, consider adding the chain IDs. Check that the system is consistent before using gmx_MMPBSA. Our program is more than tested on such systems, so any similar errors will indicate that your system is inconsistent.

**Comment by Aunity** [comment]
@Valdes-Tresanco-MS Thanks !!!
