### ISSUE TITLE
[Question]: how to define receptor and ligand groups in -cg option from index.ndx file ? 

### ISSUE THREAD

**Issue by chandan121100** [Valdes-Tresanco-MS/gmx_MMPBSA#392]
### My Question is...

how to define receptor and ligand groups in -cg option from index.ndx file ?

**Comment by chandan121100** [comment]
[index.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11957165/index.txt)
Please consider the attached index file for reference.

**Comment by Valdes-Tresanco-MS** [comment]
You must create the receptor and ligand as independent groups. You can re-generate the index file using the tpr file:
```bash
gmx make_ndx -f md.tpr -o index.ndx
```
If the ligand is not a protein, then it will be in an independent group (generally 13). If it is protein, then you must split it by chain.
