### ISSUE TITLE
gmx editconf failed when querying com_traj.xtc

### ISSUE THREAD

**Issue by afwer1231** [Valdes-Tresanco-MS/gmx_MMPBSA#393]
### Discussed in https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/discussions/391

<div type='discussions-op-text'>

<sup>Originally posted by **afwer1231** July  5, 2023</sup>
dear Valdes:
I am trying to calculate the mmpbsa between a cyclodextrin and a ligand with LPH atoms. After following this tutorial(https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/tree/master/examples/Protein_ligand_LPH_atoms_CHARMMff) to prepare my input files I use the following command:
mpirun -np 2 gmx_MMPBSA -O -i mmpbsa.in -cs str_noLP.pdb -ci index.ndx -cg 7 3 -ct com_traj.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv
However, it gives me this error and the job stops :

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/ai/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/ai/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/ai/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/ai/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group receptor_ligand (3_7) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[ERROR  ] MMPBSA_Error

/usr/bin/gmx editconf failed when querying com_traj.xtc

Check the gmx_MMPBSA.log file to report the problem.
tets
  File "/home/ai/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/ai/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/ai/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 687, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/ai/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 123, in buildTopology
    self.gmx2pdb()
  File "/home/ai/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 289, in gmx2pdb
    GMXMMPBSA_ERROR('%s failed when querying %s' % (' '.join(comprog), self.FILES.complex_trajs[0]))
  File "/home/ai/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 171, in __init__
    raise exc('\n\n' + msg + '\n\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error:

/usr/bin/gmx editconf failed when querying com_traj.xtc

Check the gmx_MMPBSA.log file to report the problem.
Error occurred on rank 0.
Exiting. All files have been retained.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

I will be glad to see you guide me on how to get this resolved .

Regards,
fengwei ai

**gmx_MMPBSA.log**
[INFO   ] Starting gmx_MMPBSA v1.6.1
[DEBUG  ] WDIR          : /home/ai/rmcd12-3dfnb(charm36)-gmxMMPDSA分析-2
[DEBUG  ] AMBERHOME     : /home/ai/miniconda3/envs/gmxMMPBSA
[DEBUG  ] PYTHON EXE    : /home/ai/miniconda3/envs/gmxMMPBSA/bin/python
[DEBUG  ] PYTHON VERSION: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) [GCC 10.3.0]
[DEBUG  ] MPI           : /home/ai/miniconda3/envs/gmxMMPBSA/bin/mpirun
[DEBUG  ] ParmEd        : 3.4.3
[DEBUG  ] OS PLATFORM   : Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
[DEBUG  ] OS SYSTEM     : Linux
[DEBUG  ] OS VERSION    : #1 SMP Fri Jan 27 02:56:13 UTC 2023
[DEBUG  ] OS PROCESSOR  : x86_64

[INFO   ] Command-line
  mpirun -np 2 gmx_MMPBSA -O -i mmpbsa.in -cs str_noLP.pdb -ci index.ndx -cg 3 7 -ct com_traj.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[DEBUG  ] |Input file:
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] |Sample input file for GB calculation
[DEBUG  ] |#This input file is meant to show only that gmx_MMPBSA works. Although, we tried to use the input files as recommended in the
[DEBUG  ] |#Amber manual, some parameters have been changed to perform more expensive calculations in a reasonable amount of time. Feel free to change the parameters
[DEBUG  ] |#according to what is better for your system.
[DEBUG  ] |
[DEBUG  ] |&general
[DEBUG  ] |sys_name="Prot-Lig-ST",
[DEBUG  ] |startframe=5,
[DEBUG  ] |endframe=9,
[DEBUG  ] |solvated_trajectory=0,
[DEBUG  ] |# In gmx_MMPBSA v1.5.0 we have added a new PB radii set named charmm_radii. This radii set should be used only
[DEBUG  ] |# with systems prepared with CHARMM force fields. Uncomment the line below to use charmm_radii set
[DEBUG  ] |#PBRadii=7,
[DEBUG  ] |/
[DEBUG  ] |&pb
[DEBUG  ] |# radiopt=0 is recommended which means using radii from the prmtop file
[DEBUG  ] |# for both the PB calculation and for the NP calculation
[DEBUG  ] |
[DEBUG  ] |istrng=0.15, fillratio=1.250, radiopt=0, inp=1,
[DEBUG  ] |/--------------------------------------------------------------
[DEBUG  ] 
[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/ai/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/ai/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/ai/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/ai/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[DEBUG  ] Running command: echo -e "name 3 GMXMMPBSA_REC\n name 7 GMXMMPBSA_LIG\n  3 | 7\n q\n" | /usr/bin/gmx make_ndx -n index.ndx -o _GMXMMPBSA_COM_index.ndx -f str_noLP.pdb
[DEBUG  ]              :-) GROMACS - gmx make_ndx, 2020.1-Ubuntu-2020.1-1 (-:
[DEBUG  ] 
[DEBUG  ]                             GROMACS is written by:
[DEBUG  ]      Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
[DEBUG  ]     Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
[DEBUG  ]  Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
[DEBUG  ]   Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
[DEBUG  ]   Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
[DEBUG  ]     Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
[DEBUG  ]   Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
[DEBUG  ]     Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
[DEBUG  ]     Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
[DEBUG  ]    Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
[DEBUG  ]  Christian Wennberg    Maarten Wolf      Artem Zhmurov   
[DEBUG  ]                            and the project leaders:
[DEBUG  ]         Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel
[DEBUG  ] 
[DEBUG  ] Copyright (c) 1991-2000, University of Groningen, The Netherlands.
[DEBUG  ] Copyright (c) 2001-2019, The GROMACS development team at
[DEBUG  ] Uppsala University, Stockholm University and
[DEBUG  ] the Royal Institute of Technology, Sweden.
[DEBUG  ] check out http://www.gromacs.org for more information.
[DEBUG  ] 
[DEBUG  ] GROMACS is free software; you can redistribute it and/or modify it
[DEBUG  ] under the terms of the GNU Lesser General Public License
[DEBUG  ] as published by the Free Software Foundation; either version 2.1
[DEBUG  ] of the License, or (at your option) any later version.
[DEBUG  ] 
[DEBUG  ] GROMACS:      gmx make_ndx, version 2020.1-Ubuntu-2020.1-1
[DEBUG  ] Executable:   /usr/bin/gmx
[DEBUG  ] Data prefix:  /usr
[DEBUG  ] Working dir:  /home/ai/rmcd12-3dfnb(charm36)-gmxMMPDSA分析-2
[DEBUG  ] Command line:
[DEBUG  ]   gmx make_ndx -n index.ndx -o _GMXMMPBSA_COM_index.ndx -f str_noLP.pdb
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] Reading structure file
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "I Wrapped a Newspaper Round My Head" (F. Zappa)
[DEBUG  ] 
[DEBUG  ] Going to read 1 old index file(s)
[DEBUG  ] 
[DEBUG  ]   0 System              :  7193 atoms
[DEBUG  ]   1 Other               :   230 atoms
[DEBUG  ]   2 fnb                 :    47 atoms
[DEBUG  ]   3 receptor            :   183 atoms
[DEBUG  ]   4 Water               :  6963 atoms
[DEBUG  ]   5 SOL                 :  6963 atoms
[DEBUG  ]   6 non-Water           :   230 atoms
[DEBUG  ]   7 ligand              :    46 atoms
[DEBUG  ]   8 receptor_ligand     :   229 atoms
[DEBUG  ] 
[DEBUG  ]  nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
[DEBUG  ]  'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
[DEBUG  ]  't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
[DEBUG  ]  'r': residue              'res' nr         'chain' char
[DEBUG  ]  "name": group             'case': case sensitive           'q': save and quit
[DEBUG  ]  'ri': residue index
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] Copied index group 3 'GMXMMPBSA_REC'
[DEBUG  ] Copied index group 7 'GMXMMPBSA_LIG'
[DEBUG  ] Merged two groups with OR: 183 46 -> 229
[DEBUG  ] 
[DEBUG  ]   9 GMXMMPBSA_REC_GMXMMPBSA_LIG:   229 atoms
[DEBUG  ] 
[DEBUG  ] > 
[INFO   ] Normal Complex: Saving group receptor_ligand (3_7) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[DEBUG  ] Running command: echo -e "GMXMMPBSA_REC_GMXMMPBSA_LIG"| /usr/bin/gmx editconf -f str_noLP.pdb -n _GMXMMPBSA_COM_index.ndx -o _GMXMMPBSA_COM.pdb
[DEBUG  ]              :-) GROMACS - gmx editconf, 2020.1-Ubuntu-2020.1-1 (-:
[DEBUG  ] 
[DEBUG  ]                             GROMACS is written by:
[DEBUG  ]      Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
[DEBUG  ]     Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
[DEBUG  ]  Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
[DEBUG  ]   Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
[DEBUG  ]   Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
[DEBUG  ]     Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
[DEBUG  ]   Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
[DEBUG  ]     Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
[DEBUG  ]     Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
[DEBUG  ]    Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
[DEBUG  ]  Christian Wennberg    Maarten Wolf      Artem Zhmurov   
[DEBUG  ]                            and the project leaders:
[DEBUG  ]         Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel
[DEBUG  ] 
[DEBUG  ] Copyright (c) 1991-2000, University of Groningen, The Netherlands.
[DEBUG  ] Copyright (c) 2001-2019, The GROMACS development team at
[DEBUG  ] Uppsala University, Stockholm University and
[DEBUG  ] the Royal Institute of Technology, Sweden.
[DEBUG  ] check out http://www.gromacs.org for more information.
[DEBUG  ] 
[DEBUG  ] GROMACS is free software; you can redistribute it and/or modify it
[DEBUG  ] under the terms of the GNU Lesser General Public License
[DEBUG  ] as published by the Free Software Foundation; either version 2.1
[DEBUG  ] of the License, or (at your option) any later version.
[DEBUG  ] 
[DEBUG  ] GROMACS:      gmx editconf, version 2020.1-Ubuntu-2020.1-1
[DEBUG  ] Executable:   /usr/bin/gmx
[DEBUG  ] Data prefix:  /usr
[DEBUG  ] Working dir:  /home/ai/rmcd12-3dfnb(charm36)-gmxMMPDSA分析-2
[DEBUG  ] Command line:
[DEBUG  ]   gmx editconf -f str_noLP.pdb -n _GMXMMPBSA_COM_index.ndx -o _GMXMMPBSA_COM.pdb
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] Select a group for output:
[DEBUG  ] Group     0 (         System) has  7193 elements
[DEBUG  ] Group     1 (          Other) has   230 elements
[DEBUG  ] Group     2 (            fnb) has    47 elements
[DEBUG  ] Group     3 (  GMXMMPBSA_REC) has   183 elements
[DEBUG  ] Group     4 (          Water) has  6963 elements
[DEBUG  ] Group     5 (            SOL) has  6963 elements
[DEBUG  ] Group     6 (      non-Water) has   230 elements
[DEBUG  ] Group     7 (  GMXMMPBSA_LIG) has    46 elements
[DEBUG  ] Group     8 (receptor_ligand) has   229 elements
[DEBUG  ] Group     9 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has   229 elements
[DEBUG  ] Select a group: 
[ERROR  ] MMPBSA_Error 

/usr/bin/gmx editconf failed when querying com_traj.xtc

Check the gmx_MMPBSA.log file to report the problem.

**Comment by Valdes-Tresanco-MS** [comment]
Please, send me the files to check them (*.tpr, *.pdb, *.ndx, 5frames *.xtc and *.top + *.itp)

**Comment by afwer1231** [comment]
> Please, send me the files to check them (*.tpr, *.pdb, *.ndx, 5frames *.xtc and *.top + *.itp)

Thank you for your reply. I can't upload the file you need, can I use your email address?

**Comment by Valdes-Tresanco-MS** [comment]
yes, send (or share) me it to my email

**Comment by afwer1231** [comment]
> yes, send (or share) me it to my email

Could you please send me your email address?thank a lot.

**Comment by afwer1231** [comment]
[rmcd12-3dfnb(charm36)-gmxMMPDSA-test.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11963523/rmcd12-3dfnb.charm36.-gmxMMPDSA-test.zip)

**Comment by afwer1231** [comment]
> yes, send (or share) me it to my email

Hello, no need to send email, I can upload the packaged file through this GitHub.

**Comment by afwer1231** [comment]
[str_noLP.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11963781/str_noLP.zip)

**Comment by Valdes-Tresanco-MS** [comment]
It seems that you did not process the trajectory, because the number of atoms is different from the tpr. Please follow the steps as listed in the [example](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Protein_ligand_LPH_atoms_CHARMMff/).

**Comment by afwer1231** [comment]
> It seems that you did not process the trajectory, because the number of atoms is different from the tpr. Please follow the steps as listed in the [example](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Protein_ligand_LPH_atoms_CHARMMff/).
What I sent to you is the original document. I followed that process before. Now I send the whole process to you for your check, thank you.
[rmcd12-3dfnb(charm36)-gmxMMPDSA-test.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11965113/rmcd12-3dfnb.charm36.-gmxMMPDSA-test.zip)

**Comment by Valdes-Tresanco-MS** [comment]
It seems that index and pdb are not fully compatible. Generating a new index from the pdb works without problems, although I could not do the calculation because itp files are missing.

```bash
gmx make_ndx -f str_noLP.pdb -o m_index.ndx
```

**Comment by afwer1231** [comment]
Yes, gmxMMPBSA works perfectly, you are so cool, thank you so much. By the way, what could possibly have caused this?  I need to extract the the complex‘pdb for indexing?

**Comment by Valdes-Tresanco-MS** [comment]
Normally, no. This can happen because there is a mismatch in the order of the atoms between one file and another. This case is particular because it is necessary to remove the LP pseudo atom. I close the issue since it has been solved. Feel free to open a new one to report any other error.
