### ISSUE TITLE
v1.6.1 Error Gromacs

### ISSUE THREAD

**Issue by laodeaman-ai** [Valdes-Tresanco-MS/gmx_MMPBSA#396]
Hello Sir...

I hope you are doing great

I am encountering an error when executing the following command using gmx_MMPBSA version 1.6.1 on Ubuntu 20.04 with gmx 2022.5 and ambertools21.12:

gmx_MMPBSA -O -i gb.in -cs ../md.tpr -ct ../md.xtc -ci ../index.ndx -cg 1 13 -cp ../topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

After running the above command, I receive the following error message:

[INFO ] Checking gb.in input file...
[INFO ] Checking gb.in input file...Done.

[INFO ] Checking external programs...
[INFO ] cpptraj found! Using /home/arga/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO ] tleap found! Using /home/arga/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO ] parmchk2 found! Using /home/arga/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO ] sander found! Using /home/arga/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO ] Using GROMACS version 4.x.x!
[ERROR ] MMPBSA_Error

I would greatly appreciate any guidance or solution to resolve this error. Thank you for your assistance.

**Comment by Valdes-Tresanco-MS** [comment]
Please, attach the gmx_MMPBSA.log file

**Comment by laodeaman-ai** [comment]
This is the log file content: 
[INFO   ] Starting gmx_MMPBSA v1.6.1
[DEBUG  ] WDIR          : /home/arga/Downloads/lig0_5fu_egfr/gb
[DEBUG  ] AMBERHOME     : /home/arga/miniconda3/envs/gmxMMPBSA
[DEBUG  ] PYTHON EXE    : /home/arga/miniconda3/envs/gmxMMPBSA/bin/python
[DEBUG  ] PYTHON VERSION: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) [GCC 10.4.0]
[DEBUG  ] MPI           : /home/arga/miniconda3/envs/gmxMMPBSA/bin/mpirun
[DEBUG  ] ParmEd        : 3.4.3+11.g41cc9ab
[DEBUG  ] OS PLATFORM   : Linux-5.15.0-76-generic-x86_64-with-glibc2.31
[DEBUG  ] OS SYSTEM     : Linux
[DEBUG  ] OS VERSION    : #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023
[DEBUG  ] OS PROCESSOR  : x86_64

[INFO   ] Command-line
  gmx_MMPBSA -O -i gb.in -cs ../md.tpr -ct ../md.xtc -ci ../index.ndx -cg 1 13 -cp ../topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[DEBUG  ] |Input file:
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] |Input file generated by gmx_MMPBSA (v1.6.1)
[DEBUG  ] |Be careful with the variables you modify, some can have severe consequences on the results you obtain.
[DEBUG  ] |
[DEBUG  ] |# General namelist variables
[DEBUG  ] |&general
[DEBUG  ] |  sys_name             = "GB"                                             # System name
[DEBUG  ] |  startframe           = 1                                              # First frame to analyze
[DEBUG  ] |  endframe             = 9999999                                        # Last frame to analyze
[DEBUG  ] |  interval             = 1                                              # Number of frames between adjacent frames analyzed
[DEBUG  ] |  forcefields          = "oldff/leaprc.ff99SB,leaprc.gaff"              # Define the force field to build the Amber topology
[DEBUG  ] |  ions_parameters      = 1                                              # Define ions parameters to build the Amber topology
[DEBUG  ] |  PBRadii              = 3                                              # Define PBRadii to build amber topology from GROMACS files
[DEBUG  ] |  temperature          = 298.15                                         # Temperature
[DEBUG  ] |  qh_entropy           = 0                                              # Do quasi-harmonic calculation
[DEBUG  ] |  interaction_entropy  = 0                                              # Do Interaction Entropy calculation
[DEBUG  ] |  ie_segment           = 25                                             # Trajectory segment to calculate interaction entropy
[DEBUG  ] |  c2_entropy           = 0                                              # Do C2 Entropy calculation
[DEBUG  ] |  assign_chainID       = 0                                              # Assign chains ID
[DEBUG  ] |  exp_ki               = 0.0                                            # Experimental Ki in nM
[DEBUG  ] |  full_traj            = 0                                              # Print a full traj. AND the thread trajectories
[DEBUG  ] |  gmx_path             = "gmx"                                             # Force to use this path to get GROMACS executable
[DEBUG  ] |  keep_files           = 2                                              # How many files to keep after successful completion
[DEBUG  ] |  netcdf               = 0                                              # Use NetCDF intermediate trajectories
[DEBUG  ] |  solvated_trajectory  = 1                                              # Define if it is necessary to cleanup the trajectories
[DEBUG  ] |  verbose              = 1                                              # How many energy terms to print in the final output
[DEBUG  ] |/
[DEBUG  ] |
[DEBUG  ] |# (AMBER) Generalized-Born namelist variables
[DEBUG  ] |&gb
[DEBUG  ] |  igb                  = 5                                              # GB model to use
[DEBUG  ] |  intdiel              = 1.0                                            # Internal dielectric constant for sander
[DEBUG  ] |  extdiel              = 78.5                                           # External dielectric constant for sander
[DEBUG  ] |  saltcon              = 0.0                                            # Salt concentration (M)
[DEBUG  ] |  surften              = 0.0072                                         # Surface tension
[DEBUG  ] |  surfoff              = 0.0                                            # Surface tension offset
[DEBUG  ] |  molsurf              = 0                                              # Use Connelly surface ('molsurf' program)
[DEBUG  ] |  msoffset             = 0.0                                            # Offset for molsurf calculation
[DEBUG  ] |  probe                = 1.4                                            # Solvent probe radius for surface area calc
[DEBUG  ] |  ifqnt                = 0                                              # Use QM on part of the system
[DEBUG  ] |  qm_theory            = ""                                             # Semi-empirical QM theory to use
[DEBUG  ] |  qm_residues          = ""                                             # Residues to treat with QM
[DEBUG  ] |  qmcharge_com         = 0                                              # Charge of QM region in complex
[DEBUG  ] |  qmcharge_lig         = 0                                              # Charge of QM region in ligand
[DEBUG  ] |  qmcharge_rec         = 0                                              # Charge of QM region in receptor
[DEBUG  ] |  qmcut                = 9999.0                                         # Cutoff in the QM region
[DEBUG  ] |  scfconv              = 1e-08                                          # Convergence criteria for the SCF calculation, in kcal/mol
[DEBUG  ] |  peptide_corr         = 0                                              # Apply MM correction to peptide linkages
[DEBUG  ] |  writepdb             = 1                                              # Write a PDB file of the selected QM region
[DEBUG  ] |  verbosity            = 0                                              # Controls the verbosity of QM/MM related output
[DEBUG  ] |  alpb                 = 0                                              # Use Analytical Linearized Poisson-Boltzmann (ALPB)
[DEBUG  ] |  arad_method          = 1                                              # Selected method to estimate the effective electrostatic size
[DEBUG  ] |/
[DEBUG  ] |
[DEBUG  ] |# Decomposition namelist variables
[DEBUG  ] |&decomposition
[DEBUG  ] |  idecomp              = 2                                              # Which type of decomposition analysis to do
[DEBUG  ] |  dec_verbose          = 0                                              # Control energy terms are printed to the output
[DEBUG  ] |  print_res            = "within 6"                                     # Which residues to print decomposition data for
[DEBUG  ] |  csv_format           = 1                                              # Write decomposition data in CSV format
[DEBUG  ] |/
[DEBUG  ] |
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] 
[INFO   ] Checking gb.in input file...
[INFO   ] Checking gb.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/arga/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/arga/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/arga/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/arga/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version 4.x.x!
[ERROR  ] MMPBSA_Error 

Could not find necessary program [ GROMACS ]

Check the gmx_MMPBSA.log file to report the problem.

**Comment by Valdes-Tresanco-MS** [comment]
You must have a gromacs executable in the PATH. You can install it from conda as follows:
```bash
conda install -c conda-forge gromacs -y -q
```

**Comment by laodeaman-ai** [comment]
Hello,

I followed the suggestion provided and attempted to install GROMACS using the command "conda install -c conda-forge gromacs -y -q". Prior to that, I deactivated the PATH in .bashrc of the previously installed GROMACS version. However, I am still encountering the same error. I have attached a screenshot and the log file for reference.

Could you please provide further assistance to resolve this issue? Your help is greatly appreciated.

Thank you.

**Comment by Valdes-Tresanco-MS** [comment]
But you installed gromacs in the base environment, not on the gmxMMPBSA one. Please, activate the gmxMMPBSA environment, install gromacs, and check if it exists.
