### ISSUE TITLE
[ENH]:peptide

### ISSUE THREAD

**Issue by CPU-HORDB** [Valdes-Tresanco-MS/gmx_MMPBSA#397]
### In which tool?

None

### New Feature

When the ligand of membrane protein is peptide instead of small molecule, how can I calculate it with gmx_MMPBSA? If it can be realized, please let me know.

### Relevance

None

### Difficulty to implement

None

**Comment by marioernestovaldes** [comment]
Same procedure as with a small molecule... Define the receptor and ligand (in this case the peptide) groups and calculate the energy using gmx_MMPBSA
