### ISSUE TITLE
encountered by following error

### ISSUE THREAD

**Issue by debanjansen48** [Valdes-Tresanco-MS/gmx_MMPBSA#398]
### My Question is...

gmx_mmpbsa -O -i MMGBSA.in -cs ../md_100.tpr -ct ../md_100.xtc -ci ../index.ndx -cg 3 4 -cp ../topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv WARNING: No ICDs were found. Either, - Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or  - Make your system-wide implementation visible by installing ocl-icd-system conda package.  [INFO   ] Starting gmx_MMPBSA v1.6.1 [INFO   ] Command-line   gmx_MMPBSA -O -i MMGBSA.in -cs ../md_100.tpr -ct ../md_100.xtc -ci ../index.ndx -cg 3 4 -cp ../topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv  tets [INFO   ] Checking MMGBSA.in input file... [INFO   ] Checking MMGBSA.in input file...Done.  [INFO   ] Checking external programs... [INFO   ] cpptraj found! Using /home/debanjan/miniconda3/envs/gmxMMPBSA/bin/cpptraj [INFO   ] tleap found! Using /home/debanjan/miniconda3/envs/gmxMMPBSA/bin/tleap [INFO   ] parmchk2 found! Using /home/debanjan/miniconda3/envs/gmxMMPBSA/bin/parmchk2 [INFO   ] sander found! Using /home/debanjan/miniconda3/envs/gmxMMPBSA/bin/sander [INFO   ] Using GROMACS version > 5.x.x! [INFO   ] gmx found! Using /home/debanjan/miniconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx [INFO   ] Checking external programs...Done.  [INFO   ] Building AMBER topologies from GROMACS files... [INFO   ] Get PDB files from GROMACS structures files... [INFO   ] Making gmx_MMPBSA index for complex... [INFO   ] Normal Complex: Saving group C-alpha_Backbone (3_4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb [INFO   ] No receptor structure file was defined. Using ST approach... [INFO   ] Using receptor structure from complex to generate AMBER topology [INFO   ] Normal Receptor: Saving group C-alpha (3) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb [INFO   ] No ligand structure file was defined. Using ST approach... [INFO   ] Using ligand structure from complex to generate AMBER topology [INFO   ] Normal Ligand: Saving group Backbone (4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb   File "/home/debanjan/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>     sys.exit(gmxmmpbsa())   File "/home/debanjan/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa     app.make_prmtops()   File "/home/debanjan/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 687, in make_prmtops     self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()   File "/home/debanjan/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 123, in buildTopology     self.gmx2pdb()   File "/home/debanjan/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 492, in gmx2pdb     self.resi, self.resl, self.orderl = res2map(self.indexes, self.complex_str)   File "/home/debanjan/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/utils.py", line 601, in res2map     for e in value['num']: TypeError: string indices must be integers Exiting. All files have been retained.

**Comment by reshugupt1** [comment]
same error i got
if you got a solution, kindly also help me

**Comment by Valdes-Tresanco-MS** [comment]
Please, use the issue template and attach all required info to identify what's going on

**Comment by debanjansen48** [comment]
sorry for late reply. Thanks for kind consideration

**Comment by z15544534** [comment]
i got same error
please tell me how to solve it
