### ISSUE TITLE
[Question]: Discrepancy in Binding Free Energy Results between GMX_MMPBSA v1.6.1 and v1.4.3

### ISSUE THREAD

**Issue by aqrzsy** [Valdes-Tresanco-MS/gmx_MMPBSA#402]
### My Question is...

Hello,  I've encountered a significant discrepancy in the results of binding free energy calculations when using two different versions of gmx_mmpbsa.  Version Details:  Using version 1.6.1, the computed binding free energy was over 512 kcal/mol. When I downgraded to version 1.4.3 and used the exact same input files, the result was -13kcal/mol, which is more in line with what I expected. Question: Is there any specific parameter or settings change between the two versions that could explain such a drastic difference? Are there any recommended settings or parameters that should be adjusted when using version 1.6.1?  Any insight into this discrepancy would be highly appreciated. Thank you!

**Comment by marioernestovaldes** [comment]
can you send us the files you are using with the results? I wouldn't expect such a difference considering the core for the program hasn't changed

**Comment by aqrzsy** [comment]
Here are my files and results. I'm sorry, the md.xtc file is too large to upload.
[files and results.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/12318380/files.and.results.zip)

**Comment by marioernestovaldes** [comment]
It seems you are using a different number of frames in the calculations... please, make sure you are using exactly the same frames in both calculations, and let us know if the issue persists

**Comment by aqrzsy** [comment]
I'm sorry, but this is the result I obtained using version 1.4.3, recalculating with the same number of frames as in version 1.6.1. The difference is still significant.
[1.4.3FINAL_RESULTS_MMPBSA.dat.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/12367143/1.4.3FINAL_RESULTS_MMPBSA.dat.zip)

**Comment by marioernestovaldes** [comment]
could you please share the trajectory file, thus we can perform the analysis?

**Comment by Valdes-Tresanco-MS** [comment]
The main change from version 1.4.x to 1.6.x is the calculation of the non-polar component of the solvation. Please compare (and attach) the _GMXMMPBSA_info files of both versions to corroborate that you are using the same parameters.
