### ISSUE TITLE
[Question]: Is there a way to monitor the progress?

### ISSUE THREAD

**Issue by avinashkarkada** [Valdes-Tresanco-MS/gmx_MMPBSA#403]
### Is there a way to monitor the progress?
The g_mmpbsa had a workaround where plotting the xvg file being generated gave an idea about the progress of the calculations. So, is there any way we could do the same in gmx_MMPBSA?

**Comment by marioernestovaldes** [comment]
In the latest versions of gmx_MMPBSA, you can track the progress of the calculations... please, update gmx_MMPBSA and let us know if that solves the issue
