### ISSUE TITLE
[Question]: Can not run gmx_MMPBSA software?

### ISSUE THREAD

**Issue by limeiling-r** [Valdes-Tresanco-MS/gmx_MMPBSA#410]
### My Question is...

Hello, I would like to use gmx_MMPBSA to calculate the binding free energy of a small molecule and membrane protein systems. But this error occurs when I running the command, how to solve it?
![294a534ac61b8598ddf71eb06fe6dac](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/83357192/e029e033-c419-4707-9d75-122b6785c2e1)

**Comment by Valdes-Tresanco-MS** [comment]
You can create a fresh conda environment by removing the previous installed (`conda env remove -n gmxMMPBSA`) and installing it again following the installation instructions listed in the documentation. 
This error is independent of the installation but is related to your internet connection, internet provider, or conda server problem. Usually, it works after a few tries.

**Comment by limeiling-r** [comment]
Hello，

I installed it using the pip method given by the gmx_MMPBSA official website. 
However, when installing mpi4py and AmberTools in step 2, the error is displayed as follows：
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/83357192/7339c41d-83b8-4c3d-8f4d-04de254b1ecd)

Please why can't I run this step successfully?

**Comment by Valdes-Tresanco-MS** [comment]
Probably, you get this error because compilers=1.2.8 don't exist. Please, try with this command line
```bash
conda install -c conda-forge mpi4py=3.1.3 ambertools=21.12 compilers=1.2.0 -y -q
```

**Comment by limeiling-r** [comment]
I tried many times with this command 'conda install -c conda-forge mpi4py=3.1.3 ambertools=21.12 compilers=1.2.0 -y -q'.

However, it still displayed the error as follows:
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/83357192/71e01b26-42dd-4173-85d3-1de4abdeb379)

How to solve it ?

**Comment by Valdes-Tresanco-MS** [comment]
Seems like you are trying to install gmx_MMPBSA in an HPC. Right? Are you sure you have an internet connection? Commonly, HPC has internet restrictions because of security

**Comment by limeiling-r** [comment]
> Probably, this error is related to the mpi library. Please, check the mpi version and try to create a fresh conda environment Let me know if you have any doubts↳

Hi Tresanco，
We have updated the MPI library and gmx_MMPBSA, and the current MPI version is 4.0.2. But it still shows the mpi library error when running the software. If we reinstall another one, it may still not work due to the MPI library. 
So, how do I solve the MPI library error?

**Comment by Valdes-Tresanco-MS** [comment]
Commonly, the HPC admins encourage users to use the module pre-compiled libraries because they optimize them according to the hardware. However, in this case, gmx_MMPBSA uses MPI externally, so you can use the mpi installed with conda. Please, check what mpi you are using (`which mpirun`)

**Comment by limeiling-r** [comment]
Hi Tresanco,
The mpi I was using is in /public/apps/intel/compilers_and_libraries_2018.1.163/linux/mpi/intel64/bin/mpirun directory. 
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/83357192/42e13d0e-fca0-4cd7-b7f4-b45ddca5f742)
Please tell me how can I use the mpi installed with conda?

Thank you.
Best wishes!

**Comment by Valdes-Tresanco-MS** [comment]
Are you activating any module containing mpi? Normally, when you activate the gmxMMPBSA environment, mpirun from conda must be accessible in the path.

**Comment by limeiling-r** [comment]
The mpi I was using is in ~/.conda/envs/gmxMMPBSA_3/bin/mpirun when I activate the gmxMMPBSA environment.
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/83357192/faed6cd5-43c3-4788-968f-3fbf4f457e8b)

**Comment by Valdes-Tresanco-MS** [comment]
Fails even using the mpi from conda? According to my search, the error "ImportError: dynamic module does not define module export function" occurs when using a shared library. In those cases, it is necessary to check the definition of the shared library (`env | grep LD_LIBRARY_PATH`). In case you are using the MPI library of a module or the system because at least one path overwrites the conda one, it is wise to export only the conda one 
(`export LD_LIBRARY_PATH=~/.conda/envs/gmxMMPBSA_2/lib`) before running gmx_MMPBSA.
Let me know if works for you

**Comment by Valdes-Tresanco-MS** [comment]
As you can see at the end, there is a path for the MPI shared library. This path takes priority over the conda library path (the first one). Yes, you should export only the conda library path (copy it as appears in the image `export LD_LIBRARY_PATH=~/.conda/envs/gmxMMPBSA_2/lib.AVX2_256`)
Let me know if this works.

**Comment by limeiling-r** [comment]
Hi Tresanco,
I have set the path using instruction (export LD_LIBRARY_PATH=~/.conda/envs/gmxMMPBSA_2/lib.AVX2_256).
However, it reports a new error as following:
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/83357192/f6aaca1f-1fb8-4247-8160-1088c9bae2e0)

**Comment by Valdes-Tresanco-MS** [comment]
Please, try it and check if it works

**Comment by limeiling-r** [comment]
I set the path to (export LD_LIBRARY_PATH=/public/home/lly/.conda/envs/gmxMMPBSA_2/lib).
However, it still report the mpi library error.
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/83357192/6bcbf8e2-76d5-4ab3-96ce-0af01dce9385)

**Comment by limeiling-r** [comment]
Hi Tresanco,
The problem has been solved. Thank you!

Best wishes!

**Comment by Valdes-Tresanco-MS** [comment]
Please share how you solved it to help other users. Thanks

**Comment by limeiling-r** [comment]
I entered 'ldconfig' before entering the software environment.

But, I don't know why this instruction works? Previously, the software did not need to enter this instruction and could be used normally.

**Comment by Valdes-Tresanco-MS** [comment]
No idea. Well, at least you solved the problem. Happy energy calculation!
