### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: Different SD and SEM values in FINAL_DECOMP_MMPBSA and gmx_MMPBSA_ana

### ISSUE THREAD

**Issue by WoutVanEynde** [Valdes-Tresanco-MS/gmx_MMPBSA#416]
### Bug summary

I get different SD and SEM values in the FINAL_DECOMP file and the gmx_MMPBSA_ana software. The averages are the same, but SD and SEM not.

I am looking at the TDC PBSA values in gmx_MMPBSA_ana and at the second DELTAS in the FINAL_DECOMP file.

### Terminal output

```bash
There is no terminal output.
```

### Actual outcome

![FINAL_DECOMP_MMPBSA](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/99839278/7f074487-8a4c-43a1-b012-d7853765a973)
![gmx_MMPBSA_ana](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/99839278/9472ef0c-0644-4781-9852-9045aa5fb11f)

### Expected outcome

I would expect the values to be the same.

### Operating system

Ubuntu

### gmx_MMPBSA_ana Version

1.6.1

### Python version

3.9.15

### Installation

AmberTools compilation + conda

**Comment by marioernestovaldes** [comment]
could you please attach or send the files?
