### ISSUE TITLE
[Question]: GromacsWarning: angles funct != 1 or 5; unknown functional warnings.warn('angles funct != 1 or 5; unknown '

### ISSUE THREAD

**Issue by C0921** [Valdes-Tresanco-MS/gmx_MMPBSA#417]
### My Question is...

gmx_MMPBSA reported: .conda/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py:650: GromacsWarning: angles funct != 1 or 5; unknown functional   warnings.warn('angles funct != 1 or 5; unknown '

**Comment by C0921** [comment]
And it displayed at the end of the output file:
 ParameterError: Not all angle parameters found

**Comment by Valdes-Tresanco-MS** [comment]
Please, check this [thread](https://www.researchgate.net/post/Error_while_calculating_binding_energy_using_gmx_mmpbsa) in ResearchGate
