### ISSUE TITLE
[Question]: Protein-membrane per residue decomposition

### ISSUE THREAD

**Issue by margretheg** [Valdes-Tresanco-MS/gmx_MMPBSA#421]
### My Question is...

I want to use gmx_MMPBSA to analyse a protein-protein complex where the receptor is embedded in a lipid bilayer. I've used the CHARMM36 ff for the simulations, and followed your tutorial (https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Protein_membrane_CHARMMff/). This seems to work fine! However, I would also like to include per-residue decomposition. Is this valid for protein-membrane systems? I only want to look at the residues in the protein complex, and treat the membrane implicitly. If valid, which option should I use for idecomp, 1 or 2? Or does it not matter? Thanks a lot for answers!

**Comment by marioernestovaldes** [comment]
yes, you can use it for decomposition... you can use idecomp=2... more info here:

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/#decomp-namelist-variables

**Comment by margretheg** [comment]
Thanks a lot for the quick response!
