### ISSUE TITLE
pb/gbsa calculation for protein-biopolymer(mix of standard/non-standard aa, chemical linker, etc) interaction

### ISSUE THREAD

**Issue by leiqian-nmsu** [Valdes-Tresanco-MS/gmx_MMPBSA#422]
### My Question is...

Dear users, in order to do pb/gbsa calc for this special case: interaction between protein and biopolymer(mix of standard/non-standard aa, chemical linker, etc), I have to firstly parametrize each monomer and then parametrize their specific linking bonds. Could you please recommand a tutorial/software to do this work? I know ambertools might be used to develop nonstandard parameters, but have no idea how to parametrize their repeated specific linking bonds. Thanks!

**Comment by Valdes-Tresanco-MS** [comment]
In some cases, you can use a fragment-based approach. You can parameterize one monomer and then parametrize each monomer fragment bonded to the other. Please check this [article](https://pubs.acs.org/doi/10.1021/acs.cgd.6b00052). In this article, they parametrize a dimer as fragments using [R.E.D server ](http://q4md-forcefieldtools.org/REDServer-Development/). Maybe, it can help you. Probably, this same focus can be applied with antechamber

**Comment by leiqian-nmsu** [comment]
@Valdes-Tresanco-MS 
Thank you for your kind reply! I will read this paper and start a test.
Thanks!
