### ISSUE TITLE
gmx_MMPBSA_ana unexpectedly closes

### ISSUE THREAD

**Issue by drbipinraj** [Valdes-Tresanco-MS/gmx_MMPBSA#428]
### My Question is...

while saving the data from gmx_MMPBSA_ana, it closes abruptly with following message  
"Traceback (most recent call last):
  File "/home/dkdas/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/plots.py", line 106, in save_figure
    fname, filter = qt_compat._getSaveFileName(
AttributeError: module 'matplotlib.backends.qt_compat' has no attribute '_getSaveFileName'
Aborted (core dumped)"

what could be the possible reason?

**Comment by Valdes-Tresanco-MS** [comment]
please, attach the output of `conda list`

**Comment by wonwill** [comment]
I have encountered the same errors on the macOS and Ubuntu 22.

######## error message on macOS ########
(gmxMMPBSA) user@MBA13M2 target-dk_gmx_mpi-am99sb-100ns-rpl1-amd3 % gmx_MMPBSA_ana
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/analyzer/plots.py", line 106, in save_figure
    fname, filter = qt_compat._getSaveFileName(
AttributeError: module 'matplotlib.backends.qt_compat' has no attribute '_getSaveFileName'
zsh: abort      gmx_MMPBSA_ana

######## conda list ########
Here is the list from "conda list" on my macOS.
# Name                    Version                   Build  Channel
ca-certificates           2023.08.22           hca03da5_0
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
fonttools                 4.43.1                   pypi_0    pypi
gmx-mmpbsa                1.6.2                    pypi_0    pypi
importlib-resources       6.1.0                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
libcxx                    14.0.6               h848a8c0_0
libffi                    3.4.4                hca03da5_0
matplotlib                3.8.0                    pypi_0    pypi
mpi4py                    3.1.5                    pypi_0    pypi
ncurses                   6.4                  h313beb8_0
numpy                     1.26.1                   pypi_0    pypi
openssl                   3.0.11               h1a28f6b_2
packaging                 23.2                     pypi_0    pypi
pandas                    1.2.2                    pypi_0    pypi
parmed                    3.4.3+11.g41cc9ab          pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3             py39hca03da5_0
pyparsing                 3.1.1                    pypi_0    pypi
pyqt5                     5.15.10                  pypi_0    pypi
pyqt5-qt5                 5.15.11                  pypi_0    pypi
pyqt5-sip                 12.13.0                  pypi_0    pypi
pyqt6                     6.5.3                    pypi_0    pypi
pyqt6-qt6                 6.5.3                    pypi_0    pypi
pyqt6-sip                 13.6.0                   pypi_0    pypi
python                    3.9.18               hb885b13_0
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
readline                  8.2                  h1a28f6b_0
scipy                     1.11.3                   pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
setuptools                68.0.0           py39hca03da5_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h80987f9_0
tk                        8.6.12               hb8d0fd4_0
tqdm                      4.66.1                   pypi_0    pypi
tzdata                    2023c                h04d1e81_0
wheel                     0.41.2           py39hca03da5_0
xz                        5.4.2                h80987f9_0
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5a0b063_0

**Comment by Valdes-Tresanco-MS** [comment]
It seems like a compatibility problem with matplotlib 3.8.0. Please, try to downgrade matplotlib to v3.5.x

**Comment by wonwill** [comment]
Thanks for your highly fast and accurate reply. It clearly works. 
`conda install matplotlib==3.5.3`
