### ISSUE TITLE
[Question]: How to calculate the entropy of protein-protein system using gmx_MMPBSA?

### ISSUE THREAD

**Issue by Ishrat-Jahan1** [Valdes-Tresanco-MS/gmx_MMPBSA#435]
### My Question is...

Dear all, I have done the 500ns MD simulation of protein-protein system and I am trying to calculate the binding free energy of protein-protein interactions using gmx_MMPBSA. For entropy calculation, I am using the Interaction entropy method but I am getting a very high entropy value i.e value of -TS is positive because of which total energy gets positive. I have used the last 100 ns of the simulation for  energy calculation and used the ie_segment= 25. 100 frames were used for the calculation and also I did the calculation by varying the number of frames but still getting the deltaG positive because of -TS. Any help/suggestion regarding this will be highly appreciated. I am also attaching the mmpbsa.in file which I have used for this purpose.  
"Sample input file for MM/PB(GB)SA calculation This input file is meant to show only that gmx_MMPBSA works. Although, we tried to used the input files as recommended in the Amber manual, some parameters have been changed to perform more expensive calculations in a reasonable amount of time. Feel free to change the parameters according to what is better for your system.  
&general
sys_name="Prot-Prot",
startframe=0,
endframe=100,
forcefields="leaprc.protein.ff14SB", interaction_entropy=1, temperature=290, solvated_trajectory=0, verbose=2, PBRadii=3,ie_segment=25,
/
&gb
igb=2, saltcon=0.150,
/
&pb
istrng=0.15, fillratio=4.0,radiopt=0,
/
&decomp
idecomp=2, dec_verbose=3,
print_res="within 5"

Thanks in advance

**Comment by marioernestovaldes** [comment]
Could you please share the results file?

**Comment by Ishrat-Jahan1** [comment]
Sure, here it is:
![Prot-Prot_Normal_GB+IE](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/152326563/a9ae85a5-c5a7-4ed6-8c1f-386e15f9d0ae)

**Comment by marioernestovaldes** [comment]
can't open the file, please attach the result file

**Comment by Ishrat-Jahan1** [comment]
Attached the result file
[Prot-Prot_Normal_GB+IE.csv](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/13492641/Prot-Prot_Normal_GB%2BIE.csv)

**Comment by marioernestovaldes** [comment]
ther hsould be a file called FINAL_RESULTS_MMPBSA.dat or somehting along those lines, this is the one I am talking about

**Comment by Ishrat-Jahan1** [comment]
Ok, here it is
[Final_results_MMPBSA.csv](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/13492727/Final_results_MMPBSA.csv)

**Comment by marioernestovaldes** [comment]
Sorry, Please send the .dat file that contains the interaction  entropy info

**Comment by Ishrat-Jahan1** [comment]
Unable to upload.dat file, saying this format is not supported

**Comment by marioernestovaldes** [comment]
Add a .TXT at the end and try to upload it...  it should be fine

**Comment by Ishrat-Jahan1** [comment]
here it is
[Final_results_MMPBSA.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/13503781/Final_results_MMPBSA.txt)

**Comment by Ishrat-Jahan1** [comment]
Please reply to my post regarding calculation of binding free energy of protein-protein system including entropy term using gmx_MMPBSA. 
Any help regarding this will be highly appreciated.
Thanks in advance.

**Comment by Valdes-Tresanco-MS** [comment]
As you can see in the output file, there is a warning related to the IE value.

> WARNING: THE INTERACTION ENERGY STANDARD DEVIATION [ σ(Int. Energy) ]
> IS GREATER THAN 3.6 kcal/mol (~15 kJ/mol). THUS, THE INTERACTION ENTROPY VALUES ARE
> NOT RELIABLE. CHECK THIS PAPER FOR MORE INFO (https://doi.org/10.1021/acs.jctc.1c00374)

The IE SD is `25.67 kcal/mol`, which means the IE value is unreliable. In this case, it is not recommended that you use the IE method. You can still compare the interaction energy using the enthalpy component and neglect the entropic one.

**Comment by Ishrat-Jahan1** [comment]
Thanks for the reply. Is there any other way to include the entropic contribution in the total binding energy of protein-protein system?

**Comment by marioernestovaldes** [comment]
NOMDE (https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Entropy_calculations/nmode/) Keep in mind that this method is extremely resource intensive and it is not guaranteed to get better results

**Comment by Ishrat-Jahan1** [comment]
Thanks for the suggestion.
