### ISSUE TITLE
The atom xxx in the complex index is not found in the topology file

### ISSUE THREAD

**Issue by whimouse** [Valdes-Tresanco-MS/gmx_MMPBSA#441]
### Bug summary

When using gmx_mmpbsa to calculate my protein-ligand trajectory(from gmx2023.3), the software seems can't read my topology correctly, which can be normally read by gmx.

### Terminal output

```bash
The atom xxx in the complex index is not found in the topology file
```

### gmx_MMPBSA.log

File "/home/room110/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/room110/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/room110/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 682, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/room110/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 125, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/room110/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 555, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/home/room110/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 853, in cleantop
    GMXMMPBSA_ERROR(f'The atom {i} in the {id} index is not found in the topology file. Please check that '
  File "/home/room110/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 171, in __init__
    raise exc('\n\n' + msg + '\n\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: 

The atom 237634 in the complex index is not found in the topology file. Please check that the files are consistent.

Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.

### Operating system

Ubuntu

### gmx_MMPBSA Version

1.6.2

### Python version

3.9.15

### Installation

conda AmberTools + conda

**Comment by marioernestovaldes** [comment]
Sorry for the delay! This usually happens when the groups selected are not the correct ones. Could you please confirm that the groups you are selecting are the correct ones? Could you please send the gmx_MMPBSA.log file

**Comment by whimouse** [comment]
Thank you for your response! I have solved this problem by deleting all molecules except proteins and ligands in .top file and .tpr file. It seems the program could not read the groups between protein and ligand, such as Na+ and Cl-.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Valdes-Tresanco-MS/gmx_MMPBSA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月5日(星期五) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Bug-gmx_MMPBSA]:  (Issue #441)





 
Sorry for the delay! This usually happens when the groups selected are not the correct ones. Could you please confirm that the groups you are selecting are the correct ones? Could you please send the gmx_MMPBSA.log file

**Comment by marioernestovaldes** [comment]
Good to know! Thanks for letting us know...
