### ISSUE TITLE
GromacsError: Only 3-point vsite type 1 is supported

### ISSUE THREAD

**Issue by yuqingxiong96** [Valdes-Tresanco-MS/gmx_MMPBSA#445]
### My Question is...

I am using gmxmmpbsa to claculate the free energy, but I get the following error: GromacsError: Only 3-point vsite type 1 is supported. Other systems can be calculated normally, may I ask what caused this problem? Here is my file. 
[mmpbsa.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/13759322/mmpbsa.zip)

**Comment by marioernestovaldes** [comment]
your ligand contains LPH particale which are not supported natively in gmx_MMPBSA... please follow this tutorial:

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Protein_ligand_LPH_atoms_CHARMMff/

**Comment by marioernestovaldes** [comment]
Please, reopen if needed...
