### ISSUE TITLE
[Question]: How to calculate GB

### ISSUE THREAD

**Issue by Admire7494** [Valdes-Tresanco-MS/gmx_MMPBSA#449]
### My Question is...

[INFO   ] Starting gmx_MMPBSA v1.6.2 [INFO   ] Command-line   gmx_MMPBSA -O -i mmpbsa_2b.in -cs md.tpr -ci index.ndx -cg 1 14 -ct md.xtc -cp complex.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv  [INFO   ] Checking mmpbsa_2b.in input file... [INFO   ] Checking mmpbsa_2b.in input file...Done.  [INFO   ] Checking external programs... [INFO   ] cpptraj found! Using /home/wangmuqiang/.conda/envs/gmxMMPBSA/bin/cpptraj [INFO   ] tleap found! Using /home/wangmuqiang/.conda/envs/gmxMMPBSA/bin/tleap [INFO   ] parmchk2 found! Using /home/wangmuqiang/.conda/envs/gmxMMPBSA/bin/parmchk2 [INFO   ] sander found! Using /home/wangmuqiang/.conda/envs/gmxMMPBSA/bin/sander [INFO   ] Using GROMACS version > 5.x.x! [INFO   ] gmx found! Using /home/wangmuqiang/.conda/envs/gmxMMPBSA/bin.AVX2_256/gmx [INFO   ] Checking external programs...Done.  [INFO   ] Building AMBER topologies from GROMACS files... [INFO   ] Get PDB files from GROMACS structures files... [INFO   ] Making gmx_MMPBSA index for complex... [INFO   ] Normal Complex: Saving group Protein_NADH (1_14) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb [INFO   ] No receptor structure file was defined. Using ST approach... [INFO   ] Using receptor structure from complex to generate AMBER topology [INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb [INFO   ] No ligand structure file was defined. Using ST approach... [INFO   ] Using ligand structure from complex to generate AMBER topology [INFO   ] Normal Ligand: Saving group NADH (14) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb [INFO   ] Checking the structures consistency... [INFO   ]  [INFO   ] Using topology conversion. Setting radiopt = 0... [INFO   ] Building Normal Complex Amber topology... [INFO   ] Detected Amber/OPLS force field topology format... [WARNING] 46 invalid DIHEDRAL_PERIODICITY = 0 found in Complex topology... Setting DIHEDRAL_PERIODICITY = 1 [INFO   ] Assigning PBRadii mbondi2 to Complex... [INFO   ] Writing Normal Complex AMBER topology... [INFO   ] No Receptor topology file was defined. Using ST approach... [INFO   ] Building AMBER Receptor topology from Complex... [INFO   ] Assigning PBRadii mbondi2 to Receptor... [INFO   ] Writing Normal Receptor AMBER topology... [INFO   ] No Ligand topology file was defined. Using ST approach... [INFO   ] Building AMBER Ligand topology from Complex... [INFO   ] Assigning PBRadii mbondi2 to Ligand... [INFO   ] Writing Normal Ligand AMBER topology... [INFO   ] Cleaning normal complex trajectories... [INFO   ] Building AMBER topologies from GROMACS files... Done.  [INFO   ] Loading and checking parameter files for compatibility...   File "/home/wangmuqiang/.conda/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>     sys.exit(gmxmmpbsa())   File "/home/wangmuqiang/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 100, in gmxmmpbsa     app.file_setup()   File "/home/wangmuqiang/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 127, in file_setup     create_inputs(INPUT, self.normal_system, self.pre)   File "/home/wangmuqiang/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 263, in create_inputs     gb_mdin.make_mdin()   File "/home/wangmuqiang/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 327, in make_mdin     self.mdin.change(self.parent_namelist[key], key, value)   File "/home/wangmuqiang/.conda/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/amber/mdin/mdin.py", line 197, in change     if (value[0] == value[-1] == "'") or (value[0] == value[-1] == '"'): IndexError: string index out of range Exiting. All files have been retained.

The mmpbsa.in :
Input file for running PB and GB in serial
&general
 startframe=1, endframe=4, interval=1, keep_files=2,
/
&gb
  igb=5, saltcon=0.100,
/
&pb
  istrng=0.100, 
/

**Comment by marioernestovaldes** [comment]
did you install Parmed from out repository?

`python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4`

**Comment by Admire7494** [comment]
It's difficult to run this command. So i download the ParmEd to the anaconda environment and run command "python -m pip install . -U". The ParmEd was downloaded by bilibili

**Comment by Admire7494** [comment]
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ambertools                21.12            py39hc630cb1_0    conda-forge
amberutils                21.0                     pypi_0    pypi
arpack                    3.7.0                hdefa2d7_2    conda-forge
binutils                  2.39                 hdd6e379_1    conda-forge
binutils_impl_linux-64    2.39                 he00db2b_1    conda-forge
binutils_linux-64         2.39                h5fc0e48_13    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.24.0               hd590300_0    conda-forge
c-compiler                1.2.0                h7f98852_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
compilers                 1.2.0                ha770c72_0    conda-forge
contourpy                 1.2.0            py39h7633fee_0    conda-forge
curl                      7.87.0               h6312ad2_0    conda-forge
cxx-compiler              1.2.0                h4bd325d_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cython                    3.0.7            py39h3d6467e_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
fftw                      3.3.10          nompi_hc118613_108    conda-forge
fonttools                 4.47.0           py39hd1e30aa_0    conda-forge
fortran-compiler          1.2.0                h1990efc_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gcc_impl_linux-64         9.5.0               h99780fb_19    conda-forge
gcc_linux-64              9.5.0               h4258300_13    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gfortran_impl_linux-64    9.5.0               hf1096a2_19    conda-forge
gfortran_linux-64         9.5.0               hdb51d14_13    conda-forge
git                       2.39.1          pl5321ha3eba64_0    conda-forge
gmx-mmpbsa                1.6.2                    pypi_0    pypi
gromacs                   2022.4          nompi_hca75aac_100    conda-forge
gxx_impl_linux-64         9.5.0               h99780fb_19    conda-forge
gxx_linux-64              9.5.0               h43f449f_13    conda-forge
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.2          nompi_h2386368_101    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
importlib-resources       6.1.1              pyhd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_16    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py39h7633fee_1    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     9.5.0               h0a57e50_19    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libhwloc                  2.9.0                hd6dc26d_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h261ec11_106    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsanitizer              9.5.0               h2f262e1_19    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-devel_linux-64  9.5.0               h0a57e50_19    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.10.3               hca2bb57_4    conda-forge
libzip                    1.9.2                hc869a4a_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
matplotlib-base           3.8.2            py39he9076e7_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.1.3            py39h32b9844_3    conda-forge
mpich                     4.1.2              h846660c_101    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
netcdf-fortran            4.5.4           nompi_hc402ea5_102    conda-forge
numpy                     1.26.3           py39h474f0d3_0    conda-forge
ocl-icd                   2.3.1                h7f98852_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openmpi                   0.0.1                    pypi_0    pypi
openssl                   1.1.1w               hd590300_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
packmol                   20.010               h86c2bf4_0    conda-forge
packmol-memgen            1.2.1rc0                 pypi_0    pypi
pandas                    1.2.2                    pypi_0    pypi
parmed                    0+unknown                pypi_0    pypi
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pillow                    9.4.0            py39h2320bf1_1    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.13.0                  pypi_0    pypi
python                    3.9.15          h47a2c10_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.4             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
sander                    16.0                     pypi_0    pypi
scipy                     1.11.4           py39h474f0d3_0    conda-forge
seaborn                   0.11.2                   pypi_0    pypi
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sysroot_linux-64          2.12                he073ed8_16    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.66.1                   pypi_0    pypi
tzdata                    2023d                h0c530f3_0    conda-forge
unicodedata2              15.1.0           py39hd1e30aa_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxt                1.3.0                hd590300_0    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
This is the package in the environment

**Comment by Valdes-Tresanco-MS** [comment]
Please, try with the new version which have a several dependencies updated including parmed
