### ISSUE TITLE
[Bug-gmx_MMPBSA]: KeyError: 'temperature' when calculating QH entropy

### ISSUE THREAD

**Issue by camattelaer** [Valdes-Tresanco-MS/gmx_MMPBSA#450]
### Bug summary

error performing quasi harmonic calculation 

error shows both without 'temperature' key in input and when adding 'temperature' key to inputfile.
Also calling gmx_MMPBSA with or without MPI parallelization causes the same issue
[example.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/13845677/example.zip)

### Terminal output

```bash
File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 100, in gmxmmpbsa
    app.file_setup()
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 127, in file_setup
    create_inputs(INPUT, self.normal_system, self.pre)
  File "/home/camattelaer/Programs/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/createinput.py", line 294, in create_inputs
    qh_in = QuasiHarmonicInput(com_mask, rec_mask, lig_mask, temperature=INPUT['temperature'],
KeyError: 'temperature'
Error occurred on rank 0.
Exiting. All files have been retained.
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/13845652/gmx_MMPBSA.log)

### Operating system

ubuntu 22.04

### gmx_MMPBSA Version

gmx_MMPBSA v1.6.2 based on MMPBSA version 16.0 and AmberTools 20

### Python version

Python 3.9.15

### Installation

conda AmberTools + conda

**Comment by marioernestovaldes** [comment]
Thanks for reporting the issue. I did fix the issue (a05956df213081e694525f5212d4b42a7e99cb14) and it should run smoothly now. Please, update gmx_MMPBSA from our repo and try again:

`python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA`

**Comment by camattelaer** [comment]
updated to my conda env and QH entropy was calculated, closing.

Thank you for your very quick reply!

**Comment by ale94mleon** [comment]
This command `python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA` is giving:

```
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'v.1.6.3-2.g6ff56c9'
```

I am in macOS Senoma-14.4.1.

**Comment by ale94mleon** [comment]
Oh, I see that it is already reported in #487

**Comment by marioernestovaldes** [comment]
> Oh, I see that it is already reported in #487

@ale94mleon please, try again as we updated the versioneer

**Comment by ale94mleon** [comment]
> > Oh, I see that it is already reported in #487
> 
> @ale94mleon please, try again as we updated the versioneer

Now is working!
