### ISSUE TITLE
[Question]: MMPBSA_Error: Could not find necessary program [sander.APBS]

### ISSUE THREAD

**Issue by fatih4534** [Valdes-Tresanco-MS/gmx_MMPBSA#451]
### My Question is...

Hi sir, I would like to compute binding energy for my complex using mmpbsa module. However, when I tended to use sander.apbs typing sander_apbs=1 in &pb section, I got an error. How can I fix this error?

**Comment by marioernestovaldes** [comment]
could you please share the gmx_MMPBSA.log file?

**Comment by fatih4534** [comment]
The log file is in the attachment.
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/13854999/gmx_MMPBSA.log)

**Comment by marioernestovaldes** [comment]
oh, I see... we haven't done much testing ion sander.APBS, but it needs to
be installed before using it (https://mccammon.ucsd.edu/iapbs/doc/amber.html).
Any particular reason to use sander.APBS and not sander to perform
the calculation?

**Comment by fatih4534** [comment]
Indeed, I tend to compare mmpbsa calculations using gmx_MMPBSA with VMD plugin called caFE. Since apbs is used in the vmd plugin, I could not make sure the energy values while comparing.

**Comment by fatih4534** [comment]
Thank you for your answer sir :)
