### ISSUE TITLE
[Question]: how can I get ΔTOTAL and ΔG binding in the output file?

### ISSUE THREAD

**Issue by niloufar1993** [Valdes-Tresanco-MS/gmx_MMPBSA#452]
Hello, my output file just has complex total energy without ligand and receptor and so, without any delta calculations. Would you please tell me what the problem is, and how can I get ΔTOTAL and ΔG binding?
The command I entered:
mpirun -np 30 gmx_MMPBSA -O -i mmpbsa.in -cs md_0_1.tpr -ct md_0_1_noPBC.xtc -ci index.ndx -cg 15 16 -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv -do Final_decomp_mmpbsa.dat -deo Final_decomp_mmpbsa.csv --stability

**Comment by marioernestovaldes** [comment]
you are calculating stability which is only the energy terms for the complex. If you want to calculate binding free energies, follow these tutorials 

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/#analysis

**Comment by niloufar1993** [comment]
> you are calculating stability which is only the energy terms for the complex. If you want to calculate binding free energies, follow these tutorials
> 
> https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/#analysis

Thank you so much. So, if I omit --stability from the command line, I will get the binding free energy.
