### ISSUE TITLE
[Bug-gmx_MMPBSA]: The number of atoms in the topology and the complex structure are different

### ISSUE THREAD

**Issue by Aunity** [Valdes-Tresanco-MS/gmx_MMPBSA#455]
### Bug summary

gmx_MMPBSA -i mmpbsa.in -cs trj.pdb -ci index.ndx -ct top.pdb -cp topol.top  -cg 18 2 -nogui
[Uploading data.tar.gz…]()

### Terminal output

```bash
MMPBSA_Error:

The number of atoms in the topology (11289) and the complex structure (11287) are different. Please check these files and verify that they are correct. Otherwise report the error...

Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

MMPBSA_Error:

The number of atoms in the topology (11289) and the complex structure (11287) are different. Please check these files and verify that they are correct. Otherwise report the error...

Check the gmx_MMPBSA.log file to report the problem.
Exiting. All files have been retained.

### Operating system

Ubuntu

### gmx_MMPBSA Version

[INFO   ] Starting gmx_MMPBSA v1.6.1 [INFO   ] Command-line   gmx_MMPBSA -v  tets gmx_MMPBSA v1.6.1 based on MMPBSA version 16.0 and AmberTools 20

### Python version

Python 3.10.10

### Installation

conda AmberTools + pip

**Comment by marioernestovaldes** [comment]
Please, attach the gmx_MMPBS.log file

**Comment by Aunity** [comment]
@marioernestovaldes  Here is my gmx_MMPBSA.log file. 
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/13974996/gmx_MMPBSA.log)

**Comment by Aunity** [comment]
Yes, here is my input files. 
[data.tar.gz](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/13975453/data.tar.gz)

**Comment by marioernestovaldes** [comment]
/home/mario/Downloads/data1/data_new.zip

I did some corrections in the inut structure file top.pdb and adjust the topology accordingly to have all elements separated. Using this command:

`gmx_MMPBSA -O -i mmpbsa.in -cs top.pdb -ci index.ndx -cg 17 16 -ct top1.pdb -cp topol.top`

I was able to calculate teh energy. Note that I used top1.pdb as trajectory (duplicated of top.pdb) as this file ahs the rigth format and organization. I didn't work with the trajectory file you sent though...

let me know if you have any questions

**Comment by Aunity** [comment]
@marioernestovaldes Thanks a lot! I can run it too. So now gmx_MMPBSA  supports a system with a metal ions?

**Comment by marioernestovaldes** [comment]
Yes, gmx_MMPBSA does support systems with metal ions (https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Metalloprotein_ligand/)

**Comment by Aunity** [comment]
Thanks. I have know the reason of this error. gmx_MMPBSA not support ions like NA, CL, K. And my pdbfile contains ion Na.

**Comment by marioernestovaldes** [comment]
Is it necessary for the calculation? If not, you can remove it and proceed with the calculation. If the Na ion is absolutely necessary for the calculation, you need to rename this ion in the topology and the input structure and make sure is not removed during the trajectory cleaning process in gmx_MMPBSA.
