### ISSUE TITLE
unable to execute after installation

### ISSUE THREAD

**Issue by ssinhachem** [Valdes-Tresanco-MS/gmx_MMPBSA#46]
**Describe the issue**
Installed the program gmx_MMPBSA with amber.python and also installed other dependencies as mentioned in program website. All path is set as instructed.

A clear and concise description of what the issue is.

**_If you will report an error, please complete this form_**
Installing collected packages: seaborn, mpi4py, gmx-MMPBSA
  WARNING: The scripts gmx_MMPBSA, gmx_MMPBSA_ana and gmx_MMPBSA_test are installed in '/home/ssinha/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed gmx-MMPBSA-1.4.3 mpi4py-3.0.3 seaborn-0.11.1

(base) ssinha@susi:~/Desktop$ gmx_MMPBSA
[INFO   ] Starting
[INFO   ] Command-line
  gmx_MMPBSA 

InputError: No input file was provided!
  Enter `gmx_MMPBSA --help` for help
(base) ssinha@susi:~/Desktop$ gmx_MMPBSA
gmx_MMPBSA       gmx_MMPBSA_ana   gmx_MMPBSA_test  
(base) ssinha@susi:~/Desktop$ gmx_MMPBSA
gmx_MMPBSA       gmx_MMPBSA_ana   gmx_MMPBSA_test  
(base) ssinha@susi:~/Desktop$ gmx_MMPBSA_test 
[INFO   ] Cloning gmx_MMPBSA repository in gmx_MMPBSA_test
Cloning into 'gmx_MMPBSA_test'...
remote: Enumerating objects: 6224, done.
remote: Counting objects: 100% (1581/1581), done.
remote: Compressing objects: 100% (527/527), done.
remote: Total 6224 (delta 1068), reused 1381 (delta 910), pack-reused 4643
Receiving objects: 100% (6224/6224), 255.69 MiB | 7.44 MiB/s, done.
Resolving deltas: 100% (4390/4390), done.
Updating files: 100% (364/364), done.
[INFO   ] Cloning gmx_MMPBSA repository...Done.
[INFO   ]                           Example                                STATE
--------------------------------------------------------------------------------
[INFO   ] Protein-Ligand (Single trajectory approximation)               RUNNING
[INFO   ] Protein-Protein                                                RUNNING
[INFO   ] Protein-Ligand (Single trajectory approximation)       [ 1/12]    DONE
[INFO   ] Protein-DNA                                                    RUNNING
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ssinha/amber20/miniconda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ssinha/.local/lib/python3.8/site-packages/GMXMMPBSA/tester.py", line 29, in calculatestar
    return run_process(*args)
  File "/home/ssinha/.local/lib/python3.8/site-packages/GMXMMPBSA/tester.py", line 33, in run_process
    os.chdir(system[0])
FileNotFoundError: [Errno 2] No such file or directory: 'gmx_MMPBSA_test/docs/examples/Protein_protein'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ssinha/.local/bin/gmx_MMPBSA_test", line 8, in <module>
    sys.exit(gmxmmpbsa_test())
  File "/home/ssinha/.local/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 146, in gmxmmpbsa_test
    run_test(parser)
  File "/home/ssinha/.local/lib/python3.8/site-packages/GMXMMPBSA/tester.py", line 132, in run_test
    for x in imap_unordered_it:
  File "/home/ssinha/amber20/miniconda/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'gmx_MMPBSA_test/docs/examples/Protein_protein'
**To Reproduce**
1. Which system type are you running? (Protein-Protein, Protein-Ligand, etc)
2. The command-line are you using.

Plz help

**Comment by Valdes-Tresanco-MS** [comment]
It is definitely a bug and is related to the definition of the examples folder path. The way to solve it without much effort is to define the path explicitly and absolutely, that is, you must define the full path (eg. `gmx_MMPBSA_test -f /home/mario/`). A relative path will end in an error similar to this (eg. `gmx_MMPBSA_test -f` [ `.` , `./Documents` , not define any path, etc])
We will solve it in the next release. Thank you for reported it

**Comment by ssinhachem** [comment]
Hi,
I could run the test. It passed. Thanks for the help.

Now for my own system, a protein-peptide one, I am getting error. I think I
am getting the error due to forcefield as I have run my simulations using
charmm36/charmm36m.
Please advise me how to change the mmpbsa.in file. Currently the default
mmpbsa.in file contains an expression "oldff/leaprc.ff99SB" in the
forcefield option.

Thanks,
Suman.

**Comment by Valdes-Tresanco-MS** [comment]
The error should not be related to the `forcefields` variable since this variable only applies when it comes to Amber's force fields. When the ff is CHARMM (any version), the generation of Amber's topologies is by conversion (You can check this information [here](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/howworks/)). 
Please attach the `gmx_MMPBSA.log` file or the Traceback shown in the terminal to be able to identify the error

**Comment by ssinhachem** [comment]
Hi,
I have restarted the calculation (not serial and not MPI as my current
gromacs 2020.2 is not an MPI version) with the given instructions for
charmmff in your website. It is running now without any errors.
So is it taking only one processor to do the calculations? My system is of
53765 atoms and I have taken 51 frames for mmpbsa calculation.
Approximately how much time it should take?

Thanks,
Suman.

**Comment by Valdes-Tresanco-MS** [comment]
No serial and not MPI? what do you mean?
`gmx_MMPBSA` is independent of GROMACS compilation. It works with MPI independently, which can significantly reduce computing time. You can see how to run it [here](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/command-line/#running-gmx_mmpbsa).
Example: ```mpirun -np 8 gmx_MMPBSA MPI -O ...```

It is difficult to know. Assuming that the 53765 atoms correspond to protein (the water molecules are not taken into account in the calculation since it is an implicit solvent, nor the ions) and using about 8 CPU it should take between 1-3 hours approximately

**Comment by ssinhachem** [comment]
The calculations were over by 40 minutes. But I am not getting neither the
IE nor the delta G-binding term, not showing in GMX-MMPBSA ana..So finally
what is the binding energy of this protein/peptide system?

Thanks,
Suman.

**Comment by Valdes-Tresanco-MS** [comment]
Did you define the `interaction_entropy = 1` or `entropy = 2` (deprecated) variable?
The ΔG binding is calculated only if some entropy term was defined.
You can modify the `_GMXMMPBSA_info` file (only the `interaction_entropy` variable) to calculate it with `gmx_MMPBSA_ana` without run the calculation again

If you only calculate the ΔG _effective_, this term is named `DELTA TOTAL` and correspond to the ΔH value

HTH!
Mario S.

**Comment by ssinhachem** [comment]
Just restarted with interaction_entropy = 1.

**Comment by Valdes-Tresanco-MS** [comment]
Note that the representation, as the value of the Interaction entropy contribution can vary with the number of frames. For more information, consult the [documentation](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/introduction/), where you can find related articles.
As the initial issue was solved, I will close it. Feel free to open another one if necessary. Also, consult our [group](https://groups.google.com/g/gmx_mmpbsa).

Best regards
Mario S.

**Comment by Valdes-Tresanco-MS** [comment]
Sorry, I completely forgot that the issue was related to `gmx_MMPBSA_test`.

To better track other types of bugs, please open a new issue.

**Comment by ssinhachem** [comment]
I am currently running a test system. I will update you.

Thanks,.
Suman.

**Comment by ssinhachem** [comment]
Hi,
The results are quite surprising. The DelG-binding comes in positive value.
The complex is a crystal structure and is supposed to be highly stable and
thus negative. I am pasting the results here:

Kindly let me know if I am missing something here.

...............................................................................................................................................
..............................................................................................................................................

| Run on Wed Jun 16 20:01:42 2021
|
|Input file:
|--------------------------------------------------------------
|Sample input file for PB calculation
|This input file is meant to show only that gmx_MMPBSA works. Althought,
|we tried to used the input files as recommended in the Amber manual,
|some parameters have been changed to perform more expensive calculations
|in a reasonable amount of time. Feel free to change the parameters
|according to what is better for your system.
|
|&general
|startframe=30, endframe=50, verbose=2, interaction_entropy = 1,
|/
|&pb
|# radiopt=0 is recommended which means using radii from the prmtop file
|# for both the PB calculation and for the NP calculation
|
|istrng=0.15, fillratio=4.0, radiopt=0
|/
|--------------------------------------------------------------
|gmx_MMPBSA Version=v1.4.3 based on MMPBSA.py v.16.0
|Complex topology file:           COM.prmtop
|Receptor topology file:          REC.prmtop
|Ligand topology file:            LIG.prmtop
|Initial mdcrd(s):                COM_traj_0.xtc
|
|Receptor mask:                  ":1-347"
|Ligand mask:                    ":348-386"
|
|Calculations performed using 21 complex frames.
|Interaction Entropy calculations performed using last 6 frames.
|Poisson Boltzmann calculations performed using internal PBSA solver in
sander.
|
|All units are reported in kcal/mole.
|All entropy results have units kcal/mol
(Temperature for NMODE and QH is 298.15 K)
(Temperature for IE is 298.15 K)

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
ENTROPY RESULTS (INTERACTION ENTROPY):
Entropy Term                Average              Std. Dev.   Std. Err. of
Mean
-------------------------------------------------------------------------------
IE                          57.5955                0.0550
 0.0224
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

POISSON BOLTZMANN:

Complex:
Energy Component            Average              Std. Dev.   Std. Err. of
Mean
-------------------------------------------------------------------------------
BOND                      1263.2076               31.7220
 6.9223
ANGLE                     3039.6469               50.9278
11.1134
DIHED                     3916.5078               22.7862
 4.9724
UB                         379.9472               10.7311
 2.3417
IMP                        213.9889                7.7140
 1.6833
CMAP                      -163.6825               12.3151
 2.6874
VDWAALS                  -2650.7345               19.9520
 4.3539
EEL                     -25887.2207               95.7047
20.8845
1-4 VDW                   1149.0130               13.5755
 2.9624
1-4 EEL                  18413.4966               56.4955
12.3283
EPB                      -4643.3859               81.5059
17.7860
ENPOLAR                   3012.9285                8.3984
 1.8327
EDISPER                  -1673.1287               11.8814
 2.5927

G gas                     -325.8297              123.5707
26.9653
G solv                   -3303.5861               85.6623
18.6930

TOTAL                    -3629.4158              100.7725
21.9904


Receptor:
Energy Component            Average              Std. Dev.   Std. Err. of
Mean
-------------------------------------------------------------------------------
BOND                      1144.8716               29.8224
 6.5078
ANGLE                     2744.1276               46.1043
10.0608
DIHED                     3583.1902               21.9916
 4.7990
UB                         344.2304               10.7252
 2.3404
IMP                        193.6893                8.5836
 1.8731
CMAP                      -161.1233               11.6012
 2.5316
VDWAALS                  -2343.8451               17.8744
 3.9005
EEL                     -23297.4376               76.3510
16.6612
1-4 VDW                   1065.3130               13.4171
 2.9279
1-4 EEL                  16517.8633               52.2190
11.3951
EPB                      -4458.6220               65.8003
14.3588
ENPOLAR                   2776.5318                7.3051
 1.5941
EDISPER                  -1606.3771                9.8293
 2.1449

G gas                     -209.1206              105.2649
22.9707
G solv                   -3288.4673               68.0261
14.8445

TOTAL                    -3497.5879               93.4050
20.3826


Ligand:
Energy Component            Average              Std. Dev.   Std. Err. of
Mean
-------------------------------------------------------------------------------
BOND                       118.3359                5.3979
 1.1779
ANGLE                      295.5193               13.5738
 2.9620
DIHED                      333.3175                6.8565
 1.4962
UB                          35.7168                2.0342
 0.4439
IMP                         20.2996                3.2170
 0.7020
CMAP                        -2.5592                5.6748
 1.2383
VDWAALS                   -139.1172                4.1061
 0.8960
EEL                      -2269.4737               35.5773
 7.7636
1-4 VDW                     83.7000                3.9234
 0.8562
1-4 EEL                   1895.6333               27.2963
 5.9565
EPB                       -554.4901               17.1292
 3.7379
ENPOLAR                    363.5139                2.4338
 0.5311
EDISPER                   -298.9073                2.1147
 0.4615

G gas                      371.3723               27.1934
 5.9341
G solv                    -489.8835               17.1117
 3.7341

TOTAL                     -118.5112               18.1647
 3.9639


Differences (Complex - Receptor - Ligand):
Energy Component            Average              Std. Dev.   Std. Err. of
Mean
-------------------------------------------------------------------------------
BOND                         0.0000                0.0000
 0.0000
ANGLE                        0.0000                0.0001
 0.0000
DIHED                       -0.0000                0.0001
 0.0000
UB                          -0.0000                0.0001
 0.0000
IMP                          0.0000                0.0001
 0.0000
CMAP                        -0.0000                0.0001
 0.0000
VDWAALS                   -167.7721                4.8959
 1.0684
EEL                       -320.3093               28.3678
 6.1904
1-4 VDW                      0.0000                0.0001
 0.0000
1-4 EEL                      0.0000                0.0000
 0.0000
EPB                        369.7262               23.8134
 5.1965
ENPOLAR                   -127.1172                3.8182
 0.8332
EDISPER                    232.1557                5.2522
 1.1461

DELTA G gas               -488.0814               28.4023
 6.1979
DELTA G solv               474.7647               25.0049
 5.4565

DELTA TOTAL                -13.3167                9.8082
 2.1403


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Using Interaction Entropy Approximation:





DELTA G binding =   44.2788 +/-  9.8084
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

**Comment by marioernestovaldes** [comment]
Hello there! there are few things that I would like to point out about your results.

1- first thing first, gmx_MMPBSA works (which means it can process your files and give you a result). Now it's time to see what could be going wrong
2- I see you are using PB with inp=2 with gives you a high positive energy value for the desolvation. We have observed this before. You might want to check this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/Q%26A/calculations/#possible-solutions_2)
3- It is recommended to use restraints when using the Interaction Entropy method since a large variation in the internal energy can give you high entropy values. See this [paper](https://pubs.acs.org/doi/abs/10.1021/jacs.6b02682)

hope this helps!

Mario E
