### ISSUE TITLE
[Question]: list index out of range error? 

### ISSUE THREAD

**Issue by Baluxy** [Valdes-Tresanco-MS/gmx_MMPBSA#461]
### My Question is...

Hi, I have encountered this problem by trying to calculate deltaG between chains of my dimer. 

[INFO   ] Starting gmx_MMPBSA v1.6.2+32.g2fdf1bc
[INFO   ] Command-line
  mpirun -np 1 gmx_MMPBSA MPI -O -nogui -i protein-protein_mmpbsa.in -cs ../md_pbc_reduced.pdb -cp ../setup/system.top -ci ../groups.ndx -cg 18 19 -ct ../md_pbc_reduced_0.1ns.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv -do FINAL_DECOMP_MMPBSA.dat -deo FINAL_DECOMP_MMPBSA.csv

[INFO   ] Checking protein-protein_mmpbsa.in input file...
[WARNING] &decomp namelist has not been defined in the input file. Ignoring '-deo' flag...
[INFO   ] Checking protein-protein_mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /p/software/jurecadc/stages/2020/software/GROMACS/2020.4-gpsmkl-2021/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group chainA_chainB (18_19) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group chainA (18) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group chainB (19) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 681, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 124, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 565, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 854, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 251, in __init__
    self.read(fname, defines, parametrize)
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 367, in read
    b, bt = self._parse_vsites3(line, molecule.atoms, params)
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 687, in _parse_vsites3
    a, b = float(words[5]), float(words[6])
IndexError: list index out of range
Exiting. All files have been retained.

Is there a way to fix this?

**Comment by marioernestovaldes** [comment]
Could you please share the files you are using?

**Comment by Baluxy** [comment]
Here are the files I used as input:

https://uni-duesseldorf.sciebo.de/s/o244G7Hjh3issiL

Thanks for your help!

Am 2024-02-19 18:06, schrieb Mario E. Valdés-Tresanco:

**Comment by marioernestovaldes** [comment]
delete everything related to virtual_sites in the topology files and it should be ok... these parameters in the topology has no impact on MMPB/GB/SA calculations

**Comment by Baluxy** [comment]
Unfortunately, there is still this calculation error: 

[INFO   ] Starting gmx_MMPBSA v1.6.2+32.g2fdf1bc
[INFO   ] Command-line
  mpirun -np 1 gmx_MMPBSA MPI -O -nogui -i protein-protein_mmpbsa.in -cs ../md_pbc_reduced.pdb -cp ../setup/system.top -ci ../groups.ndx -cg 18 19 -ct ../md_pbc_reduced_0.1ns.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv -do FINAL_DECOMP_MMPBSA.dat -deo FINAL_DECOMP_MMPBSA.csv

[INFO   ] Checking protein-protein_mmpbsa.in input file...
[WARNING] &decomp namelist has not been defined in the input file. Ignoring '-deo' flag...
[INFO   ] Checking protein-protein_mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /p/software/jurecadc/stages/2020/software/GROMACS/2020.4-gpsmkl-2021/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group chainA_chainB (18_19) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group chainA (18) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group chainB (19) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected Amber/OPLS force field topology format...
[INFO   ] Assigning PBRadii mbondi2 to Complex...
[INFO   ] Writing Normal Complex AMBER topology...
[INFO   ] No Receptor topology file was defined. Using ST approach...
[INFO   ] Building AMBER Receptor topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Receptor...
[INFO   ] Writing Normal Receptor AMBER topology...
[INFO   ] No Ligand topology file was defined. Using ST approach...
[INFO   ] Building AMBER Ligand topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Ligand...
[INFO   ] Writing Normal Ligand AMBER topology...
[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...

[INFO   ] 10 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 1 CPUs...

[INFO   ] Running calculations on normal system...
[INFO   ] Beginning GB calculations with /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ]   calculating complex contribution...
^M              0%|          | 0/10 [elapsed: 00:00 remaining: ?]  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.run_mmpbsa()
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 205, in run_mmpbsa
    self.calc_list.run(rank, self.stdout)
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 142, in run
    calc.run(rank, stdout=stdout, stderr=stderr)
  File "/p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 284, in run
    raise CalcError(f'{self.program} failed with prmtop {self.prmtop}!')
CalcError: /p/project/cics-6/bastian/software/miniconda3/envs/gmxMMPBSA/bin/sander failed with prmtop COM.prmtop!
Exiting. All files have been retained.

**Comment by marioernestovaldes** [comment]
Unfortunately, your system is prepared using vsites and sander can't handle force fields with "extra-points". At the moment there is nothing we can do about this...

```
Cannot use igb>0 with extra-point force fields

 *** input error(s)
```

sorry for the inconvenience...

**Comment by Baluxy** [comment]
This problem can be fixed by creating new .xtc and .pdb files using gmx trjconv with prot-masses (10) cutting out the virtual site and then generating new .itp files with the pdb2gmx command. Also, a new .ndx file is needed.
