### ISSUE TITLE
gmx_MMPBSA: Protein-ligand free energy calculation error

### ISSUE THREAD

**Issue by sajqazi** [Valdes-Tresanco-MS/gmx_MMPBSA#462]
### Bug summary

Running the following command for using "Prot-Lig-CHARMM" system mmpbsa.in file

gmx_MMPBSA -O -i mmpbsa.in -cs MD.tpr -ci index.ndx -cg 1 13 -ct md_fit.xtc -cp topol.top

but didn't successfully run.
###########################
I tested the above command for other receptor-ligand complexes and it's working well. 
Facing a problem with a new complex in the gmx_mmpbsa calculation.
############################

### Terminal output

```bash
gmx_MMPBSA -O -i mmpbsa.in -cs MD.tpr -ci index.ndx -cg 1 13 -ct md_fit.xtc -cp topol.top
[INFO   ] Starting gmx_MMPBSA v1.6.2
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs MD.tpr -ci index.ndx -cg 1 13 -ct md_fit.xtc -cp topol.top

tets
[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/qms/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/qms/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/qms/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/qms/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group Protein_LIG (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group LIG (13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
  File "/home/qms/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/qms/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/qms/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 682, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/qms/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 125, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/qms/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 555, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/home/qms/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 843, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/home/qms/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 251, in __init__
    self.read(fname, defines, parametrize)
  File "/home/qms/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 341, in read
    cmap = self._parse_cmaps(line, molecule.atoms)
  File "/home/qms/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 644, in _parse_cmaps
    i, j, k, l, m = (int(w)-1 for w in words[:5])
  File "/home/qms/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 644, in <genexpr>
    i, j, k, l, m = (int(w)-1 for w in words[:5])
ValueError: invalid literal for int() with base 10: '#ifdef'
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

[INFO   ] Starting gmx_MMPBSA v1.6.2
[DEBUG  ] WDIR          : /home/qms/Desktop/new_compound
[DEBUG  ] AMBERHOME     : /home/qms/miniconda3/envs/gmxMMPBSA
[DEBUG  ] PYTHON EXE    : /home/qms/miniconda3/envs/gmxMMPBSA/bin/python
[DEBUG  ] PYTHON VERSION: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) [GCC 10.4.0]
[DEBUG  ] MPI           : /home/qms/miniconda3/envs/gmxMMPBSA/bin/mpirun
[DEBUG  ] ParmEd        : 3.4.4
[DEBUG  ] OS PLATFORM   : Linux-6.5.0-18-generic-x86_64-with-glibc2.35
[DEBUG  ] OS SYSTEM     : Linux
[DEBUG  ] OS VERSION    : #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2
[DEBUG  ] OS PROCESSOR  : x86_64

[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs MD.tpr -ci index.ndx -cg 1 13 -ct md_fit.xtc -cp topol.top

[DEBUG  ] |Input file:
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] |Sample input file for PB calculation
[DEBUG  ] |This input file is meant to show only that gmx_MMPBSA works. Although, we tried to use the input files as recommended
[DEBUG  ] |in the Amber manual, some parameters have been changed to perform more expensive calculations in a reasonable amount of time. Feel free to change the
[DEBUG  ] |parameters according to what is better for your system.
[DEBUG  ] |
[DEBUG  ] |&general
[DEBUG  ] |sys_name="Prot-Lig-CHARMM",
[DEBUG  ] |startframe=1,
[DEBUG  ] |endframe=4,
[DEBUG  ] |# In gmx_MMPBSA v1.5.0 we have added a new PB radii set named charmm_radii. This radii set should be used only
[DEBUG  ] |# with systems prepared with CHARMM force fields. Uncomment the line below to use charmm_radii set
[DEBUG  ] |#PBRadii=7,
[DEBUG  ] |/
[DEBUG  ] |&pb
[DEBUG  ] |# radiopt=0 is recommended which means using radii from the prmtop file for both the PB calculation and for the NP
[DEBUG  ] |# calculation
[DEBUG  ] |istrng=0.15, fillratio=4.0, radiopt=0
[DEBUG  ] |/--------------------------------------------------------------
[DEBUG  ] 
[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/qms/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/qms/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/qms/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/qms/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[DEBUG  ] Running command: echo -e "name 1 GMXMMPBSA_REC\n name 13 GMXMMPBSA_LIG\n  1 | 13\n q\n" | /usr/local/gromacs/bin/gmx make_ndx -n index.ndx -o _GMXMMPBSA_COM_index.ndx -f MD.tpr
[DEBUG  ]                       :-) GROMACS - gmx make_ndx, 2024 (-:
[DEBUG  ] 
[DEBUG  ] Executable:   /usr/local/gromacs/bin/gmx
[DEBUG  ] Data prefix:  /usr/local/gromacs
[DEBUG  ] Working dir:  /home/qms/Desktop/new_compound
[DEBUG  ] Command line:
[DEBUG  ]   gmx make_ndx -n index.ndx -o _GMXMMPBSA_COM_index.ndx -f MD.tpr
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] Reading structure file
[DEBUG  ] Reading file MD.tpr, VERSION 2024 (single precision)
[DEBUG  ] Reading file MD.tpr, VERSION 2024 (single precision)
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "She's Not Bad, She's Just Genetically Mean" (Captain Beefheart)
[DEBUG  ] 
[DEBUG  ] Going to read 1 old index file(s)
[DEBUG  ] 
[DEBUG  ]   0 System              : 35025 atoms
[DEBUG  ]   1 Protein             :  3998 atoms
[DEBUG  ]   2 Protein-H           :  1991 atoms
[DEBUG  ]   3 C-alpha             :   267 atoms
[DEBUG  ]   4 Backbone            :   802 atoms
[DEBUG  ]   5 MainChain           :  1069 atoms
[DEBUG  ]   6 MainChain+Cb        :  1308 atoms
[DEBUG  ]   7 MainChain+H         :  1323 atoms
[DEBUG  ]   8 SideChain           :  2675 atoms
[DEBUG  ]   9 SideChain-H         :   922 atoms
[DEBUG  ]  10 Prot-Masses         :  3998 atoms
[DEBUG  ]  11 non-Protein         : 31027 atoms
[DEBUG  ]  12 Other               :    84 atoms
[DEBUG  ]  13 LIG                 :    84 atoms
[DEBUG  ]  14 NA                  :    27 atoms
[DEBUG  ]  15 CL                  :    22 atoms
[DEBUG  ]  16 Water               : 30894 atoms
[DEBUG  ]  17 SOL                 : 30894 atoms
[DEBUG  ]  18 non-Water           :  4131 atoms
[DEBUG  ]  19 Ion                 :    49 atoms
[DEBUG  ]  20 Water_and_ions      : 30943 atoms
[DEBUG  ]  21 Protein_LIG         :  4082 atoms
[DEBUG  ] 
[DEBUG  ]  nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
[DEBUG  ]  'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
[DEBUG  ]  't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
[DEBUG  ]  'r': residue              'res' nr         'chain' char
[DEBUG  ]  "name": group             'case': case sensitive           'q': save and quit
[DEBUG  ]  'ri': residue index
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] Copied index group 1 'GMXMMPBSA_REC'
[DEBUG  ] Copied index group 13 'GMXMMPBSA_LIG'
[DEBUG  ] Merged two groups with OR: 3998 84 -> 4082
[DEBUG  ] 
[DEBUG  ] > 
[INFO   ] Normal Complex: Saving group Protein_LIG (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[DEBUG  ] Running command: echo -e "GMXMMPBSA_REC_GMXMMPBSA_LIG"| /usr/local/gromacs/bin/gmx trjconv -f md_fit.xtc -s MD.tpr -o _GMXMMPBSA_COM.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ]                       :-) GROMACS - gmx trjconv, 2024 (-:
[DEBUG  ] 
[DEBUG  ] Executable:   /usr/local/gromacs/bin/gmx
[DEBUG  ] Data prefix:  /usr/local/gromacs
[DEBUG  ] Working dir:  /home/qms/Desktop/new_compound
[DEBUG  ] Command line:
[DEBUG  ]   gmx trjconv -f md_fit.xtc -s MD.tpr -o _GMXMMPBSA_COM.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ] 
[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file MD.tpr, VERSION 2024 (single precision)
[DEBUG  ] Reading file MD.tpr, VERSION 2024 (single precision)
[DEBUG  ] Group     0 (         System) has 35025 elements
[DEBUG  ] Group     1 (  GMXMMPBSA_REC) has  3998 elements
[DEBUG  ] Group     2 (      Protein-H) has  1991 elements
[DEBUG  ] Group     3 (        C-alpha) has   267 elements
[DEBUG  ] Group     4 (       Backbone) has   802 elements
[DEBUG  ] Group     5 (      MainChain) has  1069 elements
[DEBUG  ] Group     6 (   MainChain+Cb) has  1308 elements
[DEBUG  ] Group     7 (    MainChain+H) has  1323 elements
[DEBUG  ] Group     8 (      SideChain) has  2675 elements
[DEBUG  ] Group     9 (    SideChain-H) has   922 elements
[DEBUG  ] Group    10 (    Prot-Masses) has  3998 elements
[DEBUG  ] Group    11 (    non-Protein) has 31027 elements
[DEBUG  ] Group    12 (          Other) has    84 elements
[DEBUG  ] Group    13 (  GMXMMPBSA_LIG) has    84 elements
[DEBUG  ] Group    14 (             NA) has    27 elements
[DEBUG  ] Group    15 (             CL) has    22 elements
[DEBUG  ] Group    16 (          Water) has 30894 elements
[DEBUG  ] Group    17 (            SOL) has 30894 elements
[DEBUG  ] Group    18 (      non-Water) has  4131 elements
[DEBUG  ] Group    19 (            Ion) has    49 elements
[DEBUG  ] Group    20 ( Water_and_ions) has 30943 elements
[DEBUG  ] Group    21 (    Protein_LIG) has  4082 elements
[DEBUG  ] Group    22 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4082 elements
[DEBUG  ] Select a group: 
Reading frame       0 time    0.000   
[DEBUG  ] Precision of md_fit.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time   10.000   
[DEBUG  ] Dumping frame at t= 0 ps
[DEBUG  ] Last written: frame      0 time    0.000
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "She's Not Bad, She's Just Genetically Mean" (Captain Beefheart)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 22: 'GMXMMPBSA_REC_GMXMMPBSA_LIG'
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[DEBUG  ] Running command: echo -e "1"| /usr/local/gromacs/bin/gmx trjconv -f md_fit.xtc -s MD.tpr -o _GMXMMPBSA_REC.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ]                       :-) GROMACS - gmx trjconv, 2024 (-:
[DEBUG  ] 
[DEBUG  ] Executable:   /usr/local/gromacs/bin/gmx
[DEBUG  ] Data prefix:  /usr/local/gromacs
[DEBUG  ] Working dir:  /home/qms/Desktop/new_compound
[DEBUG  ] Command line:
[DEBUG  ]   gmx trjconv -f md_fit.xtc -s MD.tpr -o _GMXMMPBSA_REC.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ] 
[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file MD.tpr, VERSION 2024 (single precision)
[DEBUG  ] Reading file MD.tpr, VERSION 2024 (single precision)
[DEBUG  ] Group     0 (         System) has 35025 elements
[DEBUG  ] Group     1 (  GMXMMPBSA_REC) has  3998 elements
[DEBUG  ] Group     2 (      Protein-H) has  1991 elements
[DEBUG  ] Group     3 (        C-alpha) has   267 elements
[DEBUG  ] Group     4 (       Backbone) has   802 elements
[DEBUG  ] Group     5 (      MainChain) has  1069 elements
[DEBUG  ] Group     6 (   MainChain+Cb) has  1308 elements
[DEBUG  ] Group     7 (    MainChain+H) has  1323 elements
[DEBUG  ] Group     8 (      SideChain) has  2675 elements
[DEBUG  ] Group     9 (    SideChain-H) has   922 elements
[DEBUG  ] Group    10 (    Prot-Masses) has  3998 elements
[DEBUG  ] Group    11 (    non-Protein) has 31027 elements
[DEBUG  ] Group    12 (          Other) has    84 elements
[DEBUG  ] Group    13 (  GMXMMPBSA_LIG) has    84 elements
[DEBUG  ] Group    14 (             NA) has    27 elements
[DEBUG  ] Group    15 (             CL) has    22 elements
[DEBUG  ] Group    16 (          Water) has 30894 elements
[DEBUG  ] Group    17 (            SOL) has 30894 elements
[DEBUG  ] Group    18 (      non-Water) has  4131 elements
[DEBUG  ] Group    19 (            Ion) has    49 elements
[DEBUG  ] Group    20 ( Water_and_ions) has 30943 elements
[DEBUG  ] Group    21 (    Protein_LIG) has  4082 elements
[DEBUG  ] Group    22 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4082 elements
[DEBUG  ] Select a group: 
Reading frame       0 time    0.000   
[DEBUG  ] Precision of md_fit.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time   10.000   
[DEBUG  ] Dumping frame at t= 0 ps
[DEBUG  ] Last written: frame      0 time    0.000
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "She's Not Bad, She's Just Genetically Mean" (Captain Beefheart)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 1: 'GMXMMPBSA_REC'
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group LIG (13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[DEBUG  ] Running command: echo -e "13"| /usr/local/gromacs/bin/gmx trjconv -f md_fit.xtc -s MD.tpr -o _GMXMMPBSA_LIG.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ]                       :-) GROMACS - gmx trjconv, 2024 (-:
[DEBUG  ] 
[DEBUG  ] Executable:   /usr/local/gromacs/bin/gmx
[DEBUG  ] Data prefix:  /usr/local/gromacs
[DEBUG  ] Working dir:  /home/qms/Desktop/new_compound
[DEBUG  ] Command line:
[DEBUG  ]   gmx trjconv -f md_fit.xtc -s MD.tpr -o _GMXMMPBSA_LIG.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ] 
[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file MD.tpr, VERSION 2024 (single precision)
[DEBUG  ] Reading file MD.tpr, VERSION 2024 (single precision)
[DEBUG  ] Group     0 (         System) has 35025 elements
[DEBUG  ] Group     1 (  GMXMMPBSA_REC) has  3998 elements
[DEBUG  ] Group     2 (      Protein-H) has  1991 elements
[DEBUG  ] Group     3 (        C-alpha) has   267 elements
[DEBUG  ] Group     4 (       Backbone) has   802 elements
[DEBUG  ] Group     5 (      MainChain) has  1069 elements
[DEBUG  ] Group     6 (   MainChain+Cb) has  1308 elements
[DEBUG  ] Group     7 (    MainChain+H) has  1323 elements
[DEBUG  ] Group     8 (      SideChain) has  2675 elements
[DEBUG  ] Group     9 (    SideChain-H) has   922 elements
[DEBUG  ] Group    10 (    Prot-Masses) has  3998 elements
[DEBUG  ] Group    11 (    non-Protein) has 31027 elements
[DEBUG  ] Group    12 (          Other) has    84 elements
[DEBUG  ] Group    13 (  GMXMMPBSA_LIG) has    84 elements
[DEBUG  ] Group    14 (             NA) has    27 elements
[DEBUG  ] Group    15 (             CL) has    22 elements
[DEBUG  ] Group    16 (          Water) has 30894 elements
[DEBUG  ] Group    17 (            SOL) has 30894 elements
[DEBUG  ] Group    18 (      non-Water) has  4131 elements
[DEBUG  ] Group    19 (            Ion) has    49 elements
[DEBUG  ] Group    20 ( Water_and_ions) has 30943 elements
[DEBUG  ] Group    21 (    Protein_LIG) has  4082 elements
[DEBUG  ] Group    22 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has  4082 elements
[DEBUG  ] Select a group: 
Reading frame       0 time    0.000   
[DEBUG  ] Precision of md_fit.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time   10.000   
[DEBUG  ] Dumping frame at t= 0 ps
[DEBUG  ] Last written: frame      0 time    0.000
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "She's Not Bad, She's Just Genetically Mean" (Captain Beefheart)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 13: 'GMXMMPBSA_LIG'
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...

### Operating system

Ubuntu 22.04.3 LTS

### gmx_MMPBSA Version

gmx_MMPBSA v1.6.2 based on MMPBSA version 16.0 and AmberTools 20

### Python version

Python 3.9.15

### Installation

from source (.tar.gz)

**Comment by marioernestovaldes** [comment]
Seems like an issue with the topology format... Could you please share the topology files you are using

**Comment by marioernestovaldes** [comment]
please attach the LIG.itp file

**Comment by sajqazi** [comment]
[lig file.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/14339547/lig.file.zip)

**Comment by marioernestovaldes** [comment]
in topol.top file, lines 37757-37759 are indented and they shouldn't be:

```
; Ligand position restraints
		#ifdef POSRES
		#include "posre_LIG.itp"
		#endif
```

should be something like this:

```
; Ligand position restraints
#ifdef POSRES
#include "posre_LIG.itp"
#endif
```

let me know if that solves the issue...

**Comment by sajqazi** [comment]
Thanks for your quick support. It's running now...
