### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by kratos1459** [Valdes-Tresanco-MS/gmx_MMPBSA#463]
gmx_MMPBSA -O -i mmpbsa.in -cs MD.tpr -ct traj_comp.xtc -ci index.ndx -cg 3 4 -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv
hwloc/linux: Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
[INFO   ] Starting gmx_MMPBSA v1.6.1
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs MD.tpr -ct traj_comp.xtc -ci index.ndx -cg 3 4 -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

tets
[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/arian/miniconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/arian/miniconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/arian/miniconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/arian/miniconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] mmpbsa_py_nabnmode found! Using /home/arian/miniconda3/envs/gmxMMPBSA/bin/mmpbsa_py_nabnmode
[INFO   ] gbnsr6 found! Using /home/arian/miniconda3/envs/gmxMMPBSA/bin/gbnsr6
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group C-alpha_Backbone (3_4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group C-alpha (3) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group Backbone (4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
  File "/home/arian/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/arian/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/arian/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 687, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/arian/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 123, in buildTopology
    self.gmx2pdb()
  File "/home/arian/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 492, in gmx2pdb
    self.resi, self.resl, self.orderl = res2map(self.indexes, self.complex_str)
  File "/home/arian/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/utils.py", line 601, in res2map
    for e in value['num']:
TypeError: string indices must be integers
Exiting. All files have been retained.
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/14379410/gmx_MMPBSA.log)

**Comment by Valdes-Tresanco-MS** [comment]
As you can see in the error, you are selecting the wrong groups (C-alpha and Backbone). Please check your index file to select the appropriate groups. Probably the groups are 1 (Protein) and 13 (Ligand or any name assigned in the MD preparation)
