### ISSUE TITLE
[Bug-gmx_MMPBSA]: TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by allanlinzhang** [Valdes-Tresanco-MS/gmx_MMPBSA#469]
### Bug summary

When I run gmx_mmpbsa, some error occurs. 

### Terminal output

```bash
File "/lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
             ^^^^^^^^^^^
  File "/lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/lib/python3.11/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/lib/python3.11/site-packages/GMXMMPBSA/main.py", line 681, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/lib/python3.11/site-packages/GMXMMPBSA/make_top.py", line 122, in buildTopology
    self.gmx2pdb()
  File "/lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/lib/python3.11/site-packages/GMXMMPBSA/make_top.py", line 523, in gmx2pdb
    self.resi, self.resl, self.orderl = res2map(self.indexes, self.complex_str)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/lib/python3.11/site-packages/GMXMMPBSA/utils.py", line 600, in res2map
    for e in value['num']:
             ~~~~~^^^^^^^
TypeError: string indices must be integers, not 'str'
```

### gmx_MMPBSA.log

[INFO   ] Starting gmx_MMPBSA v1.6.3
[DEBUG  ] WDIR          : /lustre/user/lulab/lulabrotation/zhanglin/MkPX/application/clade1/mmpbsa
[DEBUG  ] AMBERHOME     : /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs
[DEBUG  ] PYTHON EXE    : /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin/python
[DEBUG  ] PYTHON VERSION: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
[DEBUG  ] MPI           : None
[DEBUG  ] ParmEd        : 4.2.2
[DEBUG  ] OS PLATFORM   : Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
[DEBUG  ] OS SYSTEM     : Linux
[DEBUG  ] OS VERSION    : #1 SMP Thu Nov 8 23:39:32 UTC 2018
[DEBUG  ] OS PROCESSOR  : x86_64

[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs md_0_1.tpr -ct trj_10-20ns.xtc -ci mmpbsa_index.ndx -cg 3 4 -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[DEBUG  ] |Input file:
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] |Sample input file for GB calculation
[DEBUG  ] |This input file is meant to show only that gmx_MMPBSA works. Althought,
[DEBUG  ] |we tried to used the input files as recommended in the Amber manual,
[DEBUG  ] |some parameters have been changed to perform more expensive calculations
[DEBUG  ] |in a reasonable amount of time. Feel free to change the parameters 
[DEBUG  ] |according to what is better for your system.
[DEBUG  ] |
[DEBUG  ] |&general
[DEBUG  ] |sys_name="Prot-Prot",
[DEBUG  ] |startframe=1,
[DEBUG  ] |endframe=10,
[DEBUG  ] |forcefields="leaprc.protein.ff14SB",
[DEBUG  ] |/
[DEBUG  ] |&gb
[DEBUG  ] |igb=2, saltcon=0.150,
[DEBUG  ] |/
[DEBUG  ] |
[DEBUG  ] |--------------------------------------------------------------
[DEBUG  ] 
[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin/cpptraj
[INFO   ] tleap found! Using /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin/tleap
[INFO   ] parmchk2 found! Using /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin/parmchk2
[INFO   ] sander found! Using /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin.AVX2_256/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[DEBUG  ] Running command: echo -e "name 3 GMXMMPBSA_REC\n name 4 GMXMMPBSA_LIG\n  3 | 4\n q\n" | /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin.AVX2_256/gmx make_ndx -n mmpbsa_index.ndx -o _GMXMMPBSA_COM_index.ndx -f md_0_1.tpr
[DEBUG  ]                :-) GROMACS - gmx make_ndx, 2023.4-conda_forge (-:
[DEBUG  ] 
[DEBUG  ] Executable:   /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin.AVX2_256/gmx
[DEBUG  ] Data prefix:  /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs
[DEBUG  ] Working dir:  /lustre/user/lulab/lulabrotation/zhanglin/MkPX/application/clade1/mmpbsa
[DEBUG  ] Command line:
[DEBUG  ]   gmx make_ndx -n mmpbsa_index.ndx -o _GMXMMPBSA_COM_index.ndx -f md_0_1.tpr
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] Reading structure file
[DEBUG  ] Reading file md_0_1.tpr, VERSION 2023.4-conda_forge (single precision)
[DEBUG  ] Reading file md_0_1.tpr, VERSION 2023.4-conda_forge (single precision)
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "Discovery: A couple of months in the laboratory can frequently save a couple of hours in the library." (Anonymous)
[DEBUG  ] 
[DEBUG  ] Going to read 1 old index file(s)
[DEBUG  ] 
[DEBUG  ]   0 System              : 556429 atoms
[DEBUG  ]   1 Protein             :  5314 atoms
[DEBUG  ]   2 Protein-H           :  2664 atoms
[DEBUG  ]   3 C-alpha             :   330 atoms
[DEBUG  ]   4 Backbone            :   990 atoms
[DEBUG  ]   5 MainChain           :  1322 atoms
[DEBUG  ]   6 MainChain+Cb        :  1639 atoms
[DEBUG  ]   7 MainChain+H         :  1639 atoms
[DEBUG  ]   8 SideChain           :  3675 atoms
[DEBUG  ]   9 SideChain-H         :  1342 atoms
[DEBUG  ]  10 Prot-Masses         :  5314 atoms
[DEBUG  ]  11 non-Protein         : 551115 atoms
[DEBUG  ]  12 Water               : 551115 atoms
[DEBUG  ]  13 SOL                 : 551115 atoms
[DEBUG  ]  14 non-Water           :  5314 atoms
[DEBUG  ] 
[DEBUG  ]  nr : group      '!': not  'name' nr name   'splitch' nr    Enter: list groups
[DEBUG  ]  'a': atom       '&': and  'del' nr         'splitres' nr   'l': list residues
[DEBUG  ]  't': atom type  '|': or   'keep' nr        'splitat' nr    'h': help
[DEBUG  ]  'r': residue              'res' nr         'chain' char
[DEBUG  ]  "name": group             'case': case sensitive           'q': save and quit
[DEBUG  ]  'ri': residue index
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] 
[DEBUG  ] > 
[DEBUG  ] Copied index group 3 'GMXMMPBSA_REC'
[DEBUG  ] Copied index group 4 'GMXMMPBSA_LIG'
[DEBUG  ] Merged two groups with OR: 330 990 -> 990
[DEBUG  ] 
[DEBUG  ] > 
[INFO   ] Normal Complex: Saving group C-alpha_Backbone (3_4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[DEBUG  ] Running command: echo -e "GMXMMPBSA_REC_GMXMMPBSA_LIG"| /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin.AVX2_256/gmx trjconv -f trj_10-20ns.xtc -s md_0_1.tpr -o _GMXMMPBSA_COM.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ]                :-) GROMACS - gmx trjconv, 2023.4-conda_forge (-:
[DEBUG  ] 
[DEBUG  ] Executable:   /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin.AVX2_256/gmx
[DEBUG  ] Data prefix:  /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs
[DEBUG  ] Working dir:  /lustre/user/lulab/lulabrotation/zhanglin/MkPX/application/clade1/mmpbsa
[DEBUG  ] Command line:
[DEBUG  ]   gmx trjconv -f trj_10-20ns.xtc -s md_0_1.tpr -o _GMXMMPBSA_COM.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ] 
[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file md_0_1.tpr, VERSION 2023.4-conda_forge (single precision)
[DEBUG  ] Reading file md_0_1.tpr, VERSION 2023.4-conda_forge (single precision)
[DEBUG  ] Group     0 (         System) has 556429 elements
[DEBUG  ] Group     1 (        Protein) has  5314 elements
[DEBUG  ] Group     2 (      Protein-H) has  2664 elements
[DEBUG  ] Group     3 (  GMXMMPBSA_REC) has   330 elements
[DEBUG  ] Group     4 (  GMXMMPBSA_LIG) has   990 elements
[DEBUG  ] Group     5 (      MainChain) has  1322 elements
[DEBUG  ] Group     6 (   MainChain+Cb) has  1639 elements
[DEBUG  ] Group     7 (    MainChain+H) has  1639 elements
[DEBUG  ] Group     8 (      SideChain) has  3675 elements
[DEBUG  ] Group     9 (    SideChain-H) has  1342 elements
[DEBUG  ] Group    10 (    Prot-Masses) has  5314 elements
[DEBUG  ] Group    11 (    non-Protein) has 551115 elements
[DEBUG  ] Group    12 (          Water) has 551115 elements
[DEBUG  ] Group    13 (            SOL) has 551115 elements
[DEBUG  ] Group    14 (      non-Water) has  5314 elements
[DEBUG  ] Group    15 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has   990 elements
[DEBUG  ] Select a group: 
Reading frame       0 time 10000.000   
[DEBUG  ] Precision of trj_10-20ns.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time 10010.000   
[DEBUG  ] Dumping frame at t= 10000 ps
[DEBUG  ] Last written: frame      0 time 10000.000
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "Science grows like a weed every year." (Kary Mullis)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 15: 'GMXMMPBSA_REC_GMXMMPBSA_LIG'
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group C-alpha (3) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[DEBUG  ] Running command: echo -e "3"| /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin.AVX2_256/gmx trjconv -f trj_10-20ns.xtc -s md_0_1.tpr -o _GMXMMPBSA_REC.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ]                :-) GROMACS - gmx trjconv, 2023.4-conda_forge (-:
[DEBUG  ] 
[DEBUG  ] Executable:   /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin.AVX2_256/gmx
[DEBUG  ] Data prefix:  /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs
[DEBUG  ] Working dir:  /lustre/user/lulab/lulabrotation/zhanglin/MkPX/application/clade1/mmpbsa
[DEBUG  ] Command line:
[DEBUG  ]   gmx trjconv -f trj_10-20ns.xtc -s md_0_1.tpr -o _GMXMMPBSA_REC.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ] 
[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file md_0_1.tpr, VERSION 2023.4-conda_forge (single precision)
[DEBUG  ] Reading file md_0_1.tpr, VERSION 2023.4-conda_forge (single precision)
[DEBUG  ] Group     0 (         System) has 556429 elements
[DEBUG  ] Group     1 (        Protein) has  5314 elements
[DEBUG  ] Group     2 (      Protein-H) has  2664 elements
[DEBUG  ] Group     3 (  GMXMMPBSA_REC) has   330 elements
[DEBUG  ] Group     4 (  GMXMMPBSA_LIG) has   990 elements
[DEBUG  ] Group     5 (      MainChain) has  1322 elements
[DEBUG  ] Group     6 (   MainChain+Cb) has  1639 elements
[DEBUG  ] Group     7 (    MainChain+H) has  1639 elements
[DEBUG  ] Group     8 (      SideChain) has  3675 elements
[DEBUG  ] Group     9 (    SideChain-H) has  1342 elements
[DEBUG  ] Group    10 (    Prot-Masses) has  5314 elements
[DEBUG  ] Group    11 (    non-Protein) has 551115 elements
[DEBUG  ] Group    12 (          Water) has 551115 elements
[DEBUG  ] Group    13 (            SOL) has 551115 elements
[DEBUG  ] Group    14 (      non-Water) has  5314 elements
[DEBUG  ] Group    15 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has   990 elements
[DEBUG  ] Select a group: 
Reading frame       0 time 10000.000   
[DEBUG  ] Precision of trj_10-20ns.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time 10010.000   
[DEBUG  ] Dumping frame at t= 10000 ps
[DEBUG  ] Last written: frame      0 time 10000.000
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "Fifty years of programming language research, and we end up with C++???" (Richard O'Keefe)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 3: 'GMXMMPBSA_REC'
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group Backbone (4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[DEBUG  ] Running command: echo -e "4"| /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin.AVX2_256/gmx trjconv -f trj_10-20ns.xtc -s md_0_1.tpr -o _GMXMMPBSA_LIG.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ]                :-) GROMACS - gmx trjconv, 2023.4-conda_forge (-:
[DEBUG  ] 
[DEBUG  ] Executable:   /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs/bin.AVX2_256/gmx
[DEBUG  ] Data prefix:  /lustre/user/lulab/lulabrotation/miniconda3/envs/gromacs
[DEBUG  ] Working dir:  /lustre/user/lulab/lulabrotation/zhanglin/MkPX/application/clade1/mmpbsa
[DEBUG  ] Command line:
[DEBUG  ]   gmx trjconv -f trj_10-20ns.xtc -s md_0_1.tpr -o _GMXMMPBSA_LIG.pdb -n _GMXMMPBSA_COM_index.ndx -dump 0
[DEBUG  ] 
[DEBUG  ] Will write pdb: Protein data bank file
[DEBUG  ] Reading file md_0_1.tpr, VERSION 2023.4-conda_forge (single precision)
[DEBUG  ] Reading file md_0_1.tpr, VERSION 2023.4-conda_forge (single precision)
[DEBUG  ] Group     0 (         System) has 556429 elements
[DEBUG  ] Group     1 (        Protein) has  5314 elements
[DEBUG  ] Group     2 (      Protein-H) has  2664 elements
[DEBUG  ] Group     3 (  GMXMMPBSA_REC) has   330 elements
[DEBUG  ] Group     4 (  GMXMMPBSA_LIG) has   990 elements
[DEBUG  ] Group     5 (      MainChain) has  1322 elements
[DEBUG  ] Group     6 (   MainChain+Cb) has  1639 elements
[DEBUG  ] Group     7 (    MainChain+H) has  1639 elements
[DEBUG  ] Group     8 (      SideChain) has  3675 elements
[DEBUG  ] Group     9 (    SideChain-H) has  1342 elements
[DEBUG  ] Group    10 (    Prot-Masses) has  5314 elements
[DEBUG  ] Group    11 (    non-Protein) has 551115 elements
[DEBUG  ] Group    12 (          Water) has 551115 elements
[DEBUG  ] Group    13 (            SOL) has 551115 elements
[DEBUG  ] Group    14 (      non-Water) has  5314 elements
[DEBUG  ] Group    15 (GMXMMPBSA_REC_GMXMMPBSA_LIG) has   990 elements
[DEBUG  ] Select a group: 
Reading frame       0 time 10000.000   
[DEBUG  ] Precision of trj_10-20ns.xtc is 0.001 (nm)
[DEBUG  ] 
Reading frame       1 time 10010.000   
[DEBUG  ] Dumping frame at t= 10000 ps
[DEBUG  ] Last written: frame      0 time 10000.000
[DEBUG  ] 
[DEBUG  ] 
[DEBUG  ] GROMACS reminds you: "Fifty years of programming language research, and we end up with C++???" (Richard O'Keefe)
[DEBUG  ] 
[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 4: 'GMXMMPBSA_LIG'

### Operating system

linux

### gmx_MMPBSA Version

1.6.3

### Python version

Python 3.11.0

### Installation

conda AmberTools + conda

**Comment by allanlinzhang** [comment]
But when I use test documents from others to gmx.mmpbsa. It still working

**Comment by marioernestovaldes** [comment]
You need to create a group for the receptor and one for the ligand in the index file and use those

**Comment by allanlinzhang** [comment]
> You need to create a group for the receptor and one for the ligand in the index file and use those

Thanks for your reply! I just use the command "gmx make_ndx " to get the index file. Some more works are needed to edit it ?

**Comment by allanlinzhang** [comment]
Or I want to know how to make a index file for gmx_mmpbsa

**Comment by marioernestovaldes** [comment]
Try:

```
gmx make_ndx -f md_0_1.tpr
>splitch 1
>q
```
After each command press enter...

this splits the group 1 "Protein" into chains and should create two new groups. Then use these two new groups in the command line. If this doesn't work, feel free to send us the files to take a look and define the best way to define the groups

**Comment by allanlinzhang** [comment]
Thanks! But it occurs the same error. I will send you my files. 
My command is "gmx_MMPBSA MPI -O -i mmpbsa.in -cs md_0_1.tpr -ci index.ndx -cg 3 4  -ct trj_10-20ns.xtc -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv"
And the examples to run gmx_mmpbsa are work successfully, which can indicate my environment is OK to run it.  
.xtc file is too big to send to you....
[Myfiles (2).zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/14552930/Myfiles.2.zip)

**Comment by Valdes-Tresanco-MS** [comment]
You are selecting the wrong groups. Note you are selecting `C-alpha` and `Backbone`. After you split the Protein group into chains, select the corresponding groups according to your needs. Please, visualize the index groups and make sure that the selected groups are consistents
