### ISSUE TITLE
[Bug-gmx_MMPBSA]: 

### ISSUE THREAD

**Issue by lachrymator** [Valdes-Tresanco-MS/gmx_MMPBSA#472]
### Bug summary

I am getting a similar error to https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/95#issuecomment-987020604

### Terminal output

```bash
[INFO   ] Building AMBER topologies from GROMACS files... Done.
[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...
[INFO   ] 1001 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 1 CPUs...
[INFO   ] Running calculations on normal system...
[INFO   ] Beginning PB calculations with /shared/amber22/bin/sander
[INFO   ]   calculating complex contribution...
[ERROR  ] CalcError
/shared/amber22/bin/sander failed with prmtop COM.prmtop!

If you are using sander and PB calculation, check the *.mdout files to get the sander error
Check the gmx_MMPBSA.log file to report the problem.
$ cat _GMXMMPBSA_*.pdb | grep TER
TER
TER    4326      SER A 265
TER    4375      J-0 B3427
TER
TER
TER    4326      SER   265
TER    4375     J-07   266
TER      50     J-07   266
TER    4326      SER   265

CPPTRAJ: Trajectory Analysis. V6.18.1 (AmberTools)

How do you make sure cpptraj has internally consistent files?

Many thanks!
```

### gmx_MMPBSA.log

[DEBUG  ] Note that major changes are planned in future for trjconv, to improve usability and utility.
[DEBUG  ] Select group for output
[DEBUG  ] Selected 21: 'GMXMMPBSA_REC_GMXMMPBSA_LIG'
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...

[INFO   ] 1001 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 1 CPUs...
[INFO   ] Running calculations on normal system...
[INFO   ] Beginning PB calculations with /shared/amber22/bin/sander
[INFO   ]   calculating complex contribution...
[ERROR  ] CalcError

/shared/amber22/bin/sander failed with prmtop COM.prmtop!

### Operating system

Ubuntu 

### gmx_MMPBSA Version

1.6.3

### Python version

3.10.13

### Installation

pip

**Comment by Valdes-Tresanco-MS** [comment]
Do you check that your structure is consistent? Please, send me your files to check what has happened.

**Comment by lachrymator** [comment]
Thanks I think I fixed it the initial coordinates were not centered in the pbc. Works fine now.
