### ISSUE TITLE
[Question]: The reason why different outcomes happen when I extract adjacent time to calculate the binding affinity. 

### ISSUE THREAD

**Issue by allanlinzhang** [Valdes-Tresanco-MS/gmx_MMPBSA#478]
### My Question is...

I want to know the reason why different outcomes happen when I extract adjacent time to calculate the binding affinity.

**Comment by allanlinzhang** [comment]
![rmsd24_compare](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/156180366/d29fd9ee-a5b8-4910-b977-6a614724b898)
As the picture shows in red, when I calculate the binding affinity of the extraction of 25-30 ns and 30-35 ns. I get totally different outcomes. -78.63 is the outcome of 25-30 ns. -53.83  is the outcome of 30-35 ns.
Additionally,  -81.11 is the outcome of 20-25 ns.  -55.41 is the outcome of 35-40 ns.

**Comment by marioernestovaldes** [comment]
That variation indicates that probably the pose is not as stable and more simulation time is probably needed...

**Comment by allanlinzhang** [comment]
Thanks, I think I find a additional configuration of the complex. Lol.
