### ISSUE TITLE
[Bug-gmx_MMPBSA]: The complex index has fewer atoms than the topology. Please check that the files are consistent.

### ISSUE THREAD

**Issue by ChenHiuhong1** [Valdes-Tresanco-MS/gmx_MMPBSA#479]
### Bug summary

I get this error after I enter the following command in the Linux terminal: The complex index has fewer atoms than the topology. But after I checked m
[data.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/14872474/data.zip)
y topology file, the atomic numbers are consistent.

### Terminal output

```bash
gmx_MMPBSA -O -i mmpbsa_mem.in -cs sys.pdb -ci 2.ndx -cg 1 13 -ct mdnopbc.xtc -cp topol.top
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/14872383/gmx_MMPBSA.log)

### Operating system

CentOS 7

### gmx_MMPBSA Version

v1.5.0.3

### Python version

3.12.2

### Installation

conda AmberTools + conda

**Comment by ChenHiuhong1** [comment]
Then I tried several times and I still couldn't fix the error. I have no idea about this.

**Comment by marioernestovaldes** [comment]
I see you have lipids in your system, please remove those form teh topology and the input files before performing the calculations. at the end they are not used as you are using implicit membrane conditions. Once you delete the lipids form the input files (strcuture, tracjetory, and topology) create a fresh new index fioe and try again

**Comment by ChenHiuhong1** [comment]
So can I keep TIP3P and POT and CLA components？

**Comment by marioernestovaldes** [comment]
You don't have to, they are no needed for the calculations

**Comment by ChenHiuhong1** [comment]
There is a new error
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/14892541/gmx_MMPBSA.log)

**Comment by ChenHiuhong1** [comment]
In this calculation, my topology file and trajectory, the structure retains only the protein component and the UNL component

**Comment by marioernestovaldes** [comment]
Please update gmx_MMPBSA to teh last version:

python -m pip install gmx_MMPBSA -U

if you get nay error, please post the error here

**Comment by ChenHiuhong1** [comment]
Thanks, I am updating the gmx_MMPBSA now.Then I will try again

**Comment by ChenHiuhong1** [comment]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Successfully built matplotlib
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects

**Comment by ChenHiuhong1** [comment]
and in the terminal: 
IndexError: list index out of range

**Comment by marioernestovaldes** [comment]
Please post a picture of the error

**Comment by ChenHiuhong1** [comment]
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/166030937/d8896020-f2de-434c-a51a-0f9ab4fcd562)
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/166030937/a2dd8a76-6fbc-4204-a325-ebd546f7e107)

**Comment by ChenHiuhong1** [comment]
The first picture：after i change the reference strcuture to the first frame in trajectory, the mmpbsa can run.But I'm not sure if I'll report an error in the future. because i still use the 1.5.0.3 mmpbsa
The second picture: when i used "python -m pip install gmx_MMPBSA -U "to update mmpbsa, it occurs this error

**Comment by ChenHiuhong1** [comment]
The first picture：when i use tpr file,it occurs this error.after i change the reference strcuture to the first frame in trajectory, the mmpbsa can run.But I'm not sure if I'll report an error in the future. because i still use the 1.5.0.3 mmpbsa
The second picture: when i used "python -m pip install gmx_MMPBSA -U "to update mmpbsa, it occurs this error

**Comment by marioernestovaldes** [comment]
Hmmm... its best if you send me the files and I see exactly what's going wrong. As per the new gmxMMPBSA installation, did you create a new fresh conda envorinment and follow all the instruction here:

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/installation/

**Comment by ChenHiuhong1** [comment]
First I use the gro file generated by molecular dynamics simulation to generate the protein_unl index group：2_produce_from_gro.ndx
Next, I use this index file to generate a tpr file with only the protein_unl index group - gmx convert-tpr -s md_100ns.tpr -n 2_produce_from_gro,ndx -o md.tpr
Then,I used a new tpr file to generate the "nopbc" xtc file containing only protein_unl, that is mdnopbc.xtc
Then I used a trajectory that is generated by this output to gain the reference struture:gmx trjconv -s md_100ns.tpr -f md_100ns.xtc -pbc cluster - center , choose protein_unl protein_unl system.I extract the structure at 60000ps in this trajectory：lastmem60ns.pdb.
At last, I used md.tpr to generate the new index file that contains protein_unl, the index file is 3.ndx
[mmpbsa.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/14894492/mmpbsa.zip)

**Comment by ChenHiuhong1** [comment]
About installation, I did not create a new environment, I will try again. Thanks!

**Comment by Wenya-27** [comment]
Hi, have you solved the problem?

**Comment by Valdes-Tresanco-MS** [comment]
@Wenya-27. Please, open a new issue or post in our group to better follow up on your doubts

**Comment by Wenya-27** [comment]
![image](https://github.com/user-attachments/assets/2d2cb078-8afd-4b57-ac44-1035557a9401)

**Comment by Wenya-27** [comment]
It reminds the complex index has fewer atoms than the topology. How can i solve this problem, thanks.

**Comment by Valdes-Tresanco-MS** [comment]
@Wenya-27 Please, open a new issue or post in our group to better follow up on your doubts. Share the information needed to identify the problem, such as files, logs, etc.
