### ISSUE TITLE
GromacsError: Structure contains XXX molecules, but no template defined

### ISSUE THREAD

**Issue by josephDeluna** [Valdes-Tresanco-MS/gmx_MMPBSA#481]
`gmx_MMPBSA -O -i mmpbsa_gb.in -cs full_md.tpr -ct full_md_center.xtc  -cp topol.top -lp c_24.top -ci index.ndx -cg 1 13  -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv`

I run this code to calculate binding free energy, I also read the other issues related to this, I make sure that my ligand.itp was defined in my top file, it was also in the same directory with all the files related to my ligand such as prm.  However, I get the following error:

```
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
  File "/home/carbon/mpi4py/mpi4py/mpi4py/myenv/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/carbon/mpi4py/mpi4py/mpi4py/myenv/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/home/carbon/mpi4py/mpi4py/mpi4py/myenv/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 681, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/carbon/mpi4py/mpi4py/mpi4py/myenv/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 124, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/carbon/mpi4py/mpi4py/mpi4py/myenv/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 565, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/home/carbon/mpi4py/mpi4py/mpi4py/myenv/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 854, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/home/carbon/mpi4py/mpi4py/mpi4py/myenv/lib/python3.10/site-packages/parmed/gromacs/gromacstop.py", line 346, in __init__
    self.read(fname, defines, parametrize)
  File "/home/carbon/mpi4py/mpi4py/mpi4py/myenv/lib/python3.10/site-packages/parmed/gromacs/gromacstop.py", line 534, in read
    raise GromacsError('Structure contains %s molecules, but no '
GromacsError: Structure contains c_24 molecules, but no template defined
```

How do I deal with this?

**Comment by marioernestovaldes** [comment]
There is a mismatch between the topology and the input structure. Please, make sure that the ligand molecule contains exactly the same name in both the input structure and the topology

**Comment by josephDeluna** [comment]
> There is a mismatch between the topology and the input structure. Please, make sure that the ligand molecule contains exactly the same name in both the input structure and the topology

I've checked all my input files and my ligand molecule files, they are all named "c_24". 

I'm new to this so your help is pretty much appreciated.

**Comment by marioernestovaldes** [comment]
Could you please send us the files you are using? This way is faster for us to detect the issue

**Comment by josephDeluna** [comment]
> Could you please send us the files you are using? This way is faster for us to detect the issue

https://drive.google.com/drive/folders/1qSpCw3jPbyijs2Kw1ZJn8QTJ__e7tfuw?usp=sharing

here is the drive, with all of the files involved in my computation. I really appreciate this.

**Comment by marioernestovaldes** [comment]
Line 54 in topol.top file should be C_24 with capital C, not c_24. The code is case-sensitive. The command line should be this:

`gmx_MMPBSA -O -i mmpbsa_gb.in -cs full_md.tpr -ct full_md_center.xtc -cp topol.top -ci index.ndx -cg 1 13  -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv` 

let me know if you have any more questions :)

**Comment by josephDeluna** [comment]
It is now working, Thank you very much. This will be a very big help for my thesis. Thanks

**Comment by marioernestovaldes** [comment]
Nice! 🙂
