### ISSUE TITLE
[Question]: How to calculate the binding free energy of lipids membrane and peptide

### ISSUE THREAD

**Issue by chanchanchanchanchan** [Valdes-Tresanco-MS/gmx_MMPBSA#502]
### My Question is...

Dear Developer,
I'm wondering if there are any force fields to use for the calculation of the binding free energy of lipid membranes and peptides. I have searched the help documentation and found that there's no available forcd field for the lipids. Thank you for your help!

**Comment by marioernestovaldes** [comment]
if you have the topology of your system there is no need for forcefields... the program will generate the proper files using your input files

**Comment by chanchanchanchanchan** [comment]
I see. Thanks! That is vert helpful to me

**Comment by chanchanchanchanchan** [comment]
> if you have the topology of your system there is no need for forcefields... the program will generate the proper files using your input files

I see. Thanks! That is vert helpful to me
