### ISSUE TITLE
[Question]: Handling Protein-Ligand Complexes Embedded in Membranes with LPH Atoms

### ISSUE THREAD

**Issue by huaiaee** [Valdes-Tresanco-MS/gmx_MMPBSA#508]
### My Question is...

I am currently working on a project involving a protein-ligand complex that is embedded in a membrane and contains LPH atoms. I've noticed that my topology file seems to differ from the examples provided for both membrane proteins and ligands with LPH atoms. Could you please advise on how to properly handle this situation? Any guidance on adjusting the topology file or any specific parameters to consider would be greatly appreciated.

**Comment by huaiaee** [comment]
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/127479531/39a5e6b2-158a-4b18-ab4c-26f6ee6685f9)
This is my topology file

**Comment by marioernestovaldes** [comment]
There should be a topol.top or something similar (this is the topology file and it is the one that you should use with the -cp flag in the command line) that contains references to all these itp files

**Comment by huaiaee** [comment]
I seem to have misunderstood you; this is a comparison of two topology files. The one on the left is the example, and the one on the right is my file.
Additionally, the parameters for the membrane protein and LPH atoms in the mmpbsa.in file also differ. How should this situation be handled?
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/127479531/d59924fe-d5e8-4d08-91fc-2fdf4d80e11e)

**Comment by marioernestovaldes** [comment]
Each system is unique in its own way and therefore the topologies tend to differ. In your case, you should follow the LPH tutorial to remove the LPH particles and then, use the membrane tutorial to get familiarized with the parameters used for membrane systems

**Comment by huaiaee** [comment]
Thank you for your answering, I will try it again
