### ISSUE TITLE
[Bug-gmx_MMPBSA]: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by suruchi-25** [Valdes-Tresanco-MS/gmx_MMPBSA#510]
### Bug summary

TypeError: string indices must be integers

### Terminal output

```bash
INFO   ] Starting gmx_MMPBSA v1.6.3
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs md_0_300.tpr -ct md_0_300_center150-300ns.xtc -ci index.ndx -cg 3 4 -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx_mpi found! Using /apps/codes/gromacs-2022/bin/gmx_mpi
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group C-alpha_Backbone (3_4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group C-alpha (3) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group Backbone (4) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 681, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 122, in buildTopology
    self.gmx2pdb()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 523, in gmx2pdb
    self.resi, self.resl, self.orderl = res2map(self.indexes, self.complex_str)
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/utils.py", line 600, in res2map
    for e in value['num']:
TypeError: string indices must be integers
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/user-attachments/files/15710388/gmx_MMPBSA.log)

### Operating system

ubantu

### gmx_MMPBSA Version

gmx_MMPBSA v1.6.3

### Python version

Python 3.10.14

### Installation

None

**Comment by Valdes-Tresanco-MS** [comment]
You are selecting wrong groups. In this case should be `-cg 1 13`

**Comment by suruchi-25** [comment]
[INFO   ] Starting gmx_MMPBSA v1.6.3
[INFO   ] Command-line
  gmx_MMPBSA -i mmpbsa.in -cs md_0_300.tpr -ct md_0_300_center150-300ns.xtc -ci index.ndx -cg 1 13 -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx_mpi found! Using /apps/codes/gromacs-2022/bin/gmx_mpi
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group Protein_6ZV (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[ERROR  ] MMPBSA_Error 

/apps/codes/gromacs-2022/bin/gmx_mpi trjconv failed when querying md_0_300_center150-300ns.xtc

Check the gmx_MMPBSA.log file to report the problem.
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 681, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 122, in buildTopology
    self.gmx2pdb()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 319, in gmx2pdb
    GMXMMPBSA_ERROR('%s failed when querying %s' % (' '.join(comprog), self.FILES.complex_trajs[0]))
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/exceptions.py", line 171, in __init__
    raise exc('\n\n' + msg + '\n\nCheck the gmx_MMPBSA.log file to report the problem.')
MMPBSA_Error: 

/apps/codes/gromacs-2022/bin/gmx_mpi trjconv failed when querying md_0_300_center150-300ns.xtc

Check the gmx_MMPBSA.log file to report the problem.


[gmx_MMPBSA.log](https://github.com/user-attachments/files/15712567/gmx_MMPBSA.log)

Please help me out with issue also

**Comment by Valdes-Tresanco-MS** [comment]
Please, don't use `GMXMMPBSA_REC`, `GMXMMPBSA_LIG`, or `GMXMMPBSA_REC_GMXMMPBSA_LIG` in the index file since these names are reserved for gmx_MMPBSA. Generate new index files using the default group names according to gromacs, and then use this index instead of the modified one you get from gmx_MMPBSA

**Comment by suruchi-25** [comment]
sorry for the issue, but i didn't understand what you want me to do for that issue. can you please help me out.

**Comment by Valdes-Tresanco-MS** [comment]
Your index.ndx (for this calculation) file looks like this
```
[DEBUG  ]   0 System              : 55821 atoms
[DEBUG  ]   1 Protein             :  4608 atoms
[DEBUG  ]   2 Protein-H           :  2297 atoms
[DEBUG  ]   3 GMXMMPBSA_REC       :   293 atoms
[DEBUG  ]   4 GMXMMPBSA_LIG       :   879 atoms
[DEBUG  ]   5 MainChain           :  1173 atoms
[DEBUG  ]   6 MainChain+Cb        :  1443 atoms
[DEBUG  ]   7 MainChain+H         :  1444 atoms
[DEBUG  ]   8 SideChain           :  3164 atoms
[DEBUG  ]   9 SideChain-H         :  1124 atoms
[DEBUG  ]  10 Prot-Masses         :  4608 atoms
[DEBUG  ]  11 non-Protein         : 51213 atoms
[DEBUG  ]  12 Other               :    69 atoms
[DEBUG  ]  13 6ZV                 :    69 atoms
[DEBUG  ]  14 Water               : 51144 atoms
[DEBUG  ]  15 SOL                 : 51144 atoms
[DEBUG  ]  16 non-Water           :  4677 atoms
[DEBUG  ]  17 Protein_6ZV         :  4677 atoms
[DEBUG  ]  18 6ZV_&_!H*           :    37 atoms
[DEBUG  ]  19 GMXMMPBSA_REC_GMXMMPBSA_LIG:   879 atoms
[DEBUG  ]  20 GMXMMPBSA_REC_GMXMMPBSA_LIG:   879 atoms
[DEBUG  ]  21 GMXMMPBSA_REC_&_GMXMMPBSA_LIG:   293 atoms
```
As you can see, groups 19 and 20 are the `GMXMMPBSA_REC_GMXMMPBSA_LIG` reserved for gmx_MMPBSA. So you must create a new index file like this (previous calculation)
```
[DEBUG  ]   0 System              : 55821 atoms
[DEBUG  ]   1 Protein             :  4608 atoms
[DEBUG  ]   2 Protein-H           :  2297 atoms
[DEBUG  ]   3 C-alpha             :   293 atoms
[DEBUG  ]   4 Backbone            :   879 atoms
[DEBUG  ]   5 MainChain           :  1173 atoms
[DEBUG  ]   6 MainChain+Cb        :  1443 atoms
[DEBUG  ]   7 MainChain+H         :  1444 atoms
[DEBUG  ]   8 SideChain           :  3164 atoms
[DEBUG  ]   9 SideChain-H         :  1124 atoms
[DEBUG  ]  10 Prot-Masses         :  4608 atoms
[DEBUG  ]  11 non-Protein         : 51213 atoms
[DEBUG  ]  12 Other               :    69 atoms
[DEBUG  ]  13 6ZV                 :    69 atoms
[DEBUG  ]  14 Water               : 51144 atoms
[DEBUG  ]  15 SOL                 : 51144 atoms
[DEBUG  ]  16 non-Water           :  4677 atoms
[DEBUG  ]  17 Protein_6ZV         :  4677 atoms
[DEBUG  ]  18 6ZV_&_!H*           :    37 atoms
```
Then, define the correct groups `-cg 1 13`. Make sure you are selecting the groups of the receptor and the ligand. Please check the gmx_MMPBSA.log file as the error is almost always defined there.

**Comment by suruchi-25** [comment]
gmx_MMPBSA -i mmpbsa.in -cs md_0_300.tpr -ct md_0_300_center150-300ns.xtc -ci index.ndx -cg 1 13 -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx_mpi found! Using /apps/codes/gromacs-2022/bin/gmx_mpi
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group Protein_6ZV (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 6ZV (13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 681, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 124, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 565, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 854, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/parmed/gromacs/gromacstop.py", line 346, in __init__
    self.read(fname, defines, parametrize)
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/parmed/gromacs/gromacstop.py", line 383, in read
    for line in f:
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/parmed/gromacs/_gromacsfile.py", line 42, in __iter__
    for line in self._handle:
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/parmed/gromacs/_cpp.py", line 174, in __iter__
    self._ppcmdmap[cmd](self, args)
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/parmed/gromacs/_cpp.py", line 29, in wrapper
    return func(self, args)
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/parmed/gromacs/_cpp.py", line 283, in _pp_include
    raise PreProcessorError(f'Could not find {includefile}')
PreProcessorError: Could not find amber99.ff/forcefield.itp

[gmx_MMPBSA.log](https://github.com/user-attachments/files/15721449/gmx_MMPBSA.log)

What can be done with this now?

**Comment by Valdes-Tresanco-MS** [comment]
Make sure that the `amber99.ff` folder is accessible. If it is not in the ambertools folder, you can copy it to the working directory folder

**Comment by suruchi-25** [comment]
from where i can get that ff folder?

**Comment by suruchi-25** [comment]
gmx_MMPBSA -i mmpbsa.in -cs md_0_300.tpr -ct md_0_300_center150-300ns.xtc -ci index.ndx -cg 1 13 -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx_mpi found! Using /apps/codes/gromacs-2022/bin/gmx_mpi
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group Protein_6ZV (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 6ZV (13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.make_prmtops()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/main.py", line 681, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 124, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 565, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/GMXMMPBSA/make_top.py", line 854, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/parmed/gromacs/gromacstop.py", line 346, in __init__
    self.read(fname, defines, parametrize)
  File "/apps/codes/anaconda3/envs/gmxMMPBSA/lib/python3.10/site-packages/parmed/gromacs/gromacstop.py", line 534, in read
    raise GromacsError('Structure contains %s molecules, but no '
GromacsError: Structure contains 6ZV molecules, but no template defined
