### ISSUE TITLE
[Questunable to get the decomposition result

### ISSUE THREAD

**Issue by suruchi-25** [Valdes-Tresanco-MS/gmx_MMPBSA#521]
### My Question is...

i have completed the calculation by using the command
gmx_MMPBSA -O -i mmpbsa.in -cs md_0_300.tpr -ct md_0_300_center150-300ns.xtc -ci index.ndx -cg 1 13 -cp topol.top -o LIG6_FINAL_RESULTS_MMPBSA.dat -eo LIG6_FINAL_RESULTS_MMPBSA.csv -do LIG6_FINAL_DECOMP_MMPBSA.dat -deo LIG6_FINAL_DECOMP_MMPBSA.csv
but is not getting the lig6_final_decomp_mmpbsa.dat fine in the working directory. can someone help me out in knowing how to get the desired result?

**Comment by Valdes-Tresanco-MS** [comment]
You are overwriting the output file. Please, carefully read the documentation and the information of `gmx_MMPBSA -h` command

**Comment by suruchi-25** [comment]
sorry, i am unable to understand what you want to say. how it can be checked?

**Comment by Valdes-Tresanco-MS** [comment]
Sorry, my mistake... 
Can you share the gmx_MMPBSA.log file and the output of ls in the working directory?

**Comment by suruchi-25** [comment]
[gmx_MMPBSA.log](https://github.com/user-attachments/files/16318955/gmx_MMPBSA.log)

gmx_MMPBSA -O -i mmpbsa.in -cs md_0_300.tpr -ct md_0_300_center150-300ns.xtc -ci index.ndx -cg 1 13 -cp topol.top -o LIG6_FINAL_RESULTS_MMPBSA.dat -eo LIG6_FINAL_RESULTS_MMPBSA.csv -do LIG6_FINAL_DECOMP_MMPBSA.dat -deo LIG6_FINAL_DECOMP_MMPBSA.csv
--------------------------------------------------------------------------
[[56362,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: CUG

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
[INFO   ] Starting gmx_MMPBSA v1.6.3
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs md_0_300.tpr -ct md_0_300_center150-300ns.xtc -ci index.ndx -cg 1 13 -cp topol.top -o LIG6_FINAL_RESULTS_MMPBSA.dat -eo LIG6_FINAL_RESULTS_MMPBSA.csv -do LIG6_FINAL_DECOMP_MMPBSA.dat -deo LIG6_FINAL_DECOMP_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[WARNING] &decomp namelist has not been defined in the input file. Ignoring '-deo' flag... 
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /apps/codes/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx_mpi found! Using /apps/codes/gromacs-2022/bin/gmx_mpi
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group Protein_UNK (1_13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group Protein (1) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group UNK (13) in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected Amber/OPLS force field topology format...
[WARNING] 14 invalid DIHEDRAL_PERIODICITY = 0 found in Complex topology... Setting DIHEDRAL_PERIODICITY = 1
[INFO   ] Assigning PBRadii mbondi2 to Complex...
[INFO   ] Writing Normal Complex AMBER topology...
[INFO   ] No Receptor topology file was defined. Using ST approach...
[INFO   ] Building AMBER Receptor topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Receptor...
[INFO   ] Writing Normal Receptor AMBER topology...
[INFO   ] No Ligand topology file was defined. Using ST approach...
[INFO   ] Building AMBER Ligand topology from Complex...
[INFO   ] Assigning PBRadii mbondi2 to Ligand...
[INFO   ] Writing Normal Ligand AMBER topology...
[INFO   ] Cleaning normal complex trajectories...
[INFO   ] Building AMBER topologies from GROMACS files... Done.

[INFO   ] Loading and checking parameter files for compatibility...
[INFO   ] Preparing trajectories for simulation...

[INFO   ] 10 frames were processed by cpptraj for use in calculation.
[INFO   ] Starting calculations in 1 CPUs...

[INFO   ] Running calculations on normal system...
[INFO   ] Beginning GB calculations with /apps/codes/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ]   calculating complex contribution...
            100%|######################| 10/10 [elapsed: 00:17 remaining: 00:00]
[INFO   ]   calculating receptor contribution...
            100%|######################| 10/10 [elapsed: 00:17 remaining: 00:00]
[INFO   ]   calculating ligand contribution...
            100%|######################| 10/10 [elapsed: 00:01 remaining: 00:00]
[INFO   ] Parsing results to output files...

[INFO   ] Timing:
[INFO   ] Total GROMACS setup time:                  12.950 sec.
[INFO   ] Total AMBER setup time:                     0.723 sec.
[INFO   ] Creating trajectories with cpptraj:         0.254 sec.
[INFO   ] Total calculation time:                    36.355 sec.
[INFO   ] Total GB calculation time:                 33.424 sec.
[INFO   ] Statistics calculation & output writing:    0.018 sec.
[INFO   ] Total time taken:                          50.323 sec.

[INFO   ] 
   Finalizing gmx_MMPBSA: [ERROR  ] = 0; [WARNING] = 2
   Check the gmx_MMPBSA.log file for more details...

[INFO   ] 
 Thank you for using gmx_MMPBSA. Please consider supporting gmx_MMPBSA by citing our publication:
    Valdés-Tresanco, M.S., Valdés-Tresanco, M.E., Valiente, P.A. and Moreno E. 
    gmx_MMPBSA: A New Tool to Perform End-State Free Energy Calculations with GROMACS. 
    J Chem Theory Comput., 2021, 17 (10):6281-6291. Epub 2021 Sep 29. PMID: 34586825.
    https://pubs.acs.org/doi/10.1021/acs.jctc.1c00645

Also consider citing MMPBSA.py:
    Miller III, B. R., McGee Jr., T. D., Swails, J. M. Homeyer, N. Gohlke, H. and Roitberg, A. E.
    MMPBSA.py: An Efficient Program for End-State Free Energy Calculations.
    J. Chem. Theory Comput., 2012, 8 (9) pp 3314-3321

[INFO   ] Opening gmx_MMPBSA_ana to analyze results...

[INFO   ] Finalized...

**Comment by Valdes-Tresanco-MS** [comment]
According to the gmx_MMPBSA.log file you should get the output file in `/home/suruchi/Desktop/S_3/CDK4/Lig6`. Please, check if the file exist
```bash
ls | grep "LIG6_FINAL_RESULTS_MMPBSA.dat"
```

**Comment by suruchi-25** [comment]
no file like this is obtained in the working directory

**Comment by suruchi-25** [comment]
Please reply the results are not obtained even after the command is
completed?

**Comment by suruchi-25** [comment]
Hello Valdes-Tresanco-MS/gmx_MMPBSA
Please reply as it is important for me to calculate and unable to proceed
further because of this issue
