### ISSUE TITLE
[Bug-gmx_MMPBSA]: ImportError with mpi4py

### ISSUE THREAD

**Issue by jstump-1999** [Valdes-Tresanco-MS/gmx_MMPBSA#526]
### Bug summary

gmx_MMPBSA installs correctly with python 3.9, but running it prints this error. I had already tried with 3.10 but couldn't get through install due to an "unable to build wheels for pandas" error. Looking around I've seen this type of error thrown when cuda is present on the system already as a form of mpi, but I'm generally unfamiliar with how that's installed and so am unsure of how to proceed.

### Terminal output

```bash
Traceback (most recent call last):
  File "/home/coby/Softwares/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/coby/Softwares/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 53, in gmxmmpbsa
    from mpi4py import MPI
ImportError: /home/coby/Softwares/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/mpi4py/MPI.cpython-39-x86_64-linux-gnu.so: undefined symbol: MPI_Message_c2f
```

### gmx_MMPBSA.log

Traceback (most recent call last):
  File "/home/coby/Softwares/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/coby/Softwares/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 53, in gmxmmpbsa
    from mpi4py import MPI
ImportError: /home/coby/Softwares/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/mpi4py/MPI.cpython-39-x86_64-linux-gnu.so: undefined symbol: MPI_Message_c2f

### Operating system

Ubuntu

### Python version

Python 3.9.19

### Installation

conda AmberTools + pip

**Comment by Valdes-Tresanco-MS** [comment]
Please, attach the `conda list` output

**Comment by jstump-1999** [comment]
\# packages in environment at /home/coby/Softwares/anaconda3/envs/gmxMMPBSA:
\#
\# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   h69a702a_16    conda-forge
ambertools                23.6             py39h472d8b1_1    conda-forge
amberutils                21.0                     pypi_0    pypi
arpack                    3.8.0           nompi_h0baa96a_101    conda-forge
binutils                  2.40                 h4852527_7    conda-forge
binutils_impl_linux-64    2.40                 ha1999f0_7    conda-forge
binutils_linux-64         2.40                 hb3c18ed_0    conda-forge
blosc                     1.21.5               hc2324a3_1    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.32.3               h4bc722e_0    conda-forge
c-compiler                1.7.0                hd590300_1    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
compilers                 1.7.0                ha770c72_1    conda-forge
contourpy                 1.2.1            py39h7633fee_0    conda-forge
cxx-compiler              1.7.0                h00ab1b0_1    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
edgembar                  0.2                      pypi_0    pypi
fftw                      3.3.10          nompi_hf1063bd_110    conda-forge
fonttools                 4.53.1           py39hcd6043d_0    conda-forge
fortran-compiler          1.7.0                heb67821_1    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gcc                       12.4.0               h236703b_0    conda-forge
gcc_impl_linux-64         12.4.0               hb2e57f8_0    conda-forge
gcc_linux-64              12.4.0               h6b7512a_0    conda-forge
gfortran                  12.4.0               h236703b_0    conda-forge
gfortran_impl_linux-64    12.4.0               hc568b83_0    conda-forge
gfortran_linux-64         12.4.0               hd748a6a_0    conda-forge
gmx-mmpbsa                1.6.3                    pypi_0    pypi
gxx                       12.4.0               h236703b_0    conda-forge
gxx_impl_linux-64         12.4.0               h557a472_0    conda-forge
gxx_linux-64              12.4.0               h8489865_0    conda-forge
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
impi_rt                   2021.13.0          ha770c72_720    conda-forge
importlib-resources       6.4.0              pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
kernel-headers_linux-64   3.10.0              h4a8ded7_16    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py39h7633fee_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libblas                   3.9.0           23_linux64_openblas    conda-forge
libboost                  1.84.0               hba137d9_3    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           23_linux64_openblas    conda-forge
libcurl                   8.8.0                hca28451_1    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.4                h6a678d5_1  
libgcc-devel_linux-64     12.4.0             ha4f9413_100    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           23_linux64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_h135f659_114    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsanitizer              12.4.0               h46f95d5_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-devel_linux-64  12.4.0             ha4f9413_100    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hd590300_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               hc051c1a_1    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
matplotlib                3.5.2                    pypi_0    pypi
mmpbsa-py                 16.0                     pypi_0    pypi
mpi                       1.0                        impi    conda-forge
mpi4py                    3.1.5                    pypi_0    pypi
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h6a678d5_0  
netcdf-fortran            4.6.1           nompi_h228c76a_104    conda-forge
numpy                     1.26.4           py39h474f0d3_0    conda-forge
olefile                   0.47               pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                h7d73246_0    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
packmol-memgen            2024.2.9                 pypi_0    pypi
pandas                    1.2.2                    pypi_0    pypi
parmed                    4.2.2            py39h3d6467e_1    conda-forge
pdb4amber                 22.0                     pypi_0    pypi
perl                      5.32.1          7_hd590300_perl5    conda-forge
pillow                    8.4.0            py39ha612740_0    conda-forge
pip                       24.0             py39h06a4308_0  
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pymsmt                    22.0                     pypi_0    pypi
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyqt5                     5.15.11                  pypi_0    pypi
pyqt5-qt5                 5.15.14                  pypi_0    pypi
pyqt5-sip                 12.15.0                  pypi_0    pypi
python                    3.9.19               h955ad1f_1  
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
readline                  8.2                  h5eee18b_0  
sander                    22.0                     pypi_0    pypi
scipy                     1.13.1           py39haf93ffa_0    conda-forge
seaborn                   0.11.2                   pypi_0    pypi
setuptools                69.5.1           py39h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
sqlite                    3.45.3               h5eee18b_0  
sysroot_linux-64          2.17                h4a8ded7_16    conda-forge
tk                        8.6.14               h39e8969_0  
tqdm                      4.66.4                   pypi_0    pypi
tzdata                    2024a                h04d1e81_0  
unicodedata2              15.1.0           py39hd1e30aa_0    conda-forge
wheel                     0.43.0           py39h06a4308_0  
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.4.6                h5eee18b_1  
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

**Comment by Valdes-Tresanco-MS** [comment]
The problem is the mpi4py was installed via pypi. Please, create a new environment following these instructions
```bash
💬 Update conda
conda update conda

💬 Create a new environment and activate it
conda create -n gmxMMPBSA python=3.9 -y -q
conda activate gmxMMPBSA

💬 Install mpi4py and AmberTools
conda install -c conda-forge "mpi4py<=3.1.5" "ambertools<=23.3" -y -q

💬 Install PyQt6 required to use the GUI analyzer tool (gmx_MMPBSA_ana). Not needed for HPC
python -m pip install "pyqt6<=6.6.1"

💬 (Optional) Install GROMACS
conda install -c conda-forge "gromacs<=2023.4" pocl -y -q
```

**Comment by jstump-1999** [comment]
That followed by using conda to install gmx_MMPBSA instead of pip did the trick, thanks!
