### ISSUE TITLE
could not convert string to float

### ISSUE THREAD

**Issue by julianaamorim** [Valdes-Tresanco-MS/gmx_MMPBSA#53]
Hello sir, I would like some help with an error that presented itself when I was working with some data...

I attach the .log

Attentively

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6679382/gmx_MMPBSA.log)

**Comment by marioernestovaldes** [comment]
Hi Juliana! we have observed that error in the past and is well documented. Please, check this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/Q%26A/calculations/#possible-solutions)

let us know if the error persists

cheers!

Mario E.

**Comment by julianaamorim** [comment]
Problem resolved

Gracias

Juliana
