### ISSUE TITLE
[Doc]: Alanine Scann issue

### ISSUE THREAD

**Issue by julruiz72** [Valdes-Tresanco-MS/gmx_MMPBSA#531]
### Problem

Hello everyone 

I am currently running a MD and I am calculating the energy from the trajectory using MMPBSA and it works normally, but now that I have to make a alanine scan I am following the documentation (https://ambermd.org/tutorials/advanced/tutorial3/py_script/index.htm) but as I errase the sidechain atoms manually to turn the residue of interest into an alanine and  it shows tdiferent issues including "PrmtopError: Complex natom != receptor natom + ligand natom

Fatal Error! 
All files have been retained for your error investigation: 
You should begin by examining the output files of the first failed calculation.
Consult the "Temporary Files" subsection of the MMPBSA.py chapter in the
manual for file naming conventions."

But I don't really understand, because as it's a mutant it will never have the same amount of atoms

Can you help me?

**Comment by marioernestovaldes** [comment]
Seems you are using MMPBSA.py from AMBER. This group provides support for gmx_MMPBSA for GROMACS.
