### ISSUE TITLE
[Question]: Which file was used to create index.ndx file for binding energay caluclation?

### ISSUE THREAD

**Issue by Tangbbmc** [Valdes-Tresanco-MS/gmx_MMPBSA#536]
### My Question is...

After molecular dynamic production, Gromacs produced many *. gro files, such as em.gro, npt.gro, and nvt.gro. Which gro file should I use to create index.ndx file?

**Comment by Valdes-Tresanco-MS** [comment]
At this point, you should have an index.ndx file, so you don't need to generate a new one. If you do, use the latest tpr, usually md.tpr, as a reference file.

**Comment by Tangbbmc** [comment]
In my study, Gromacs was used to perform molecular dynamic simulation of antigen-antibody complex, which did not produce index.ndx file. A index.ndx file is required to calculate binding energy between antigen and antibody using gmx_MMPBSA. When I created index.file with em.gro, I could successfully run gmx_MMPBSA. Next, I plan to test md.tpr to output index.ndx file according to your advice.


---- Replied Message ----
From  Mario Sergio Valdés ***@***.***> Date  09/21/2024 22:59 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Question]: Which file was used to create index.ndx file for binding energay caluclation? (Issue #536)  

At this point, you should have an index.ndx file, so you don't need to generate a new one. If you do, use the latest tpr, usually md.tpr, as a reference file.

**Comment by Valdes-Tresanco-MS** [comment]
Ah, I see. Please use the tpr file to generate the index file since it preserves information like the chains ID to create the receptor and ligand in your case (using splitch). Since the gro files do not contain this information, you will have to manually define which residues belong to the receptor and which to the ligand.

**Comment by Tangbbmc** [comment]
Yes, I did manually define which residues belong to the receptor and which to the ligand. Is there anything difference in result when using two different creation methods?


---- Replied Message ----
From  Mario Sergio Valdés ***@***.***> Date  09/21/2024 23:29 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Question]: Which file was used to create index.ndx file for binding energay caluclation? (Issue #536)  

Ah, I see. Please use the tpr file to generate the index file since it preserves information like the chains ID to create the receptor and ligand in your case (using splitch). Since the gro files do not contain this information, you will have to manually define which residues belong to the receptor and which to the ligand.

**Comment by Valdes-Tresanco-MS** [comment]
No, none. It would just be the ease of defining it.

**Comment by Tangbbmc** [comment]
Ok. Thank you very much for your guidance!


---- Replied Message ----
From  Mario Sergio Valdés ***@***.***> Date  09/21/2024 23:44 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [Valdes-Tresanco-MS/gmx_MMPBSA] [Question]: Which file was used to create index.ndx file for binding energay caluclation? (Issue #536)  

No, none. It would just be the ease of defining it.
