### ISSUE TITLE
[Question]: having index error with assigning chain ID.

### ISSUE THREAD

**Issue by tjrong123** [Valdes-Tresanco-MS/gmx_MMPBSA#539]
### My Question is...

the simulation was done using gromacs 2024. the trajectory is xtc form, for analysis purposes, i filtered it using mdtraj and export in xtc format.  Now i like to analyse the protein ligand binding energy but it keep giving index error in assigning chain ID. MMPBSA/make_top.py", line 514, in gmx2pdb   command :gmx_MMPBSA -O -i mmpbsa.in -cs step3_input.pdb -ct filtered_trajectory.xtc -ci index.ndx -cg 1 2 -cp topol.top -o final_result_mmpbsa.dat -eo final_results_MMPBSA.csv  self.check_structures(self.complex_str, self.receptor_str, self.ligand_str)   File "/home/ivybridge/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 1414, in check_structures     self._assign_chains_IDs(com_str, rec_str, lig_str)   File "/home/ivybridge/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 1470, in _assign_chains_IDs     if self.resl[c + 1].is_receptor(): IndexError: list index out of range Exiting. All files have been retained.

**Comment by tjrong123** [comment]
[step3_input (3).zip](https://github.com/user-attachments/files/17142750/step3_input.3.zip)
this is my input coordinate in pdb

**Comment by tjrong123** [comment]
[step3_input (3).zip](https://github.com/user-attachments/files/17142758/step3_input.3.zip)
this is my coordinate file I used. also, I have fix the PBC, with mol option. Thanks in advance

**Comment by marioernestovaldes** [comment]
This is usually related to the groups selected. Are you certain that the groups you are selecting (1 and 2) are the receptor and the ligand?

**Comment by tjrong123** [comment]
@marioernestovaldes I have solved the problem. turn out it was because of a breaking xtc file inherent from the analysis. i re-run the trjconv to repair the trajectory file, then now I have energy calculated. Thanks for your speedy reply btw.
