### ISSUE TITLE
[Question]: running MMPBSA by  gromos forcefield toplogy and gromacs 2023.2

### ISSUE THREAD

**Issue by benyamin-moraditabar** [Valdes-Tresanco-MS/gmx_MMPBSA#543]
### My Question is...

Hi, I have ran a protein-peptide simulation by gromacs 2023.2 and gromos 43a1.ff forcefield for parametrization. 

Now I can't run gmx_mmpbsa because I came across this Error: Not all bond parameters found.

So how can I calculate the binding free energy with my xtc trajectory files generated by this version of gromacs and gromos forcefield???

Thanks for your attention.

**Comment by Valdes-Tresanco-MS** [comment]
Unfortunately, GROMOS is not supported. We will try to make it work in new versions implementing other programs and methods for PB.

**Comment by benyamin-moraditabar** [comment]
> Unfortunately, GROMOS is not supported. We will try to make it work in new versions implementing other programs and methods for PB.
Do you know how can I calculate the binding energy with other ways? would you please give me any clue for performing binding energy calculation?

**Comment by benyamin-moraditabar** [comment]
Thank you so much I will do all.
