### ISSUE TITLE
Create a conda package

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/gmx_MMPBSA#55]
Create a conda package
Packages to be installed:
- `AmberTools >= 20` (if not installed by compilation)
- `mpi4py >= 3.0.3` (PyPi == conda) --> conda is preferred to avoid the incompatibility with compilers package])
- `pandas >= 1.2.4` (PyPi == conda)
- `matplotlib >= 3.4.2` (PyPi == conda)
- `scipy >= 1.6.1` (PyPi = 1.7.0 | conda = 1.6.3)
- `seaborn >= 0.11.1` (PyPi == conda)
- `PyQt5 >= 5.15.4` (PyPi = 5.15.4 | conda = 5.9.2)

**Comment by vsdepontes** [comment]
I've recently created a Docker image containing Gromacs, AmberTools, gmx_MMPBSA and all the dependencies needed. That way, the users can easily use these software in a portable and isolated environment without worrying about installations and configurations. A conda environment would still be important in case someone wants to use gmx_MMPBSA with a custom compiled Gromacs, for example, but I wonder if a Docker image would be of your interest too.

**Comment by vsdepontes** [comment]
> I've recently created a Docker image containing Gromacs, AmberTools, gmx_MMPBSA and all the dependencies needed. That way, the users can easily use these software in a portable and isolated environment without worrying about installations and configurations. A conda environment would still be important in case someone wants to use gmx_MMPBSA with a custom compiled Gromacs, for example, but I wonder if a Docker image would be of your interest too.

The Docker image also removes the possibility of #54 happening

**Comment by Valdes-Tresanco-MS** [comment]
Hi @vsdepontes 
Thanks for showing interest in `gmx_MMPBSA`. Of course, any collaboration is welcome. Since I am not active in the development of the program at the moment, I have not reviewed how to generate a package or work with docker. So I would trust you for this activity.

Cheers!
Mario S.

**Comment by vsdepontes** [comment]
Thanks for the quick reply, @Valdes-Tresanco-MS
I've put my Dockerfile at https://github.com/vsdepontes/mmpbsa and the "ready to go" image at https://hub.docker.com/r/lammfar/mmpbsa. If one has Docker, NVIDIA-Docker and the recommended NVIDIA driver installed, will be able to start a terminal with GROMACS, AmberTools and gmx_MMPBSA using just `docker run -it --gpus all lammfar/mmpbsa:latest`. 
It is important to note that, with the command above, it won't be possible to use gmx_MMPBSA_ana since no socket for the video is being passed. It can be done without much effort, but I did not put on my example for the sake of simplicity and because I think that just gmx_MMPBSA _de per si_ will suffice for most users.
I've tested the container and everything seems to be working just fine, however, if you try and find some error, let me know. Also, if you have any remark about the Docker image, Dockerfile, Readme or anything, please contact me.
Atm I am bit busy, but I took a look at the to do list and will try to contribute more in the near future.

**Comment by Valdes-Tresanco-MS** [comment]
Thank you. I will try to test it asap. I will try to spend a few minutes learning about `docker` since I have no experience in that field. Additionally, `gmx_MMPBSA_ana` is important, so I'll also see how to make it work. Once everything is ready we will officially add it to the documentation as part of the installation.

Cheers! 
Mario S.

**Comment by vsdepontes** [comment]
Later I will test a way to use gmx_MMPBSA_ana in the container and put it in the readme, then. Also, there are links for installing Docker and NVIDIA-Docker on my readme. Maybe they can help a bit.
Btw, I have to thank you too. gmx_MMPBSA is really making a difference on my analysis.

**Comment by Valdes-Tresanco-MS** [comment]
Excellent!
We are glad that it is of help to you. I will be on the lookout, so we can make `gmx_MMPBSA` more accessible to reach more users.

Best!
Mario S.

**Comment by vsdepontes** [comment]
Just upgraded the Ubuntu, GROMACS and CUDA versions from the container and tested the use of gmx_MMPBSA_ana. An example on how to run the container with GUI support (needed for gmx_MMPBSA_ana) was included in the readme of the github repo and the image's docker hub page.

**Comment by Valdes-Tresanco-MS** [comment]
Excellent, I tested it and it works fine. We will put it in the installation section asap.
At that time we will add several options for non-expert users such as `--mount` to be able to work by synchronizing the files in the container with the working folder on the host.
This distribution option is very interesting, thanks for collaborating and for letting me know. We hope you can continue collaborating with us

Cheers!
Mario S.

**Comment by vsdepontes** [comment]
Perfect! Will be a pleasure to contribute more to gmx_MMPBSA.

**Comment by Valdes-Tresanco-MS** [comment]
We have already submitted the [recipe](https://github.com/conda-forge/staged-recipes/pull/17561) to `conda-forge`, now we just have to wait for it to be uploaded to the repository

**Comment by Valdes-Tresanco-MS** [comment]
We already have a working package of version `1.4.3`, so we can consider this issue resolved.
We will deal with the creation and maintenance of the docker container in a separate thread.
