### ISSUE TITLE
[Question]: How to determine the index value of -cg from index.ndx file?

### ISSUE THREAD

**Issue by chain-buds** [Valdes-Tresanco-MS/gmx_MMPBSA#553]
### My Question is...

sry, I don't know how to determine the index value of -cg from index.ndx file.

Below is my command, I try to index protein and my ligand as their name, but it didn't work.
`mpirun -np 8 gmx_MMPBSA -O -i mmpbsa.in -cs md_0_10.tpr -ci index.ndx -cg Protein JZ4 -ct md_95_100.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv -nogui`

Form the tutorial, I didn't find the way to determine the value of -cg. Need I to count the ordinal of Protein and JZ4 in the index.ndx file?

**Comment by Valdes-Tresanco-MS** [comment]
You must select the group number. For example:
```
  0 System              : 57679 atoms
  1 Protein             :  4409 atoms
  2 Protein-H           :  2199 atoms
  3 C-alpha             :   273 atoms
  4 Backbone            :   819 atoms
  5 MainChain           :  1093 atoms
  6 MainChain+Cb        :  1351 atoms
  7 MainChain+H         :  1354 atoms
  8 SideChain           :  3055 atoms
  9 SideChain-H         :  1106 atoms
 10 Prot-Masses         :  4409 atoms
 11 non-Protein         : 53270 atoms
 12 Other               :    34 atoms
 13 LIG                 :    34 atoms
 14 NA                  :    53 atoms
 15 CL                  :    56 atoms
 16 Water               : 53127 atoms
 17 SOL                 : 53127 atoms
 18 non-Water           :  4552 atoms
 19 Ion                 :   109 atoms
```
Here the option will be `-cg 1 13`. Please, consult the [documentation](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/gmx_MMPBSA_command-line/) or the command-line `gmx_MMPBSA -h` for more information
