### ISSUE TITLE
Cannot use MPI with -np higher than 2

### ISSUE THREAD

**Issue by vsdepontes** [Valdes-Tresanco-MS/gmx_MMPBSA#56]
**Describe the issue**
Cannot use MPI with `-np` higher than 2

**_If you will report an error, please complete this form_**
**To Reproduce**
1. Which system type are you running? 
Protein-DNA-RNA-Ions-Ligand
2. The command-line are you using.
mpirun -np 3 gmx_MMPBSA MPI -O -i mmpbsa.in -cs md_0_1_rstw.tpr -ci md_0_1_rstw.ndx -cg 1 12 -ct md_0_1_mmpbsa.xtc
**Additional context**
Everytime I try to run a MPI job with more than 2 proccesses, an error appears on the stderr/stdout, despite no error showing on gmx_MMPBSA.log
[stdout.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6785463/stdout.txt)
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/6785464/gmx_MMPBSA.log)

**Comment by vsdepontes** [comment]
Obviously, there were an error on my trajectory. By mistake, it had only two frames. My bad! :P. Anyway, adding a specific error message to this would help to identify this kind of user error more easly. Will look into it later.

**Comment by Valdes-Tresanco-MS** [comment]
The errors you report seem to be related: one to the execution command-line and the other to the default MPI configuration.

We implement a simple way to run `gmx_MMPBSA` with **MPI**, so we don't have to create a new executable. This is why execution errors can be made. Based on the output file you include, it appears that it was run with `mpirun` but without the **MPI** option. That is if it is executed with mpirun, but without the correct instruction, it means that everything in the program will be executed as many times as threads you have defined, which is chaotic and ends in errors like the one you show.

On the other hand, **MPI** by default only uses as many threads as the physical cores your processor has. If your processor is only 2 physical and 4 logical cores, **MPI** will only take 2 as the maximum number of processes it can create. This can be changed by including the `--use-hwthread-cpus` flag:
      
     mpirun -np 3 --use-hwthread-cpus gmx_MMPBSA MPI -O ...
And I think also modifying an environment variable (`OMP_NUM_THREADS` if I remember correctly) that assigns the number of tasks per core

I haven't done tests like this so I really have no idea if it will scale properly

**Comment by vsdepontes** [comment]
I'm trying to run it with `mpirun -np 3 gmx_MMPBSA MPI -O -i mmpbsa.in -cs md_0_1_rstw.tpr -ci md_0_1_rstw.ndx -cg 1 12 -ct md_0_1_mmpbsa.xtc`, based on the examples in the docs, and i get this error:  
~~~
[INFO   ] Making gmx_MMPBSA index for complex...
  File "/root/miniconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 95, in gmxmmpbsa
    app.make_prmtops()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 560, in make_prmtops
    self.remove(0)
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 973, in remove
    utils.remove(flag, mpi_size=self.mpi_size, fnpre=self.pre)
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/utils.py", line 273, in remove
    for fil in tempfiles: os.remove(fil)
FileNotFoundError: [Errno 2] No such file or directory: '_GMXMMPBSA_REC.inpcrd'
Exiting. All files have been retained.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[24109,1],0]
  Exit code:    1
--------------------------------------------------------------------------
~~~

When I try with `mpirun -np 3 gmx_MMPBSA MPI -i mmpbsa.in -cs md_0_1_rstw.tpr -ci md_0_1_rstw.ndx -cg 1 12 -ct md_0_1_mmpbsa.xtc`, I get this:   
~~~
[INFO   ] Normal ligand: Saving group 12 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
  File "/root/miniconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 95, in gmxmmpbsa
    app.make_prmtops()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 576, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 115, in buildTopology
    self.gmx2pdb()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 287, in gmx2pdb
    self.receptor_str = self.molstr(self.receptor_str_file)
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 1153, in molstr
    structure = parmed.read_PDB(pdb_file)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 376, in parse
    inst._parse_open_file(fileobj)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 430, in _parse_open_file
    method_dispatch[rec](line)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 624, in _parse_atom_record
    atom_parts = self._parse_atom_parts(line)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 523, in _parse_atom_parts
    x=float(line[30:38]), y=float(line[38:46]), z=float(line[46:54]),
ValueError: could not convert string to float: ''
Exiting. All files have been retained.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
~~~

**Comment by vsdepontes** [comment]
Running without MPI (`gmx_MMPBSA -O -i mmpbsa.in -cs md_0_1_rstw.tpr -ci md_0_1_rstw.ndx -cg 1 12 -ct md_0_1_mmpbsa.xtc`), it works.

**Comment by Valdes-Tresanco-MS** [comment]
We have tested `gmx_MMPBSA` with **MPI** many times so this problem is strange. This environment is from a docker container? If you run `gmx_MMPBSA` with **MPI** and only one core (`mpirun -np 1 gmx_MMPBSA ...`) does it work?
If `gmx_MMPBSA` in serial mode works fine and when run with **MPI** then it fails, the problem is in the runtime environment.

**Comment by vsdepontes** [comment]
If it is only one core (`-np 1`), it works. And yes, I am using a container. Btw, the processor has 16 cores and 32 threads

**Comment by vsdepontes** [comment]
If I try `mpirun -np 3 gmx_MMPBSA MPI -O -i mmpbsa.in -cs md_0_1_rstw.tpr -ci md_0_1_rstw.ndx -cg 1 12 -ct md_0_1_mmpbsa.xtc` more than once, I start getting different errors. Here are two of them:
~~~
[INFO   ] Normal ligand: Saving group 12 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
  File "/root/miniconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 95, in gmxmmpbsa
    app.make_prmtops()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 576, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 115, in buildTopology
    self.gmx2pdb()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 287, in gmx2pdb
    self.receptor_str = self.molstr(self.receptor_str_file)
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 1153, in molstr
    structure = parmed.read_PDB(pdb_file)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 376, in parse
    inst._parse_open_file(fileobj)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 430, in _parse_open_file
    method_dispatch[rec](line)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 624, in _parse_atom_record
    atom_parts = self._parse_atom_parts(line)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 521, in _parse_atom_parts
    parts = cls._parse_atom_parts_1(line)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 514, in _parse_atom_parts_1
    residue_number=line[22:26].strip(), insertion_code=line[26].strip(),
IndexError: string index out of range
Exiting. All files have been retained.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
~~~
   
~~~
[INFO   ] Normal ligand: Saving group 12 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
  File "/root/miniconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 95, in gmxmmpbsa
    app.make_prmtops()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 576, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 115, in buildTopology
    self.gmx2pdb()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 286, in gmx2pdb
    self.complex_str = self.molstr(self.complex_str_file)
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 1153, in molstr
    structure = parmed.read_PDB(pdb_file)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 383, in parse
    inst.struct.assign_bonds()
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/structure.py", line 973, in assign_bonds
    pairs = find_atom_pairs(self, mindist, unassigned_atoms)
  File "/root/miniconda3/lib/python3.8/site-packages/parmed/utils/pairlist.py", line 39, in find_atom_pairs
    voxels = np.array((coords - coords.min(axis=0)) / dist, dtype=int)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
Exiting. All files have been retained.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
~~~

**Comment by vsdepontes** [comment]
The curious thing is that running `mpirun -np 2 gmx_MMPBSA MPI -i mmpbsa.in -cs md_0_1_rstw.tpr -ci md_0_1_rstw.ndx -cg 1 12 -ct md_0_1_mmpbsa.xtc` works

**Comment by Valdes-Tresanco-MS** [comment]
In the docker container, I am getting an error related to mpi shared libraries (ImportError: libmpi.so.12: cannot open shared object file: no such file or directory). I guess it is related to the definition of the environment variable `LD_LIBRARY_PATH`. Any suggestion?

This error seems environment-related, however, based on a preliminary search, it does not appear that many similar issues have been reported

**Comment by vsdepontes** [comment]
Yep. About that, I am searching for a good solution. The one I used is to install `libmpich-dev` and `libmpich12` with APT and then link `libmpich.so.12` to `libmpi.so.12` using `ln -sf /usr/lib/x86_64-linux-gnu/libmpich.so.12 /usr/lib/x86_64-linux-gnu/libmpi.so.12`. The problem is that mpi4py looks for `libmpi.so.12` while the OS has `libmpi.so.40`, that is related to a newer version of MPI and does not have backwards compatibility

**Comment by vsdepontes** [comment]
I will try installing in the host OS and not a container to see if it works. However, I think we can try to figure out what is happening and make it work in the container, if this really is the problem. Since you have already tested MPI well, I might be doing something else wrong

**Comment by vsdepontes** [comment]
> Yep. About that, I am searching for a good solution. The one I used is to install `libmpich-dev` and `libmpich12` with APT and then link `libmpich.so.12` to `libmpi.so.12` using `ln -sf /usr/lib/x86_64-linux-gnu/libmpich.so.12 /usr/lib/x86_64-linux-gnu/libmpi.so.12`. The problem is that mpi4py looks for `libmpi.so.12` while the OS has `libmpi.so.40`, that is related to a newer version of MPI and does not have backwards compatibility

Had to do the same thing with my host OS (Ubuntu 20.04 LTS) since the default library is `libmpi.so.40` and not the `libmpi.so.12` required by mpi4py. I am still having the problems described. What OS did you test MPI on?

**Comment by Valdes-Tresanco-MS** [comment]
I think I found the problem. Some time ago I was checking mpi4py depth since it reported an issue incompletely. The developer explained to me that the package that he manages/updates is in `conda-forge` (`conda install -c conda-forge mpi4py`). Installing this version seems to work without problems.
To do this, I uninstalled the `mpi4py` version and installed it from `conda-forge`
In any case, we have tested `gmx_MMPBSA` on Ubuntu 20.04, 19.10, and 18.04, Linux Mint 20.1 and 19.3, and on macOS Big Sur.
Let me know how you do

**Comment by vsdepontes** [comment]
Bingo! You're the guy. Using `conda install -c conda-forge mpi4py` solved the problem for both the container and my host OS. Both using Ubuntu 20.04. I will update the docker image on Docker Hub and the Dockerfile on the repo soon.

**Comment by vsdepontes** [comment]
I updated them now and everything should be fine. I also used the opportunity to make keeping the container up (after the user exits the interactive mode) easier with the `keepalive.sh script`. 
Since the problem was solved, I am closing the issue. Thanks a lot for your help.
