### ISSUE TITLE
OverflowError on IE calculation

### ISSUE THREAD

**Issue by vsdepontes** [Valdes-Tresanco-MS/gmx_MMPBSA#57]
**Describe the issue**
I am having an overflow error when trying to use Interaction Entropy

**To Reproduce**
1. Which system type are you running?
Protein-DNA-RNA-Ions-Ligand
2. The command-line are you using.
mpirun -np 14 --allow-run-as-root gmx_MMPBSA MPI -O -i mmpbsa.in -cs md_0_1_rstw.tpr -ci md_0_1_rstw.ndx -cg 1 12 -ct md_0_1_mmpbsa.xtc -nogui

**Additional context**
The input file:
~~~
&general
verbose=2, interval=10, interaction_entropy=1, ie_segment=100, temperature=303.15
/
&gb
saltcon=0.1
/
~~~  
  
The error:
~~~
Preparing trajectories for simulation...
201 frames were processed by cpptraj for use in calculation.

Running calculations on normal system...

Beginning GB calculations with /root/miniconda3/bin/mmpbsa_py_energy
  calculating complex contribution...
  calculating receptor contribution...
  calculating ligand contribution...
  File "/root/miniconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 107, in gmxmmpbsa
    app.parse_output_files()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 1068, in parse_output_files
    ie = InteractionEntropyCalc(edata, self, self.pre + 'iteraction_entropy.dat')
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/calculation.py", line 566, in __init__
    self._calculate()
  File "/root/miniconda3/lib/python3.8/site-packages/GMXMMPBSA/calculation.py", line 583, in _calculate
    eceint = math.exp(deint / (k * temp))
OverflowError: math range error
Error occured on rank 0.
Exiting. All files have been retained.
~~~

**Comment by marioernestovaldes** [comment]
Hello there! this is a typical error when dealing with a result that is too large... "k" and "temp" are constants in this equation, so the only reason for a large result here, is a large "deint". Could you please check the internal energy values and see if there si something wrong going on with them?

**Comment by Valdes-Tresanco-MS** [comment]
This error is due to the exponent value exceeding the maximum number allowed by python which is ~709 ( `exp(709) = 8.22e+307` which does not make sense in energetic terms).
Please make sure that the energy values you get are consistent.

This error is related to a sudden energy change. The term `deint` in the expression  is calculated as:
![image](https://user-images.githubusercontent.com/36672242/125834667-77f35b1f-dd13-4785-9377-721ab2ea00f0.png)

that is, the value of `ΔG gas` in the frame `_i_` minus the average `ΔG gas` up to the frame `_i_`. The expected value should be small, but if there is a large fluctuation `> 425 kcal` from frame to frame then you get this error

Also, check the value of `ie_segment`. This value should not cover the entire trajectory. The authors of the method suggest taking special care when selecting this interval, since there must be convergence, to obtain a reliable value. This is why we defined it in 25%.
It would be prudent to analyze the energy values first, then include the interaction entropy with a more affordable interval

**Comment by vsdepontes** [comment]
Thanks for the reply! I will take a better look at my inputs.

**Comment by vsdepontes** [comment]
I tried using `ie_segment=50` and had the same error.
When I removed IE, got the following result:

~~~
| Run on Thu Jul 15 18:31:26 2021
|
|Input file:
|--------------------------------------------------------------
|&general
|verbose=2, interval=10, temperature=303.15
|/
|
|
|&gb
|saltcon=0.1
|/
|--------------------------------------------------------------
|gmx_MMPBSA Version=v1.4.3 based on MMPBSA.py v.16.0
|Complex topology file:           COM.prmtop
|Receptor topology file:          REC.prmtop
|Ligand topology file:            LIG.prmtop
|Initial mdcrd(s):                COM_traj_0.xtc
|
|Receptor mask:                  ":1-1418"
|Ligand mask:                    ":1419-1470"
|
|Calculations performed using 201 complex frames.
|
|Generalized Born ESURF calculated using 'LCPO' surface areas
|
|All units are reported in kcal/mole.
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

GENERALIZED BORN:

Complex:
Energy Component            Average              Std. Dev.   Std. Err. of Mean
-------------------------------------------------------------------------------
BOND                      4962.6094               65.8201              4.6426
ANGLE                    12021.2426               79.9340              5.6381
DIHED                    16783.6846               50.2655              3.5455
VDWAALS                 -12822.2774              329.1996             23.2199
EEL                     -85793.0825              528.1246             37.2510
1-4 VDW                   5743.1635               29.9343              2.1114
1-4 EEL                  52904.6657              110.0656              7.7634
EGB                     -38408.8426              460.0312             32.4481
ESURF                      516.7536                4.4980              0.3173

G gas                    -6199.9941              606.2207             42.7595
G solv                  -37892.0890              458.6385             32.3499

TOTAL                   -44092.0832              377.8137             26.6489


Receptor:
Energy Component            Average              Std. Dev.   Std. Err. of Mean
-------------------------------------------------------------------------------
BOND                      4320.4183               53.1257              3.7472
ANGLE                    10964.2442               76.7275              5.4119
DIHED                    15518.9142               48.0107              3.3864
VDWAALS                 -11700.4332               51.4805              3.6312
EEL                    -100003.7089              333.1036             23.4953
1-4 VDW                   5264.8067               29.0189              2.0468
1-4 EEL                  58726.2657              105.1435              7.4163
EGB                     -17663.9122              254.8360             17.9747
ESURF                      485.5793                4.3958              0.3101

G gas                   -16909.4930              308.7268             21.7759
G solv                  -17178.3329              252.2216             17.7903

TOTAL                   -34087.8259              122.3966              8.6332


Ligand:
Energy Component            Average              Std. Dev.   Std. Err. of Mean
-------------------------------------------------------------------------------
BOND                       642.1910               34.4971              2.4332
ANGLE                     1056.9984               23.4332              1.6529
DIHED                     1264.7704               13.0220              0.9185
VDWAALS                   -857.4465              330.5840             23.3176
EEL                      15799.7986              291.9969             20.5959
1-4 VDW                    478.3568                9.0494              0.6383
1-4 EEL                  -5821.5999               25.7713              1.8178
EGB                     -22458.8108              283.5157             19.9977
ESURF                       68.9484                0.4196              0.0296

G gas                    12563.0688              424.1475             29.9171
G solv                  -22389.8624              283.5806             20.0022

TOTAL                    -9826.7937              344.4267             24.2940


Differences (Complex - Receptor - Ligand):
Energy Component            Average              Std. Dev.   Std. Err. of Mean
-------------------------------------------------------------------------------
BOND                        -0.0000                0.0001              0.0000
ANGLE                        0.0000                0.0001              0.0000
DIHED                       -0.0000                0.0000              0.0000
VDWAALS                   -264.3976               13.0257              0.9188
EEL                      -1589.1723              286.6261             20.2170
1-4 VDW                      0.0000                0.0000              0.0000
1-4 EEL                     -0.0000                0.0000              0.0000
EGB                       1713.8803              277.9401             19.6044
ESURF                      -37.7741                1.3932              0.0983

DELTA G gas              -1853.5699              287.8859             20.3059
DELTA G solv              1676.1063              277.5452             19.5765

DELTA TOTAL               -177.4636               23.2174              1.6376


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
~~~

**Comment by vsdepontes** [comment]
Do you spot something that might be causing the problem?

**Comment by Valdes-Tresanco-MS** [comment]
Open the gmx_MMPBSA_ana and show me the `ΔG gas` line plot

**Comment by vsdepontes** [comment]
Since remote access to the lab is down, I will only be able to provide this info monday

**Comment by vsdepontes** [comment]
The problem was my enormous double strand RNA violently shaking

**Comment by wangshuai-simulation** [comment]
> This error is due to the exponent value exceeding the maximum number allowed by python which is ~709 ( `exp(709) = 8.22e+307` which does not make sense in energetic terms). Please make sure that the energy values you get are consistent.
> 
> This error is related to a sudden energy change. The term `deint` in the expression is calculated as: ![image](https://user-images.githubusercontent.com/36672242/125834667-77f35b1f-dd13-4785-9377-721ab2ea00f0.png)
> 
> that is, the value of `ΔG gas` in the frame `_i_` minus the average `ΔG gas` up to the frame `_i_`. The expected value should be small, but if there is a large fluctuation `> 425 kcal` from frame to frame then you get this error
> 
> Also, check the value of `ie_segment`. This value should not cover the entire trajectory. The authors of the method suggest taking special care when selecting this interval, since there must be convergence, to obtain a reliable value. This is why we defined it in 25%. It would be prudent to analyze the energy values first, then include the interaction entropy with a more affordable interval

I have the same question as that in this case. 
~~~~~~~~~~~~~~~
[INFO   ] Parsing results to output files...
[INFO   ] Beginning Interaction Entropy calculations...
^M              0%|          | 0/54 [elapsed: 00:00 remaining: ?]^M             61%|######1   | 33/54 [elapsed: 00:00 remaining: 00:00]
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 109, in gmxmmpbsa
    app.parse_output_files()
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 1103, in parse_output_files
    self.get_iec2entropy(from_calc)
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 1123, in get_iec2entropy
    ie = InteractionEntropyCalc(edata, self.INPUT)
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 676, in __init__
    self._calculate()
  File "/home/tea_yiming/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/calculation.py", line 690, in _calculate
    eceint = math.exp(deint / (k * temperature))
OverflowError: math range error
Error occurred on rank 0.
Exiting. All files have been retained.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
~~~~~~~~~~~~~~~~~~
As you said above, the error is related to a sudden energy change (deint > 425 kcal from frame to frame). However, i don't 
know where to find the value of deint or how to make the value of deint small. Appreciate if anyone can help me !
All my result files are saved as _GMXMMPBSA, top and remaining files :
[https://github.com/wangshuai-simulation/wangshuai-simulation.github.io/tree/master1](url)

**Comment by wangshuai-simulation** [comment]
@Valdes-Tresanco-MS, need your attention about my comment to your reply to "OverflowError on IE calculation". Appreciate a lot !

**Comment by Valdes-Tresanco-MS** [comment]
Interaction Entropy is not applicable at all for this system. Please read the reference article in our documentation and the article that determines the value of the standard deviation of the internal energy to be considered reliable. I don't think there is a way to sample this system and apply Interaction Entropy. Also, the entropic contribution here must be enormous, but first, you must be concerned that the enthalpic contribution calculations are at least logical.
As far as I saw, the standard deviation of the EEL values (at least of the ligand) is absurdly large. The system seems to have a disruption between frames 201-202, which could be a cause, but I am not sure because I did not check it in detail. You could set the inner dielectric constant very high (for example, 5, 6, or 7) so that the electrostatic contribution decreases, and you can better analyze the values you get. In any case, this is a completely untested system, so I am not entirely sure what parameter values you could use to get reliable results.
My recommendation is to check that the whole trajectory is consistent. Set up some tests with different frame intervals so you can cover the whole trajectory without having to spend too much computational resources and time. Just calculate the enthalpy because the entropy in this case, I think, is out of scope, because of the size and complexity of the system. Also, I think the entropy in this system will contribute more to separation than bonding. You can try some different parameter settings. Finally, check if the results you get make sense and can be justified.
