### ISSUE TITLE
gmx_MMPBSA does not recognize variable Temperature in .in file

### ISSUE THREAD

**Issue by EdwardMendez95** [Valdes-Tresanco-MS/gmx_MMPBSA#58]
Greetings,

I'm running a single trajectory protein-ligand system GBSA free energy calculation with IE using a temperature for the IE of 310.15 K. 

When I run the software, the next prompt appears:

**[INFO   ] Started
InputError: Unknown variable temperature in &general
Enter `gmx_MMPBSA --help` for help** 

Here is the command line:

`gmx_MMPBSA -O -i mmpbsa.in -cs md_0_10.tpr -ci index_mmpbsa.ndx -cg 1 13 -ct md_0_10_mmpbsa.xtc -lm MOL.mol2 -eo output `

Here is the log file output
`
**[INFO   ] Started**`

Here is the .in file input

```
Sample input file for entropy calculations (IE)
This input file is meant to show only that gmx_MMPBSA works. Although,
we tried to use the input files as recommended in the Amber manual,
some parameters have been changed to perform more expensive calculations
in a reasonable amount of time. Feel free to change the parameters according to what is better for your system.

&general
#
startframe=3000, endframe=5000, verbose=2, interval=4,
protein_forcefield="oldff/leaprc.ff99SB",

#entropy variable control whether to perform a quasi-harmonic entropy (QH)
# approximation or the Interaction Entropy approximation
# (https://pubs.acs.org/doi/abs/10.1021/jacs.6b02682) 
entropy=2, entropy_seg=25, temperature=310.15
/

&gb
igb=2, saltcon=0.01,
/
```

Thank you

**Comment by Valdes-Tresanco-MS** [comment]
Hi Edward
Please, check the `gmx_MMPBSA` version. We changed `entropy_temp` by `temperature` since version v1.4.0

Mario S.

**Comment by EdwardMendez95** [comment]
I see. Thank you.

I will try to upgrade the package
