### ISSUE TITLE
Fatal error: reading tpx file (step7.tpr) version 122 with version 116 program

### ISSUE THREAD

**Issue by ataulislam80** [Valdes-Tresanco-MS/gmx_MMPBSA#61]
**Describe the issue**
I have done 50ns of MD simulation in Gromacs for a membrane protein-ligand complex. The system was build in CHARMM-GUI. The simulation was done in Gromacs 2021.1 version. When I was trying to run gmx_MMPBSA its given following error.

Fatal error:
reading tpx file (step7.tpr) version 122 with version 116 program

Please help to solve the issue

**_If you will report an error, please complete this form_**
**To Reproduce**
1. Which system type are you running? (Protein-Protein, Protein-Ligand, etc)
2. The command-line are you using.

**Additional context**
The gmx_MMPBSA.log file

**Comment by Valdes-Tresanco-MS** [comment]
You are using a lower version of GROMACS to process the tpr file than the one you used to create it. Use the same version or higher
