### ISSUE TITLE
gmx_MMPBSA installation error

### ISSUE THREAD

**Issue by ataulislam80** [Valdes-Tresanco-MS/gmx_MMPBSA#62]
**Describe the issue**

Trying to install gmx_MMPBSA getting following error.

amber.python -m pip install gmx_MMPBSA
/home/muzzammel/amber/amber20/bin/amber.python: No module named pip

I checked the pip and found following:
whereis pip
pip: /usr/bin/pip /home/muzzammel/.local/bin/pip3.8 /home/muzzammel/.local/bin/pip /usr/share/man/man1/pip.1.gz

I also re-installed the pip but no solution.

Please help to solve the issue.

**_If you will report an error, please complete this form_**
**To Reproduce**
1. Which system type are you running? (Protein-Protein, Protein-Ligand, etc)
2. The command-line are you using.

**Additional context**
The gmx_MMPBSA.log file

**Comment by Valdes-Tresanco-MS** [comment]
It seems to be a problem with the latest version of miniconda. I had that problem in a recent install. You can try to install a new miniconda environment and install ambertools from the `conda-forge` repository

- Download the miniconda installer
- Install `mpi4py` and `ambertools` (`conda install -c conda-forge mpi4py ambertools=21`)
- Install `gmx_MMPBSA` (`python -m pip install gmx-mmpbsa`)

Tell me how it went
Cheers!

Mario S.

**Comment by Valdes-Tresanco-MS** [comment]
This is a miniconda problem, so we can only point out the solution in the documentation.
See the [Installation](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/installation/#installation) section in the documentation

Close via 9b37ed3

**Comment by debanjansen48** [comment]
Thank you for this information.
