### ISSUE TITLE
need help for an unexpected issue

### ISSUE THREAD

**Issue by debanjansen48** [Valdes-Tresanco-MS/gmx_MMPBSA#69]
**Describe the issue**
i was installed gmx_MMPBSA previouslu and it workd nicely.

Today I tried to install it in my lab ..I dont know it returns an unexpected error
 
@dschemlab-1:~$ amber.python -m pip install PyQt5
/home/dschemlab-1/Amber20/bin/amber.python: **No module named pip**

**_If you will report an error, please complete this form_**
**To Reproduce**
1. Which system type are you running? (Protein-Protein, Protein-Ligand, etc)
2. The command-line are you using.

**Additional context**
The gmx_MMPBSA.log file

**Comment by Valdes-Tresanco-MS** [comment]
This is a miniconda problem, so we can only point out the solution in the documentation.
See the [Installation](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/installation/#installation) section in the documentation

Close via 9b37ed3
