### ISSUE TITLE
Error: PrmtopError: provided receptor/ligand masks don't select every atom in the complex topology!

### ISSUE THREAD

**Issue by tanush84** [Valdes-Tresanco-MS/gmx_MMPBSA#92]
The error is described below:
Prmto
![error_gmx_MMPBSA_PRMTOP](https://user-images.githubusercontent.com/12098453/140854989-cb6c3fe1-94b4-4dfd-a89b-670c29f3cdcb.png)
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7501602/gmx_MMPBSA.log)
pError: provided receptor/ligand masks don't select every atom in the complex topology!

I am running Protein-Ligand system
I am using Terminal for running command and command is below:
gmx_MMPBSA -O -i mmpbsa.in -cs md.tpr -ci index.ndx -cg 1 13 -ct md_nojump.xtc -cp topol.top
I am getting prmtop error.
I am attaching the screenshot for the error. 
please assist. 
Regards
Tanuj

**Comment by marioernestovaldes** [comment]
Hello Tanuj and welcome!

the fastest way to deal with these problems is to share with us the files you're using, so we can identify quickly what's going wrong... Please, send us the mmpbsa.in, md.tpr, index.ndx, md_nojump.xtc and the topol.top with all its files and folders associated...

looking forward to hearing from you soon!

Mario E.

**Comment by marioernestovaldes** [comment]
closing the issue as we didn't receive any information... feel free to reopen it if the issue persists...
