### ISSUE TITLE
PB calculations fail to calculate EPB and G sol values

### ISSUE THREAD

**Issue by pacho2** [Valdes-Tresanco-MS/gmx_MMPBSA#96]
**Describe the issue**
I am trying to calculate PBSA with a peptide acting as a ligand of a bilayer membrane (all built with charmm-gui and using charmm36m FF)

**To Reproduce**
1. Which system type are you running? Protein-ligand (peptide + lipid bilayer)
2. The command-line are you using.
```
$ cat mmpbsa.in 
Sample input file for PB calculation
This input file is meant to show only that gmx_MMPBSA works. Although, we tried to use the input files as recommended
in the Amber manual, some parameters have been changed to perform more expensive calculations in a reasonable amount of time. Feel free to change the
parameters according to what is better for your system.

&general
sys_name="Prot-Lig-CHARMM",
startframe=8000, endframe=10000, interval=20, verbose=2,
# https://valdes-tresanco-ms.github.io/gmx_MMPBSA/examples/Entropy_calculations/Interaction_Entropy/
entropy=2, entropy_seg=25, temperature=310
/
&pb
# radiopt=0 is recommended which means using radii from the prmtop file for both the PB calculation and for the NP
# calculation
istrng=0.0, fillratio=4.0, radiopt=0
```

Command line:
```
mpirun --oversubscribe -np 28 gmx_MMPBSA MPI -nogui -O -i mmpbsa.in -cs ../step7.tpr -ci ../index.ndx -cg 1 0 -ct ../step7_mol.xtc -cp ../topol.top
```

**Additional context**
The gmx_MMPBSA.log file is attached
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7627450/gmx_MMPBSA.log)
[FINAL_RESULTS_MMPBSA.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7627453/FINAL_RESULTS_MMPBSA.txt)
[index.ndx.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7627468/index.ndx.txt)
[step7.gro.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7627472/step7.gro.txt)

Thanks a lot for your help

**Comment by marioernestovaldes** [comment]
Hello there! seems like the PB energies you are getting are extremely high which is expected... could you please send us the *.mdout file to double check?

There is a built-in function in gmx_MMPBSA that handles membranes environment implicitly and is used when working with receptors embedded in membranes... I am not sure how meaningful could the results be in this case though where you are trying to calculate the binding free energy of the peptide with the membrane... Do you have any reference of the use of MMPBSA to calculate binding free energy of peptides with membranes?

cheers!

**Comment by pacho2** [comment]
Hi!

There are some studies involving them:
https://doi.org/10.1021/acs.jcim.9b00245
https://doi.org/10.1371/journal.pone.0187216
https://www.sciencedirect.com/science/article/pii/S0005273617301839
https://www.mdpi.com/1422-0067/19/4/1186/htm

I also tried in the past with g_mmpbsa and it seemed to work for PC and PE membranes... but I was unable to find a proper value for pdie for membranes containing charged lipids (https://rashmikumari.github.io/g_mmpbsa/Polar-solvation-input-parameters.html#pdie) and at the end I gave up as it was also getting harder and harder to use with recent gromacs versions :(

I attach a zip with all the mdout files

Thanks!
[mdout.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7627705/mdout.zip)

**Comment by marioernestovaldes** [comment]
Oh, I see... I was checking your files and seems like the number of steps to reach convergence in the receptor (membrane) was exceeded... see line 342 in `GMXMMPBSA_receptor_pb.mdout.0` file

PBSA WARNING: in MG: SOR maxitn exceeded!

my first approach to this would be to increase the value of `maxitn` variable in the `mmpbsa.in`. Currently is set to 1000... try with 10000 and see how it goes...

cheers!

Mario E.

**Comment by pacho2** [comment]
In which part should I add it? Per https://valdes-tresanco-ms.github.io/gmx_MMPBSA/input_file/ it seems to go in &pb section, I did:
```
&general
sys_name="Prot-Lig-CHARMM",
startframe=8000, endframe=10000, interval=20, verbose=2,
# https://valdes-tresanco-ms.github.io/gmx_MMPBSA/examples/Entropy_calculations/Interaction_Entropy/
entropy=2, entropy_seg=25, temperature=310
/
&pb
# radiopt=0 is recommended which means using radii from the prmtop file for both the PB calculation and for the NP
# calculation
istrng=0.0, fillratio=4.0, radiopt=0, maxitn=10000
```

But it fails with:
```[INFO   ] Starting
[INFO   ] Command-line
  gmx_MMPBSA -nogui -O -i mmpbsa.in -cs ../step7.tpr -ci ../index.ndx -cg 1 0 -ct ../step7_mol.xtc -cp ../topol.top

InputError: Unknown variable maxitn in &pb
  Enter `gmx_MMPBSA --help` for help
```

**Comment by marioernestovaldes** [comment]
my bad... I should have clarified that `maxitn` variable corresponds to `linit` in gmx_MMPBSA... should be like this:

&general
sys_name="Prot-Lig-CHARMM",
startframe=8000, endframe=10000, interval=20, verbose=2,
entropy=2, entropy_seg=25, temperature=310
/
&pb
istrng=0.0, fillratio=4.0, radiopt=0, linit=10000


cheers!

**Comment by pacho2** [comment]
Perfect, I will let you know when it finishes

Thanks a lot!

**Comment by pacho2** [comment]
It seems to work fine (also it finishes in half an hour instead of days like before :/)

I am unsure about the finally obtained values, but that is my job to do ;-)

Thanks a lot for this fantastic tool!

**Comment by marioernestovaldes** [comment]
that's great! closing the issue...
