### ISSUE TITLE
Multi-trajectory with replicates

### ISSUE THREAD

**Issue by wrmartin** [Valdes-Tresanco-MS/gmx_MMPBSA#97]
Hello,

I have a perhaps odd use case. I'm sure it's not possible in the current iteration, but I'd be curious if it would be possible to implement. I have a protein-protein complex I'm interested in determining the binding affinity for, and also have simulations of both proteins in the heteromer. Additionally, I have 3 replicates of the "receptor", "ligand", and complex. Would it be possible to implement replicates like this, or is my best bet just concatenating the portions of the trajectories for analysis and ignoring the wonky graphs they will generate?

I hope my description is clear.

Will

**Comment by marioernestovaldes** [comment]
Hello Will and welcome! 

As I don't how long your simulations are, a possible solution for your case will be running three independent gmx_MMPBSA calculations, then extracting the data and doing the stats by yourself... All the data in gmx_MMPBSA can be accessed through gmx_MMPBSA_ana or the API... 

The possibility of passing several simulations for each component (_i.e._ receptor, ligand and/or complex) to gmx_MMPBSA is inspired in the fact that it has been shown that it is more effective to run many short independent simulations than a single long (check chapter 3 "The precision" in this [publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4487606/))... that way, differences between simulations won't be that large and graphs remain "clean"

hope this answers your question!

cheers!

Mario E.
